### ISSUE TITLE
Crash report from Dynamo 2.2.1.5175

### ISSUE THREAD

**Issue by nicebikemate** [DynamoDS/Dynamo#10144]
# Issue Description
Please fill in the following information to help us reproduce the issue:
Worth mentioning here that i'm using latest version of Dynamo, Revit 2020.1 on latest win 10 service pack.

### What did you do?
(Fill in here)
Attempted to run Launch Window for Mandrill by Archi-lab

### What did you expect to see?
(Fill in here)
Window should pop up showing a donut chart

### What did you see instead?
(Fill in here)
Nothing, Dynamo just crashes out.

### What packages or external references (if any) were used?
(Fill in here)
Mandrill
Clockwork
NodeModelCharts

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```
The process cannot access the file 'C:\Users\RobertS\AppData\Roaming\Dynamo\Dynamo Revit\2.2\packages\Archi-lab_Mandrill\bin\eowp.exe' because it is being used by another process.

   at EO.Internal.ji.a(String A_0, Byte[] A_1)
   at Mandrill.ChromeWindow.MandrillWindow..ctor()
   at Mandrill.ChromeWindow.MandrillWindowNodeViewCustomization.CreateNewWindow()
   at Mandrill.ChromeWindow.MandrillWindowNodeModel.ShowMessage(Object obj)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---
OS: `Microsoft Windows NT 10.0.18362.0`
CLR: `4.0.30319.42000`
Dynamo: `2.2.1.5175`
![Capture](https://user-images.githubusercontent.com/57957262/69166814-c52eea80-0aeb-11ea-900d-18697661042a.PNG)

**Comment by mjkkirschner** [comment]
please report this to the author here:
https://github.com/BadMonkeysTeam/Mandrill
