### ISSUE TITLE
Crash report from Dynamo 2.2.1.5175

### ISSUE THREAD

**Issue by MAHadaway** [DynamoDS/Dynamo#10205]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
Code Block parameter - entered [90;210;330]; - when I clicked out of the code block it turned red and an error stating Dynamo has crashed appeared.

### What did you expect to see?
3 points on my screen

### What did you see instead?
an error and a red parameter block

### What packages or external references (if any) were used?
(Fill in here)

### Stack Trace
```
Exception of type 'ProtoCore.Exceptions.CompilerInternalException' was thrown.
![error](https://user-images.githubusercontent.com/50992636/70384001-623bb100-193d-11ea-90b1-260f5b59b918.png)


  at Dynamo.Engine.CodeGeneration.AstBuilder.CompileToAstNodes(NodeModel node, List`1 resultList, CompilationContext context, Boolean verboseLogging)
   at Dynamo.Engine.CodeGeneration.AstBuilder.CompileToAstNodes(IEnumerable`1 nodes, CompilationContext context, Boolean verboseLogging)
   at Dynamo.Engine.CodeGeneration.AstBuilder.CompileCustomNodeDefinition(Guid functionId, IEnumerable`1 returnKeys, String functionName, IEnumerable`1 funcBody, IEnumerable`1 outputNodes, IEnumerable`1 parameters, Boolean verboseLogging)
   at Dynamo.Engine.EngineController.GenerateGraphSyncDataForCustomNode(IEnumerable`1 nodes, CustomNodeDefinition definition, Boolean verboseLogging)
   at Dynamo.Models.DynamoModel.UpdateCustomNodeDefinition(CustomNodeDefinition definition)
   at Dynamo.Core.CustomNodeManager.OnDefinitionUpdated(CustomNodeDefinition obj)
   at System.Action.Invoke()
   at Dynamo.Graph.Workspaces.CustomNodeWorkspaceModel.OnDefinitionUpdated()
   at System.Action`1.Invoke(T obj)
   at Dynamo.Graph.Nodes.NodeModel.OnNodeModified(Boolean forceExecute)
   at Dynamo.Graph.Nodes.NodeModel.ConnectorsCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.InsertItem(Int32 index, T item)
   at Dynamo.Graph.Connectors.ConnectorModel.Connect(PortModel p)
   at Dynamo.Graph.Connectors.ConnectorModel.Make(NodeModel start, NodeModel end, Int32 startIndex, Int32 endIndex, Nullable`1 guid)
   at Dynamo.Graph.Nodes.CodeBlockNodeModel.LoadAndCreateConnectors(OrderedDictionary inportConnections, OrderedDictionary outportConnections, SaveContext context)
   at Dynamo.Graph.Nodes.CodeBlockNodeModel.SetCodeContent(String newCode, ElementResolver workspaceElementResolver)
   at Dynamo.Graph.Nodes.CodeBlockNodeModel.UpdateValueCore(UpdateValueParams updateValueParams)
   at Dynamo.Graph.Workspaces.WorkspaceModel.UpdateModelValue(IEnumerable`1 modelGuids, String propertyName, String value)
   at Dynamo.Models.DynamoModel.UpdateModelValueImpl(UpdateModelValueCommand command)
   at Dynamo.Models.DynamoModel.ExecuteCommand(RecordableCommand command)
   at Dynamo.UI.Controls.CodeCompletionEditor.UpdateNodeValue(String property)
   at Dynamo.UI.Controls.CodeBlockEditor.CommitChanges(UndoRedoRecorder recorder)
   at Dynamo.UI.Controls.CodeBlockEditor.OnCommitChange()
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.IsFocused_Changed(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at ICSharpCode.AvalonEdit.Editing.TextArea.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.ClearValueCommon(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata)
   at System.Windows.DependencyObject.ClearValue(DependencyPropertyKey key)
   at System.Windows.Input.FocusManager.OnFocusedElementChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.Input.FocusManager.SetFocusedElement(DependencyObject element, IInputElement value)
   at System.Windows.Input.KeyboardNavigation.UpdateFocusedElement(DependencyObject focusTarget)
   at System.Windows.FrameworkElement.OnGotKeyboardFocus(Object sender, KeyboardFocusChangedEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.KeyboardDevice.ChangeFocus(DependencyObject focus, Int32 timestamp)
   at System.Windows.Input.KeyboardDevice.TryChangeFocus(DependencyObject newFocus, IKeyboardInputProvider keyboardInputProvider, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   at System.Windows.Input.KeyboardDevice.Focus(DependencyObject focus, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   at System.Windows.Input.KeyboardDevice.Focus(IInputElement element)
   at System.Windows.UIElement.Focus()
   at Dynamo.Controls.DynamoView.OnRequestReturnFocusToView()
   at Dynamo.ViewModels.DynamoViewModel.OnRequestReturnFocusToView()
   at Dynamo.Controls.NodeView.topControl_MouseLeftButtonDown(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

---
OS: `Microsoft Windows NT 10.0.18362.0`
CLR: `4.0.30319.42000`
Dynamo: `2.2.1.5175`

**Comment by QilongTang** [comment]
@MAHadaway Hi we are sorry that you encountered the crash like this, do you happen to have a backup dyn or saved version so that you know what you typed in or connected to the Code Block Node making this happen?

**Comment by MAHadaway** [comment]
No worries, things happen.

Yes, and I think I know what happened.  I used a semi colon instead of a
comma.  but I have never had it crash like that.  I'm attaching a picture
and the file.

On another note, I have another dynamo issue with the Input Parameter ...
how do I go about getting help with that?

Thanks,
MH

**Comment by mjkkirschner** [comment]
tracked with: https://jira.autodesk.com/browse/DYN-2433
