### ISSUE TITLE
Dynamo severe slowdown after many runs - may have to do with python

### ISSUE THREAD

**Issue by mjkkirschner** [DynamoDS/Dynamo#1022]
After many runs of graphs using python nodes I get severe slowdown of the entire graph - especially upon graph execution completion.  Timing my python node execution seems reasonable, but I get a loading cursor for about 5 seconds after the python node shows it's output.

Starting a new graph does not fix the slowdown, but restarting dynamo does fix it.

eventually, typing any "obj ." in python will produce a loading cursor for up to 30 seconds while autocomplete members load.

upon typing any "obj ." I also get this error in the logger:

System.MissingMemberException: attribute 'GetType' of 'namespace#' object is read-only
   at IronPython.Runtime.Binding.PythonGetMemberBinder.NamespaceTrackerDelegate.Target(CallSite site, Object self, CodeContext context)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Microsoft.Scripting.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
   at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
   at IronPython.Compiler.PythonScriptCode.EvalWrapper(CodeContext ctx)
   at IronPython.Compiler.RuntimeScriptCode.InvokeTarget(Scope scope)
   at Microsoft.Scripting.SourceUnit.Execute(Scope scope)
   at DynamoPython.IronPythonCompletionProvider.TryGetType(String name)
Failed to look up type

**Comment by ikeough** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version. 

Thank you!
