### ISSUE TITLE
Virtual Machine is experiencing some unexpected errors internally...

### ISSUE THREAD

**Issue by Hyun-Tak** [DynamoDS/Dynamo#10243]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version
Dynamo Revit 2.0.3, Revit 2019

## Operating system
Window 10

## What did you do? 
I tried to get the elements by 'AllElementsofCategory' node. But, I got the popup error message.

## What did you see instead?
![image](https://user-images.githubusercontent.com/12069639/71430301-9084f480-2690-11ea-9d36-d9700cd9bc03.png)

Unhandled exception in Dynamo engine.
The virtual machine that powers Dynamo is experiencing some unexpected errors internally and is likely having great difficulties pulling itself together. ....

Runtime exception occured. The type of StackValue is not FunctionIndex

   
  at ProtoCore.DSASM.StackValue.get_FunctionIndex()
   at ProtoCore.DSASM.Executive.GetCurrentScope(Int32& classIndex, Int32& functionIndex)
   at ProtoCore.DSASM.Executive.DEP_Handler(Instruction instruction)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
   at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   at ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()

**Comment by Hyun-Tak** [comment]
I found my mistakes on the code block. I should have a capital ‘O’ for ‘OfCategory(c1)’. It works well after fixing the script.

**Comment by QilongTang** [comment]
@Hyun-Tak Still thank you for reporting, we will see you next time :)
