### ISSUE TITLE
Dynamo Unhandled Error Message - D_2.0.3.8810

### ISSUE THREAD

**Issue by Fluffy347** [DynamoDS/Dynamo#10265]
## Dynamo version
2.0.3.8810
## Revit Version
2.0.3.8811
## Operating system
Win10 64-B
## What did you do? 

I attempted to run a .DYN to retrieve the GUID of Revit elements. 

## What did you expect to see?

I expected to see the GUID of the Revit elements

## What did you see instead?

Received an error message about "Unhandled Exception Error". I have attached a screenshot of the message.

```
Runtime exception occured. The Type of StackValue is not Integer

   at ProtoCore.DSASM.StackValue.get_IntegerValue()
   at ProtoCore.DSASM.Executive.GetCurrentScope(Int32& classIndex, Int32& functionIndex)
   at ProtoCore.DSASM.Executive.DEP_Handler(Instruction instruction)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
   at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   at ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()
```

**Comment by Amoursol** [comment]
Hello @Fluffy347 ,

Could you please provide a screenshot of what you are attempting to do with your graph and/or upload the graph itself? 

As per the runtime exception, it appears that something is failing when the get_IntergerValue() call is being made. We'll need a little more information to be able to dig down into this one.

**Comment by Amoursol** [comment]
Hello @Fluffy347 - As we have not received any additional information to this issue and cannot progress any further, we are going to close it for now. Please reopen with additional information if you run into this issue again.
