### ISSUE TITLE
Crash report from Dynamo 2.5.0.7186

### ISSUE THREAD

**Issue by minjie1980** [DynamoDS/Dynamo#10281]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
I opened Dynamo 2.5 in Revit application, after running several Dynamo Revit sample scripts, and I would like to create a new Dynamo file, the crash just happened. Please notice there is no open dynamo files.

### What did you expect to see?
No crash when creating a new dynamo file.

### What did you see instead?
(Fill in here)

### What packages or external references (if any) were used?
No package has been downloaded.

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```
Starting a transaction from an external application running outside of API context is not allowed.

   at Autodesk.Revit.DB.Transaction.Start()
   at RevitServices.Transactions.TransactionWrapper.StartTransaction(Document document)
   at RevitServices.Transactions.TransactionManager.EnsureInTransaction(Document document)
   at RevitServices.Persistence.DocumentManager.DeleteElement(ElementUUID element)
   at ProtoFFI.CLRObjectMarshaler.core_Dispose(RuntimeCore sender)
   at ProtoCore.RuntimeCore.DisposeDelegate.Invoke(RuntimeCore sender)
   at ProtoCore.RuntimeCore.OnDispose()
   at ProtoScript.Runners.LiveRunner.Dispose(Boolean disposing)
   at Dynamo.Engine.LiveRunnerServices.Dispose()
   at Dynamo.Engine.EngineController.Dispose()
   at Dynamo.Models.DynamoModel.ResetEngineInternal()
   at Dynamo.Models.DynamoModel.ResetEngine(Boolean markNodesAsDirty)
   at Dynamo.ViewModels.DynamoViewModel.MakeNewHomeWorkspace(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---
OS: `Microsoft Windows NT 10.0.15063.0`
CLR: `4.0.30319.42000`
Dynamo: `2.5.0.7186`

**Comment by mjkkirschner** [comment]
@minjie1980 - this is a regression - tracked with https://jira.autodesk.com/browse/DYN-2379 @aparajit-pratap is on it.
