### ISSUE TITLE
Crash report from Dynamo 2.3.0.5885

### ISSUE THREAD

**Issue by sansha777** [DynamoDS/Dynamo#10299]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
Ran the graph

### What did you expect to see?
Load UI from graph (Data-Shapes)

### What did you see instead?
Dialog box saying there was an error and asking to send info to GitHub

### What packages or external references (if any) were used?
Data-Shapes v.2019.2.40
BumbleBee v.2019.2.1
BimorphNodes v.3.0.3
Hot Gear v.2017.11.9

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
`Index was outside the bounds of the array.

   at ProtoCore.DSASM.Executive.GetProcedureNode(Int32 blockId, Int32 classIndex, Int32 functionIndex)
   at ProtoCore.DSASM.Executive.UpdateMethodDependencyGraph(Int32 entry, Int32 procIndex, Int32 classIndex)
   at ProtoCore.DSASM.Executive.SetupExecutive(Int32 exeblock, Int32 entry)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
   at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   at ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()``

---
OS: `Microsoft Windows NT 10.0.17763.0`
CLR: `4.0.30319.42000`
Dynamo: `2.3.0.5885`

**Comment by Amoursol** [comment]
@mjkkirschner Is this an issue on our end or Mostafa's?

**Comment by mjkkirschner** [comment]
Looks like a problem in the vm when looking for a particular function - we’d need the graph to duplicate and steps - ie does it happen every time ? Because the stack trace is an extremely common function.

**Comment by sansha777** [comment]
FYI, the error message dissapeared when I unisnstalled/reinstalled the HotGear package.  Everything works properly at the moment.  I don't mind sending the graph if it can help, just let me know.

**Comment by mjkkirschner** [comment]
If the problem can be reproduced when you install that package, then yes please send all relevant info and steps for us to repro so we can fix it if possible.

**Comment by sansha777** [comment]
I was not able to reproduce it after reinstalling the package.

You can disregard this thread.

Regards,

Maxime Sanschagrin
Directeur BIM / BIM Director
[http://www.pageaumorel.com/signature/logo-pma.png]<http://www.pageaumorel.com/>
Pageau Morel et associés inc.
210, boul. Crémazie O., bur. 110
Montréal (Québec) H2P 1C6
T 514 382-5150 (2290) | C 438 494-6623


De : Michael Kirschner <notifications@github.com>
Envoyé : 3 février 2020 12:33
À : DynamoDS/Dynamo <Dynamo@noreply.github.com>
Cc : Sanschagrin Maxime <msanschagrin@pageaumorel.com>; Author <author@noreply.github.com>
Objet : Re: [DynamoDS/Dynamo] Crash report from Dynamo 2.3.0.5885 (#10299)


If the problem can be reproduced when you install that package, then yes please send all relevant info and steps for us to repro so we can fix it if possible.
