### ISSUE TITLE
Crash report from Dynamo 2.3.0.5885

### ISSUE THREAD

**Issue by yanksfan** [DynamoDS/Dynamo#10298]
# Issue Description
Please fill in the following information to help us reproduce the issue:
Dynamo Player for Revit 2020 does not open
### What did you do?
(Fill in here)
Pressed Dynamo Player button; Player does not open; Dynamo Player button becomes greyed out
### What did you expect to see?
(Fill in here)
Dynamo Player
### What did you see instead?
(Fill in here)
Nothing
### What packages or external references (if any) were used?
(Fill in here)

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```
Index was outside the bounds of the array.

   at ProtoCore.Lang.ArrayUtilsForBuiltIns.Transpose(StackValue sv, Interpreter runtime)
   at ProtoCore.Lang.BuiltInFunctionEndPoint.Execute(Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.CallSite.ExecWithZeroRI(List`1 functionEndPoint, Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore, SingleRunTraceData previousTraceData, SingleRunTraceData newTraceData, FunctionEndPoint finalFep)
   at ProtoCore.CallSite.Execute(List`1 functionEndPoint, Context c, List`1 formalParameters, List`1 replicationInstructions, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.CallSite.DispatchNew(Context context, List`1 arguments, List`1 partialReplicationGuides, DominantListStructure domintListStructure, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.DSASM.Executive.Callr(Int32 blockDeclId, Int32 functionIndex, Int32 classIndex, Boolean& explicitCall, Boolean isDynamicCall, Boolean hasDebugInfo)
   at ProtoCore.DSASM.Executive.CALLR_Handler(Instruction instruction)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
   at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   at ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()
---
OS: `Microsoft Windows NT 10.0.18363.0`
CLR: `4.0.30319.42000`
Dynamo: `2.3.0.5885`

**Comment by Amoursol** [comment]
Hello @yanksfan, would you please be able to tell us what you were aiming to do and what you expected to see?

**Comment by yanksfan** [comment]
I upgraded to Revit 2020 and installed all the updates for it. When I click on Dynamo player, it doesn’t open and the button gray’s.

**Comment by mjkkirschner** [comment]
where do you see this crash trace? Does it happen when you click Dynamo Player? Does Dynamo work by itself?

**Comment by Amoursol** [comment]
Hello @yanksfan - Unfortunately we haven't been able to make any progress on this, so will close for now. If this issue still persists for you, and you know what you were doing when it happened (i.e. a reproducible case) then please do re-open and append more information.
