### ISSUE TITLE
Archi-lab_Mandrill "Create Report" node causes Dynamo to Either Crash or Show Blank White Window

### ISSUE THREAD

**Issue by bonfylife** [DynamoDS/Dynamo#10381]
## Dynamo version

1.3.4.6666

## Operating system

Windows 10 Pro

## What did you do? 

Here's Code:

![Code](https://user-images.githubusercontent.com/60966324/74328710-749ff400-4d9f-11ea-80f0-9e82c6a2d8e4.png)

Revit 2016,17,18,19 were used with a sample project. Also I tried with a different project.

## What did you expect to see?

Something Like This:

![Expected to see](https://user-images.githubusercontent.com/60966324/74327955-23dbcb80-4d9e-11ea-8b48-156a5a6a6c43.PNG)

## What did you see instead?

***With Archi-lab_Mandrill 2017.11.3 it shows blank white screen

![Blank](https://user-images.githubusercontent.com/60966324/74330374-9fd81280-4da2-11ea-916d-4fea00db6435.PNG)

***With Archi-lab_Mandrill 2018.0.2 Dynamo Crashes

Here are the issue details:

Operation is not valid due to the current state of the object.

   at EO.Internal.jh.a(Boolean& A_0, String[] A_1, String A_2, String A_3, String A_4, String A_5)
   at EO.Internal.jh.a(String[] A_0, String A_1, String A_2, String A_3, String A_4)
   at EO.Internal.jh.o.c()
   at EO.Internal.jh.o.f()
   at EO.Internal.jh.l()
   at EO.Internal.jh.a(Boolean& A_0, String[] A_1, String A_2, String A_3, String A_4, String A_5)
   at EO.Internal.jh.a(String[] A_0, String A_1, String A_2, String A_3, String A_4)
   at EO.Internal.awp.e()
   at EO.WebEngine.Engine.Start()
   at EO.Internal.awp.a()
   at EO.Internal.cm..ctor(WebView A_0)
   at EO.WebBrowser.WebView.w()
   at EO.WebBrowser.WebView.b(IntPtr A_0, Boolean A_1)
   at EO.WebBrowser.Wpf.WebControl.a.a(HandleRef A_0)
   at System.Windows.Interop.HwndHost.BuildWindow(HandleRef hwndParent)
   at System.Windows.Interop.HwndHost.BuildOrReparentWindow()
   at System.Windows.Interop.HwndHost.OnSourceChanged(Object sender, SourceChangedEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.PresentationSource.UpdateSourceOfElement(DependencyObject doTarget, DependencyObject doAncestor, DependencyObject doOldParent)
   at System.Windows.PresentationSource.OnVisualAncestorChanged(DependencyObject uie, AncestorChangedEventArgs e)
   at System.Windows.UIElement.OnVisualAncestorChanged(Object sender, AncestorChangedEventArgs e)
   at System.Windows.Media.Visual.ProcessAncestorChangedNotificationRecursive(DependencyObject e, AncestorChangedEventArgs args)
   at System.Windows.Media.Visual.AddVisualChild(Visual child)
   at System.Windows.Controls.Decorator.set_Child(UIElement value)
   at EO.WebBrowser.Wpf.WebControl.OnApplyTemplate()
   at System.Windows.FrameworkElement.ApplyTemplate()
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Grid.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at MS.Internal.Helper.MeasureElementWithSingleChild(UIElement element, Size constraint)
   at System.Windows.Controls.ContentPresenter.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Documents.AdornerDecorator.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Border.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Window.MeasureOverrideHelper(Size constraint)
   at System.Windows.Window.MeasureOverride(Size availableSize)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Interop.HwndSource.SetLayoutSize()
   at System.Windows.Interop.HwndSource.set_RootVisualInternal(Visual value)
   at System.Windows.Window.SetRootVisual()
   at System.Windows.Window.SetRootVisualAndUpdateSTC()
   at System.Windows.Window.SetupInitialState(Double requestedTop, Double requestedLeft, Double requestedWidth, Double requestedHeight)
   at System.Windows.Window.CreateSourceWindow(Boolean duringShow)
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at Mandrill.ChromeWindow.MandrillWindowNodeViewCustomization.CreateNewWindow()
   at Mandrill.ChromeWindow.MandrillWindowNodeViewCustomization.<CustomizeView>b__4_0()
   at Mandrill.ChromeWindow.MandrillWindowNodeModel.ShowMessage(Object obj)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

***

**Comment by mjkkirschner** [comment]
Hi @bonfylife - you should report this here:
https://github.com/BadMonkeysTeam/Mandrill
