### ISSUE TITLE
Crash report from Dynamo 2.3.0.5885

### ISSUE THREAD

**Issue by ViktorKuzev** [DynamoDS/Dynamo#10409]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
CUrve.PointAtParameter crashes Dynamo repeatedly
### What did you expect to see?
(Fill in here)

### What did you see instead?
(Fill in here)

### What packages or external references (if any) were used?
(Fill in here)

### Stack Trace
```
Could not find parameter at Point

   at Autodesk.LibG.PolyCurve.parameter_at_point(Point p)
   at Dynamo.Manipulation.PointOnCurveManipulator.UpdatePosition()
   at Dynamo.Manipulation.NodeManipulator.GenerateRenderPackages()
   at Dynamo.Manipulation.NodeManipulator.DrawManipulator()
   at Dynamo.Manipulation.NodeManipulator..ctor(NodeModel node, DynamoManipulationExtension manipulatorContext)
   at Dynamo.Manipulation.PointOnCurveManipulatorFactory.Create(NodeModel node, DynamoManipulationExtension manipulatorContext)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dynamo.Manipulation.ZeroTouchManipulatorFactory.Create(NodeModel node, DynamoManipulationExtension manipulatorContext)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dynamo.Manipulation.ManipulatorDaemon.CreateManipulator(NodeModel model, DynamoManipulationExtension manipulatorContext)
   at Dynamo.Manipulation.DynamoManipulationExtension.TryCreateManipulator(NodeModel node)
   at Dynamo.Manipulation.DynamoManipulationExtension.CreateManipulators(IEnumerable`1 nodes)
   at Dynamo.Wpf.Extensions.ViewLoadedParams.OnSelectionCollectionChanged(Object sender, NotifyCollectionChangedEventArgs notifyCollectionChangedEventArgs)
   at System.Collections.Specialized.NotifyCollectionChangedEventHandler.Invoke(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.InsertItem(Int32 index, T item)
   at Dynamo.Models.DynamoModel.SelectModelImpl(SelectModelCommand command)
   at Dynamo.Models.DynamoModel.ExecuteCommand(RecordableCommand command)
   at Dynamo.UI.Controls.PreviewControl.OnMapPinMouseClick(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

---
OS: `Microsoft Windows NT 10.0.17134.0`
CLR: `4.0.30319.42000`
Dynamo: `2.3.0.5885`

**Comment by Amoursol** [comment]
Hello @ViktorKuzev  - Unfortunately we haven't been able to make any progress on this, so will close for now. If this issue still persists for you, and you know what you were doing when it happened (i.e. a reproducible case) then please do re-open and append more information.
