### ISSUE TITLE
Crash report from Dynamo 2.3.0.5885

### ISSUE THREAD

**Issue by lakshyanakc** [DynamoDS/Dynamo#10436]
# Issue Description
Please fill in the following information to help us reproduce the issue:
![Error](https://user-images.githubusercontent.com/43673188/75818837-9ae5fd80-5d67-11ea-92f4-2f328155e72d.png)

### What did you do?
(Fill in here)
I was running a dynamo script periodically. It runs fine for roughly 100 runs, and then crashes and shows the error message as attacged
### What did you expect to see?
(Fill in here)

### What did you see instead?
(Fill in here)

### What packages or external references (if any) were used?
(Fill in here)

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
OS: `Microsoft Windows NT 6.2.9200.0`
CLR: `4.0.30319.42000`
Dynamo: `2.3.0.5885`

**Comment by mjkkirschner** [comment]
@aparajit-pratap thoughts? It looks like the runtime memory continues to grow - but in periodic mode shouldn't the vm be reset?

**Comment by mjkkirschner** [comment]
@lakshyanakc thanks for the report - can you attach the graph in question with all necessary dependencies to run it? Or a simpler graph which reproduces the issue?

**Comment by lakshyanakc** [comment]
Thanks for your response. Here's the link to the folder with the script and other dependencies for your reference. [https://drive.google.com/open?id=1GbUzBlirr5PYMf9I4vpvAnPilldtixu0](url)

**Comment by faizanmaaz** [comment]
Runtime exception occured. The Type of StackValue is not Integer

   at ProtoCore.DSASM.StackValue.get_IntegerValue()
   at ProtoCore.DSASM.Executive.GetCurrentScope(Int32& classIndex, Int32& functionIndex)
   at ProtoCore.DSASM.Executive.DEP_Handler(Instruction instruction)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
   at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   at ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()

**Comment by avidit** [comment]
tracked internally [DYN-6222](https://jira.autodesk.com/browse/DYN-6222)
