### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Akitsmiller** [DynamoDS/Dynamo#10551]
Was using dynamo to export multiple merged sheets from Revit to dwg from documents 

Runtime exception occured. The Type of StackValue is not ClassIndex

   at ProtoCore.DSASM.StackValue.get_ClassIndex()
   at ProtoCore.DSASM.Executive.GetCallerInformation(Int32& classIndex, Int32& functionIndex)
   at ProtoCore.DSASM.Executive.Callr(Int32 blockDeclId, Int32 functionIndex, Int32 classIndex, Boolean& explicitCall, Boolean isDynamicCall, Boolean hasDebugInfo)
   at ProtoCore.DSASM.Heap.GCDisposeObject(StackValue svPtr, Executive exe)
   at ProtoCore.DSASM.Heap.Sweep()
   at ProtoCore.DSASM.Heap.SingleStep(Boolean forceGC)
   at ProtoCore.DSASM.Heap.FullGC(IEnumerable`1 gcroots, Executive exe)
   at ProtoScript.Runners.LiveRunner.ApplyUpdate()
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()

**Comment by Amoursol** [comment]
Hello @Akitsmiller ,

Would you please be able to tell us the version of Dynamo and Revit you were using, as well as provide a mock-up script of what you were trying to achieve?
