### ISSUE TITLE
Crash report from Dynamo 2.3.0.5885

### ISSUE THREAD

**Issue by askgrkumar** [DynamoDS/Dynamo#10759]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
Custom Colored Option from Monocle

### What did you expect to see?
to Get the Custom Colors for my Nodes & Custom Nodes

### What did you see instead?
Dynamo Crashed - BUG

### What packages or external references (if any) were used?
Monocle

### Stack Trace
```
'Initialization of 'Xceed.Wpf.Toolkit.ColorPicker' threw an exception.' Line number '20' and line position '206'.

   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at MonocleViewExtension.ColorCodeGroups.ColorCodeWindow.InitializeComponent()
   at MonocleViewExtension.ColorCodeGroups.ColorCodeWindow..ctor()
   at MonocleViewExtension.MonocleViewExtension.<>c__DisplayClass16_0.<Loaded>b__3(Object sender, RoutedEventArgs args)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

---
OS: `Microsoft Windows NT 10.0.18363.0`
CLR: `4.0.30319.42000`
Dynamo: `2.3.0.5885`

**Comment by aparajit-pratap** [comment]
FYI: @johnpierson

**Comment by Amoursol** [comment]
Closing this as it's an issue for the **Monocle Extension** from @johnpierson

**Comment by johnpierson** [comment]
And I fixed it here. 🙂 https://github.com/johnpierson/MonocleForDynamo/issues/11
