### ISSUE TITLE
Crash report from Dynamo 2.3.0.5885

### ISSUE THREAD

**Issue by skyyyyboi** [DynamoDS/Dynamo#10808]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
Tried to use custom color grouping from drop down menu (also happens with other tools, Doge is fine tho)

### What did you expect to see?
the same pop up window as the previous version

### What did you see instead?
crash report

### What packages or external references (if any) were used?
none

### Stack Trace
```
Initialization of 'Xceed.Wpf.Toolkit.ColorPicker' threw an exception.

   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at MonocleViewExtension.ColorCodeGroups.ColorCodeWindow..ctor()
   at MonocleViewExtension.MonocleViewExtension.<>c__DisplayClass22_0.<Loaded>b__7(Object sender, RoutedEventArgs args)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

---
OS: `Microsoft Windows NT 10.0.18362.0`
CLR: `4.0.30319.42000`
Dynamo: `2.3.0.5885`

**Comment by mjkkirschner** [comment]
you should report this here:
https://github.com/johnpierson/MonocleForDynamo

you are using monocole
`at MonocleViewExtension.ColorCodeGroups.ColorCodeWindow..ctor()`

**Comment by skyyyyboi** [comment]
thanks
