### ISSUE TITLE
Отчет о сбое в Dynamo 2.5.0.7460

### ISSUE THREAD

**Issue by maravillosome** [DynamoDS/Dynamo#10806]
# Error : Index was outside the bounds of the array.
Please Help! The whole project is going to be crashed!!

### What did you do?
Tried to use List.Combine to combine to lists (a group of points) and then flatten them (using List.map with function List.Flatten) 

### What did you expect to see?
A combined group of points

### What did you see instead?
Error

### What packages or external references (if any) were used?
None (except Clockwork List.DropLastItem at the beginning)

### Stack Trace
 at ProtoCore.DSASM.Executive.GetProcedureNode(Int32 blockId, Int32 classIndex, Int32 functionIndex)
   at ProtoCore.DSASM.Executive.UpdateMethodDependencyGraph(Int32 entry, Int32 procIndex, Int32 classIndex)
   at ProtoCore.DSASM.Executive.SetupExecutive(Int32 exeblock, Int32 entry)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
   at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   at ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()

---
OS: `Microsoft Windows NT 10.0.19041.0`
CLR: `4.0.30319.42000`
Dynamo: `2.5.0.7460`

**Comment by Amoursol** [comment]
Hello @maravillosome - is it possible for you to upload your dynamo file?

**Comment by Amoursol** [comment]
Hello @maravillosome  -  As we have not received any additional information in the past 3 weeks we are going to close for now. If you can provide us your Dynamo file then we can try and reproduce this issue to fix on our end and re-open this issue.
