### ISSUE TITLE
Crash report from Dynamo 2.4.1.6394

### ISSUE THREAD

**Issue by MissmelissaL** [DynamoDS/Dynamo#10817]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
Open new dynamo workspace and places import data node Data.importexcel from dynamo internal library

### What did you expect to see?
node in graph

### What did you see instead?
Error message pop up window

### What packages or external references (if any) were used?
None

### Stack Trace
```
Runtime exception occured. The Type of StackValue is not Integer

   at ProtoCore.DSASM.StackValue.get_IntegerValue()
   at ProtoCore.DSASM.Executive.GetCurrentScope(Int32& classIndex, Int32& functionIndex)
   at ProtoCore.DSASM.Executive.DEP_Handler(Instruction instruction)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
   at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   at ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()
```

---
OS: `Microsoft Windows NT 10.0.17134.0`
CLR: `4.0.30319.42000`
Dynamo: `2.4.1.6394`

**Comment by aparajit-pratap** [comment]
@MissmelissaL could you list any packages you had installed if any?

**Comment by MissmelissaL** [comment]
![1593438674561944215624059861176](https://user-images.githubusercontent.com/66793695/86014257-18f0a300-b9ee-11ea-96fc-12491a29509f.jpg)

**Comment by Amoursol** [comment]
Hello @MissmelissaL - Unfortunately we haven't been able to make any progress on this, so will close for now. If this issue still persists for you, and you know what you were doing when it happened (i.e. a reproducible case) then please do re-open and append more information.
