### ISSUE TITLE
Crash report from Dynamo 2.4.1.6394

### ISSUE THREAD

**Issue by MissmelissaL** [DynamoDS/Dynamo#10816]
# Issue Description
Dynamo will not run the graph and every node has a null value

### What did you do?
Modified nodes with is input testing in dynamo player

### What did you expect to see?
Run completed or run with warnings and see values at each node 

### What did you see instead?
Nulls for every node including the first node which is an import or an excel file

### What packages or external references (if any) were used?
Data-shapes, Bake ++

### Stack Trace
```
Retrive attribute failed.

   at Autodesk.Civil.AttributeHelper.getAttributeGeneric<AeccAtom>(AeccAtom* , UInt32 attributeId, IAeccAttributeBin* pAttrBin, AeccUserParam* userParam)
   at Autodesk.Civil.AttributeHelper.getAttributeAeccAtom(AeccAtom* , UInt32 attributeId, IAeccAttributeBin* pAttrBin, AeccUserParam* userParam)
   at Autodesk.Civil.AttributeHelper.getAttributeAeccAtom(AeccAtom* , UInt32 attributeId, IAeccAttributeBin* pAttrBin)
   at Autodesk.Civil.DatabaseServices.Entity.get_Name()
   at Autodesk.Civil.DynamoNodes.CivilObject.ToString()
   at ProtoFFI.CLRObjectMarshaler.GetStringValue(StackValue dsObject)
   at ProtoCore.DSASM.Mirror.ExecutionMirror.GetClassTrace(StackValue val, Heap heap, Int32 langblock, Boolean forPrint)
   at ProtoCore.DSASM.Mirror.ExecutionMirror.GetStringValue(StackValue val, Heap heap, Int32 langblock, Int32 maxArraySize, Int32 maxOutputDepth, Boolean forPrint)
   at ProtoCore.Utils.StringUtils.ConvertToString(StackValue sv, RuntimeCore runtimeCore, RuntimeMemory rmem)
   at ProtoCore.Lang.BuiltInFunctionEndPoint.Execute(Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.CallSite.ExecWithZeroRI(List`1 functionEndPoint, Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore, SingleRunTraceData previousTraceData, SingleRunTraceData newTraceData, FunctionEndPoint finalFep)
   at ProtoCore.CallSite.Execute(List`1 functionEndPoint, Context c, List`1 formalParameters, List`1 replicationInstructions, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.CallSite.DispatchNew(Context context, List`1 arguments, List`1 partialReplicationGuides, DominantListStructure domintListStructure, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.DSASM.Executive.Callr(Int32 blockDeclId, Int32 functionIndex, Int32 classIndex, Boolean& explicitCall, Boolean isDynamicCall, Boolean hasDebugInfo)
   at ProtoCore.DSASM.Executive.CALLR_Handler(Instruction instruction)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
   at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   at ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()
```
---
OS: `Microsoft Windows NT 10.0.17134.0`
CLR: `4.0.30319.42000`
Dynamo: `2.4.1.6394`

**Comment by QilongTang** [comment]
@angelowang Who would be the best guy to look at this on Civil end?

**Comment by angelowang** [comment]
It seems some exception is thrown when trying to get the civil object name... and this name is used when showing Dynamo node description. There are two issues to find out:
- What is the object type? Or any other reason causing the getting name failure? @MissmelissaL 
- Is Dynamo Core or Civil 3D node responsible for catching the exception from ToString()? Is there an easy fix on Dynamo Core side? @QilongTang 

cc @CoolStarLee

**Comment by mjkkirschner** [comment]
should be addressed by:
https://github.com/DynamoDS/Dynamo/pull/10952
