### ISSUE TITLE
Design code sin(theta), cos(theta)

### ISSUE THREAD

**Issue by brianAboye** [DynamoDS/Dynamo#10829]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.0.3.811

## Operating system

Windows 10

## What did you do? 

theta=45.0;
Math.cos(theta);
Math.sin(theta);

## What did you expect to see?

(Fill in here)

## What did you see instead?
Runtime exception occured. The Type of StackValue is not Integer

   at ProtoCore.DSASM.StackValue.get_IntegerValue()
   at ProtoCore.DSASM.Executive.GetCurrentScope(Int32& classIndex, Int32& functionIndex)
   at ProtoCore.DSASM.Executive.DEP_Handler(Instruction instruction)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
   at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   at ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()

**Comment by Amoursol** [comment]
Hello @brianAboye,

I cannot reproduce this issue - were you simply trying to write this code in a Codeblock as shown in my screenshot below?

1. Your code has lowercase `cos` and `sin` - which will throw a syntax error. If you make the capitalized, it works in Dynamo 2.7 😊 

![image](https://user-images.githubusercontent.com/12857357/87799222-fac2d980-c81a-11ea-81f4-9790120fc226.png)

**Comment by brianAboye** [comment]
Yes. it is fine now. it was because of the lowercase
