### ISSUE TITLE
Crash report from Dynamo 2.3.0.5885

### ISSUE THREAD

**Issue by AnthonyViscusi** [DynamoDS/Dynamo#10954]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
Went to File > New > Custom Node

### What did you expect to see?
After filling in the form, and hitting create it makes the editing environment then crashes.  This is repeatable.

### What did you see instead?
Crash.

### What packages or external references (if any) were used?
I have numerous packages installed but none were used.  I was just starting the Custom Node command.

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```Object reference not set to an instance of an object.

   at DynaStandard.DynaStandardEvents.NewDynamoRunTypeChange(Object sender, PropertyChangedEventArgs e)
   at System.ComponentModel.PropertyChangedEventHandler.Invoke(Object sender, PropertyChangedEventArgs e)
   at Microsoft.Practices.Prism.ViewModel.NotificationObject.RaisePropertyChanged(String propertyName)
   at Dynamo.ViewModels.DynamoViewModel.set_ShowStartPage(Boolean value)
   at Dynamo.ViewModels.DynamoViewModel.ShowNewFunctionDialogAndMakeFunction(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

---
OS: `Microsoft Windows NT 10.0.16299.0`
CLR: `4.0.30319.42000`
Dynamo: `2.3.0.5885`

**Comment by mjkkirschner** [comment]
Hi @AnthonyViscusi you should report this to the author of DynamoStandard:
https://github.com/brencass/DynaStandard_public
