### ISSUE TITLE
Отчет о сбое в Dynamo 2.3.0.5885

### ISSUE THREAD

**Issue by GeorgGrebenyuk** [DynamoDS/Dynamo#11148]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
Uploading custom node (DLL) for Revit 2020.3 with Nuget package ZeroTouchLibrary (Net Framework 4.7). Node contained XML-description. Without it all imported correctly
All files in attachment

Below my XML-file
<?xml version="1.0"?>
<doc>
    <assembly>
        <name>RevitGP_AnalyzeSurface_ver3</name>
    </assembly>
    <members>
        <member name="M:RevitGP_AnalyzeSurface_ver3.TopoAnalyze.ReadXML_file_ForGetElevationVersion2(System.Double,System.Double,System.String)">
            <summary> ReadXML_file_ForGetElevationVersion2 read XMK-description of surface ang get Z-value of point (from input X,Y coordinate)</summary>
            <param name="X_coord">Revit's X coordinate, meters</param>>
            <param name="Y_coord">Revit's Y coordinate, meters</param>>
            <param name="data_input">Absolute path to file besides quotation marks, for example: "C:\Work\Code\_Experiments\AnalyzeSurface\00_IW-model-all_002.xml"</param>>
            <returns>Value of elevation, meters</returns>
            <search>XML, elevation, triangulation, surface</search>
        </member>
    </members>
</doc>

### What did you expect to see?
Correct import to Dynamo for Revit (in Dynamo Sandbox all were imported correctly independent language of comments - XML's par
[Debug.zip](https://github.com/DynamoDS/Dynamo/files/5288358/Debug.zip)

am names)
### What did you see instead?
Error screen (contains below)

### What packages or external references (if any) were used?
ZeroTouchLibrary ver 2,1,0,7465

### Stack Trace
```
An item with the same key has already been added.

   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Dynamo.Engine.XmlDocumentationExtensions.LoadDataFromXml(XmlReader reader, String assemblyName)
   at Dynamo.Engine.XmlDocumentationExtensions.GetMemberDocumentNode(FunctionDescriptor function, XmlReader xml)
   at Dynamo.Engine.XmlDocumentationExtensions.GetMemberElement(FunctionDescriptor function, XmlReader xml, DocumentElementType property, String paramName)
   at Dynamo.Engine.FunctionDescriptor.get_Summary()
   at Dynamo.Engine.FunctionDescriptor.get_Description()
   at Dynamo.Search.SearchElements.ZeroTouchSearchElement..ctor(FunctionDescriptor functionDescriptor)
   at Dynamo.Models.DynamoModel.AddZeroTouchNodeToSearch(FunctionGroup funcGroup)
   at Dynamo.Models.DynamoModel.AddZeroTouchNodesToSearch(IEnumerable`1 functionGroups)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Dynamo.Engine.LibraryServices.OnLibraryLoaded(LibraryLoadedEventArgs e)
   at Dynamo.Engine.LibraryServices.ImportLibrary(String library, Boolean isExplicitlyImportedLib)
   at Dynamo.ViewModels.DynamoViewModel.ImportLibrary(Object parameter)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

---
OS: `Microsoft Windows NT 10.0.18363.0`
CLR: `4.0.30319.42000`
Dynamo: `2.3.0.5885`

**Comment by mjkkirschner** [comment]
@GeorgGrebenyuk does this node have a compile time dependency on RevitAPI? This may be why no crash occurred importing it into sandbox.

Does your binary contain overloads or multiple functions with the same name - or only a single function?
