### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Reda2688** [DynamoDS/Dynamo#11183]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.
Object reference not set to an instance of an object.

   at ProtoCore.DSASM.Heap.Sweep()
   at ProtoCore.DSASM.Heap.SingleStep(Boolean forceGC)
   at ProtoCore.DSASM.Heap.FullGC(IEnumerable`1 gcroots, Executive exe)
   at ProtoScript.Runners.LiveRunner.ApplyUpdate()
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()
![image](https://user-images.githubusercontent.com/72881738/96019232-408f3e00-0e1a-11eb-84e9-79ab3fedf378.png)

## Dynamo version
2.0.4.12684
(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Operating system
windows 10
(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 

architectural designer

## What did you expect to see?

the graph run, assigned material to my objects

## What did you see instead?
the errors above

**Comment by mjkkirschner** [comment]
Hi @Reda2688 can you please list Revit version and attach the required .dyn and .rvt files for us to reproduce this issue?
