### ISSUE TITLE
Crashing when connecting up XYZ points

### ISSUE THREAD

**Issue by michaelbergin** [DynamoDS/Dynamo#1119]
Collection was modified; enumeration operation may not execute.

    at System.Collections.Generic.Dictionary`2.ValueCollection.Enumerator.MoveNext()
    at System.Linq.Enumerable.<SelectManyIterator>d__14`2.MoveNext()
    at Dynamo.Utilities.ExtensionMethods.ToThreadSafeList[TSource](IEnumerable`1 source)
    at Dynamo.VisualizationManager.AggregateRenderDescriptions()
    at Dynamo.VisualizationManager.RenderUpstream(NodeModel node)
    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
    at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32

**Comment by ikeough** [comment]
Closing as out of date. If this is still an error in more recent builds, please re-open.
