### ISSUE TITLE
Curve.Reverse keep crashing Dynamo Sandbox

### ISSUE THREAD

**Issue by LUC-ian** [DynamoDS/Dynamo#11222]
## Dynamo version

Dynamo Core 2.8.0.2471

## Operating system

Windows 10 Home

## What did you do? 

I have a curve projected on two inclined plans, hence I get two curves after he operation. I want to reverse the direction of one curve, so I decompose the list, and then try to reverse the first curve.  

## What did you expect to see?

That the curve direction is reversed. 

## What did you see instead?

Dynamo crashing. 

## Error log. 
here is the log I get in the console when running the executable from the terminal. 
`Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

   at Autodesk.LibG.LibGPINVOKE.Curve_reverse__SWIG_0(HandleRef jarg1)
   at Autodesk.LibG.Curve.reverse(Curve ptr)
   at Autodesk.LibG.CurveHost.Reverse()
   at Autodesk.DesignScript.Geometry.Curve.Reverse()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at ProtoFFI.FFIMethodInfo.Invoke(Object thisObject, Object[] parameters)
   at ProtoFFI.CLRFFIFunctionPointer.InvokeFunctionPointerNoThrow(Context c, Interpreter dsi, Object thisObject, Object[] parameters)
   at ProtoFFI.CLRFFIFunctionPointer.Execute(Context c, Interpreter dsi, List`1 s)
   at ProtoCore.Lang.FFIFunctionEndPoint.Execute(Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.CallSite.ExecWithZeroRI(List`1 functionEndPoint, Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore, SingleRunTraceData previousTraceData, SingleRunTraceData newTraceData, FunctionEndPoint finalFep)
   at ProtoCore.CallSite.ExecWithRISlowPath(List`1 functionEndPoint, Context c, List`1 formalParameters, List`1 replicationInstructions, StackFrame stackFrame, RuntimeCore runtimeCore, SingleRunTraceData previousTraceData, SingleRunTraceData newTraceData, FunctionEndPoint finalFunctionEndPoint)
   at ProtoCore.CallSite.ExecWithRISlowPath(List`1 functionEndPoint, Context c, List`1 formalParameters, List`1 replicationInstructions, StackFrame stackFrame, RuntimeCore runtimeCore, SingleRunTraceData previousTraceData, SingleRunTraceData newTraceData, FunctionEndPoint finalFunctionEndPoint)
   at ProtoCore.CallSite.Execute(List`1 functionEndPoint, Context c, List`1 formalParameters, List`1 replicationInstructions, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.CallSite.DispatchNew(Context context, List`1 arguments, List`1 partialReplicationGuides, DominantListStructure domintListStructure, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.DSASM.Executive.Callr(Int32 blockDeclId, Int32 functionIndex, Int32 classIndex, Boolean& explicitCall, Boolean isDynamicCall, Boolean hasDebugInfo)
   at ProtoCore.DSASM.Executive.CALLR_Handler(Instruction instruction)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
   at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   at ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()
   at Dynamo.Scheduler.DynamoScheduler.ProcessTaskInternal(AsyncTask asyncTask)
   at Dynamo.Scheduler.DynamoScheduler.ProcessNextTask(Boolean waitIfTaskQueueIsEmpty)
   at Dynamo.Scheduler.DynamoSchedulerThread.ThreadProc()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
`
## Dynamo Definition
I could not attach the dynamo definition, but I provide here a download link from the google drive. 
https://drive.google.com/file/d/1TzVmpZge-3Sokpd4dPgPiPKMLi2xhGdH/view?usp=sharing

**Comment by mmisol** [comment]
Hi @LUC-ian. First of all, thanks for taking the time to provide all this information.

Taking a look at the error, it seems to originate from LibG, which is the library Dynamo uses to interact with ASM, the Autodesk geometry library shipped with most products. In order to determine which version of LibG/ASM you are using, can you tell us which version of an Autodesk product, probably Revit, you have installed on your machine?

Also I tried to access the file you shared in Google Drive and I couldn't access it but was asked to request access. If that was intentional I can provide my e-mail address. Please let me know.

Thank you and have a good day!

**Comment by mmisol** [comment]
I tried this with ASM 226 and 225 and it didn't crash for me using DynamoCoreRuntime_2.8.0.2471_20200908T2048.zip from dynamobuilds.com. @mjkkirschner Do you think there is anything else we could try?

**Comment by LUC-ian** [comment]
@mmisol sorry I forgot to mention...there is a parameter Arches.InclinationAngle changes his value...currently it is set to zero... change the value and it will crash...

**Comment by mmisol** [comment]
Thanks @LUC-ian . Changing that to 18 I was able to reproduce the error. It's also reproducible with our latest binaries. 
I believe we have all the info we need to investigate the issue. We'll let you know of any updates we have. Thanks for helping us get better!

**Comment by LUC-ian** [comment]
Thanks @mmisol for looking into this, and I'm looking forward to have any updates on this issue.

**Comment by mjkkirschner** [comment]
this fix should be in master now - closing.

**Comment by LUC-ian** [comment]
hi @mjkkirschner I'm assuming the fix is available when downloading the daily builds, and not for the Dynamo Sandbox release, right?
