### ISSUE TITLE
Crash report from Dynamo 2.3.0.5885

### ISSUE THREAD

**Issue by DynamoGuy** [DynamoDS/Dynamo#11234]
[PC3 Mechanical Single Zone VRP Tool.zip](https://github.com/DynamoDS/Dynamo/files/5491649/PC3.Mechanical.Single.Zone.VRP.Tool.zip)

# Issue Description
I have a very large DYN that I'm running in Revit.  It pulls data from the Spaces, Zones, and Mechanical Equipment and use it to perform engineering calculations that determine the required ventilation airflow.

### What did you do?
This DYN has been in use before, but I've been making continual changes to it.  It was created in 1.3x and I recently upgraded it to 2.x.  

It was working after swapping out the Clockwork nodes for their 2.x versions.

I tried to use it today and started seeing errors and a dialog box recomending that I restart Dynamo.

### What did you expect to see?
The DYN had been completing with no errors.

### What did you see instead?
Numerous nodes that were working are turning yellow.

### What packages or external references (if any) were used?
Clockwork 2.3
spring nodes

### Stack Trace
```
Index was outside the bounds of the array.

   at ProtoCore.DSASM.Executive.GetProcedureNode(Int32 blockId, Int32 classIndex, Int32 functionIndex)
   at ProtoCore.DSASM.Executive.UpdateMethodDependencyGraph(Int32 entry, Int32 procIndex, Int32 classIndex)
   at ProtoCore.DSASM.Executive.SetupExecutive(Int32 exeblock, Int32 entry)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
   at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   at ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()
```

---
OS: `Microsoft Windows NT 10.0.18362.0`
CLR: `4.0.30319.42000`
Dynamo: `2.3.0.5885`

**Comment by mjkkirschner** [comment]
Hi @DynamoGuy what version of Revit are you using?

**Comment by DynamoGuy** [comment]
Hi Michael,



I was able to work around the problem, but thanks for reaching out.  The
graph I was using was made in 1.3 but has been upgraded to 2.x.



Robert



*From:* Michael Kirschner <notifications@github.com>
*Sent:* Wednesday, December 2, 2020 2:52 PM
*To:* DynamoDS/Dynamo <Dynamo@noreply.github.com>
*Cc:* DynamoGuy <robert.baillet@taiengineering.com>; Mention <
mention@noreply.github.com>
*Subject:* [EXTERNAL] Re: [DynamoDS/Dynamo] Crash report from Dynamo
2.3.0.5885 (#11234)



Hi @DynamoGuy <https://github.com/DynamoGuy> what version of Revit are you
using?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/DynamoDS/Dynamo/issues/11234#issuecomment-737457842>,
or unsubscribe

**Comment by mjkkirschner** [comment]
I'm going to close this as it seems the included .dyn is not enough to reproduce this without additional files and its been quite while - please reopen if you have repro steps and rvt files etc.
