### ISSUE TITLE
Crash report from Dynamo 2.3.0.5885

### ISSUE THREAD

**Issue by jdefrates** [DynamoDS/Dynamo#11343]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
(Fill in here)changed the node package path
### What did you expect to see?
(Fill in here)Acceptance of the accept changes

### What did you see instead?
(Fill in here)

### What packages or external references (if any) were used?
(Fill in here)n/a
Dynamo has crashed

### Stack Trace
```
![image](https://user-images.githubusercontent.com/70775924/101412220-121c6500-3897-11eb-81d8-6e4d0b418551.pn

(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```
Could not load file or assembly 'file:///C:\Users\jdefrates\Prime\PNC-VCS - 00-Software\01-Automation\02-Dynamo\00 Nodes\Bakery\bin\Package.customization.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)

   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Dynamo.PackageManager.PackageLoader.TryLoadFrom(String filename, Assembly& assem)
   at Dynamo.PackageManager.Package.EnumerateAssembliesInBinDirectory()
   at Dynamo.PackageManager.PackageLoader.<>c.<LoadPackages>b__50_0(Package x)
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Dynamo.Models.DynamoModel.LibraryLoaded(Object sender, LibraryLoadedEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Dynamo.Engine.LibraryServices.OnLibrariesImported(LibraryLoadedEventArgs e)
   at Dynamo.PackageManager.PackageLoader.LoadPackages(IEnumerable`1 packages)
   at Dynamo.PackageManager.PackageLoader.LoadAll(LoadPackageParams loadPackageParams)
   at Dynamo.PackageManager.PackageLoader.LoadCustomNodesAndPackages(LoadPackageParams loadPackageParams, CustomNodeManager customNodeManager)
   at Dynamo.ViewModels.PackagePathViewModel.CommitChanges(Object param)
   at Dynamo.Wpf.Views.PackageManager.PackagePathView.OnOkButtonClicked(Object sender, RoutedEventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---
OS: `Microsoft Windows NT 10.0.18363.0`
CLR: `4.0.30319.42000`
Dynamo: `2.3.0.5885`

**Comment by mjkkirschner** [comment]
are you trying to load packages from a network drive or did you download this package manually?
https://stackoverflow.com/questions/34400546/could-not-load-file-or-assembly-operation-is-not-supported-exception-from-hres

**Comment by jdefrates** [comment]
From a network Drive. I am attempting to centralize the location of my Company’s Node library. I copied the files from the Appdata folder to the network drive location.

I get the issue in both 2020 and 2021.

Jason De Frates


PRIME ELECTRIC   O: 925.961.1600 | C: 669.210.6160 | D: 669.214.2036
1941 RINGWOOD AVE SAN JOSE, CA 95131 | primee.com

**Comment by mjkkirschner** [comment]
please see:
https://github.com/DynamoDS/Dynamo/wiki/Loading-Packages-with-Binaries-from-a-Network-Location
