### ISSUE TITLE
Crash report from Dynamo 2.3.0.5885

### ISSUE THREAD

**Issue by LinasMM** [DynamoDS/Dynamo#11391]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
Created a code block, typed in test (with no ", not a string) and run the script

### What did you expect to see?
code block to be created

### What did you see instead?
An error message

### What packages or external references (if any) were used?
No packages were used.
There are some packages installed in the dynamo though.

### Stack Trace
```
Exception of type 'ProtoCore.Exceptions.CompilerInternalException' was thrown.

   at ProtoCore.AssociativeEngine.Utils.IsGlobalScopeDirty(Executable exe)
   at ProtoScript.Runners.LiveRunner.ApplyUpdate()
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()```

---
OS: `Microsoft Windows NT 10.0.18363.0`
CLR: `4.0.30319.42000`
Dynamo: `2.3.0.5885`


Snapshot of the error:
![image](https://user-images.githubusercontent.com/77129045/103954071-6d997700-5111-11eb-9245-a54a201a8ab3.png)


Full log:
Dynamo log started 2021-01-07 22:47:15Z
Python template set to default.
Dynamo -- Build 2.3.0.5885
Duplicate migration type registered for SunPathDirection
Dynamo will use the package manager server at : https://www.dynamopackages.com
System.InvalidOperationException:
There already exists an AlsoKnownAs mapping for Fill Pattern Targets.

System.InvalidOperationException:
There already exists an AlsoKnownAs mapping for Fill Patterns.

System.InvalidOperationException:
There already exists an AlsoKnownAs mapping for Schedule Type.

Build error for library: C:\Users\SUR84888\AppData\Roaming\Dynamo\Dynamo Revit\2.3\packages\Autodesk Analytical Modeling 2020 Dynamo\bin\log4net.dll
Unknown base class 'log4net.Util.TextWriterAdapter' (9E44FFB3).

Failed to load library: C:\Users\SUR84888\AppData\Roaming\Dynamo\Dynamo Revit\2.3\packages\Autodesk Analytical Modeling 2020 Dynamo\bin\log4net.dll
notification:Dynamo.Exceptions.LibraryLoadFailedException: Failed to load library: C:\Users\SUR84888\AppData\Roaming\Dynamo\Dynamo Revit\2.3\packages\Autodesk Analytical Modeling 2020 Dynamo\bin\log4net.dll:
 Failed to load library: C:\Users\SUR84888\AppData\Roaming\Dynamo\Dynamo Revit\2.3\packages\Autodesk Analytical Modeling 2020 Dynamo\bin\log4net.dll: 
 Build error for library: C:\Users\SUR84888\AppData\Roaming\Dynamo\Dynamo Revit\2.3\packages\Autodesk Analytical Modeling 2020 Dynamo\bin\log4net.dll
Unknown base class 'log4net.Util.TextWriterAdapter' (9E44FFB3).

Dynamo.Exceptions.LibraryLoadFailedException:
Failed to load library: C:\Users\SUR84888\AppData\Roaming\Dynamo\Dynamo Revit\2.3\packages\Autodesk Analytical Modeling 2020 Dynamo\bin\log4net.dll

Dynamo.Exceptions.LibraryLoadFailedException: Failed to load library: C:\Users\SUR84888\AppData\Roaming\Dynamo\Dynamo Revit\2.3\packages\Autodesk Analytical Modeling 2020 Dynamo\bin\log4net.dll
Failed to load library: C:\Users\SUR84888\AppData\Roaming\Dynamo\Dynamo Revit\2.3\packages\Autodesk Analytical Modeling 2020 Dynamo\bin\Dynamo4AMLib.dll
notification:Dynamo.Exceptions.LibraryLoadFailedException: Failed to load library: C:\Users\SUR84888\AppData\Roaming\Dynamo\Dynamo Revit\2.3\packages\Autodesk Analytical Modeling 2020 Dynamo\bin\Dynamo4AMLib.dll:
 Failed to load library: C:\Users\SUR84888\AppData\Roaming\Dynamo\Dynamo Revit\2.3\packages\Autodesk Analytical Modeling 2020 Dynamo\bin\Dynamo4AMLib.dll: 
 Library C:\Users\SUR84888\AppData\Roaming\Dynamo\Dynamo Revit\2.3\packages\Autodesk Analytical Modeling 2020 Dynamo\bin\Dynamo4AMLib.dll has been loaded.
Dynamo.Exceptions.LibraryLoadFailedException:
Failed to load library: C:\Users\SUR84888\AppData\Roaming\Dynamo\Dynamo Revit\2.3\packages\Autodesk Analytical Modeling 2020 Dynamo\bin\Dynamo4AMLib.dll

Dynamo.Exceptions.LibraryLoadFailedException: Failed to load library: C:\Users\SUR84888\AppData\Roaming\Dynamo\Dynamo Revit\2.3\packages\Autodesk Analytical Modeling 2020 Dynamo\bin\Dynamo4AMLib.dll
Autodesk Analytical Modeling 2021 Dynamo contains the node library Dynamo4AMGui, which has already been loaded by another package. This may cause inconsistent results when determining which package nodes from this node library are dependent on.
Autodesk Analytical Modeling 2021 Dynamo contains the node library Dynamo4AMLib, which has already been loaded by another package. This may cause inconsistent results when determining which package nodes from this node library are dependent on.
Autodesk Analytical Modeling 2021 Dynamo contains the node library log4net, which has already been loaded by another package. This may cause inconsistent results when determining which package nodes from this node library are dependent on.
Failed to load library: C:\Users\SUR84888\AppData\Roaming\Dynamo\Dynamo Revit\2.3\packages\Clockwork for Dynamo 2.x\dyf
notification:Dynamo.Exceptions.CustomNodePackageLoadException: Failed to load library: C:\Users\SUR84888\AppData\Roaming\Dynamo\Dynamo Revit\2.3\packages\Clockwork for Dynamo 2.x\dyf:
 Failed to load library: C:\Users\SUR84888\AppData\Roaming\Dynamo\Dynamo Revit\2.3\packages\Clockwork for Dynamo 2.x\dyf: 
 C:\Users\SUR84888\AppData\Roaming\Dynamo\Dynamo Revit\2.3\packages\Clockwork for Dynamo 2.x\dyf cannot be loaded. 
Installing it will conflict with one or more node definitions that already exist in C:\Users\SUR84888\AppData\Roaming\Dynamo\Dynamo Revit\2.3\packages\Bakery\dyf, which is currently loaded. 
To install C:\Users\SUR84888\AppData\Roaming\Dynamo\Dynamo Revit\2.3\packages\Clockwork for Dynamo 2.x\dyf, Dynamo needs to first uninstall C:\Users\SUR84888\AppData\Roaming\Dynamo\Dynamo Revit\2.3\packages\Bakery\dyf. 
Restart Dynamo to complete the uninstall.
Dynamo.Exceptions.CustomNodePackageLoadException:
Failed to load library: C:\Users\SUR84888\AppData\Roaming\Dynamo\Dynamo Revit\2.3\packages\Clockwork for Dynamo 2.x\dyf

Exception of type 'ProtoCore.Exceptions.CompilerInternalException' was thrown.
DynamoPackageManager (id: FCABC211-D56B-4109-AF18-F434DFE48139) extension is added
Backup files timer is started with an interval of 60000 milliseconds
SYSTEM:Environment Path:C:\Program Files\Autodesk\Revit 2020\AddIns\SteelConnections;C:\Program Files\Autodesk\Revit 2020\en-US;C:\Program Files\Autodesk\Revit 2020;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Common Files\Autodesk Shared\;C:\Program Files\dotnet\;C:\Program Files\Common Files\Autodesk Shared\Advance\;C:\Program Files\Microsoft VS Code\bin;C:\Users\SUR84888\AppData\Local\Continuum\anaconda3;C:\Users\SUR84888\AppData\Local\Continuum\anaconda3\Library\mingw-w64\bin;C:\Users\SUR84888\AppData\Local\Continuum\anaconda3\Library\usr\bin;C:\Users\SUR84888\AppData\Local\Continuum\anaconda3\Library\bin;C:\Users\SUR84888\AppData\Local\Continuum\anaconda3\Scripts;C:\Users\SUR84888\AppData\Local\Microsoft\WindowsApps;C:\Users\SUR84888\AppData\Roaming\pyRevit-Master\bin;C:\Program Files\Common Files\Autodesk Shared\Advance\;C:\Program Files (x86)\Common Files\Autodesk Shared\Advance\;C:\Program Files\Autodesk\Revit 2020\AddIns\DynamoForRevit;C:\Program Files\Autodesk\Revit 2020\AddIns\DynamoForRevit;C:\Program Files\Autodesk\Revit 2020\AddIns\DynamoForRevit
RENDER : Rendering Tier: 2
RENDER : Pixel Shader 3 Supported: True
RENDER : Pixel Shader 4 Supported: False
RENDER : Software Effect Rendering Supported: True
RENDER : Maximum hardware texture size: 16384,16384
RENDER : Rendering Tier: 2
RENDER : Pixel Shader 3 Supported: True
RENDER : Pixel Shader 4 Supported: False
RENDER : Software Effect Rendering Supported: True
RENDER : Maximum hardware texture size: 16384,16384
DynamoManipulationExtension (id: 58B0496A-E3F8-43D9-86D2-94823D1D0F98) view extension is added
LibraryUI (id: 85941358-5525-4FF4-8D61-6CA831F122AB) view extension is added
NotificationsExtension (id: ef6cd025-514f-44cd-b6b1-69d9f5cce004) view extension is added
Monocle View Extension (id: 5A256B35-BD09-423C-82A1-372957143927) view extension is added
PackageManagerViewExtension (id: 100f5ec3-fde7-4205-80a7-c968b3a5a27b) view extension is added
Workspace Dependency ViewExtension (id: A6706BF5-11C2-458F-B7C8-B745A77EF7FD) view extension is added
Welcome to Dynamo!
00:00:00.3291041 elapsed for loading Dynamo main window.
Preparing to load the library resources.
WPF Render Mode: SoftwareOnly
notification:System.IO.FileLoadException:
 Dynamo has detected a conflict with a dependency and may be unstable. If any issues are detected, please uninstall addins or packages and contact the provider.: 
 While loading assembly MonocleViewExtension, Version=2020.10.1.0, Culture=neutral, PublicKeyToken=null, Dynamo detected that the dependency Xceed.Wpf.Toolkit, Version=4.0.0.0, Culture=neutral, PublicKeyToken=3e4669d2f30244f4 was already loaded with an incompatiable version. It is likely that another Revit Addin has loaded this assembly, please try uninstalling other Addins, and starting Dynamo again. Dynamo may be unstable in this state.
It is likely one of the following assemblies loaded the incompatible version:
CoreNodeModelsWpf
notification:System.IO.FileLoadException:
 Dynamo has detected a conflict with a dependency and may be unstable. If any issues are detected, please uninstall addins or packages and contact the provider.: 
 While loading assembly MonocleViewExtension, Version=2020.10.1.0, Culture=neutral, PublicKeyToken=null, Dynamo detected that the dependency Xceed.Wpf.AvalonDock, Version=4.0.0.0, Culture=neutral, PublicKeyToken=3e4669d2f30244f4 was already loaded with an incompatiable version. It is likely that another Revit Addin has loaded this assembly, please try uninstalling other Addins, and starting Dynamo again. Dynamo may be unstable in this state.
It is likely one of the following assemblies loaded the incompatible version:
UIFramework, Microsoft.GeneratedCode
notification:System.IO.FileLoadException:
 Dynamo has detected a conflict with a dependency and may be unstable. If any issues are detected, please uninstall addins or packages and contact the provider.: 
 While loading assembly Xceed.Wpf.AvalonDock, Version=4.0.0.0, Culture=neutral, PublicKeyToken=3e4669d2f30244f4, Dynamo detected that the dependency Xceed.Wpf.AvalonDock, Version=4.0.0.0, Culture=neutral, PublicKeyToken=3e4669d2f30244f4 was already loaded with an incompatiable version. It is likely that another Revit Addin has loaded this assembly, please try uninstalling other Addins, and starting Dynamo again. Dynamo may be unstable in this state.
It is likely one of the following assemblies loaded the incompatible version:
UIFramework, Microsoft.GeneratedCode
notification:System.IO.FileLoadException:
 Dynamo has detected a conflict with a dependency and may be unstable. If any issues are detected, please uninstall addins or packages and contact the provider.: 
 While loading assembly Xceed.Wpf.AvalonDock.Themes.Aero, Version=4.0.0.0, Culture=neutral, PublicKeyToken=3e4669d2f30244f4, Dynamo detected that the dependency Xceed.Wpf.AvalonDock, Version=4.0.0.0, Culture=neutral, PublicKeyToken=3e4669d2f30244f4 was already loaded with an incompatiable version. It is likely that another Revit Addin has loaded this assembly, please try uninstalling other Addins, and starting Dynamo again. Dynamo may be unstable in this state.
It is likely one of the following assemblies loaded the incompatible version:
UIFramework, Microsoft.GeneratedCode
notification:System.IO.FileLoadException:
 Dynamo has detected a conflict with a dependency and may be unstable. If any issues are detected, please uninstall addins or packages and contact the provider.: 
 While loading assembly Xceed.Wpf.AvalonDock.Themes.Metro, Version=4.0.0.0, Culture=neutral, PublicKeyToken=3e4669d2f30244f4, Dynamo detected that the dependency Xceed.Wpf.AvalonDock, Version=4.0.0.0, Culture=neutral, PublicKeyToken=3e4669d2f30244f4 was already loaded with an incompatiable version. It is likely that another Revit Addin has loaded this assembly, please try uninstalling other Addins, and starting Dynamo again. Dynamo may be unstable in this state.
It is likely one of the following assemblies loaded the incompatible version:
UIFramework, Microsoft.GeneratedCode
notification:System.IO.FileLoadException:
 Dynamo has detected a conflict with a dependency and may be unstable. If any issues are detected, please uninstall addins or packages and contact the provider.: 
 While loading assembly Xceed.Wpf.AvalonDock.Themes.VS2010, Version=4.0.0.0, Culture=neutral, PublicKeyToken=3e4669d2f30244f4, Dynamo detected that the dependency Xceed.Wpf.AvalonDock, Version=4.0.0.0, Culture=neutral, PublicKeyToken=3e4669d2f30244f4 was already loaded with an incompatiable version. It is likely that another Revit Addin has loaded this assembly, please try uninstalling other Addins, and starting Dynamo again. Dynamo may be unstable in this state.
It is likely one of the following assemblies loaded the incompatible version:
UIFramework, Microsoft.GeneratedCode
notification:System.IO.FileLoadException:
 Dynamo has detected a conflict with a dependency and may be unstable. If any issues are detected, please uninstall addins or packages and contact the provider.: 
 While loading assembly Xceed.Wpf.Toolkit, Version=4.0.0.0, Culture=neutral, PublicKeyToken=3e4669d2f30244f4, Dynamo detected that the dependency Xceed.Wpf.Toolkit, Version=4.0.0.0, Culture=neutral, PublicKeyToken=3e4669d2f30244f4 was already loaded with an incompatiable version. It is likely that another Revit Addin has loaded this assembly, please try uninstalling other Addins, and starting Dynamo again. Dynamo may be unstable in this state.
It is likely one of the following assemblies loaded the incompatible version:
CoreNodeModelsWpf
Clearing workspace...
Failed to get mirror for variable:  var_92aad6a1a3a1434aab22f0694c7abf2f; reason: Exception of type 'ProtoCore.Exceptions.CompilerInternalException' was thrown..
Failed to get mirror for variable:  t6BBA4B28C5E54CF89F300D510499A00E_0_92aad6a1a3a1434aab22f0694c7abf2f; reason: Exception of type 'ProtoCore.Exceptions.CompilerInternalException' was thrown..
Failed to get mirror for variable:  t6BBA4B28C5E54CF89F300D510499A00E_0_92aad6a1a3a1434aab22f0694c7abf2f; reason: Exception of type 'ProtoCore.Exceptions.CompilerInternalException' was thrown..
Saving C:\Users\SUR84888\AppData\Roaming\Dynamo\Dynamo Revit\backup\backup.DYN ...
Backup file is saved: C:\Users\SUR84888\AppData\Roaming\Dynamo\Dynamo Revit\backup\backup.DYN
Failed to get mirror for variable:  t6BBA4B28C5E54CF89F300D510499A00E_0_92aad6a1a3a1434aab22f0694c7abf2f; reason: Exception of type 'ProtoCore.Exceptions.CompilerInternalException' was thrown..
Failed to get mirror for variable:  var_ab5cd0679f484f45852a6eafe776d0c6; reason: Exception of type 'ProtoCore.Exceptions.CompilerInternalException' was thrown..
Failed to get mirror for variable:  t6BBA4B28C5E54CF89F300D510499A00E_0_92aad6a1a3a1434aab22f0694c7abf2f; reason: Exception of type 'ProtoCore.Exceptions.CompilerInternalException' was thrown..
Failed to get mirror for variable:  t6BBA4B28C5E54CF89F300D510499A00E_0_ab5cd0679f484f45852a6eafe776d0c6; reason: Exception of type 'ProtoCore.Exceptions.CompilerInternalException' was thrown..
Failed to get mirror for variable:  t6BBA4B28C5E54CF89F300D510499A00E_0_ab5cd0679f484f45852a6eafe776d0c6; reason: Exception of type 'ProtoCore.Exceptions.CompilerInternalException' was thrown..
Saving C:\Users\SUR84888\AppData\Roaming\Dynamo\Dynamo Revit\backup\backup.DYN ...
Backup file is saved: C:\Users\SUR84888\AppData\Roaming\Dynamo\Dynamo Revit\backup\backup.DYN
Failed to get mirror for variable:  t6BBA4B28C5E54CF89F300D510499A00E_0_92aad6a1a3a1434aab22f0694c7abf2f; reason: Exception of type 'ProtoCore.Exceptions.CompilerInternalException' was thrown..
Failed to get mirror for variable:  t6BBA4B28C5E54CF89F300D510499A00E_0_ab5cd0679f484f45852a6eafe776d0c6; reason: Exception of type 'ProtoCore.Exceptions.CompilerInternalException' was thrown..
Failed to get mirror for variable:  var_4af7c9d4073e44f39324815a676949e2; reason: Exception of type 'ProtoCore.Exceptions.CompilerInternalException' was thrown..
Failed to get mirror for variable:  t6BBA4B28C5E54CF89F300D510499A00E_0_92aad6a1a3a1434aab22f0694c7abf2f; reason: Exception of type 'ProtoCore.Exceptions.CompilerInternalException' was thrown..
Failed to get mirror for variable:  t6BBA4B28C5E54CF89F300D510499A00E_0_ab5cd0679f484f45852a6eafe776d0c6; reason: Exception of type 'ProtoCore.Exceptions.CompilerInternalException' was thrown..
Failed to get mirror for variable:  t6BBA4B28C5E54CF89F300D510499A00E_0_4af7c9d4073e44f39324815a676949e2; reason: Exception of type 'ProtoCore.Exceptions.CompilerInternalException' was thrown..
Failed to get mirror for variable:  t6BBA4B28C5E54CF89F300D510499A00E_0_4af7c9d4073e44f39324815a676949e2; reason: Exception of type 'ProtoCore.Exceptions.CompilerInternalException' was thrown..
Saving C:\Users\SUR84888\AppData\Roaming\Dynamo\Dynamo Revit\backup\backup.DYN ...
Backup file is saved: C:\Users\SUR84888\AppData\Roaming\Dynamo\Dynamo Revit\backup\backup.DYN
Saving C:\Users\SUR84888\AppData\Roaming\Dynamo\Dynamo Revit\backup\backup.DYN ...
Backup file is saved: C:\Users\SUR84888\AppData\Roaming\Dynamo\Dynamo Revit\backup\backup.DYN
Failed to get mirror for variable:  t6BBA4B28C5E54CF89F300D510499A00E_0_92aad6a1a3a1434aab22f0694c7abf2f; reason: Exception of type 'ProtoCore.Exceptions.CompilerInternalException' was thrown..
Failed to get mirror for variable:  t6BBA4B28C5E54CF89F300D510499A00E_0_ab5cd0679f484f45852a6eafe776d0c6; reason: Exception of type 'ProtoCore.Exceptions.CompilerInternalException' was thrown..
Failed to get mirror for variable:  t6BBA4B28C5E54CF89F300D510499A00E_0_4af7c9d4073e44f39324815a676949e2; reason: Exception of type 'ProtoCore.Exceptions.CompilerInternalException' was thrown..
Failed to get mirror for variable:  var_505221b9ae504a97ac1b8b0e6217f0da; reason: Exception of type 'ProtoCore.Exceptions.CompilerInternalException' was thrown..
Failed to get mirror for variable:  t6BBA4B28C5E54CF89F300D510499A00E_0_92aad6a1a3a1434aab22f0694c7abf2f; reason: Exception of type 'ProtoCore.Exceptions.CompilerInternalException' was thrown..
Failed to get mirror for variable:  t6BBA4B28C5E54CF89F300D510499A00E_0_ab5cd0679f484f45852a6eafe776d0c6; reason: Exception of type 'ProtoCore.Exceptions.CompilerInternalException' was thrown..
Failed to get mirror for variable:  t6BBA4B28C5E54CF89F300D510499A00E_0_4af7c9d4073e44f39324815a676949e2; reason: Exception of type 'ProtoCore.Exceptions.CompilerInternalException' was thrown..
Failed to get mirror for variable:  t6BBA4B28C5E54CF89F300D510499A00E_0_505221b9ae504a97ac1b8b0e6217f0da; reason: Exception of type 'ProtoCore.Exceptions.CompilerInternalException' was thrown..
Failed to get mirror for variable:  t6BBA4B28C5E54CF89F300D510499A00E_0_505221b9ae504a97ac1b8b0e6217f0da; reason: Exception of type 'ProtoCore.Exceptions.CompilerInternalException' was thrown..
Saving C:\Users\SUR84888\AppData\Roaming\Dynamo\Dynamo Revit\backup\backup.DYN ...
Backup file is saved: C:\Users\SUR84888\AppData\Roaming\Dynamo\Dynamo Revit\backup\backup.DYN
Saving C:\Users\SUR84888\AppData\Roaming\Dynamo\Dynamo Revit\backup\backup.DYN ...
Backup file is saved: C:\Users\SUR84888\AppData\Roaming\Dynamo\Dynamo Revit\backup\backup.DYN
Failed to get mirror for variable:  t6BBA4B28C5E54CF89F300D510499A00E_0_92aad6a1a3a1434aab22f0694c7abf2f; reason: Exception of type 'ProtoCore.Exceptions.CompilerInternalException' was thrown..
Failed to get mirror for variable:  t6BBA4B28C5E54CF89F300D510499A00E_0_ab5cd0679f484f45852a6eafe776d0c6; reason: Exception of type 'ProtoCore.Exceptions.CompilerInternalException' was thrown..
Failed to get mirror for variable:  t6BBA4B28C5E54CF89F300D510499A00E_0_4af7c9d4073e44f39324815a676949e2; reason: Exception of type 'ProtoCore.Exceptions.CompilerInternalException' was thrown..
Failed to get mirror for variable:  t6BBA4B28C5E54CF89F300D510499A00E_0_505221b9ae504a97ac1b8b0e6217f0da; reason: Exception of type 'ProtoCore.Exceptions.CompilerInternalException' was thrown..
Failed to get mirror for variable:  var_f3cbce7a646f442590cc14c2656d7a04; reason: Exception of type 'ProtoCore.Exceptions.CompilerInternalException' was thrown..
Failed to get mirror for variable:  t6BBA4B28C5E54CF89F300D510499A00E_0_f3cbce7a646f442590cc14c2656d7a04; reason: Exception of type 'ProtoCore.Exceptions.CompilerInternalException' was thrown..
Failed to get mirror for variable:  t6BBA4B28C5E54CF89F300D510499A00E_0_f3cbce7a646f442590cc14c2656d7a04; reason: Exception of type 'ProtoCore.Exceptions.CompilerInternalException' was thrown..
Saving C:\Users\SUR84888\AppData\Roaming\Dynamo\Dynamo Revit\backup\backup.DYN ...
Backup file is saved: C:\Users\SUR84888\AppData\Roaming\Dynamo\Dynamo Revit\backup\backup.DYN

**Comment by mjkkirschner** [comment]
I think this was resolved by removing  Dynamo4AMGui
