### ISSUE TITLE
Crash report from Dynamo 2.3.0.5885

### ISSUE THREAD

**Issue by michaldengusiak** [DynamoDS/Dynamo#11501]
# Issue Description
Please fill in the following information to help us reproduce the issue:
Unable to edit Python Code 
### What did you do?
(Fill in here)
open dynamo script
### What did you expect to see?
(Fill in here)
python code
### What did you see instead?
(Fill in here)
![image](https://user-images.githubusercontent.com/26113670/108085734-8df01600-706d-11eb-9f17-9b3dd81309bb.png)
None
### What packages or external references (if any) were used?
(Fill in here)
None
![image](https://user-images.githubusercontent.com/26113670/108086501-5e8dd900-706e-11eb-8eee-c76c263e522e.png)
![image](https://user-images.githubusercontent.com/26113670/108086742-9dbc2a00-706e-11eb-88b8-2aef91548be6.png)

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```
Method not found: 'Microsoft.Scripting.Hosting.ScriptEngine IronPython.Hosting.Python.CreateEngine()'.

   at Dynamo.Python.IronPythonCompletionProvider..ctor(String dynamoCoreDir)
   at PythonNodeModelsWpf.ScriptEditorWindow..ctor(DynamoViewModel dynamoViewModel, PythonNode nodeModel, NodeView nodeView, WindowRect& windowRect)
   at PythonNodeModelsWpf.PythonNodeViewCustomization.EditScriptContent()
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

---
OS: `Microsoft Windows NT 10.0.17134.0`
CLR: `4.0.30319.42000`
Dynamo: `2.3.0.5885`

File:
[R2a.DeleteAllSheetsExceptOriginals_ver02samBUG.dyn.zip](https://github.com/DynamoDS/Dynamo/files/5989799/R2a.DeleteAllSheetsExceptOriginals_ver02samBUG.dyn.zip)

**Comment by michaldengusiak** [comment]
all data provided

**Comment by mjkkirschner** [comment]
Hmm - do you have revit addins installed, like PyRevit? 
A good first step is to remove all addins to see if the problem resolves.

Some other information that may be useful can be the list of ALL loaded modules - you should be able to get that by using 

process explorer:
https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer

or listdlls:
https://docs.microsoft.com/en-us/sysinternals/downloads/listdlls

you'd run these on revit.
