### ISSUE TITLE
Crash report from Dynamo 2.10.1.3976

### ISSUE THREAD

**Issue by EricLrnt** [DynamoDS/Dynamo#11582]
# Issue Description
Inserting a Mesh through Mesh Toolkit with Large OBJ file

### What did you do?
everything was running fine, mesh uploading, extracting edges, started to right codes around in code blocks, and for any known reason (for me) dynamo.mesh.importfile started to return "null" while the file path is still showing the correct path at the bottom of the node. Tried on a fresh dynamo file to past the same nodes (filepath - dynamo.mesh.importfile - Mesh.edges) from the file that stopped working and it worked perfectly and loaded in seconds...
In original file, what ever I do I get a Crash

### What did you expect to see?
(Fill in here)

### What did you see instead?
Array dimensions exceeded supported range.

   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at ProtoCore.CallSite.AreParametersHomogeneousTypes(List`1 formalParameters, RuntimeCore runtimeCore)
   at ProtoCore.CallSite.ExecWithRISlowPath(List`1 functionEndPoint, Context c, List`1 formalParameters, List`1 replicationInstructions, StackFrame stackFrame, RuntimeCore runtimeCore, SingleRunTraceData previousTraceData, SingleRunTraceData newTraceData, FunctionEndPoint finalFunctionEndPoint)
   at ProtoCore.CallSite.Execute(List`1 functionEndPoint, Context c, List`1 formalParameters, List`1 replicationInstructions, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.CallSite.DispatchNew(Context context, List`1 arguments, List`1 partialReplicationGuides, DominantListStructure domintListStructure, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.DSASM.Executive.Callr(Int32 blockDeclId, Int32 functionIndex, Int32 classIndex, Boolean& explicitCall, Boolean isDynamicCall, Boolean hasDebugInfo)
   at ProtoCore.DSASM.Executive.CALLR_Handler(Instruction instruction)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
   at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   at ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()

### What packages or external references (if any) were used?
Mesh Toolkit

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
OS: `Microsoft Windows NT 6.2.9200.0`
CLR: `4.0.30319.42000`
Dynamo: `2.10.1.3976`

**Comment by EricLrnt** [comment]
[](url)
![image](https://user-images.githubusercontent.com/61023754/112716070-731e8600-8ee4-11eb-8867-543e51201f1c.png)

**Comment by EricLrnt** [comment]
"Array dimensions exceeded supported range."
From this, I would say that I need to increase Geo Scaling... But I am already "Extra large"... I cannot find in my code anything that exceeds the 100,000,000 units values ?!

**Comment by EricLrnt** [comment]
OK... Don't know what I drank this morning, but my code is just full of mistakes ate every line...

**Comment by EricLrnt** [comment]
My code was filled with mistakes at every line, I must have been drunk this morning while writing it
