### ISSUE TITLE
Crash report from Dynamo 2.10.1.3976

### ISSUE THREAD

**Issue by adamwilliamsmsc** [DynamoDS/Dynamo#11635]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
Install Lunchbox package. I had earlier installed Archi-Lab package which didn't appear, even though it said it had installed.

### What did you expect to see?
Packages installed.

### What did you see instead?
Error box appeared saying Dynamo has crashed.

### What packages or external references (if any) were used?
I had a script open from previous Dynamo version which used an Archi-Lab node, so I was trying to install packages to the new Dynamo version.

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```
Index (zero based) must be greater than or equal to zero and less than the size of the argument list.

   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object arg0)
   at Dynamo.ViewModels.PackageManagerClientViewModel.<>c__DisplayClass48_0.<ExecutePackageDownload>b__0(Dependency dep, Int32 i)
   at System.Linq.Enumerable.<SelectIterator>d__5`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dynamo.ViewModels.PackageManagerClientViewModel.ExecutePackageDownload(String name, PackageVersion version, String downloadPath)
   at Dynamo.PackageManager.ViewModels.PackageManagerSearchElementViewModel.OnRequestDownload(PackageVersion version, Boolean downloadToCustomPath)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---
OS: `Microsoft Windows NT 10.0.19042.0`
CLR: `4.0.30319.42000`
Dynamo: `2.10.1.3976`

**Comment by mjkkirschner** [comment]
Hi @adamwilliamsmsc can you reproduce this crash?

**Comment by QilongTang** [comment]
@adamwilliamsmsc Did you installed Archi-Lab package then Lunchbox package to get the crash right away? Were you able to reproduce it later? We would need some help from you reproducing this. Appreciate it!
