### ISSUE TITLE
Crash report from Dynamo 2.3.0.5885

### ISSUE THREAD

**Issue by cellophane303** [DynamoDS/Dynamo#11642]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
Ran a graph to select group elements inside groups and set a parameter value for all elements in the group.  I can get a link to a cleaned up model if it helps and am happy to upload the graph.

### What did you expect to see?
All elements to set the parameter to the new value, in this case 'Yes'

### What did you see instead?
Unhandled Exception (see below) and none of the parameters were set.  All nodes in the graph appear to have run correctly (no yellow or red nodes)

### What packages or external references (if any) were used?
SteamNodes 1.2.4
Clockwork 2.1.2
Data-Shapes 2021.2.91
Rhythm 2020.9.8

### Stack Trace
```
Object reference not set to an instance of an object.

   at ProtoCore.DSASM.Heap.RecursiveMark(StackValue root)
   at ProtoCore.DSASM.Heap.SingleStep(Boolean forceGC)
   at ProtoCore.DSASM.Executive.POP_helper(Instruction instruction, Int32& blockId, Int32& dimensions)
   at ProtoCore.DSASM.Executive.POP_Handler(Instruction instruction)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
   at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   at ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()
```

---
OS: `Microsoft Windows NT 10.0.19042.0`
CLR: `4.0.30319.42000`
Dynamo: `2.3.0.5885`

**Comment by cellophane303** [comment]
Dynamo Version 2.3.0.5885
Revit 2020.2.30.42
Windows Pro 10 20H2

I copied the groups into a blank file and the graph ran fine, so it seems to be related to the project file somehow.  I'll try to get a stripped copy of it uploaded this afternoon.  DYN enclosed.
[SetGroupElements-IsUnitGroup.zip](https://github.com/DynamoDS/Dynamo/files/6366594/SetGroupElements-IsUnitGroup.zip)

Thanks
