### ISSUE TITLE
Informe de conflictos de Dynamo 2.5.0.7460

### ISSUE THREAD

**Issue by Auraarq** [DynamoDS/Dynamo#11654]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do
I0m working with revit and Dynamo and I tried to download the steal connetion package and the generative design extension and the programa and the program shows me this notification...
Dynamo.Exceptions.LibraryLoadFailedException: No se ha podido cargar la biblioteca: C:\ProgramData\Autodesk\RVT 2021\Dynamo\2.5\packages\GenerativeDesign.Revit
   at Dynamo.PackageManager.PackageLoader.CheckPackageNodeLibraryCertificates(String packageDirectoryPath, Package discoveredPkg)
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates)

### What did you expect to see?
the library of steel connection of dynamo for Revit

### What did you see instead?
the steel connection is empty of information and models

### What packages or external references (if any) were used?
steel connections and generative design
![error](https://user-images.githubusercontent.com/83415317/116574914-2e6b7d80-a8dc-11eb-96ae-1dc79563e5df.PNG)

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
OS: `Microsoft Windows NT 10.0.19041.0`
CLR: `4.0.30319.42000`
Dynamo: `2.5.0.7460`

**Comment by Auraarq** [comment]
SO: Microsoft Windows NT 10.0.19041.0
CLR: 4.0.30319.42000
Dynamo:2.5.0.7460

¿Qué hizo? 
Fui a Paquetes, busque Steel Connections y lo descargue, tambien descargue la actualizacion de diseño generativo desde la aplicacion de escritorio de autodesk, solo he hecho descargas.

¿Qué esperabas ver?
la biblioteca de conexiones de acero de dynamo para Revit y la extencion de diseño generativo

¿Qué viste en su lugar?
la conexión de acero está vacía de información y modelos, diseño generativo no carga y en su lugar sale el mismo mensaje de que no se ha podido descargar...

¿Qué paquetes o referencias externas (si las hubiera) se utilizaron?
No use nada externo, todo lo descargue directo del propio programma

El mensaje error es el siguiente:
Dynamo.Exceptions.LibraryLoadFailedException: No se ha podido cargar la biblioteca: C:\ProgramData\Autodesk\RVT 2021\Dynamo\2.5\packages\GenerativeDesign
   at Dynamo.PackageManager.PackageLoader.CheckPackageNodeLibraryCertificates(String packageDirectoryPath, Package discoveredPkg)
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates)

En los pasos que segui solo descargue desde el buscador de paquetes de dynamo y desde la aplicacion de escritorio de autodesk
![error](https://user-images.githubusercontent.com/83415317/116578542-8657b380-a8df-11eb-8d1b-d9881684577c.PNG)
