### ISSUE TITLE
Dynamo crash when migrating Python code

### ISSUE THREAD

**Issue by cjmccrone** [DynamoDS/Dynamo#11712]
# Issue Description
Dynamo crash when attempting to visualize Python 2 / Python 3 migration suggestions. Python script behavior changes between interpretation regimes. Reproduce with attached dyn (no dependencies).

### What did you do?
Attempted to migrate Python 2 to Python 3. Clicked on the automated tool to visualize syntax differences

### What did you expect to see?
I expected to see a comparison of Python 2 and Python 3 code.

### What did you see instead?
Dynamo crashed.

### What packages or external references (if any) were used?
[Python migration crash reproduce.zip](https://github.com/DynamoDS/Dynamo/files/6542261/Python.migration.crash.reproduce.zip)

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
OS: `Microsoft Windows NT 10.0.19042.0`
CLR: `4.0.30319.42000`
Dynamo: `2.10.1.3976`

**Comment by QilongTang** [comment]
@mjkkirschner @aparajit-pratap @sm6srw Would you take a look of this crash with attached zip?

**Comment by mjkkirschner** [comment]
I can repro it -  looking into it.

 stack trace is:
```
Value does not fall within the expected range.

   at Dynamo.PythonMigration.Differ.RichTextBoxHandler.ShowLineDiffs(RichTextBox diffBox, DiffPaneModel model, String senderPanel) in C:\Users\kirschm\Documents\Dynamo\src\PythonMigrationViewExtension\Differ\RichTextBoxHandler.cs:line 63
   at Dynamo.PythonMigration.Differ.RichTextBoxHandler.DiffPanelsChange(DependencyObject dep, DependencyPropertyChangedEventArgs e) in C:\Users\kirschm\Documents\Dynamo\src\PythonMigrationViewExtension\Differ\RichTextBoxHandler.cs:line 40
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   at System.Windows.Data.BindingExpressionBase.Invalidate(Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.Activate(Object item)
   at System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)
   at System.Windows.Data.BindingExpression.MS.Internal.Data.IDataBindEngineClient.AttachToContext(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Task.Run(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Run(Object arg)
   at System.Windows.ContextLayoutManager.fireLayoutUpdateEvent()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.Interop.HwndSource.SetLayoutSize()
   at System.Windows.Interop.HwndSource.set_RootVisualInternal(Visual value)
   at System.Windows.Window.SetRootVisual()
   at System.Windows.Window.SetRootVisualAndUpdateSTC()
   at System.Windows.Window.SetupInitialState(Double requestedTop, Double requestedLeft, Double requestedWidth, Double requestedHeight)
   at System.Windows.Window.CreateSourceWindow(Boolean duringShow)
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Window.ShowDialog()
   at Dynamo.PythonMigration.PythonMigrationViewExtension.OnMigrationAssistantRequested(Object sender, EventArgs e) in C:\Users\kirschm\Documents\Dynamo\src\PythonMigrationViewExtension\PythonMigrationViewExtension.cs:line 138
   at PythonNodeModelsWpf.ScriptEditorWindow.OnMigrationAssistantClicked(Object sender, RoutedEventArgs e) in C:\Users\kirschm\Documents\Dynamo\src\Libraries\PythonNodeModelsWpf\ScriptEditorWindow.xaml.cs:line 209
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at DynamoSandbox.DynamoCoreSetup.RunApplication(Application app) in C:\Users\kirschm\Documents\Dynamo\src\DynamoSandbox\DynamoCoreSetup.cs:line 69```

**Comment by mjkkirschner** [comment]
we have an unhandled change type `imaginary` 😄  - I think this occurs when an entire line is removed during the migration.

**Comment by mjkkirschner** [comment]
@cjmccrone I also looked that the difference in behavior, I got it to return the same data by making one change in your type checking.

![Screen Shot 2021-06-28 at 11 45 20 AM](https://user-images.githubusercontent.com/508936/123665688-82281380-d806-11eb-9e51-3dbea9a54374.png)

in intersectMultiple - check for "[]" instead of "Array" - this appears to be an ironPython vs PythonNet difference - it may be safer to check for the presence of attributes (like length) instead of type names.
