### ISSUE TITLE
Crash report from Dynamo 2.3.0.5885

### ISSUE THREAD

**Issue by SUDHEER0025** [DynamoDS/Dynamo#11811]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
(Fill in here) INSTAL PACAGE

### What did you expect to see?
(Fill in here) WITH OUT BUG

### What did you see instead?
(Fill in here) OPEN DYNAMO WITH OUT BUG

### What packages or external references (if any) were used?
(Fill in here)

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```
Could not load file or assembly 'file://\\10.174.176.243\09 bim\20 BIM Staff\04 Sudheer\009 DYNAMO\New folder\packages\archi-lab.net\bin\archilab2021.customization.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)

   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Dynamo.PackageManager.PackageLoader.TryLoadFrom(String filename, Assembly& assem)
   at Dynamo.PackageManager.Package.EnumerateAssembliesInBinDirectory()
   at Dynamo.PackageManager.PackageLoader.<>c.<LoadPackages>b__50_0(Package x)
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Dynamo.Models.DynamoModel.LibraryLoaded(Object sender, LibraryLoadedEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Dynamo.Engine.LibraryServices.OnLibrariesImported(LibraryLoadedEventArgs e)
   at Dynamo.PackageManager.PackageLoader.LoadPackages(IEnumerable`1 packages)
   at Dynamo.PackageManager.PackageLoader.LoadAll(LoadPackageParams loadPackageParams)
   at Dynamo.PackageManager.PackageLoader.LoadCustomNodesAndPackages(LoadPackageParams loadPackageParams, CustomNodeManager customNodeManager)
   at Dynamo.ViewModels.PackagePathViewModel.CommitChanges(Object param)
   at Dynamo.Wpf.Views.PackageManager.PackagePathView.OnOkButtonClicked(Object sender, RoutedEventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---
OS: `Microsoft Windows NT 10.0.18363.0`
CLR: `4.0.30319.42000`
Dynamo: `2.3.0.5885`

**Comment by SUDHEER0025** [comment]
DYNAMO VERSION  2.3.1
OPERATING SYSTEM WINDOWS 10

**Comment by SUDHEER0025** [comment]
![image](https://user-images.githubusercontent.com/86944445/124468517-dfd9d400-dda1-11eb-88c5-2efbc947973f.png)

**Comment by SUDHEER0025** [comment]
I CANT OPEN  DYNAMO WHEN IAM INSTAL PACKAGE 
BUG IS CAME

**Comment by QilongTang** [comment]
@SUDHEER0025 Can you talk a bit about your setup, curious about the fact your are loading packages from a network drive by reading the error message
```
Could not load file or assembly 'file://\10.174.176.243\09 bim\20 BIM Staff\04 Sudheer\009 DYNAMO\New folder\packages\archi-lab.net\bin\archilab2021.customization.dll' or one of its dependencies. Operation is not supported.
```
