### ISSUE TITLE
Crash report from Dynamo 2.12.0.5650

### ISSUE THREAD

**Issue by Julie-Kidder** [DynamoDS/Dynamo#12125]
# Issue Description
Please fill in the following information to help us reproduce the issue:

## Dynamo version
Dynamo: `2.12.0.5650`

## Operating system
OS: `Microsoft Windows NT 10.0.19042.0`

## What did you do?
Try to annotate custom nodes with Monocle.  

## What did you expect to see?
A Dynamo note added/updated above nodes from custom packages specifying their source

## What did you see instead?
A crash.  When the script is saved as offered during the crash all previous package notes from Monocle have been deleted.  The package worked fine in 2.10, but has crashed every time I have attempted to use in 2.12.  The path it can not access does not exist (there is no "Built-In Packages" folder)

## What packages or external references (if any) were used?
Dynamo crashes when Monocle annotate custom nodes tool is run

### Loaded Packages
- Clockwork for Dynamo 2.x 2.3.0
- Monocle 2021.9.1
- Rhythm 2021.7.3
- spring nodes 204.1.0
- GenerativeDesign 1.9.3.0
- GenerativeDesign.Extension 1.9.3.0
- GenerativeDesign.Revit 1.9.3.0
- Data-Shapes 2022.2.96

## Stack Trace
```
Access to the path 'C:\Program Files\Autodesk\Revit 2022\AddIns\DynamoForRevit\Built-In Packages\Packages' is denied.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at MonocleViewExtension.PackageUsage.DogeUtilities.GetPackageVersion(NodeModel node)
   at MonocleViewExtension.PackageUsage.PackageUsageDogeWindow.Button_Click_2(Object sender, RoutedEventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

---
CLR: `4.0.30319.42000`

**Comment by Julie-Kidder** [comment]
Thank you!  The update resolved the issue.  I apologize if it should have been posted under Monocle initially.
