### ISSUE TITLE
Crash report from Dynamo 2.10.1.3976

### ISSUE THREAD

**Issue by MadiJun** [DynamoDS/Dynamo#12146]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
Ribbon > "View" > Turn on "Show Workspace Reference"

### What did you expect to see?
My Workspace References showing which packages are active in the current project.

### What did you see instead?
A prompt with the title: "Dynamo has crashed, stating:

"Uh oh... something went wrong and Dynamo has crashed, sorry about that.

You will get a chance to save your work."

### What packages or external references (if any) were used?
A whole bunch:
archilab
archilab_Bumblebee
Clockwork
Data-Shapes
FemDesign
GenereativeDesign
LunchBox
LunchBoxML
Orchid
Structural Design

Of the above, I believe only Bumblebee and FemDesign were actually used in the graph.

### Stack Trace
```
Object reference not set to an instance of an object.

   at Dynamo.WorkspaceDependency.WorkspaceDependencyView.DependencyRegen(WorkspaceModel ws)
   at Dynamo.WorkspaceDependency.WorkspaceDependencyViewExtension.<>c__DisplayClass20_0.<Loaded>b__1(Object sender, RoutedEventArgs args)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

---
OS: `Microsoft Windows NT 10.0.19042.0`
CLR: `4.0.30319.42000`
Dynamo: `2.10.1.3976`

**Comment by Amoursol** [comment]
Thank you for the submission @MadiJun - we will look into this 😊 

@QilongTang do you think there is enough information to go on here? Looks like we may need to guard the Workspace References extension?
