### ISSUE TITLE
Crash report from Dynamo 2.13.0.3077

### ISSUE THREAD

**Issue by johnpierson** [DynamoDS/Dynamo#12266]
# Issue Description
Please fill in the following information to help us reproduce the issue:

## Dynamo version
Dynamo: `2.13.0.3077`

## Operating system
OS: `Microsoft Windows NT 6.2.9200.0`

## What did you do?
Monocle View Extension has options for creating code blocks on the fly. Upon code block creation this exception happens from Dynamo.
![image](https://user-images.githubusercontent.com/15744724/140972777-9c496e47-834b-49d0-9859-080f342a86a0.png)

## What did you expect to see?
Just the new code block no error

## What did you see instead?
This crash which does not seem to be in my code (in debug for monocle)

### Loaded Packages
- Monocle 2021.9.1

## Stack Trace
```
Object reference not set to an instance of an object.

   at Dynamo.Controls.NodeView.topControl_MouseLeftButtonDown(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at DynamoSandbox.DynamoCoreSetup.RunApplication(Application app)

-------- Assemblies --------

mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089|DynamoSandbox, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35|WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35|System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089|System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089|PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35|System.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089|DynamoCore, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|DynamoApplications, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|DynamoInstallDetective, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a|NDesk.Options, Version=0.2.1.0, Culture=neutral, PublicKeyToken=null|System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089|DynamoCoreWpf, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|Microsoft.Practices.Prism, Version=4.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35|SharpDX.Mathematics, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b4dcf0f35e5521f1|DynamoServices, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|DynamoShapeManager, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|LibG.AsmPreloader.Managed, Version=2.13.0.6656, Culture=neutral, PublicKeyToken=null|LibG.AsmPreloader.Unmanaged, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null|Greg, Version=2.1.7972.24350, Culture=neutral, PublicKeyToken=null|ProtoCore, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|DynamoUtilities, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|ProtoAssociative, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|ProtoImperative, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|Microsoft.GeneratedCode, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null|Analytics.Net.ADP, Version=2.12.0.0, Culture=neutral, PublicKeyToken=null|Analytics.NET.Core, Version=2.12.0.20758, Culture=neutral, PublicKeyToken=null|AdpSDKCSharpWrapper, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null|System.Web.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35|System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a|DynamoUnits, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|DynamoCore.resources, Version=2.13.0.3077, Culture=en-US, PublicKeyToken=null|IronPythonExtension, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|DynamoPackages, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|DesignScriptBuiltin, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|VMDataBridge, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|ProtoCore.resources, Version=2.13.0.3077, Culture=en-US, PublicKeyToken=null|Microsoft.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a|Anonymously Hosted DynamicMethods Assembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null|System.Dynamic, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a|ProtoGeometry, Version=2.13.0.6656, Culture=neutral, PublicKeyToken=null|LibG.Interface, Version=2.13.0.6656, Culture=neutral, PublicKeyToken=null|DSCoreNodes, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a|Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed|DSCoreNodes.resources, Version=2.13.0.3077, Culture=en-US, PublicKeyToken=null|DSOffice, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|DSOffice.resources, Version=2.13.0.3077, Culture=en-US, PublicKeyToken=null|DSCPython, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|Python.Runtime, Version=2.5.1.2374, Culture=neutral, PublicKeyToken=null|DynamoConversions, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|Tessellation, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|MIConvexHull.NET Standard, Version=1.0.17.411, Culture=neutral, PublicKeyToken=null|System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a|Analysis, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|Analysis.resources, Version=2.13.0.3077, Culture=en-US, PublicKeyToken=null|GeometryColor, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|ProtoScript, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|LibG.ProtoInterface, Version=2.13.0.6656, Culture=neutral, PublicKeyToken=null|LibG.Managed, Version=2.13.0.6656, Culture=neutral, PublicKeyToken=null|CoreNodeModels.customization, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|CoreNodeModels, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|CoreNodeModels.resources, Version=2.13.0.3077, Culture=en-US, PublicKeyToken=null|CoreNodeModelsWpf, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|GeometryUI.customization, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|GeometryUI, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|GeometryUI.resources, Version=2.13.0.3077, Culture=en-US, PublicKeyToken=null|GeometryUIWpf, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|Migrations, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|NCalc, Version=1.3.8.0, Culture=neutral, PublicKeyToken=973cde3f1cafed03|PythonNodeModels.customization, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|PythonNodeModels, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|PythonNodeModels.resources, Version=2.13.0.3077, Culture=en-US, PublicKeyToken=null|PythonNodeModelsWpf, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|ICSharpCode.AvalonEdit, Version=4.3.1.9429, Culture=neutral, PublicKeyToken=9cc39be672370310|UnitsUI.customization, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|UnitsUI, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|UnitsUI.resources, Version=2.13.0.3077, Culture=en-US, PublicKeyToken=null|Watch3DNodeModels.customization, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|Watch3DNodeModels, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|Watch3DNodeModels.resources, Version=2.13.0.3077, Culture=en-US, PublicKeyToken=null|Watch3DNodeModelsWpf, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|Xceed.Wpf.Toolkit, Version=3.0.0.0, Culture=neutral, PublicKeyToken=3e4669d2f30244f4|System.Xml.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089|BuiltIn.customization, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|Operators.customization, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|ProtoGeometry.customization, Version=2.13.0.6656, Culture=neutral, PublicKeyToken=null|DesignScriptBuiltin.customization, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|DSCoreNodes.customization, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|DSOffice.customization, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|DynamoUnits.customization, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|Tessellation.customization, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|Analysis.customization, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|GeometryColor.customization, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|RestSharp, Version=106.12.0.0, Culture=neutral, PublicKeyToken=598062e77f915f75|DynamoPackages.resources, Version=2.13.0.3077, Culture=en-US, PublicKeyToken=null|System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089|System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089|System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089|Cheet.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null|Cheet.Wpf, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null|ControlzEx, Version=4.0.0.0, Culture=neutral, PublicKeyToken=69f1c32f803d307e|MahApps.Metro, Version=2.0.0.0, Culture=neutral, PublicKeyToken=51482d6f650b2b3f|Microsoft.Xaml.Behaviors, Version=1.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a|MonocleViewExtension, Version=2021.10.1.0, Culture=neutral, PublicKeyToken=null|WpfAnimatedGif, Version=2.0.0.0, Culture=neutral, PublicKeyToken=9e7cd3b544a090dc|Xceed.Wpf.AvalonDock, Version=4.0.0.0, Culture=neutral, PublicKeyToken=3e4669d2f30244f4|Xceed.Wpf.AvalonDock.Themes.Aero, Version=4.0.0.0, Culture=neutral, PublicKeyToken=3e4669d2f30244f4|Xceed.Wpf.AvalonDock.Themes.Metro, Version=4.0.0.0, Culture=neutral, PublicKeyToken=3e4669d2f30244f4|Xceed.Wpf.AvalonDock.Themes.VS2010, Version=4.0.0.0, Culture=neutral, PublicKeyToken=3e4669d2f30244f4|Xceed.Wpf.Toolkit, Version=4.0.0.0, Culture=neutral, PublicKeyToken=3e4669d2f30244f4|DSIronPython, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|HelixToolkit.Wpf.SharpDX, Version=2.17.0.0, Culture=neutral, PublicKeyToken=52aa3500039caf0d|SharpDX, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b4dcf0f35e5521f1|DynamoCoreWpf.resources, Version=2.13.0.3077, Culture=en-US, PublicKeyToken=null|HelixToolkit, Version=2.17.0.0, Culture=neutral, PublicKeyToken=52aa3500039caf0d|SharpDX.DXGI, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b4dcf0f35e5521f1|SharpDX.Direct3D11, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b4dcf0f35e5521f1|SharpDX.Direct2D1, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b4dcf0f35e5521f1|FontAwesome.WPF, Version=4.7.0.37774, Culture=neutral, PublicKeyToken=0758b07a11a4f466|UIAutomationProvider, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35|System.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a|System.Data.SqlXml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089|System.Windows.Interactivity, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35|System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089|System.Web.ApplicationServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35|System.ServiceModel.Activation, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35|System.Web.Services, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a|System.ComponentModel.DataAnnotations, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35|System.Runtime.Caching, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a|Microsoft.Build.Framework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a|System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089|PresentationFramework.Aero2, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35|PresentationFramework-SystemXml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089|UIAutomationTypes, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35|DocumentationBrowserViewExtension, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|DocumentationBrowserViewExtension.resources, Version=2.13.0.3077, Culture=en-US, PublicKeyToken=null|DynamoManipulation, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|GraphMetadataViewExtension, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|LibraryViewExtensionMSWebBrowser, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|LintingViewExtension, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|Notifications, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|PackageDetailsViewExtension, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|DynamoPackagesWPF, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|PythonMigrationViewExtension, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|WorkspaceDependencyViewExtension, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|WorkspaceDependencyViewExtension.resources, Version=2.13.0.3077, Culture=en-US, PublicKeyToken=null|Notifications.resources, Version=2.13.0.3077, Culture=en-US, PublicKeyToken=null|PackageDetailsViewExtension.resources, Version=2.13.0.3077, Culture=en-US, PublicKeyToken=null|Microsoft.GeneratedCode, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null|PresentationFramework-SystemXmlLinq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089|PresentationFramework-SystemCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089|Microsoft.VisualStudio.DesignTools.WpfTap, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a|SMDiagnostics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089|System.ServiceModel.Internals, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35|PresentationFramework-SystemData, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089|GraphMetadataViewExtension.resources, Version=2.13.0.3077, Culture=en-US, PublicKeyToken=null|LibraryViewExtensionMSWebBrowser.resources, Version=2.13.0.3077, Culture=en-US, PublicKeyToken=null|WindowsFormsIntegration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35|LintingViewExtension.resources, Version=2.13.0.3077, Culture=en-US, PublicKeyToken=null|System.IdentityModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089|System.EnterpriseServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a|System.Runtime.DurableInstancing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35|Accessibility, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a|Cyotek.Drawing.BitmapFont, Version=1.0.0.0, Culture=neutral, PublicKeyToken=58daa28b0b2de221|SharpDX.D3DCompiler, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b4dcf0f35e5521f1|SharpDX.Direct3D9, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b4dcf0f35e5521f1|Microsoft.mshtml, Version=7.0.3300.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a|Windows.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime|System.Runtime.InteropServices.WindowsRuntime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a|System.Collections.Immutable, Version=1.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a|System.Runtime.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a|DynamoCore.customization, Version=2.13.0.3077, Culture=neutral, PublicKeyToken=null|System.Resources.ResourceManager, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
```

---
CLR: `4.0.30319.42000`

**Comment by mjkkirschner** [comment]
@johnpierson can you link to the code where you create a code block?

**Comment by johnpierson** [comment]
Of course! https://github.com/johnpierson/MonocleForDynamo/blob/e140880a5143f342d3d0f74c1c4f1ca5e61c6401/src/KeyboardShorties.cs#L112-L215

**Comment by johnpierson** [comment]
Quick Update: It seems related to the deletion of the original node. When I remove https://github.com/johnpierson/MonocleForDynamo/blob/e140880a5143f342d3d0f74c1c4f1ca5e61c6401/src/KeyboardShorties.cs#L207 it works without crash.

**Comment by mjkkirschner** [comment]
thanks @johnpierson - how does this function actually get called? `ReplaceDropdown`

**Comment by johnpierson** [comment]
I am calling the command with `DelegateCommand` from a contextual menu.

```
DelegateCommand command = MonocleViewExtension.ConvertDropdownCommand;
command.Execute("");
```
