### ISSUE TITLE
Crash report from Dynamo 2.5.0.7460

### ISSUE THREAD

**Issue by bmcassol** [DynamoDS/Dynamo#12359]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
Run the script

### What did you expect to see?
To run, as usual, it did use to work before on my previous computer

### What did you see instead?
It did run, however with errors, also it seems like it won't run again sometimes until I close and open it again

### What packages or external references (if any) were used?
(Fill in here)

Clockwork for Dynamo 1.x version: 1.31.1
Bakery version: 2019.5.8
Orchid version: 230.0.1.7346

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

Index was outside the bounds of the array.

   at ProtoCore.DSASM.Executive.GetProcedureNode(Int32 blockId, Int32 classIndex, Int32 functionIndex)
   at ProtoCore.DSASM.Executive.UpdateMethodDependencyGraph(Int32 entry, Int32 procIndex, Int32 classIndex)
   at ProtoCore.DSASM.Executive.SetupExecutive(Int32 exeblock, Int32 entry)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
   at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   at ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()

---
OS: `Microsoft Windows NT 10.0.18363.0`
CLR: `4.0.30319.42000`
Dynamo: `2.5.0.7460`

**Comment by bmcassol** [comment]
OS: Microsoft Windows NT 10.0.18363.0
Dynamo: 2.5.0.7460


What did you do?
Run the script

What did you expect to see?
To run, as usual, it did use to work before on my previous computer

What did you see instead?
It did run, however with errors, also it seems like it won't run again sometimes until I close and open it again

What packages or external references (if any) were used?
Clockwork for Dynamo 1.x version: 1.31.1
Bakery version: 2019.5.8
Orchid version: 230.0.1.7346

Stack Trace
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
Index was outside the bounds of the array.

at ProtoCore.DSASM.Executive.GetProcedureNode(Int32 blockId, Int32 classIndex, Int32 functionIndex)
at ProtoCore.DSASM.Executive.UpdateMethodDependencyGraph(Int32 entry, Int32 procIndex, Int32 classIndex)
at ProtoCore.DSASM.Executive.SetupExecutive(Int32 exeblock, Int32 entry)
at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List1 breakpoints, Language language) at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List1 breakpoints)
at ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
at ProtoScript.Runners.LiveRunner.CompileAndExecute(List1 astList) at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List1 astList)
at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
at Dynamo.Scheduler.AsyncTask.Execute()


![image](https://user-images.githubusercontent.com/61735089/145988266-88af3212-6aa6-4638-a230-8ff3cf60d5a6.png)
