### ISSUE TITLE
Crash report from Dynamo 2.6.1.8786

### ISSUE THREAD

**Issue by haziq993** [DynamoDS/Dynamo#12487]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
I cannot preview the 3D view on Dynamo. I tried to export 3D view as image and Dynamo crashed

### What did you expect to see?
The background 3D view of a simple cube geometry

### What did you see instead?
Nothing, just grids

### What packages or external references (if any) were used?
Nil

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```
Object reference not set to an instance of an object.

   at Dynamo.Controls.DynamoView.DynamoViewModelRequestSave3DImage(Object sender, ImageSaveEventArgs e)
   at Dynamo.ViewModels.DynamoViewModel.OnRequestSave3DImage(Object sender, ImageSaveEventArgs e)
   at Dynamo.ViewModels.DynamoViewModel.ShowSaveImageDialogAndSaveResult(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

---
OS: `Microsoft Windows NT 10.0.19042.0`
CLR: `4.0.30319.42000`
Dynamo: `2.6.1.8786`

**Comment by haziq993** [comment]
**1) Dynamo Version**
Dynamo Core 2.6.1.8786
Dynamo Revit 2.6.1.8850

**2) Operating System**
Windows 10

**Other information:**
I reported this issue on dynamobim.org as well. See [https://forum.dynamobim.com/t/no-3d-view-toggle-button/71232]
_TLDR_
a) The toggle button between 3D and graph is not there. 
b) The options under View > Background 3D View are mostly greyed out.
![image](https://user-images.githubusercontent.com/91877782/145719040-2507e3b2-bab1-4962-ba82-16cee734327a.png)

I would also like to add that I recently installed the whole Revit software, on a new computer and the problem is still there. Seems like an issue with new installs?

**Comment by mjkkirschner** [comment]
for dynamo versions below 2.7 you need directX 10 - https://www.microsoft.com/en-us/download/details.aspx?id=8109

**Comment by haziq993** [comment]
I have installed DirectX from the link you provided @mjkkirschner, but I am still unable to see the 3D background preview.

Out of curiosity, why is this only a problem I am encountering recently? Is the dynamo version installed with recent Revit installations just of an earlier version?
