### ISSUE TITLE
Crash report from Dynamo 2.13.0.3485

### ISSUE THREAD

**Issue by johnpierson** [DynamoDS/Dynamo#12532]
# Issue Description
Right-click lacing menu persists during other right-click events

## Dynamo version
Dynamo: `2.13.0.3485`

## Operating system
OS: Windows 10

## What did you do?
![20220106-lacingPersist2](https://user-images.githubusercontent.com/15744724/148439535-c9bc6e47-3237-4cdf-a521-2826d72551ec.gif)

## What did you expect to see?
Lacing menu to disappear once I right-click somewhere else (similar to left click)

## What did you see instead?
Menu stayed. Crash

## What packages or external references (if any) were used?
No loaded packages were found.

## Stack Trace
```
UpdateModelValue: Model not found

   at Dynamo.Graph.Workspaces.WorkspaceModel.UpdateModelValue(IEnumerable`1 modelGuids, String propertyName, String value)
   at Dynamo.Models.DynamoModel.UpdateModelValueImpl(UpdateModelValueCommand command)
   at Dynamo.Models.DynamoModel.ExecuteCommand(RecordableCommand command)
   at Dynamo.ViewModels.InPortViewModel.UseLevel(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at DynamoSandbox.DynamoCoreSetup.RunApplication(Application app)

-------- Assemblies --------

mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089|DynamoSandbox, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35|WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35|System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089|System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089|PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35|System.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089|DynamoCore, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|DynamoApplications, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|DynamoInstallDetective, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a|DynamoServices, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|NDesk.Options, Version=0.2.1.0, Culture=neutral, PublicKeyToken=null|System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089|DynamoCoreWpf, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|Microsoft.Practices.Prism, Version=4.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35|SharpDX.Mathematics, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b4dcf0f35e5521f1|DynamoShapeManager, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|LibG.AsmPreloader.Managed, Version=2.13.0.6926, Culture=neutral, PublicKeyToken=null|LibG.AsmPreloader.Unmanaged, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null|Greg, Version=2.1.8012.31283, Culture=neutral, PublicKeyToken=null|ProtoCore, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|DynamoUtilities, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|ProtoAssociative, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|ProtoImperative, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|Microsoft.GeneratedCode, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null|Analytics.Net.ADP, Version=2.13.0.0, Culture=neutral, PublicKeyToken=null|Analytics.NET.Core, Version=2.13.0.24836, Culture=neutral, PublicKeyToken=null|AdpSDKCSharpWrapper, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null|DynamoUnits, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|DynamoCore.resources, Version=2.13.0.3485, Culture=en-US, PublicKeyToken=null|DynamoPackages, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|DesignScriptBuiltin, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|VMDataBridge, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|ProtoCore.resources, Version=2.13.0.3485, Culture=en-US, PublicKeyToken=null|Microsoft.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a|Anonymously Hosted DynamicMethods Assembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null|System.Dynamic, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a|ProtoGeometry, Version=2.13.0.6925, Culture=neutral, PublicKeyToken=null|LibG.Interface, Version=2.13.0.6925, Culture=neutral, PublicKeyToken=null|DSCoreNodes, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a|Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed|DSCoreNodes.resources, Version=2.13.0.3485, Culture=en-US, PublicKeyToken=null|DSOffice, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|DSOffice.resources, Version=2.13.0.3485, Culture=en-US, PublicKeyToken=null|DSCPython, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|Python.Runtime, Version=2.5.1.2374, Culture=neutral, PublicKeyToken=null|DynamoConversions, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|Tessellation, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|MIConvexHull.NET Standard, Version=1.0.17.411, Culture=neutral, PublicKeyToken=null|System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a|Analysis, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|Analysis.resources, Version=2.13.0.3485, Culture=en-US, PublicKeyToken=null|GeometryColor, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|ProtoScript, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|LibG.ProtoInterface, Version=2.13.0.6926, Culture=neutral, PublicKeyToken=null|LibG.Managed, Version=2.13.0.6926, Culture=neutral, PublicKeyToken=null|CoreNodeModels.customization, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|CoreNodeModels, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|CoreNodeModels.resources, Version=2.13.0.3485, Culture=en-US, PublicKeyToken=null|CoreNodeModelsWpf, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|GeometryUI.customization, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|GeometryUI, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|GeometryUI.resources, Version=2.13.0.3485, Culture=en-US, PublicKeyToken=null|GeometryUIWpf, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|Migrations, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|NCalc, Version=1.3.8.0, Culture=neutral, PublicKeyToken=973cde3f1cafed03|PythonNodeModels.customization, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|PythonNodeModels, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|PythonNodeModels.resources, Version=2.13.0.3485, Culture=en-US, PublicKeyToken=null|PythonNodeModelsWpf, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|ICSharpCode.AvalonEdit, Version=4.3.1.9429, Culture=neutral, PublicKeyToken=9cc39be672370310|UnitsUI.customization, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|UnitsUI, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|UnitsUI.resources, Version=2.13.0.3485, Culture=en-US, PublicKeyToken=null|Watch3DNodeModels.customization, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|Watch3DNodeModels, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|Watch3DNodeModels.resources, Version=2.13.0.3485, Culture=en-US, PublicKeyToken=null|Watch3DNodeModelsWpf, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|Xceed.Wpf.Toolkit, Version=3.0.0.0, Culture=neutral, PublicKeyToken=3e4669d2f30244f4|System.Xml.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089|BuiltIn.customization, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|Operators.customization, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|ProtoGeometry.customization, Version=2.13.0.6925, Culture=neutral, PublicKeyToken=null|DesignScriptBuiltin.customization, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|DSCoreNodes.customization, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|DSOffice.customization, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|DynamoUnits.customization, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|Tessellation.customization, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|Analysis.customization, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|GeometryColor.customization, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|RestSharp, Version=106.12.0.0, Culture=neutral, PublicKeyToken=598062e77f915f75|DynamoPackages.resources, Version=2.13.0.3485, Culture=en-US, PublicKeyToken=null|HelixToolkit.Wpf.SharpDX, Version=2.17.0.0, Culture=neutral, PublicKeyToken=52aa3500039caf0d|SharpDX, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b4dcf0f35e5521f1|DynamoCoreWpf.resources, Version=2.13.0.3485, Culture=en-US, PublicKeyToken=null|HelixToolkit, Version=2.17.0.0, Culture=neutral, PublicKeyToken=52aa3500039caf0d|SharpDX.DXGI, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b4dcf0f35e5521f1|SharpDX.Direct3D11, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b4dcf0f35e5521f1|SharpDX.Direct2D1, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b4dcf0f35e5521f1|FontAwesome.WPF, Version=4.7.0.37774, Culture=neutral, PublicKeyToken=0758b07a11a4f466|System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089|PresentationFramework.Aero2, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35|PresentationFramework-SystemXml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089|UIAutomationTypes, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35|UIAutomationProvider, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35|DocumentationBrowserViewExtension, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|DocumentationBrowserViewExtension.resources, Version=2.13.0.3485, Culture=en-US, PublicKeyToken=null|DynamoManipulation, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|GraphMetadataViewExtension, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|LibraryViewExtensionMSWebBrowser, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|LintingViewExtension, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|Notifications, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|PackageDetailsViewExtension, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|DynamoPackagesWPF, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|PythonMigrationViewExtension, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|WorkspaceDependencyViewExtension, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|WorkspaceDependencyViewExtension.resources, Version=2.13.0.3485, Culture=en-US, PublicKeyToken=null|Notifications.resources, Version=2.13.0.3485, Culture=en-US, PublicKeyToken=null|PackageDetailsViewExtension.resources, Version=2.13.0.3485, Culture=en-US, PublicKeyToken=null|PresentationFramework-SystemXmlLinq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089|PresentationFramework-SystemCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089|System.Windows.Interactivity, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35|GraphMetadataViewExtension.resources, Version=2.13.0.3485, Culture=en-US, PublicKeyToken=null|System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089|System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089|System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089|LibraryViewExtensionMSWebBrowser.resources, Version=2.13.0.3485, Culture=en-US, PublicKeyToken=null|LintingViewExtension.resources, Version=2.13.0.3485, Culture=en-US, PublicKeyToken=null|PresentationFramework-SystemData, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089|Cyotek.Drawing.BitmapFont, Version=1.0.0.0, Culture=neutral, PublicKeyToken=58daa28b0b2de221|WindowsFormsIntegration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35|SharpDX.D3DCompiler, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b4dcf0f35e5521f1|SharpDX.Direct3D9, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b4dcf0f35e5521f1|Microsoft.mshtml, Version=7.0.3300.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a|Accessibility, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a|Windows.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime|System.Runtime.InteropServices.WindowsRuntime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a|DynamoCore.customization, Version=2.13.0.3485, Culture=neutral, PublicKeyToken=null|System.Collections.Immutable, Version=1.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a|System.Runtime.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a|System.Resources.ResourceManager, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
```

---
CLR: `4.0.30319.42000`

**Comment by QilongTang** [comment]
This looks pretty bad @johnpierson @Amoursol I will log it

**Comment by johnpierson** [comment]
Thanks, @QilongTang , I actually noticed this when the autocomplete menu showed up (kind of easy to double click that while connecting a node). So a similar crash can happen in that case too.

![image](https://user-images.githubusercontent.com/15744724/148442852-27b149c2-2ed1-4f02-be3f-c5b747906105.png)

**Comment by johnpierson** [comment]
https://user-images.githubusercontent.com/15744724/148444142-0a8889f8-a67f-4f69-84de-9f6713a1d542.mp4

**Comment by QilongTang** [comment]
I have a PR to fix both issue https://github.com/DynamoDS/Dynamo/pull/12565
