### ISSUE TITLE
Crash report from Dynamo 2.12.0.5650

### ISSUE THREAD

**Issue by dslicona** [DynamoDS/Dynamo#12603]
# Issue Description
Please fill in the following information to help us reproduce the issue:

## Dynamo version
Dynamo: `2.12.0.5650`

## Operating system
OS: `Microsoft Windows NT 10.0.18363.0`

## What did you do?
Added custom node (helper) opened it to copy the nodes inside and add them to my graph

## What did you expect to see?
custom node definition with all its nodes 
## What did you see instead?
Dynamo Crash

### Loaded Packages
- CivilConnection2022 6.0.0
- spring nodes 204.1.0
- TuneUp 1.0.7
- GenerativeDesign 1.9.3.0
- GenerativeDesign.Extension 1.9.3.0
- GenerativeDesign.Revit 1.9.3.0

## Stack Trace
```
Object reference not set to an instance of an object.

   at Dynamo.WorkspaceDependency.WorkspaceDependencyView.DependencyRegen(WorkspaceModel ws)
   at Dynamo.WorkspaceDependency.WorkspaceDependencyView.OnWorkspaceChanged(IWorkspaceModel obj)
   at System.Action`1.Invoke(T obj)
   at Dynamo.Extensions.ReadyParams.OnDynamoModelPropertyChanged(Object sender, PropertyChangedEventArgs e)
   at System.ComponentModel.PropertyChangedEventHandler.Invoke(Object sender, PropertyChangedEventArgs e)
   at Dynamo.Models.DynamoModel.OnPropertyChanged(String propertyName)
   at Dynamo.Models.DynamoModel.OpenCustomNodeWorkspace(Guid guid)
   at Dynamo.ViewModels.DynamoViewModel.FocusCustomNodeWorkspace(Guid symbol)
   at Dynamo.ViewModels.DynamoViewModel.GoToWorkspace(Object parameter)
   at Dynamo.Controls.NodeView.topControl_MouseLeftButtonDown(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

---
CLR: `4.0.30319.42000`

**Comment by mjkkirschner** [comment]
thanks for reporting @dslicona - can you also share the custom node file that you describe above?
