### ISSUE TITLE
Crash report from Dynamo 2.12.0.5650

### ISSUE THREAD

**Issue by glavoc** [DynamoDS/Dynamo#12616]
# Issue Description
Please fill in the following information to help us reproduce the issue:

## Dynamo version
Dynamo: `2.12.0.5650`

## Operating system
OS: `Microsoft Windows NT 10.0.19042.0`

## What did you do?
double clicked on custom node to edit it.

## What did you expect to see?
custom node editing window

## What did you see instead?
"Dynamo has crashed" popup window

### Loaded Packages
- archi-lab.net 2022.212.2922
- Data-Shapes 2022.2.102
- spring nodes 204.1.0
- GenerativeDesign 1.9.3.0
- GenerativeDesign.Extension 1.9.3.0
- GenerativeDesign.Revit 1.9.3.0

## Stack Trace
```
Object reference not set to an instance of an object.

   at Dynamo.WorkspaceDependency.WorkspaceDependencyView.DependencyRegen(WorkspaceModel ws)
   at Dynamo.WorkspaceDependency.WorkspaceDependencyView.OnWorkspaceChanged(IWorkspaceModel obj)
   at System.Action`1.Invoke(T obj)
   at Dynamo.Extensions.ReadyParams.OnDynamoModelPropertyChanged(Object sender, PropertyChangedEventArgs e)
   at System.ComponentModel.PropertyChangedEventHandler.Invoke(Object sender, PropertyChangedEventArgs e)
   at Dynamo.Models.DynamoModel.OnPropertyChanged(String propertyName)
   at Dynamo.Models.DynamoModel.OpenCustomNodeWorkspace(Guid guid)
   at Dynamo.ViewModels.DynamoViewModel.FocusCustomNodeWorkspace(Guid symbol)
   at Dynamo.ViewModels.DynamoViewModel.GoToWorkspace(Object parameter)
   at Dynamo.Controls.NodeView.topControl_MouseLeftButtonDown(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

---
CLR: `4.0.30319.42000`

**Comment by Amoursol** [comment]
@glavoc would you be willing to share the custom node that causes the crash with us?

**Comment by glavoc** [comment]
@Amoursol 
I have reinstalled all the packages and that had resolved the issue. But to answer your question, it was all and any custom node (from packages and my own created)

Thanks

**Comment by Amoursol** [comment]
Hi @glavoc - Ah, interesting. Thanks for the heads up! I'll close for now, but see if the stack trace is actionable from the team. 

@QilongTang is there enough information to go on in the stack trace here (No reproducible custom nodes) for us to look into guarding Custom Nodes better against crashes?
