### ISSUE TITLE
Crash report from Dynamo 2.6.1.8786

### ISSUE THREAD

**Issue by Lulumarc** [DynamoDS/Dynamo#12623]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
have many packages. update revit to 2021.5

### What did you expect to see?
script run

### What did you see instead?
didnt run. run yesterday. Present error. Dy files are always read only

### What packages or external references (if any) were used?
BIM4Struc v.2.2.2
archilab v.2022.210.2221
Rhythm v.2021.7.3
LunchBox v.2018.7.6
spring nodes v.203.2.0
Orchid v. 206.3.0.8046

### Stack Trace
Index was outside the bounds of the array.

   at ProtoCore.Lang.ArrayUtilsForBuiltIns.Transpose(StackValue sv, Interpreter runtime)
   at ProtoCore.Lang.BuiltInFunctionEndPoint.Execute(Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.CallSite.ExecWithZeroRI(List`1 functionEndPoint, Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore, SingleRunTraceData previousTraceData, SingleRunTraceData newTraceData, FunctionEndPoint finalFep)
   at ProtoCore.CallSite.Execute(List`1 functionEndPoint, Context c, List`1 formalParameters, List`1 replicationInstructions, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.CallSite.DispatchNew(Context context, List`1 arguments, List`1 partialReplicationGuides, DominantListStructure domintListStructure, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.DSASM.Executive.Callr(Int32 blockDeclId, Int32 functionIndex, Int32 classIndex, Boolean& explicitCall, Boolean isDynamicCall, Boolean hasDebugInfo)
   at ProtoCore.DSASM.Executive.CALLR_Handler(Instruction instruction)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
   at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   at ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()

---
OS: `Microsoft Windows NT 10.0.19044.0`
CLR: `4.0.30319.42000`
![Doors-Windows View Generation_EXCEL FILE_2022-02-10_12-18-33](https://user-images.githubusercontent.com/99169096/153401357-a9632f11-6694-43ce-bb1a-a484885baff5.png)

Dynamo: `2.6.1.8786`

**Comment by Lulumarc** [comment]
While loading assembly Xceed.Wpf.AvalonDock.Themes.Aero, Version=4.0.0.0, Culture=neutral, PublicKeyToken=3e4669d2f30244f4, Dynamo detected that the dependency Xceed.Wpf.AvalonDock, Version=4.0.0.0, Culture=neutral, PublicKeyToken=3e4669d2f30244f4 was already loaded with an incompatiable version. It is likely that another Revit Addin has loaded this assembly, please try uninstalling other Addins, and starting Dynamo again. Dynamo may be unstable in this state.
It is likely one of the following assemblies loaded the incompatible version:
UIFramework, pyRevit_2021_777416d2e497d69a_PyRevitLabs.PyRevit.Runtime.dll, Microsoft.GeneratedCode

**Comment by QilongTang** [comment]
@mjkkirschner and the rest of @DynamoDS/dynamo , I interpret this as conflict with pyRevit add-in of Revit host?

**Comment by mjkkirschner** [comment]
missed this one @QilongTang I'm not so sure - I wouldn't expect these wpf library conflicts to impact the vm.

**Comment by mjkkirschner** [comment]
Hi @Lulumarc - Were you able to resolve this?
If not please attach the necessary files to recreate the error as well as the exact steps you take. It looks like some of the package nodes are missing or throwing errors in the image above, but I can't see the exact errors.
