### ISSUE TITLE
bug when export as image

### ISSUE THREAD

**Issue by danibarbo** [DynamoDS/Dynamo#12635]
## Dynamo version

Dynamo Core 2.12.0.5650

## Operating system

Windows 10

## What did you do? 

Save as image

## What did you expect to see?

save image successfully

## What did you see instead?

"Uh oh... something went wrong and Dynamo has crashed, sorry about that."

Log:

The image data generated an overflow during processing.

   at System.Windows.Media.Renderer.Render(IntPtr pRenderTarget, Channel channel, Visual visual, Int32 width, Int32 height, Double dpiX, Double dpiY, Matrix worldTransform, Rect windowClip)
   at System.Windows.Media.Imaging.BitmapVisualManager.Render(Visual visual, Matrix worldTransform, Rect windowClip)
   at System.Windows.Media.Imaging.BitmapVisualManager.Render(Visual visual)
   at Dynamo.Views.WorkspaceView.SaveWorkspaceAsImage(String path)
   at Dynamo.ViewModels.DynamoViewModel.OnRequestSaveImage(Object sender, ImageSaveEventArgs e)
   at Dynamo.ViewModels.DynamoViewModel.SaveImage(Object parameters)
   at Dynamo.ViewModels.DynamoViewModel.ShowSaveImageDialogAndSaveResult(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by QilongTang** [comment]
hi @danibarbo it is not super clear from the stack trace but from your experience, does this happen a lot when the graph is giant? Can you elaborate a bit more about the problem here?

**Comment by danibarbo** [comment]
Hi, @QilongTang 

I have problem When i export my graphics as image!

I believe what this issue has be occurred by size of programing!
Because when I reduced your size of printable area, this issue has solved!

**Comment by QilongTang** [comment]
hi @danibarbo Thank you for your findings, are you willing to share your graph with our team to better digest this problem? my email is aaron.tang@autodesk.com
