### ISSUE TITLE
Crash report from Dynamo 2.12.0.5650

### ISSUE THREAD

**Issue by danibarbo** [DynamoDS/Dynamo#12631]
# Issue Description
Please fill in the following information to help us reproduce the issue:

## Dynamo version
Dynamo: `2.12.0.5650`

## Operating system
OS: `Microsoft Windows NT 10.0.19044.0`

## What did you do?
(Fill in here)

## What did you expect to see?
(Fill in here)

## What did you see instead?
(Fill in here)

### Loaded Packages
- archi-lab.net 2018.0.6
- Bakery 2018.4.301
- Beyond Dynamo 1.1.0
- BIM4Struc.Rebar 1.3.0
- bimorphNodes 4.0.13
- BumbleBee 2021.25.3
- Clockwork for Dynamo 2.x 2.3.0
- Data-Shapes 2022.2.100
- DynaWorks22 2.0.0
- Genius Loci 2021.11.10
- MEPover 2020.6.2
- Rhythm 2021.7.3
- SpeckleDynamo2 2.0.0
- spring nodes 204.1.0
- SteamNodes 1.2.4
- Structural Analysis for Dynamo 2.11.0
- Structural Design 2021.9.23
- GenerativeDesign 1.10.10.0
- GenerativeDesign.Extension 1.10.10.0
- GenerativeDesign.Revit 1.10.10.0

## Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```
The image data generated an overflow during processing.

   at System.Windows.Media.Renderer.Render(IntPtr pRenderTarget, Channel channel, Visual visual, Int32 width, Int32 height, Double dpiX, Double dpiY, Matrix worldTransform, Rect windowClip)
   at System.Windows.Media.Imaging.BitmapVisualManager.Render(Visual visual, Matrix worldTransform, Rect windowClip)
   at System.Windows.Media.Imaging.BitmapVisualManager.Render(Visual visual)
   at Dynamo.Views.WorkspaceView.SaveWorkspaceAsImage(String path)
   at Dynamo.ViewModels.DynamoViewModel.OnRequestSaveImage(Object sender, ImageSaveEventArgs e)
   at Dynamo.ViewModels.DynamoViewModel.SaveImage(Object parameters)
   at Dynamo.ViewModels.DynamoViewModel.ShowSaveImageDialogAndSaveResult(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---
CLR: `4.0.30319.42000`

**Comment by danibarbo** [comment]
![1](https://user-images.githubusercontent.com/76652897/153881731-5a8f9879-1bdf-401c-85b2-91d919054d82.PNG)
![3](https://user-images.githubusercontent.com/76652897/153881792-73a7c56b-7461-4753-8cc7-d50506489c7c.PNG)

**Comment by QilongTang** [comment]
@danibarbo We noticed that you closed this, what happened? Were you able to resolve this yourself?

**Comment by danibarbo** [comment]
No, i didn't solve it.

**Comment by QilongTang** [comment]
@Amoursol I remember there was a bug that super large graph saving as image may crash Dynamo, is it similar to this case?

**Comment by Amoursol** [comment]
> @Amoursol I remember there was a bug that super large graph saving as image may crash Dynamo, is it similar to this case?

This looks to be the same case, yes. @danibarbo did it crash when you tried to use the "Export Workspace as Image" feature? Or were you doing something else?
