### ISSUE TITLE
Crash report from Dynamo 2.12.0.5650

### ISSUE THREAD

**Issue by aniketdikshit** [DynamoDS/Dynamo#12689]
# Issue Description
Please fill in the following information to help us reproduce the issue:

## Dynamo version
Dynamo: `2.12.0.5650`

## Operating system
OS: `Microsoft Windows NT 10.0.19044.0`

## What did you do?
tried to open the genius Loci LinkCad python package

## What did you expect to see?
(Fill in here)

## What did you see instead?
(Fill in here)

### Loaded Packages
- archi-lab.net 2022.212.3221
- Genius Loci 2022.3.9
- Monocle 2022.2.1
- Rhythm 2022.3.1
- GenerativeDesign 1.9.3.0
- GenerativeDesign.Extension 1.9.3.0
- GenerativeDesign.Revit 1.9.3.0

## Stack Trace
```
Object reference not set to an instance of an object.

   at Dynamo.WorkspaceDependency.WorkspaceDependencyView.DependencyRegen(WorkspaceModel ws)
   at Dynamo.WorkspaceDependency.WorkspaceDependencyView.OnWorkspaceChanged(IWorkspaceModel obj)
   at System.Action`1.Invoke(T obj)
   at Dynamo.Extensions.ReadyParams.OnDynamoModelPropertyChanged(Object sender, PropertyChangedEventArgs e)
   at System.ComponentModel.PropertyChangedEventHandler.Invoke(Object sender, PropertyChangedEventArgs e)
   at Dynamo.Models.DynamoModel.OnPropertyChanged(String propertyName)
   at Dynamo.Models.DynamoModel.OpenCustomNodeWorkspace(Guid guid)
   at Dynamo.ViewModels.DynamoViewModel.FocusCustomNodeWorkspace(Guid symbol)
   at Dynamo.ViewModels.DynamoViewModel.GoToWorkspace(Object parameter)
   at Dynamo.Controls.NodeView.topControl_MouseLeftButtonDown(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

---
CLR: `4.0.30319.42000`

**Comment by Amoursol** [comment]
Hello @aniketdikshit, thank you for submitting this issue! We are super excited that you want to help us make Dynamo all that it can be. However, we need some more information in order for the Dynamo team to investigate any further.

Can you please fill in the following to the best of your ability:

- What did you expect to see?
- What did you see instead?


 **Additional information:**
- Filling in of the provided Template (What did you do, What did you expect to see, What did you see instead, What packages or external references (if any) were used)
- Attaching the Stack Trace (Error message that shows up when Dynamo crashes - You can copy and paste this into the Github Issue)
- Upload a .DYN file that showcases the issue in action and any additional needed files, such as Revit (Note: If you cannot share a project, you can recreate this in a quick mock-up file)
- Upload a Screenshot of the error messages you see (Hover over the offending node and showcase said errors message in the screenshot)
- Reproducible steps on how to create the error in question.
