### ISSUE TITLE
Crash report from Dynamo 2.6.1.8786

### ISSUE THREAD

**Issue by JennyYang29** [DynamoDS/Dynamo#12722]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
open a revit project and try to run Dynamo then open a script file.

### What did you expect to see?
file opened

### What did you see instead?
warning message said dynamo has crashed.

### What packages or external references (if any) were used
Civilconnection2020

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
Access to the path 'C:\Users\AUJY502061\AppData\Roaming\Analytics\CSharpAnalytics-MeasurementSession' is denied.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at CSharpAnalytics.Serializers.AppDataContractSerializer.<Save>d__7`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CSharpAnalytics.WinFormAutoMeasurement.<Save>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Analytics.NET.Google.WinNativeAutoMeasurement.<Save>d__11`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CSharpAnalytics.BaseAutoMeasurement.<Start>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

---
OS: `Microsoft Windows NT 10.0.19044.0`
CLR: `4.0.30319.42000`
Dynamo: `2.6.1.8786`

**Comment by Amoursol** [comment]
Hello @JennyYang29, thank you for submitting this issue! We are super excited that you want to help us make Dynamo all that it can be. However, we need some more information in order for the Dynamo team to investigate any further.

Can you please fill in the following to the best of your ability:

- What did you expect to see?
- What did you see instead?


 **Additional information:**
- Filling in of the provided Template (What did you do, What did you expect to see, What did you see instead, What packages or external references (if any) were used)
- Attaching the Stack Trace (Error message that shows up when Dynamo crashes - You can copy and paste this into the Github Issue)
- Upload a .DYN file that showcases the issue in action and any additional needed files, such as Revit (Note: If you cannot share a project, you can recreate this in a quick mock-up file)
- Upload a Screenshot of the error messages you see (Hover over the offending node and showcase said errors message in the screenshot)
- Reproducible steps on how to create the error in question.

**Comment by avidit** [comment]
@JennyYang29 Can you try to delete the file `%APPDATA%\Analytics\CSharpAnalytics-MeasurementSession` ?
