### ISSUE TITLE
Crash report from Dynamo 2.3.1.11775

### ISSUE THREAD

**Issue by erinchia** [DynamoDS/Dynamo#12837]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
Open any files will get this error

### What did you expect to see?
Dynamo is not working like usual

### What did you see instead?
Error message: Object reference not set to an instance of an object.

   at Dynamo.Models.DynamoModel.Dispose()
   at Dynamo.Models.DynamoModel.ShutDownCore(Boolean shutdownHost)
   at Dynamo.Applications.Models.RevitDynamoModel.ShutDownCore(Boolean shutDownHost)
   at Dynamo.Models.DynamoModel.ShutDown(Boolean shutdownHost)
   at Dynamo.ViewModels.DynamoViewModel.PerformShutdownSequence(ShutdownParams shutdownParams)
   at Dynamo.Controls.DynamoView.PerformShutdownSequenceOnViewModel()
   at Dynamo.Controls.DynamoView.WindowClosing(Object sender, CancelEventArgs e)
   at System.Windows.Window.OnClosing(CancelEventArgs e)
   at System.Windows.Window.WmClose()
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### What packages or external references (if any) were used?
(Fill in here)

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
OS: `Microsoft Windows NT 10.0.19044.0`
CLR: `4.0.30319.42000`
Dynamo: `2.3.1.11775`

**Comment by erinchia** [comment]
OS: Microsoft Windows NT 10.0.19044.1586
Dynamo 2.3.1.11775

Cannot do anything at the canvas, such as right-click and click on one of the nodes from the library. Restart machine didn't work.


https://user-images.githubusercontent.com/64710379/165577763-488b190f-d5a3-4273-b8da-b67416613553.MP4

**Comment by erinchia** [comment]
![Snag_da79795](https://user-images.githubusercontent.com/64710379/165578177-5ae81c22-a07a-4caa-9823-f79af4730165.png)

**Comment by Amoursol** [comment]
Hello @erinchia - thank you for submitting this error report. We are sorry that your Dynamo has fallen into a broken state :( 

@mjkkirschner any ideas on this one?

**Comment by erinchia** [comment]
![91aed93e-750b-4fd9-9c13-beb3d52262c4](https://user-images.githubusercontent.com/64710379/165630003-11c6d338-1742-4e72-97e2-f2d141d87e45.jpg)

Also, has this happens on multiple different machines.

**Comment by mjkkirschner** [comment]
there are 30 notifications and tons of packages installed. I would start there and also disabling all Revit add-ins, especially new ones.

**Comment by erinchia** [comment]
After uninstalling all the packages and only installing a few that we need. And also disabling all Revit add-ins, we got this error.
![efcb92ab-9bf6-432c-bf6d-8c47ba0b6bcf](https://user-images.githubusercontent.com/64710379/165640576-29c42199-b96b-4dc7-b8a2-cf7a763ec6ef.jpg)
