### ISSUE TITLE
Crash report from Dynamo 2.13.1.3887

### ISSUE THREAD

**Issue by armandomanuel** [DynamoDS/Dynamo#12920]
# Issue Description
Please fill in the following information to help us reproduce the issue:

## Dynamo version
Dynamo: `2.13.1.3887`

## Operating system
OS: `Microsoft Windows NT 10.0.19044.0`

## What did you do?
(I selected a group of nodes and then node to code)

## What did you expect to see?
(Nodes convert to code)

## What did you see instead?
(Crash)

### Loaded Packages
- GenerativeDesign 2.0.10.0
- GenerativeDesign.Extension 2.0.10.0
- GenerativeDesign.Revit 2.0.10.0

## Stack Trace
```
(An item with the same key has already been added.

   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Dynamo.Engine.NodeToCode.NodeToCodeCompiler.GetCliques(IEnumerable`1 selection)
   at Dynamo.Graph.Workspaces.NodesToCodeExtensions.ConvertNodesToCodeInternal(WorkspaceModel workspace, EngineController engineController, INamingProvider namingProvider)
   at Dynamo.Models.DynamoModel.ConvertNodesToCodeImpl(ConvertNodesToCodeCommand command)
   at Dynamo.Models.DynamoModel.ExecuteCommand(RecordableCommand command)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler))
```

---
CLR: `4.0.30319.42000`

**Comment by armandomanuel** [comment]
Thanks, but I wasn't able to reproduce. Worked when I tried it a second time.
