### ISSUE TITLE
Crash report from Dynamo 2.12.0.5650

### ISSUE THREAD

**Issue by acheilman** [DynamoDS/Dynamo#12933]
# Issue Description
Please fill in the following information to help us reproduce the issue:

## Dynamo version
Dynamo: `2.12.0.5650`

## Operating system
OS: `Microsoft Windows NT 10.0.19042.0`

## What did you do?
Try to open Generative Design

https://forum.dynamobim.com/t/generative-design-21-16-10-crashes/61461/9
CTC has been removed and there is still a crash

## What did you expect to see?
Generative Design

## What did you see instead?
Crash

Set property 'System.Windows.ResourceDictionary.Source' threw an exception.

   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at GenerativeDesign.Dynamo.UI.Views.GenerativeDesignMainView..ctor(GenerativeDesignMainViewModel viewModel)
   at GenerativeDesign.Dynamo.ViewExtension.GenerativeDesignViewExtension.OpenSidePanel()
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Loaded Packages
- archi-lab.net 2022.212.2922
- BumbleBee 2021.25.3
- Clockwork for Dynamo 2.x 2.4.0
- Flackage 2.12.0
- Refinery Toolkit 1.1.1
- Rhythm 2021.1.1
- SteamNodes 1.2.4
- GenerativeDesign 1.9.3.0
- GenerativeDesign.Extension 1.9.3.0
- GenerativeDesign.Revit 1.9.3.0

## Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
CLR: `4.0.30319.42000`

**Comment by acheilman** [comment]
https://forum.dynamobim.com/t/generative-design-21-16-10-crashes/61461/16?u=acheilman

Issue solved
