### ISSUE TITLE
Strange cascade of errors when using watch node in recursive solar sample.

### ISSUE THREAD

**Issue by mjkkirschner** [DynamoDS/Dynamo#1296]
![screen shot 2014-03-17 at 3 30 14 pm](https://f.cloud.github.com/assets/508936/2440717/df081a56-ae0a-11e3-8091-d8036076ce09.png)

When introducing a watch node inside this custom node which is being called recursively I am getting this error about incomparable types, Somehow the structure of this list has become a nested list of list of list etc...

This graph runs fine if I use calls to dynamoLogger directly to look at the data, but as soon as I include a watch node this error below occurs which might shed some light on it.

```
Error saving:System.NotSupportedException
System.NotSupportedException:
This type of CollectionView does not support changes to its SourceCollection from a thread different from the Dispatcher thread.
   at System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.Collection`1.Remove(T item)
   at Dynamo.ViewModels.NodeViewModel.outports_collectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at Dynamo.Models.NodeModel.RegisterOutputs()
   at Dynamo.FunctionDefinition.<>c__DisplayClass20.<Compile>b__14(Function node)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Dynamo.FunctionDefinition.Compile()
   at Dynamo.FunctionDefinition.SyncWithWorkspace(Boolean addToSearch, Boolean compileFunction)
Error saving:System.NotSupportedException```

**Comment by ikeough** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version. 

Thank you!
