### ISSUE TITLE
Archi-lab package fails on install, yet was installed before and crashed

### ISSUE THREAD

**Issue by adamostra** [DynamoDS/Dynamo#13123]
# Issue Description
Please fill in the following information to help us reproduce the issue:
I have installed Archi-lab package. Everything worked properly. Restarted dynamo and it failed and has been removed from dynamo. It asked me to report this on GitHub. I am unable to install the Archi-lab again.

### What did you do?
used a node from the package. saved and closed, Reopened, copied the node and it showed that it is deprecated. Then the package disappeared and I am unable to install it again.

### What did you expect to see?
functional node and package

### What did you see instead?
removed package, unable to install again

### What packages or external references (if any) were used?
Archi-lab 2023.213.1523

### Stack Trace
```
Dynamo.Exceptions.LibraryLoadFailedException: Failed to load library: C:\ProgramData\Autodesk\RVT 2021\Dynamo\2.6\packages\archi-lab.net
   at Dynamo.PackageManager.PackageLoader.CheckPackageNodeLibraryCertificates(String packageDirectoryPath, Package discoveredPkg)
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates)

Failed to load library: C:\ProgramData\Autodesk\RVT 2021\Dynamo\2.6\packages\archi-lab.net

"A package called archi-lab.net found at C:\ProgramData\Autodesk\RVT 2021\Dynamo\2.6\packages\archi-lab.net could not be verified to have signed dll files.  A dll file found at C:\ProgramData\Autodesk\RVT 2021\Dynamo\2.6\packages\archi-lab.net\bin\archilab2023.dll did not have a signed certificate.  Ignoring it."
```

---
OS: `Microsoft Windows NT 10.0.19044.0`
CLR: `4.0.30319.42000`
Dynamo: `2.6.2.15705`

![Capture](https://user-images.githubusercontent.com/109588002/179717768-1215f14a-d02b-4d2f-a98f-692e73c6a7de.PNG)

**Comment by adamostra** [comment]
OS: Microsoft Windows NT 10.0.19044.0
CLR: 4.0.30319.42000
Dynamo: 2.6.2.15705

**Comment by adamostra** [comment]
> Hello adamostra, thank you for submitting this issue! We are super excited that you want to help us make Dynamo all that it can be. However, we need some more information in order for the Dynamo team to investigate any further.
> 
> Can you please fill in the following to the best of your ability:
> 
> * Dynamo version
> * Operating system.
> 
> Additional information:
> 
> * Filling in of the provided Template (What did you do, What did you expect to see, What did you see instead, What packages or external references (if any) were used)
> * Attaching the Stack Trace (Error message that shows up when Dynamo crashes - You can copy and paste this into the Github Issue)
> * Upload a .DYN file that showcases the issue in action and any additional needed files, such as Revit (Note: If you cannot share a project, you can recreate this in a quick mock-up file)
> * Upload a Screenshot of the error messages you see (Hover over the offending node and showcase said errors message in the screenshot)
> * Reproducible steps on how to create the error in question.

OS: Microsoft Windows NT 10.0.19044.0
CLR: 4.0.30319.42000
Dynamo: 2.6.2.15705

**Comment by mjkkirschner** [comment]
Hi @adamostra - somehow your packages are being installed into the wrong package folder.
Try going into manage node and package paths, and use the arrows to move the `%appData%` one above the `%programData% entry.

In this version of Dynamo I think packages get installed to the first entry in the list.
