### ISSUE TITLE
Crash report from Dynamo 2.3.2.15696

### ISSUE THREAD

**Issue by ART-Raina** [DynamoDS/Dynamo#13205]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
Replaced nodes in a graph with newer versions

### What did you expect to see?
Nothing - hadn't run the graph or anything. Purely replacing nodes, preparing to run. 

### What did you see instead?
Dynamo crash popup

### What packages or external references (if any) were used?
Crumple, Data-Shapes, Bumble Bee, bimorphNodes

### Stack Trace
```
The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.

   at System.IO.PathHelper.GetFullPathName()
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.Path.GetFullPath(String path)
   at System.Windows.Forms.IntSecurity.UnsafeGetFullPath(String fileName)
   at System.Windows.Forms.IntSecurity.DemandFileIO(FileIOPermissionAccess access, String fileName)
   at System.Windows.Forms.FileDialog.get_FileName()
   at Dynamo.ViewModels.DynamoViewModel.ShowSaveDialogAndSaveResult(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

---
OS: `Microsoft Windows NT 10.0.19044.0`
CLR: `4.0.30319.42000`
Dynamo: `2.3.2.15696`

**Comment by QilongTang** [comment]
as indicated by the error `The fully qualified file name must be less than 260 characters`, the path you are using seems too long
