### ISSUE TITLE
Crash report from Dynamo 2.12.1.8246

### ISSUE THREAD

**Issue by JezDeM** [DynamoDS/Dynamo#13311]
# Issue Description
Please fill in the following information to help us reproduce the issue:

## Dynamo version
Dynamo: `2.12.1.8246`

## Operating system
OS: `Microsoft Windows NT 10.0.19044.0`

## What did you do?
(Selected Monocle, package usage, package usage doge)

## What did you expect to see?
(Documenting custom nodes)

## What did you see instead?
(Error and Dynamo crashed)

### Loaded Packages
- Clockwork for Dynamo 2.x 2.4.0
- Monocle 2022.9.1
- spring nodes 210.1.1
- GenerativeDesign 1.10.10.0
- GenerativeDesign.Extension 1.10.10.0
- GenerativeDesign.Revit 1.10.10.0

## Stack Trace
```
(Could not load file or assembly 'WpfAnimatedGif, PublicKeyToken=9e7cd3b544a090dc' or one of its dependencies. The system cannot find the file specified.

   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at MonocleViewExtension.PackageUsage.PackageUsageCommand.<>c__DisplayClass0_0.<AddMenuItem>b__0(Object sender, RoutedEventArgs args)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler))
```

---
CLR: `4.0.30319.42000`

**Comment by mjkkirschner** [comment]
Hi @JezDeM this likely belongs in https://github.com/johnpierson/MonocleForDynamo repo, we cannot transfer it there, I believe you'll need to create a new issue there.

**Comment by johnpierson** [comment]
fixed in modern versions of monocle
