### ISSUE TITLE
Crash report from Dynamo 2.15.0.5383

### ISSUE THREAD

**Issue by ottoxinauzer** [DynamoDS/Dynamo#13316]
Haven't yet tried to export using Python, that might be a workaround, but I believe this would be a good 

# Issue Description
Please fill in the following information to help us reproduce the issue:

## Dynamo version
Dynamo: `2.15.0.5383`

## Operating system
OS: `Microsoft Windows NT 10.0.22000.0`

## What did you do?
`I've been having this error when trying to export a bunch of data to excel. The export node used is the Data.ExportToExcel.`

## What did you expect to see?
`The export process should go smoothly.`

## What did you see instead?
`Dynamo crashing.`

### Loaded Packages
- Clockwork for Dynamo 2.x 2.4.0
- DynamoIronPython2.7 2.1.0
- Monocle 2022.7.1
- Orchid 212.1.0.8046
- Rhythm 2022.7.2
- spring nodes 210.1.1
- Topologic 1.4.0

## Stack Trace
```
Object reference not set to an instance of an object.

   at DSCore.File.FilenameNodeViewCustomization.readFileButton_Click(Object sender, RoutedEventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

---
CLR: `4.0.30319.42000`

**Comment by mjkkirschner** [comment]
@QilongTang perhaps this has something to do with your recent changes to the file path node?

@ottoxinauzer please share you .dyn file that reproduces this issue.

**Comment by QilongTang** [comment]
@mjkkirschner My recent changes to the file path node is not in RC2.15.0 branch, see https://github.com/DynamoDS/Dynamo/blob/RC2.15.0_master/src/Libraries/CoreNodeModelsWpf/NodeViewCustomizations/Filename.cs.

@ottoxinauzer were you trying to export to a network location or local path?

**Comment by ottoxinauzer** [comment]
Hey guys, sorry for the lateness in my reply. The problem seemed to be associated with PyRevit...I disabled it and everything works fine now...it was either that or some other coincidence... I'll keep my eye open and if the problem reappear I'll open a new issue claim.
Thanks!
