### ISSUE TITLE
Crash when removing duplicate file from package

### ISSUE THREAD

**Issue by JacobSmall** [DynamoDS/Dynamo#13325]
# Issue Description
Please fill in the following information to help us reproduce the issue:

## Dynamo version
Dynamo: `2.13.1.3887`

## Operating system
OS: `Microsoft Windows NT 10.0.19044.0`

## What did you do?
tried to remove a duplicated file from a package.

## What did you expect to see?
the file remove from the list

## What did you see instead?
hard crash, ahve ot restart revit as it was locked behind the now missing publish package window

## What packages or external references (if any) were used?
doesn't seem to matter, but below was self populated
- Ampersand 2019.12.31
- dyn2ifc 1.3.1
- Dynamo Text 2.0.1
- DynamoIronPython2.7 2.5.0
- ExcelReader 134.1.1
- Generative_Design_at_Hogwarts 0.0.3
- Monocle 2022.9.1
- Refinery Toolkit 1.1.1
- spring nodes 210.1.1
- Topologic 1.4.0
- TuneUp 1.0.7
- VASA 0.2.1
- GenerativeNeighborhoods 1.0.0
- GenerativeDesign 2.0.10.0
- GenerativeDesign.Extension 2.0.10.0
- GenerativeDesign.Revit 2.0.10.0

## Stack Trace
```
Object reference not set to an instance of an object.

   at Dynamo.PackageManager.PublishPackageViewModel.<>c__DisplayClass203_0.<RemoveItem>b__1(PackageItemRootViewModel x)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Dynamo.PackageManager.PublishPackageViewModel.RemoveItem(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

---
CLR: `4.0.30319.42000`

**Comment by QilongTang** [comment]
This should be fixed by https://github.com/DynamoDS/Dynamo/issues/13325, closing. Fix included in upcoming 2.19 release
