### ISSUE TITLE
Crash report from Dynamo 2.6.2.15705

### ISSUE THREAD

**Issue by boiiinng** [DynamoDS/Dynamo#13333]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
close program while script was active, asked me if i wanted to save, clicked yes

### What did you expect to see?
program close

### What did you see instead?
black screen and crash error popup

### What packages or external references (if any) were used?
bimorphnodes

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```
The active document may not be closed from the API.

   at Autodesk.Revit.DB.Document.Close(Boolean saveModified)
   at  .()
   at System.Action.Invoke()
   at Dynamo.Graph.Workspaces.WorkspaceModel.Dispose()
   at Dynamo.Graph.Workspaces.HomeWorkspaceModel.Dispose()
   at Dynamo.Models.DynamoModel.Dispose()
   at Dynamo.Models.DynamoModel.ShutDownCore(Boolean shutdownHost)
   at Dynamo.Applications.Models.RevitDynamoModel.ShutDownCore(Boolean shutDownHost)
   at Dynamo.Models.DynamoModel.ShutDown(Boolean shutdownHost)
   at Dynamo.ViewModels.DynamoViewModel.PerformShutdownSequence(ShutdownParams shutdownParams)
   at Dynamo.Controls.DynamoView.PerformShutdownSequenceOnViewModel()
   at Dynamo.Controls.DynamoView.WindowClosing(Object sender, CancelEventArgs e)
   at System.Windows.Window.OnClosing(CancelEventArgs e)
   at System.Windows.Window.WmClose()
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---
OS: `Microsoft Windows NT 10.0.19044.0`
CLR: `4.0.30319.42000`
Dynamo: `2.6.2.15705`

**Comment by boiiinng** [comment]
> 

Dynamo Core 2.6.2.15705
Dynamo Revit 2.6.2.15772
Windows 10 Pro build 19044.1889
