### ISSUE TITLE
Crash report from Dynamo 2.2.1.5175

### ISSUE THREAD

**Issue by Woodplcnancy** [DynamoDS/Dynamo#13339]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
open Dynamo from revit manage tab

### What did you expect to see?
Dynamo menu

### What did you see instead?
Dynamo has crashed
![Capture](https://user-images.githubusercontent.com/114378601/192195379-51af196c-3ed4-4a2a-9629-47f62f44e2b9.PNG)

### What packages or external references (if any) were used?
(Fill in here)

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
Access to the path 'C:\Users\nancy.zhao\AppData\Roaming\Analytics\CSharpAnalytics-MeasurementSession' is denied.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at CSharpAnalytics.Serializers.AppDataContractSerializer.<Save>d__7`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CSharpAnalytics.WinFormAutoMeasurement.<Save>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Analytics.NET.Google.WinNativeAutoMeasurement.<Save>d__11`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CSharpAnalytics.BaseAutoMeasurement.<Start>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegat

---
OS: `Microsoft Windows NT 10.0.19042.0`
CLR: `4.0.30319.42000`
Dynamo: `2.2.1.5175`

**Comment by Woodplcnancy** [comment]
I have Revit 2019, Revit 2020 and Revit 2021, Dynamo is not working on three of Revit visions. I couldn't open Dynamo scripts at all. Not sure how to solve this problem, even IT support doesn't know either.
Please help and let me know what to do.

**Comment by Woodplcnancy** [comment]
Hi GitHub,

Please find additional infor. Of Dynamo:
Dynamo version: Dynamo 2.2.1.5175
Operating system: Microsoft Windows 10 Enterprise 10.0.19042.0
Thanks in advance,
Regards,



Nancy Zhao
Senior Architectural Draftsperson - Life Sciences, Australia
Level 11, 171 Collins St, Melbourne, VIC 3000, Australia (reception on level 3)
Reception: +61 (3) 9944 5500
Mobile: +61 (4) 0010 3067
www.woodplc.com

***@***.***<https://www.woodplc.com/sectors/industrial-and-manufacturing/life-sciences>

**Comment by QilongTang** [comment]
@Woodplcnancy It looks like our analytics component was crashing Dynamo. Is it the case that you could not see Dynamo screen at all?

**Comment by Woodplcnancy** [comment]
Good Morning Aaron,

Thanks for reply my queries. Yes, when dynamo crashed, closed itself, not able to open scripts. In this case, how can I fix the problem?

Regards,






Nancy Zhao
Senior Architectural Draftsperson - Life Sciences, Australia
Level 11, 171 Collins St, Melbourne, VIC 3000, Australia (reception on level 3)
Reception: +61 (3) 9944 5500
Mobile: +61 (4) 0010 3067
www.woodplc.com

***@***.***<https://www.woodplc.com/sectors/industrial-and-manufacturing/life-sciences>

**Comment by QilongTang** [comment]
@Woodplcnancy You can try turning the analytics feature off not through Dynamo UI but through touching the `DynamoSettings.xml` on your computer. 

Try to look for %AppData%\Roaming\Dynamo\Dynamo Core\[Your Dynamo Version]\DynamoSettings.xml (Sandbox) or %AppData%\Roaming\Dynamo\Dynamo Revit\[Your Dynamo Version]\DynamoSettings.xml (DynamoRevit), etc depending on which flavor of Dynamo you are using.

Find this line where there is `<IsAnalyticsReportingApproved>false</IsAnalyticsReportingApproved>` and make sure it is set to false. 

Save the file and restart Revit->DynamoRevit to see if DynamoRevit launches with this change

**Comment by Woodplcnancy** [comment]
Hello Aaron,

Thanks for the email, I changed Dynamo settings as you mentioned, but dynamo still crashed, I copied the error message see below.
If I uninstall and reinstall Revit, does it help?

***@***.***


Access to the path 'C:\Users\nancy.zhao\AppData\Roaming\Analytics\CSharpAnalytics-MeasurementSession' is denied.   I have full right to access this path

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at CSharpAnalytics.Serializers.AppDataContractSerializer.<Save>d__7`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CSharpAnalytics.WinFormAutoMeasurement.<Save>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Analytics.NET.Google.WinNativeAutoMeasurement.<Save>d__11`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CSharpAnalytics.BaseAutoMeasurement.<Start>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)






Nancy Zhao
Senior Architectural Draftsperson - Life Sciences, Australia
Level 11, 171 Collins St, Melbourne, VIC 3000, Australia (reception on level 3)
Reception: +61 (3) 9944 5500
Mobile: +61 (4) 0010 3067
www.woodplc.com

***@***.***<https://www.woodplc.com/sectors/industrial-and-manufacturing/life-sciences>

**Comment by Woodplcnancy** [comment]
Hello Aaron,

I want let you know a good news - I can open Dynamo in Revit 2021 now (Dynamo vision 2.6), but not in Revit 2020 (Dynamo vision 2.2)

Thanks a lot for your help.





Nancy Zhao
Senior Architectural Draftsperson - Life Sciences, Australia
Level 11, 171 Collins St, Melbourne, VIC 3000, Australia (reception on level 3)
Reception: +61 (3) 9944 5500
Mobile: +61 (4) 0010 3067
www.woodplc.com

***@***.***<https://www.woodplc.com/sectors/industrial-and-manufacturing/life-sciences>

**Comment by QilongTang** [comment]
If you still see access error around `C:\Users\nancy.zhao\AppData\Roaming\Analytics\CSharpAnalytics-MeasurementSession`, try to delete this file using your admin rights the open Dynamo again or launch Revit using admin right.

**Comment by Woodplcnancy** [comment]
Good Morning Aaron,

You are legend, I deleted “C:\Users\nancy.zhao\AppData\Roaming\Analytics\CSharpAnalytics-MeasurementSession” as you said, then Revit 2020 Dynamo works!!!

Thanks so much for your help,

Cheers






Nancy Zhao
Senior Architectural Draftsperson - Life Sciences, Australia
Level 11, 171 Collins St, Melbourne, VIC 3000, Australia (reception on level 3)
Reception: +61 (3) 9944 5500
Mobile: +61 (4) 0010 3067
www.woodplc.com

***@***.***<https://www.woodplc.com/sectors/industrial-and-manufacturing/life-sciences>
