### ISSUE TITLE
Crash report from Dynamo 2.12.1.8246

### ISSUE THREAD

**Issue by zawmin76** [DynamoDS/Dynamo#13502]
# Issue Description
Please fill in the following information to help us reproduce the issue:

## Dynamo version
Dynamo: `2.12.1.8246`

## Operating system
OS: `Microsoft Windows NT 10.0.19044.0`

## What did you do?
(Fill in here)

## What did you expect to see?
(Fill in here)

## What did you see instead?
(Fill in here)

## Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
Object reference not set to an instance of an object.

   at ProtoCore.Utils.ArrayUtils.GetMaxRankForArray(StackValue array, RuntimeCore runtimeCore, Int32 tracer)
   at ProtoCore.FunctionEndPoint.DoesTypeDeepMatch(List`1 formalParameters, RuntimeCore runtimeCore)
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at ProtoCore.FunctionGroup.GetExactTypeMatches(Context context, List`1 formalParams, List`1 replicationInstructions, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.CallSite.GetCompleteMatchFunctionEndPoint(Context context, List`1 arguments, FunctionGroup funcGroup, List`1 replicationInstructions, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.CallSite.ComputeFeps(Context context, List`1 arguments, FunctionGroup funcGroup, List`1 instructions, StackFrame stackFrame, RuntimeCore runtimeCore, List`1& resolvedFeps, List`1& replicationInstructions)
   at ProtoCore.CallSite.DispatchNew(Context context, List`1 arguments, List`1 partialReplicationGuides, DominantListStructure domintListStructure, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.DSASM.Executive.Callr(Int32 blockDeclId, Int32 functionIndex, Int32 classIndex, Boolean& explicitCall, Boolean isDynamicCall, Boolean hasDebugInfo)
   at ProtoCore.DSASM.Executive.CALLR_Handler(Instruction instruction)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
   at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   at ProtoScript.Runners.LiveRunner.ApplyUpdate()
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()
```

---
CLR: `4.0.30319.42000`

**Comment by zawmin76** [comment]
# Load the Python Standard and DesignScript Libraries
import sys
import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Enable Python support and load DesignScript library

# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *
#from Autodesk.Revit.DB.Structure import *

# Import RevitAPIUI
clr.AddReference("RevitAPIUI")
from Autodesk.Revit.UI import *

# Import System
clr.AddReference('System')
from System.Collections.Generic import List

# Import DocumentManager and TransactionManager
clr.AddReference('RevitServices')
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument
uidoc = DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument

#Function

def flatten(x):
	result = []
	for ed in x:
		if hasattr(ed, "__iter__") and not isinstance(ed, basestring):
			result.extend(flatten(ed))
		else:
			result.append(ed)
	return result

def tolist(obj1):
	if hasattr(obj1,'__iter__'): return obj1
	return [obj1]

# The inputs to this node will be stored as a list in the IN variables.
sharedparameter = FilteredElementCollector(doc).OfClass(SharedParameterElement).WhereElementIsNotElementType().ToElements()


shParaName = []
parameterGroup = []
parameterType = []
cat = []
pn = []
toremove = []
nametoRemove = []

for s in sharedparameter:
	shParaName.append((s.Name))
	parameterGroup.append(s.GetDefinition().ParameterGroup.ToString())
	parameterType.append(s.GetDefinition().ParameterType.ToString())


OUT =  shParaName, parameterGroup, parameterType

**Comment by zawmin76** [comment]
I updated BIMInteropTools_9_0_8326_2022.exe yesterday for Revit 2022.

**Comment by zawmin76** [comment]
![image](https://user-images.githubusercontent.com/63436325/201264113-eff70fd8-c77f-48b0-a1a0-d47fbc5352ef.png)
