### ISSUE TITLE
Crash report from Dynamo 2.10.1.3976

### ISSUE THREAD

**Issue by adriencraye** [DynamoDS/Dynamo#13667]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
Crash when running the script.
The "Topography.ToPolySurface node does not return anything although the topography has been simplified (~1400points)

### What did you expect to see?
A polycurve should have been projected to the topography converted to surface.

### What did you see instead?
Topography not converted.

### What packages or external references (if any) were used?
Springnodes

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
OS: `Microsoft Windows NT 10.0.19044.0`
CLR: `4.0.30319.42000`
Dynamo: `2.10.1.3976`

**Comment by adriencraye** [comment]
> Hello adriencraye, thank you for submitting this issue! We are super excited that you want to help us make Dynamo all that it can be. However, we need some more information in order for the Dynamo team to investigate any further.
> 
> Can you please fill in the following to the best of your ability:
> 
> * Dynamo version: 
Core 2.10.3976 / Revit 2.10.1.4002
> * Operating system: 
Windows 10 Enterprise 64bits
> 
> Additional information:
> 
> * Filling in of the provided Template (What did you do, What did you expect to see, What did you see instead, What packages or external references (if any) were used)
> * Attaching the Stack Trace (Error message that shows up when Dynamo crashes - You can copy and paste this into the Github Issue):

Index was outside the bounds of the array.

   at ProtoCore.DSASM.Executive.GetProcedureNode(Int32 blockId, Int32 classIndex, Int32 functionIndex)
   at ProtoCore.DSASM.Executive.UpdateMethodDependencyGraph(Int32 entry, Int32 procIndex, Int32 classIndex)
   at ProtoCore.DSASM.Executive.SetupExecutive(Int32 exeblock, Int32 entry)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
   at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   at ProtoScript.Runners.LiveRunner.ApplyUpdate()
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()

> * Upload a .DYN file that showcases the issue in action and any additional needed files, such as Revit (Note: If you cannot share a project, you can recreate this in a quick mock-up file)
> * Upload a Screenshot of the error messages you see (Hover over the offending node and showcase said errors message in the screenshot)
> * Reproducible steps on how to create the error in question.

**Comment by adriencraye** [comment]
Issue solved by using subregion for the topo.
The topography was too heavy.

**Comment by adriencraye** [comment]
Issue solved by using subregion for the topo.
The topography was too heavy.

**Comment by adriencraye** [comment]
Issue solved by using subregion for the topo.
The topography was too heavy.
