### ISSUE TITLE
Crash report from Dynamo 2.6.2.15705

### ISSUE THREAD

**Issue by Ikthala** [DynamoDS/Dynamo#13679]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
I finished my script, saved the file, and tried to open the Generative Design Tools. Dynamo crashes every time after clicking it.

### What did you expect to see?
I was expecting the options to open so I can export my generative design script.

### What did you see instead?
An error window pops up saying Dynamo is crashing.

### What packages or external references (if any) were used?
Generative Design

### Stack Trace
```
Set property 'System.Windows.ResourceDictionary.Source' threw an exception.

   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at GenerativeDesign.Dynamo.UI.Views.GenerativeDesignMainView..ctor(GenerativeDesignMainViewModel viewModel)
   at GenerativeDesign.Dynamo.ViewExtension.GenerativeDesignViewExtension.OpenSidePanel()
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

---
OS: `Microsoft Windows NT 10.0.22621.0`
CLR: `4.0.30319.42000`
Dynamo: `2.6.2.15705`

**Comment by Ikthala** [comment]
Dynamo Version: 2.6.2.15705
OS: Windows 11 Pro 22H2

Here are the files I was working on when the crash happened:
[Generative Window Placement - 1-13-23.zip](https://github.com/DynamoDS/Dynamo/files/10415999/Generative.Window.Placement.-.1-13-23.zip)
