### ISSUE TITLE
Crash report from Dynamo 2.18.0.4384

### ISSUE THREAD

**Issue by aliasguru** [DynamoDS/Dynamo#13826]
# Issue Description
Freshly checked out sources and compiled in Visual Studio 17.5.0. Compilation runs fine without errors. Running Dynamo Sandbox, new file, and tried adding any of the Units nodes to the node tree. BANG. This is a recent thing, I was using self-compiled Dynamo with units already before, can't tell what broke it.

## Dynamo version
Dynamo: `2.18.0.4384`

## Operating system
OS: `Microsoft Windows NT 6.2.9200.0`

## What did you do?
see issue description

## What did you expect to see?
no crash I guess

## What did you see instead?
submit bug to GitHub button

## What packages or external references (if any) were used?
No loaded packages were found.

## Stack Trace
```
The type initializer for 'DynamoUnits.Utilities' threw an exception.

   at DynamoUnits.Utilities.get_SchemaDirectory()
   at UnitsUI.Units.PopulateItemsCore(String currentSelection) in C:\DATEN\git-repos\Dynamo\src\Libraries\UnitsUI\UnitsUI.cs:line 651
   at CoreNodeModels.DSDropDownBase.PopulateItems() in C:\DATEN\git-repos\Dynamo\src\Libraries\CoreNodeModels\DropDown.cs:line 302
   at CoreNodeModels.DSDropDownBase..ctor(String outputName) in C:\DATEN\git-repos\Dynamo\src\Libraries\CoreNodeModels\DropDown.cs:line 153
   at lambda_method(Closure )
   at Dynamo.Wpf.ViewModels.NodeSearchElementViewModel.OnClicked() in C:\DATEN\git-repos\Dynamo\src\DynamoCoreWpf\ViewModels\Search\NodeSearchElementViewModel.cs:line 366
   at Dynamo.UI.Controls.InCanvasSearchControl.ExecuteSearchElement(ListBoxItem listBoxItem) in C:\DATEN\git-repos\Dynamo\src\DynamoCoreWpf\Controls\InCanvasSearchControl.xaml.cs:line 72
   at Dynamo.UI.Controls.InCanvasSearchControl.OnInCanvasSearchKeyDown(Object sender, KeyEventArgs e) in C:\DATEN\git-repos\Dynamo\src\DynamoCoreWpf\Controls\InCanvasSearchControl.xaml.cs:line 192
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at System.Windows.Threading.Dispatcher.Invoke(DispatcherPriority priority, Delegate method, Object arg)
   at System.Windows.Interop.HwndSource.OnPreprocessMessageThunk(MSG& msg, Boolean& handled)
   at System.Windows.Interop.ThreadMessageEventHandler.Invoke(MSG& msg, Boolean& handled)
   at System.Windows.Interop.ComponentDispatcherThread.RaiseThreadMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at DynamoSandbox.DynamoCoreSetup.RunApplication(Application app) in C:\DATEN\git-repos\Dynamo\src\DynamoSandbox\DynamoCoreSetup.cs:line 73

-------- InnerException --------

Could not load file or assembly 'ForgeUnitsCLR.dll' or one of its dependencies. Das angegebene Modul wurde nicht gefunden.

   at DynamoUnits.Utilities.Initialize()
   at DynamoUnits.Utilities..cctor() in C:\DATEN\git-repos\Dynamo\src\Libraries\DynamoUnits\Utilities.cs:line 32
```

---
CLR: `4.0.30319.42000`

**Comment by aliasguru** [comment]
The dll that the stack trace speaks about IS being compiled just fine.
A downloaded Dynamo works fine on the same system. It must be something on my side, but I have no clue where to look for

**Comment by QilongTang** [comment]
@saintentropy Sounds like you would know?

**Comment by aliasguru** [comment]
OK, I resolved it for now by doing this:

- check out `RC 16.1` tag, rebuild  -->  no crashes when adding units
- check out `RC 17.0` tag, rebuild  -->  no crashes when adding units
- check out `RC 17.1` tag, rebuild  -->  no crashes when adding units
- check out `master` branch, rebuild  -->  no crashes when adding units

No clue what fixed it in the end, but this ticket can be closed for now.
