### ISSUE TITLE
Crash report from Dynamo 2.3.2.15696

### ISSUE THREAD

**Issue by smhtpc** [DynamoDS/Dynamo#13838]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
Accidently again and again I click the wire and some box appears, I use redo and than I removed wire to archilab's connector, It's giving error. 

### What did you expect to see?
Remove connectors

### What did you see instead?
archilab's connectors ( I don't want to this

### What packages or external references (if any) were used?
archilab

### Stack Trace
```
Object reference not set to an instance of an object.

   at Dynamo.ViewModels.ConnectorViewModel.Dispose()
   at Dynamo.ViewModels.WorkspaceViewModel.Connectors_ConnectorDeleted(ConnectorModel c)
   at Dynamo.Graph.Workspaces.WorkspaceModel.OnConnectorDeleted(ConnectorModel obj)
   at System.Action.Invoke()
   at Dynamo.Graph.Connectors.ConnectorModel.OnDeleted()
   at Dynamo.Models.DynamoModel.GetConnectorsToAddAndDelete(PortModel endPort, PortModel startPort)
   at Dynamo.Models.DynamoModel.EndConnection(Guid nodeId, Int32 portIndex, PortType portType)
   at Dynamo.Models.DynamoModel.MakeConnectionImpl(MakeConnectionCommand command)
   at Dynamo.Models.DynamoModel.ExecuteCommand(RecordableCommand command)
   at Dynamo.ViewModels.WorkspaceViewModel.StateMachine.HandlePortClicked(PortViewModel portViewModel)
   at Dynamo.ViewModels.PortViewModel.Connect(Object parameter)
   at System.Windows.Interactivity.InvokeCommandAction.Invoke(Object parameter)
   at System.Windows.Interactivity.TriggerBase.InvokeActions(Object parameter)
   at Dynamo.UI.Views.HandlingEventTrigger.OnEvent(EventArgs eventArgs)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

---
OS: `Microsoft Windows NT 10.0.22621.0`
CLR: `4.0.30319.42000`
Dynamo: `2.3.2.15696`

**Comment by QilongTang** [comment]
Hi There have been a bunch of crash-related fixes in the ConnectorViewModel files Dispose() function for the last couple of years so I believe most likely this has been fixed in newer versions of Dynamo. e.g. https://github.com/DynamoDS/Dynamo/pull/12533

Unfortunately, you may still see this in v2.3.2, if allowed, I would recommend you try this on a newer Dynamo instance
