### ISSUE TITLE
Crash report from Dynamo 2.10.1.3976

### ISSUE THREAD

**Issue by Alashhar** [DynamoDS/Dynamo#14053]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
I am working on script for converting point cloud to mesh and had some Nan values. so I used "List.RemoveItemAtIndex" and the dynamo ran smoothly at the beginning then crashed.

### What did you expect to see?
See a clean list with no "NaN" values.

### What did you see instead?
Nothing, just Dynamo crashed.

### What packages or external references (if any) were used?
I used Python Script node, File Path, List.RemoveItem AtIndex....

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```
Runtime exception occured. The Type of StackValue is not Integer

   at ProtoCore.DSASM.StackValue.get_IntegerValue()
   at ProtoCore.DSASM.Executive.GetCurrentScope(Int32& classIndex, Int32& functionIndex)
   at ProtoCore.DSASM.Executive.DEP_Handler(Instruction instruction)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
   at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   at ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()
---
OS: `Microsoft Windows NT 10.0.19044.0`
CLR: `4.0.30319.42000`
Dynamo: `2.10.1.3976`

**Comment by mjkkirschner** [comment]
Hi @Alashhar we will need the files you are using so we can reproduce.

**Comment by mjkkirschner** [comment]
Hi @Alashhar you can change the file extension to .txt - or make a zip archive. We need all files necessary to reproduce, for example the .rvt if you are working in Revit as well.
