### ISSUE TITLE
Crash report from Dynamo 2.6.1.8786

### ISSUE THREAD

**Issue by djdarkstream** [DynamoDS/Dynamo#14182]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
Scroll in a big Watch window

### What did you expect to see?
No crash as Dynamo was all done with running my script and I was just reviewing the results

### What did you see instead?
When the window wanted to resize because all the lists in the window were empty, dynamo crashed, this happens to me all the time when scrolling in Watch windows that are extensive (L5 nested list with a few thousand lines, line start/endpoints & vector and a few thousand more lists that are empty)

### What packages or external references (if any) were used?
Data-Shapes v.2021.2.94
Clockwork v.2.4.0
GeniusLoci v.2021.11.10

Dynamo Core: 2.6.1.8786
Dynamo Revit: 2.6.1.8850

### Stack Trace
```
Value cannot be null.
Parameter name: element

   at MS.Internal.Media.VisualTreeUtils.AsNonNullVisual(DependencyObject element, Visual& visual, Visual3D& visual3D)
   at System.Windows.Media.VisualTreeHelper.GetParent(DependencyObject reference)
   at System.Windows.Controls.VirtualizingStackPanel.FindScrollOffset(Visual v)
   at System.Windows.Controls.VirtualizingStackPanel.OnAnchorOperation(Boolean isAnchorOperationPending)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

---
OS: `Microsoft Windows NT 10.0.19045.0`
CLR: `4.0.30319.42000`
Dynamo: `2.6.1.8786`

**Comment by mjkkirschner** [comment]
Hi @djdarkstream two things
1. can you try to repro this in a more recent daily build?
2. can you provide a sample graph that does not require revit that reproduces the issue for us?

**Comment by djdarkstream** [comment]
Hi there, sorry for the very late reply. I am unable to try this with a more recent build nor can I provide a sample graph that doesn't use Revit. Seeing as this is work-related for me and not very consequential for my production I cannot spend any time on that. 

I hope this issues will get spotted by someone that does have the time for this. You may close this issue I guess
