### ISSUE TITLE
Crash report from Dynamo 2.18.1.5096 - Copying code block

### ISSUE THREAD

**Issue by ParametricMonkey** [DynamoDS/Dynamo#14259]
# Issue Description
Please fill in the following information to help us reproduce the issue:

## Dynamo version
Dynamo: `2.18.1.5096`

## Operating system
Windows 11

## What did you do?
Copy and pasted a code block

## What did you expect to see?
A duplicated code block

## What did you see instead?
Dynamo crash error

## What packages or external references (if any) were used?
None

## Stack Trace
```
Runtime exception occured. The type of StackValue is not FunctionIndex

   at ProtoCore.DSASM.StackValue.get_FunctionIndex()
   at ProtoCore.DSASM.Executive.GetCurrentScope(Int32& classIndex, Int32& functionIndex)
   at ProtoCore.DSASM.Executive.DEP_Handler(Instruction instruction)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
   at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   at ProtoScript.Runners.LiveRunner.ApplyUpdate()
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()
```

---
CLR: `4.0.30319.42000`

**Comment by avidit** [comment]
Tracked internally [DYN-6164](https://jira.autodesk.com/browse/DYN-6164)

**Comment by pinzart90** [comment]
@ParametricMonkey if you still have them around, please attach the graph (.dyn) and any files or steps that could help reproduce the issue.
