### ISSUE TITLE
Crash report from Dynamo 2.15.1.6076

### ISSUE THREAD

**Issue by jfmarquitectura** [DynamoDS/Dynamo#14494]
# Issue Description
Dynamo node "OBJECT.GEOMETRY" doesnt work into Civil3d when I try to read de geometry of a solid element.

## Dynamo version
Dynamo: `2.15.1.6076`

## Operating system
OS: `Microsoft Windows NT 10.0.19045.0`

## What did you do?
I try to red a solid geometry with the node "object.geometry" but doesn't works

## What did you expect to see?
a solid geometry into dynamo model space

## What did you see instead?
nothing . Null

## What packages or external references (if any) were used?
No Package

## Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```
Runtime exception occured. The Type of StackValue is not Integer

   at ProtoCore.DSASM.StackValue.get_IntegerValue()
   at ProtoCore.DSASM.Executive.GetCurrentScope(Int32& classIndex, Int32& functionIndex)
   at ProtoCore.DSASM.Executive.DEP_Handler(Instruction instruction)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
   at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   at ProtoScript.Runners.LiveRunner.ApplyUpdate()
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()
---
CLR: `4.0.30319.42000`

**Comment by mjkkirschner** [comment]
@jfmarquitectura can you provide sample files to reproduce this issue?

**Comment by jfmarquitectura** [comment]
Hello, I solved the problem by emptying the **%TEMP%** windows folder.
