### ISSUE TITLE
Crash report from Dynamo 2.13.1.3887

### ISSUE THREAD

**Issue by sujung60** [DynamoDS/Dynamo#14504]
# Issue Description
Please fill in the following information to help us reproduce the issue:

## Dynamo version
Dynamo: `2.13.1.3887`

## Operating system
OS: `Microsoft Windows NT 10.0.22621.0`

## What did you do?
(Fill in here)

## What did you expect to see?
(Fill in here)

## What did you see instead?
(Fill in here)

### Loaded Packages
- archi-lab.net 2024.217.1024
- BriMohareb_2023 6.0.0
- Crumple 2022.5.27
- Refinery Toolkit 1.1.1
- SpaceAnalysis 0.5.0
- spring nodes 210.1.1
- GenerativeDesign 2.0.10.0
- GenerativeDesign.Extension 2.0.10.0
- GenerativeDesign.Revit 2.0.10.0

## Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```
Object reference not set to an instance of an object.

   at GenerativeDesign.Dynamo.Visualization.ViewModels.ExampleConnectorViewModel..ctor(ConnectorViewModel connectorViewModel, DynamoViewModel dynamoViewModel, NodeStatus status)
   at GenerativeDesign.Dynamo.Visualization.ViewModels.BaseVisualizationViewModel.OnConnectorAdded(ConnectorModel obj)
   at GenerativeDesign.Dynamo.Visualization.ViewModels.BaseVisualizationViewModel.InitializeGraphVisualization()
   at GenerativeDesign.Dynamo.ViewExtension.GenerativeDesignViewExtension.LoadGraphModelVisualization(DynamoGraphModel graphModel)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---
CLR: `4.0.30319.42000`

**Comment by mjkkirschner** [comment]
@twastvedt @BogdanZavu fyi
