### ISSUE TITLE
Failed to load language IronPython 2.7.9

### ISSUE THREAD

**Issue by jmosh6** [DynamoDS/Dynamo#14509]
## Dynamo version
Dynamo Core 2.6.2.15705
Dynamo Revit 2.6.2.15772

## Operating system
Windows 10

## What did you do? 
Opened Dynamo player and ran a script. The script did not run. When opened in dynamo, there was an error with a python node. The error was as follows:

Warning: IronPythonEvaluator.EvaluateIronPythonScript operation failed. Failed to load language IronPython 2.7.9': Object reference not set to an instance of an object.

This is happening on all the scripts on this particular computer. I am responsible for the automation in our VDC department. I have been starting to see this error pop up on a few different computers.

## What did you expect to see?

I expected the script to be able to run.

## What did you see instead?

I saw the error:

Warning: IronPythonEvaluator.EvaluateIronPythonScript operation failed. Failed to load language IronPython 2.7.9': Object reference not set to an instance of an object.

**Comment by avidit** [comment]
@jmosh6 Can you please provide the list of packages installed?

**Comment by jmosh6** [comment]
@avidit  Yes, attached below you will see an image of the packages installed. Thanks!

![32b91067-15d3-4efa-b2f6-c23ff602c34a](https://github.com/DynamoDS/Dynamo/assets/142407607/6cd918d3-9144-4246-8720-eb1c6a5ea54b)

**Comment by jmosh6** [comment]
I had it happen again. Here is the error report for reference.
Failed to load language 'IronPython 2.7.9': Object reference not set to an instance of an object.

   at Microsoft.Scripting.Runtime.LanguageConfiguration.LoadLanguageContext(ScriptDomainManager domainManager, Boolean& alreadyLoaded)
   at Microsoft.Scripting.Runtime.DlrConfiguration.LoadLanguageContext(ScriptDomainManager manager, LanguageConfiguration config)
   at Microsoft.Scripting.Runtime.DlrConfiguration.TryLoadLanguage(ScriptDomainManager manager, AssemblyQualifiedTypeName providerName, LanguageContext& language)
   at Microsoft.Scripting.Runtime.ScriptDomainManager.GetLanguageByTypeName(String providerAssemblyQualifiedTypeName)
   at Microsoft.Scripting.Hosting.ScriptRuntime.GetEngineByTypeName(String assemblyQualifiedTypeName)
   at Dynamo.Python.IronPythonCompletionProvider..ctor(String dynamoCoreDir)
   at PythonNodeModelsWpf.ScriptEditorWindow..ctor(DynamoViewModel dynamoViewModel, PythonNode nodeModel, NodeView nodeView, WindowRect& windowRect)
   at PythonNodeModelsWpf.PythonNodeViewCustomization.EditScriptContent()
   at PythonNodeModelsWpf.PythonNodeViewCustomization.view_MouseDown(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
