### ISSUE TITLE
Crash report from Dynamo 2.13.1.3887

### ISSUE THREAD

**Issue by ececorlu** [DynamoDS/Dynamo#14623]
# Issue Description
I was trying to get first point group from a list to create polylines. Then the dynamo crashed. Because there are many points and I get the data type I want to get can't pulled out writing a code block like this  ` data[0]:`

## Dynamo version
Dynamo: `2.13.1.3887`

## Operating system
OS: `Microsoft Windows NT 10.0.22631.0`

## What did you do?
The list is created from json file which includes  points group of buildings footprints. I wanted to get coordinates out of list like this in a code block   `get_data_values[x]["geometry"]["coordinates"];` to get building footprints points and then 2009 elements was created. Then, I wanted to create polylines from coordinates points but it crashed. that is why I wanted to get first points group so that I could create one buildings footprint but it is crashed.

## What did you expect to see?
get first buildings footprint

## What did you see instead?
it has crashed 

## What packages or external references (if any) were used?
none but the json file was [this.]([zonalstatistics_azbaşlıklıgeojson.json]

## Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Runtime exception occured. The Type of StackValue is not Integer

   at ProtoCore.DSASM.StackValue.get_IntegerValue()
   at ProtoCore.DSASM.Executive.GetCurrentScope(Int32& classIndex, Int32& functionIndex)
   at ProtoCore.DSASM.Executive.DEP_Handler(Instruction instruction)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
   at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   at ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute())
```

---
CLR: `4.0.30319.42000`

**Comment by avidit** [comment]
Hi @ececorlu, is it possible for you to upload a screenshot and/or the sample dyn and json files?

**Comment by ececorlu** [comment]
Hi, Aabishkar,
I guess I have solved my problem.  I have changed how I write the code. Thank you for your return.
