### ISSUE TITLE
Crash report from Dynamo 2.19.3.6394

### ISSUE THREAD

**Issue by L-Vaselaar** [DynamoDS/Dynamo#14865]
# Issue Description
Please fill in the following information to help us reproduce the issue:

## Dynamo version
Dynamo: `2.19.3.6394`

## Operating system
OS: `Microsoft Windows NT 10.0.19045.0`

## What did you do?
tried to run a script with nodes from the crumple package
## What did you expect to see?
nodes return Family Types, Names, and Parameters

## What did you see instead?
Bug Error came up and nodes return a null value 

## What packages or external references (if any) were used?
Crumple

## Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```
 at ProtoFFI.CLRObjectMarshaler.CreateCLRObject(StackValue dsObject, Type type)
   at ProtoFFI.CLRObjectMarshaler.UnMarshal(StackValue dsObject, Context context, Interpreter dsi, Type expectedCLRType)
   at ProtoFFI.DisposeFunctionPointer.Execute(Context c, Interpreter dsi, List`1 s)
   at ProtoCore.Lang.FFIFunctionEndPoint.Execute(Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.CallSite.DispatchDispose(StackValue stackValue, RuntimeCore runtimeCore)
   at ProtoCore.DSASM.Executive.CallDispose(ProcedureNode fNode, StackValue svThisPtr, Int32 classIndex)
   at ProtoCore.DSASM.Heap.GCDisposeObject(StackValue svPtr, Executive exe)
   at ProtoCore.DSASM.Heap.Sweep()
   at ProtoCore.DSASM.Heap.SingleStep(Boolean forceGC)
   at ProtoCore.DSASM.Heap.FullGC(IEnumerable`1 gcroots, Executive exe)
   at ProtoScript.Runners.LiveRunner.ApplyUpdate()
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()
---
CLR: `4.0.30319.42000`

**Comment by avidit** [comment]
@L-Vaselaar Do you see similar error when not using the crumple package?
