### ISSUE TITLE
Crash report from Dynamo 2.6.2.15705

### ISSUE THREAD

**Issue by aginella95** [DynamoDS/Dynamo#14945]
# Issue Description
Dynamo crush

### What did you do?
Tried to change dynamo visualization and suddenly dynamo crushed.
Now every time I open it, crush appears.

### Stack Trace
```
HRESULT: [0x8876086A], Module: [SharpDX.Direct3D9], ApiCode: [D3DERR_NOTAVAILABLE/NotAvailable], Message: Unknown

   at SharpDX.Result.CheckError()
   at SharpDX.Direct3D9.Direct3DEx.CreateDeviceEx(Int32 adapter, DeviceType deviceType, IntPtr hFocusWindow, Int32 behaviorFlags, PresentParameters[] presentationParametersRef, DisplayModeEx[] fullscreenDisplayModeRef, DeviceEx returnedDeviceInterfaceOut)
   at HelixToolkit.Wpf.SharpDX.DX11ImageSource.StartD3D()
   at HelixToolkit.Wpf.SharpDX.DX11ImageSource..ctor()
   at HelixToolkit.Wpf.SharpDX.DPFCanvas.StartD3D()
   at HelixToolkit.Wpf.SharpDX.DPFCanvas.RenderTechniquesManagerPropertyChanged()
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at HelixToolkit.Wpf.SharpDX.Viewport3DX.RenderTechniquesManagerPropertyChanged()
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   at System.Windows.Data.BindingExpressionBase.Invalidate(Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.Activate(Object item)
   at System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)
   at System.Windows.Data.BindingExpression.MS.Internal.Data.IDataBindEngineClient.AttachToContext(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Task.Run(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Run(Object arg)
   at System.Windows.ContextLayoutManager.fireLayoutUpdateEvent()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

---
OS: `Microsoft Windows NT 10.0.19044.0`
CLR: `4.0.30319.42000`
Dynamo: `2.6.2.15705`

**Comment by aginella95** [comment]
Dynamo version: 2.6.2.15705
Operatin system: Windows 10
What did you expect to see? Dynamo opening as usual
What did you see instead? Dynamo crushing.



![Dynamo crush image](https://github.com/DynamoDS/Dynamo/assets/160175603/0ef2e6e3-05ca-4d25-8db0-e2aaa453820f)
[Dynamo crush info.txt](https://github.com/DynamoDS/Dynamo/files/14301899/Dynamo.crush.info.txt)

**Comment by avidit** [comment]
tracked internally [DYN-6723](https://jira.autodesk.com/browse/DYN-6723)

**Comment by avidit** [comment]
@avidit Do you have the latest DirectX installed that is available for your system?
https://github.com/DynamoDS/Dynamo/wiki/How-to-Utilize-Dynamo-Builds#installing-directx
