### ISSUE TITLE
Crash report from Dynamo 3.0.3.7597

### ISSUE THREAD

**Issue by Gerbz89** [DynamoDS/Dynamo#15240]
### Dynamo Version

3.0.3.7597

### Operating System

Microsoft Windows NT 10.0.19045.0

### What did you do?

Ran a script

### What did you expect to see?

For the script to work.

### What did you see instead?

Bug error message

### What packages or external references (if any) were used?

Rhythm and Orchid

### Details

CLR: 8.0.5

**Comment by avidit** [comment]
@Gerbz89 Could you provide the error message content or screenshot? Can you also uninstall the 
 external packages and try to run the graph?

**Comment by Gerbz89** [comment]
If I uninstall the packages and then run the script, it won't run and defeats the purpose of the script. It also happens on all versions of Revit/Dynamo, not exclusive to one version.

Here is the error message content and screenshot:

The referenced object is not valid, possibly because it has been deleted from the database, or its creation was undone.

   at Autodesk.Revit.Proxy.DB.DocumentProxy.getValidObject()
   at Autodesk.Revit.DB.Document.GetHashCode()
   at System.Collections.Generic.Dictionary`2.Remove(TKey key)
   at ProtoFFI.CLRObjectMarshaler.OnDispose(StackValue dsObject, Context context, Interpreter dsi)
   at ProtoFFI.DisposeFunctionPointer.Execute(Context c, Interpreter dsi, List`1 s)
   at ProtoCore.Lang.FFIFunctionEndPoint.Execute(Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.CallSite.DispatchDispose(StackValue stackValue, RuntimeCore runtimeCore)
   at ProtoCore.DSASM.Executive.CallDispose(ProcedureNode fNode, StackValue svThisPtr, Int32 classIndex)
   at ProtoCore.DSASM.Heap.GCDisposeObject(StackValue svPtr, Executive exe)
   at ProtoCore.DSASM.Heap.Sweep()
   at ProtoCore.DSASM.Heap.SingleStep(Boolean forceGC)
   at ProtoCore.DSASM.Heap.FullGC(IEnumerable`1 gcroots, Executive exe)
   at ProtoScript.Runners.LiveRunner.ForceGC()
   at ProtoScript.Runners.LiveRunner.ApplyUpdate()
   at ProtoScript.Runners.LiveRunner.PostExecution()
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Engine.LiveRunnerServices.UpdateGraph(GraphSyncData graphData, Boolean verboseLogging)
   at Dynamo.Engine.EngineController.UpdateGraphImmediate(GraphSyncData graphSyncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()
   
   
![image](https://github.com/DynamoDS/Dynamo/assets/152930496/9a3a32f7-4fe9-44af-9be1-bed57066b91b)

**Comment by jnealb** [comment]
Can you please provide us with your script and Revit model?
