### ISSUE TITLE
Crash report from Dynamo 2.15.2.6417

### ISSUE THREAD

**Issue by MohamedMabr0uk** [DynamoDS/Dynamo#15252]
# Issue Description
Please fill in the following information to help us reproduce the issue:

## Dynamo version
Dynamo: `2.15.2.6417`

## Operating system
OS: `Microsoft Windows NT 10.0.19045.0`

## What did you do?
(Method not found: 'System.String PythonNodeModels.PythonNodeBase.get_EngineName()'.

   at Dynamo.PythonMigration.GraphPythonDependencies.IsIronPythonNode(NodeModel obj)
   at Dynamo.PythonMigration.PythonMigrationViewExtension.OnNodeAdded(NodeModel obj)
   at System.Action`1.Invoke(T obj)
   at Dynamo.Graph.Workspaces.WorkspaceModel.OnNodeAdded(NodeModel node)
   at Dynamo.Graph.Workspaces.WorkspaceModel.AddNode(NodeModel node)
   at Dynamo.Graph.Workspaces.WorkspaceModel.AddAndRegisterNode(NodeModel node, Boolean centered)
   at Dynamo.Models.DynamoModel.CreateNodeImpl(CreateNodeCommand command)
   at Dynamo.Models.DynamoModel.ExecuteCommand(RecordableCommand command)
   at Dynamo.ViewModels.WorkspaceViewModel.StateMachine.CreateCodeBlockNode(Point cursor)
   at Dynamo.ViewModels.WorkspaceViewModel.StateMachine.HandleLeftButtonDown(Object sender, MouseButtonEventArgs e)
   at Dynamo.Views.WorkspaceView.OnMouseLeftButtonDown(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler))

## What did you expect to see?
(Fill in here)

## What did you see instead?
(Fill in here)

### Loaded Packages
- archi-lab.net 2024.217.1024

## Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
CLR: `4.0.30319.42000`

**Comment by avidit** [comment]
@MohamedMabr0uk Can you provide more details as steps to reproduce or screenshots or gifs?
