### ISSUE TITLE
Crash report from Dynamo 2.5.0.7460

### ISSUE THREAD

**Issue by MohamedOsama211** [DynamoDS/Dynamo#15253]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
(Fill in here)

### What did you expect to see?
(Fill in here)

### What did you see instead?
(Fill in here)

### What packages or external references (if any) were used?
(Fill in here)

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.


   at SharpDX.Result.CheckError()
   at SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   at HelixToolkit.Wpf.SharpDX.DPFCanvas.CreateAndBindTargets()
   at HelixToolkit.Wpf.SharpDX.DPFCanvas.<OnRenderSizeChanged>b__77_0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

---
OS: `Microsoft Windows NT 10.0.19045.0`
CLR: `4.0.30319.42000`
Dynamo: `2.5.0.7460`

**Comment by avidit** [comment]
@MohamedOsama211 Is it possible for you to upgrade Dynamo to 2.7 or higher?
