### ISSUE TITLE
Crash report from Dynamo 2.16.2.5624

### ISSUE THREAD

**Issue by MoosiestMoose** [DynamoDS/Dynamo#15422]
# Issue Description
Please fill in the following information to help us reproduce the issue:

## Dynamo version
Dynamo: `2.16.2.5624`

## Operating system
OS: `Microsoft Windows NT 10.0.19045.0`

## What did you do?

Object reference not set to an instance of an object.

   at Autodesk.Revit.DB.Category.get_Id()
   at Revit.Elements.Category.get_Id()
   at Revit.Elements.Category.GetHashCode()
   at System.Collections.Generic.Dictionary`2.Remove(TKey key)
   at ProtoFFI.CLRObjectMarshaler.OnDispose(StackValue dsObject, Context context, Interpreter dsi)
   at ProtoFFI.DisposeFunctionPointer.Execute(Context c, Interpreter dsi, List`1 s)
   at ProtoCore.Lang.FFIFunctionEndPoint.Execute(Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.CallSite.DispatchDispose(StackValue stackValue, RuntimeCore runtimeCore)
   at ProtoCore.DSASM.Executive.CallDispose(ProcedureNode fNode, StackValue svThisPtr, Int32 classIndex)
   at ProtoCore.DSASM.Heap.GCDisposeObject(StackValue svPtr, Executive exe)
   at ProtoCore.DSASM.Heap.Sweep()
   at ProtoCore.DSASM.Heap.SingleStep(Boolean forceGC)
   at ProtoCore.DSASM.Heap.FullGC(IEnumerable`1 gcroots, Executive exe)
   at ProtoScript.Runners.LiveRunner.ApplyUpdate()
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()

## What did you expect to see?
OST_PlumbingFixtures

## What did you see instead?
crash thingy

## Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```
Unable to locate managed object for given dsObject.

   at ProtoFFI.CLRObjectMarshaler.CreateCLRObject(StackValue dsObject, Type type)
   at ProtoFFI.CLRObjectMarshaler.UnMarshal(StackValue dsObject, Context context, Interpreter dsi, Type expectedCLRType)
   at ProtoFFI.DisposeFunctionPointer.Execute(Context c, Interpreter dsi, List`1 s)
   at ProtoCore.Lang.FFIFunctionEndPoint.Execute(Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.CallSite.DispatchDispose(StackValue stackValue, RuntimeCore runtimeCore)
   at ProtoCore.DSASM.Executive.CallDispose(ProcedureNode fNode, StackValue svThisPtr, Int32 classIndex)
   at ProtoCore.DSASM.Heap.GCDisposeObject(StackValue svPtr, Executive exe)
   at ProtoCore.DSASM.Heap.Sweep()
   at ProtoCore.DSASM.Heap.SingleStep(Boolean forceGC)
   at ProtoCore.DSASM.Heap.FullGC(IEnumerable`1 gcroots, Executive exe)
   at ProtoScript.Runners.LiveRunner.ApplyUpdate()
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()
---
CLR: `4.0.30319.42000`

**Comment by casandraAr** [comment]
Hi @MoosiestMoose Can you please provide a step-by-step description of what you were doing when the error occurred? Sharing a simplified graph will greatly help us further troubleshoot this issue. Thanks!
