### ISSUE TITLE
Crash report from Dynamo 2.19.3.6394

### ISSUE THREAD

**Issue by LLShrestha** [DynamoDS/Dynamo#15567]
# Issue Description
Please fill in the following information to help us reproduce the issue:

## Dynamo version
Dynamo: `2.19.3.6394`

## Operating system
OS: `Microsoft Windows NT 10.0.22631.0`

## What did you do?
Clicked 'Run' then in 'Export Model Data' selected 'Continue'.
## What did you expect to see?
A spreadsheet with information from the model.

## What did you see instead?
The error message:
'Unhandled Exception in Dynamo Engine'

## What packages or external references (if any) were used?
Clockwork for Dyn 2.4.0
archi-lab.net 2023.2.13.1
Data-Shapes 2022.2.106
Rhythm 2023.4.2024
DynamoIronPython2.7 2.4.0

## Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
 
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at ProtoCore.FunctionEndPoint.DoesTypeDeepMatch(List`1 formalParameters, RuntimeCore runtimeCore)
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at ProtoCore.FunctionGroup.GetExactTypeMatches(Context context, List`1 formalParams, List`1 replicationInstructions, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.CallSite.GetCompleteMatchFunctionEndPoint(Context context, List`1 arguments, FunctionGroup funcGroup, List`1 replicationInstructions, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.CallSite.ComputeFeps(Context context, List`1 arguments, FunctionGroup funcGroup, List`1 instructions, StackFrame stackFrame, RuntimeCore runtimeCore, List`1& resolvedFeps, List`1& replicationInstructions)
   at ProtoCore.CallSite.DispatchNew(Context context, List`1 arguments, List`1 partialReplicationGuides, DominantListStructure domintListStructure, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.DSASM.Executive.Callr(Int32 blockDeclId, Int32 functionIndex, Int32 classIndex, Boolean& explicitCall, Boolean isDynamicCall, Boolean hasDebugInfo)
   at ProtoCore.DSASM.Executive.CALLR_Handler(Instruction instruction)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
   at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   at ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()

---
CLR: `4.0.30319.42000`

**Comment by LLShrestha** [comment]
I can upload he dynamo script to you.  It looks like before the crash I had to bring in default OOTB 'If' statements

**Comment by avidit** [comment]
tracked internally https://jira.autodesk.com/browse/DYN-7665

**Comment by avidit** [comment]
> I can upload he dynamo script to you. It looks like before the crash I had to bring in default OOTB 'If' statements

That would be really helpful.
