### ISSUE TITLE
Crash report from Dynamo 2.13.1.3887

### ISSUE THREAD

**Issue by onurgoztepe** [DynamoDS/Dynamo#15563]
# Issue Description
Please fill in the following information to help us reproduce the issue:

## Dynamo version
Dynamo: `2.13.1.3887`

## Operating system
OS: `Microsoft Windows NT 10.0.22631.0`

## What did you do?
(Fill in here)

## What did you expect to see?
(Fill in here)

## What did you see instead?
(Fill in here)

### Loaded Packages
- archi-lab.net 2023.213.1523
- bimorphNodes 5.1.3
- Clockwork for Dynamo 2.x 2.6.0
- Crumple 2024.4.3
- DynamoIronPython2.7 2.1.0
- Genius Loci 2024.5.29
- Modelical 2023.10.6
- Rhythm 2023.5.5
- spring nodes 121.0.2

## Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
CLR: `4.0.30319.42000`

**Comment by onurgoztepe** [comment]
Object reference not set to an instance of an object.

   at Dynamo.WorkspaceDependency.WorkspaceDependencyView.DependencyRegen(WorkspaceModel ws)
   at Dynamo.WorkspaceDependency.WorkspaceDependencyView.OnWorkspaceChanged(IWorkspaceModel obj)
   at System.Action`1.Invoke(T obj)
   at Dynamo.Extensions.ReadyParams.OnDynamoModelPropertyChanged(Object sender, PropertyChangedEventArgs e)
   at System.ComponentModel.PropertyChangedEventHandler.Invoke(Object sender, PropertyChangedEventArgs e)
   at Dynamo.Models.DynamoModel.OnPropertyChanged(String propertyName)
   at Dynamo.Models.DynamoModel.OpenCustomNodeWorkspace(Guid guid)
   at Dynamo.ViewModels.DynamoViewModel.FocusCustomNodeWorkspace(Guid symbol)
   at Dynamo.ViewModels.DynamoViewModel.GoToWorkspace(Object parameter)
   at Dynamo.Controls.NodeView.topControl_MouseLeftButtonDown(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
