### ISSUE TITLE
BUG- for slice list and during conector removal and 

### ISSUE THREAD

**Issue by LUC-ian** [DynamoDS/Dynamo#1557]
I've got this when I've tryed to remove a conector:

Collection was modified; enumeration operation may not execute.

   at System.Collections.Generic.Dictionary`2.ValueCollection.Enumerator.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__14`2.MoveNext()
   at Dynamo.Utilities.ExtensionMethods.ToThreadSafeList[TSource](IEnumerable`1 source)
   at Dynamo.VisualizationManager.AggregateRenderDescriptions()
   at Dynamo.VisualizationManager.DynamoModel_ConnectorDeleted(ConnectorModel connector)
   at Dynamo.Models.PortModel.Disconnect(ConnectorModel connector)
   at Dynamo.Models.ConnectorModel.NotifyConnectedPortsOfDeletion()
   at Dynamo.ViewModels.WorkspaceViewModel.StateMachine.HandlePortClicked(PortViewModel portViewModel)
   at Dynamo.Connectors.dynPortView.UserControl_MouseLeftButtonDown(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

![bug](https://cloud.githubusercontent.com/assets/7398467/2793666/bf872a64-cbe2-11e3-856f-c3afa1eae8b1.PNG)

Also, please check the slice list . In the lesson "Dynamo - part 2B" is shows that  we should be able get multiple slices of the main list, but I was able to get only one. :(.

**Comment by ke-yu** [comment]
Close as not enough information to do the investigation.
