### ISSUE TITLE
Crash report from Dynamo 2.6.2.15705

### ISSUE THREAD

**Issue by Praxa1** [DynamoDS/Dynamo#15643]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
Wanted to run this script 
[Export NWC with several documents (1)_2024-11-13_01-12-57](https://github.com/user-attachments/assets/6123b052-e210-4b06-8adb-0436fc0be1d1)

### What did you expect to see?
Create nwc file

### What did you see instead?
Error

### What packages or external references (if any) were used?
Genius Loci, Rythm

### Stack Trace
```
The referenced object is not valid, possibly because it has been deleted from the database, or its creation was undone.

   at validateNativeInstance(Void* ptr)
   at Autodesk.Revit.RevitDBAPIManagedWeakPointer<ADocument>.getValidPtr()
   at Autodesk.Revit.DB.Document.GetHashCode()
   at System.Collections.Generic.Dictionary`2.Remove(TKey key)
   at ProtoFFI.CLRObjectMarshaler.OnDispose(StackValue dsObject, Context context, Interpreter dsi)
   at ProtoFFI.DisposeFunctionPointer.Execute(Context c, Interpreter dsi, List`1 s)
   at ProtoCore.Lang.FFIFunctionEndPoint.Execute(Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.CallSite.ExecWithZeroRI(List`1 functionEndPoint, Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore, SingleRunTraceData previousTraceData, SingleRunTraceData newTraceData, FunctionEndPoint finalFep)
   at ProtoCore.CallSite.Execute(List`1 functionEndPoint, Context c, List`1 formalParameters, List`1 replicationInstructions, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.CallSite.DispatchNew(Context context, List`1 arguments, List`1 partialReplicationGuides, DominantListStructure domintListStructure, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.DSASM.Executive.Callr(Int32 blockDeclId, Int32 functionIndex, Int32 classIndex, Boolean& explicitCall, Boolean isDynamicCall, Boolean hasDebugInfo)
   at ProtoCore.DSASM.Heap.GCDisposeObject(StackValue svPtr, Executive exe)
   at ProtoCore.DSASM.Heap.Sweep()
   at ProtoCore.DSASM.Heap.SingleStep(Boolean forceGC)
   at ProtoCore.DSASM.Heap.FullGC(IEnumerable`1 gcroots, Executive exe)
   at ProtoScript.Runners.LiveRunner.ApplyUpdate()
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()
```

---
OS: `Microsoft Windows NT 10.0.19045.0`
CLR: `4.0.30319.42000`
Dynamo: `2.6.2.15705`

**Comment by avidit** [comment]
tracked internally https://jira.autodesk.com/browse/DYN-7822

**Comment by casandraAr** [comment]
@Praxa1 Can you please share the .dyn file to help us reproduce this issue?

**Comment by casandraAr** [comment]
@Praxa1 can you please check if the issue can be reproduced in newer versions of Dynamo, with Revit 2023 or newer? Thanks!
