### ISSUE TITLE
Crash report from Dynamo 2.13.1.3887

### ISSUE THREAD

**Issue by SANJ3861** [DynamoDS/Dynamo#15732]
# Issue Description
Please fill in the following information to help us reproduce the issue: Dynamo crash

## Dynamo version
Dynamo: `2.13.1.3887`

## Operating system
OS: `Microsoft Windows10

## What did you do?
edit script via dynamo player

## What did you expect to see?
dynamo script

## What did you see instead?
warning as dynamo crash

### Loaded Packages
- archi-lab.net 2023.213.1722
- bimorphNodes 4.2.4
- BlackBox 2016.8.5
- Clockwork for Dynamo 2.x 2.3.0
- Crumple 2022.5.27
- DynamoIronPython2.7 2.1.0
- Genius Loci 2022.7.5
- Rhythm 2023.6.2020
- spring nodes 210.1.1
- GenerativeDesign 2.0.10.0
- GenerativeDesign.Extension 2.0.10.0
- GenerativeDesign.Revit 2.0.10.0

## Stack Trace
```
Object reference not set to an instance of an object.

   at OrkestraCore.Services.WorkspacesService.<GetWorkspaces>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at OrkestraIntegrations.MVVM.ViewModel.OnlineBrowserViewModelBase.<RefreshWorkSpace>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

---
CLR: `4.0.30319.42000`

**Comment by mjkkirschner** [comment]
it looks like you should report this here instead:
https://github.com/OrkestraOnline/Orkestra_Online
