### ISSUE TITLE
Dynamo Crash - Definition goes null at Curve.ParamterAtPoint

### ISSUE THREAD

**Issue by RonFS** [DynamoDS/Dynamo#2001]
The script worked fine initially. Added additional functionality, and the script began to fail.Cannot identify the issue. Is it possible to attach the file?

Thank you...

Exception has been thrown by the target of an invocation.

   at System.RuntimeMethodHandle.SerializationInvoke(IRuntimeMethodInfo method, Object target, SerializationInfo info, StreamingContext& context)
   at System.Runtime.Serialization.ObjectManager.CompleteISerializableObject(Object obj, SerializationInfo info, StreamingContext context)
   at System.Runtime.Serialization.ObjectManager.FixupSpecialObject(ObjectHolder holder)
   at System.Runtime.Serialization.ObjectManager.DoFixups()
   at System.Runtime.Serialization.Formatters.Soap.ObjectReader.Deserialize(HeaderHandler handler, ISerParser serParser)
   at System.Runtime.Serialization.Formatters.Soap.SoapFormatter.Deserialize(Stream serializationStream, HeaderHandler handler)
   at ProtoCore.CallSite.LoadSerializedDataIntoTraceCache(String serializedTraceData)
   at ProtoCore.CallSite..ctor(Int32 classScope, String methodName, FunctionTable globalFunctionTable, ExecutionMode execMode, String serializedTraceData)
   at ProtoCore.Core.GetCallSite(GraphNode graphNode, Int32 classScope, String methodName)
   at ProtoCore.DSASM.Executive.Callr(Int32 functionIndex, Int32 classIndex, Int32 depth, Boolean& explicitCall, Boolean isDynamicCall, Boolean hasDebugInfo)
   at ProtoCore.DSASM.Executive.CALLR_Handler(Instruction instruction)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoAssociative.Executive.Execute(Int32 codeblock, Int32 entry, Context callContext, EventSink sink)
   at ProtoCore.Core.Bounce(Int32 exeblock, Int32 entry, Context context, StackFrame stackFrame, Int32 locals, EventSink sink)
   at ProtoScript.Runners.ProtoScriptTestRunner.Execute(Core core, Context context)
   at ProtoScript.Runners.LiveRunner.Execute()
   at ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.DSEngine.EngineController.UpdateGraph(Exception& fatalException)

**Comment by kronz** [comment]
obsolete
