### ISSUE TITLE
Dynamo 0.7.2.39296 crashes with Vasari

### ISSUE THREAD

**Issue by mostaphaRoudsari** [DynamoDS/Dynamo#2115]
Looks like the latest build of Dynamo easily makes Vasari to crash. This is the error for trying to create a level:

![image](https://cloud.githubusercontent.com/assets/2915573/3848671/362c680a-1e72-11e4-8ca0-53c5dc8c5e50.png)

```
The referenced object is not valid, possibly because it has been deleted from the database, or its creation was undone.

   at Autodesk.Revit.RevitAPIManagedWeakPointer<Element>.getValidPtr()
   at Autodesk.Revit.DB.Element.get_Name()
   at Revit.Elements.Level.ToString()
   at Dynamo.UI.Controls.PreviewControl.RefreshCondensedDisplay()
   at Dynamo.UI.Controls.PreviewControl.BeginFadeInTransition()
   at Dynamo.UI.Controls.PreviewControl.OnPreviewControlLoaded(Object sender, RoutedEventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at MS.Internal.FrameworkObject.OnLoaded(RoutedEventArgs args)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
```

cc: @tatlin @ikeough 
FYI: @bhowes-tt @eertugrul

**Comment by ikeough** [comment]
Closing as out of date. If this is still an error in more recent builds, please re-open.
