### ISSUE TITLE
Select Model Element node fails in Vasari

### ISSUE THREAD

**Issue by bhowes-tt** [DynamoDS/Dynamo#2116]
with the following error using Dynamo 0.7.1.39296:

External component has thrown an exception.
   at Autodesk.Revit.UI.Selection.SelElementSet.Clear()
   at Revit.Interactivity.SelectionHelper.RequestModelElementSelection(String message) in e:\DynamoCombo\src\Libraries\Revit\RevitNodesUI\SelectionHelper.cs:line 351
   at Dynamo.Nodes.DSElementSelection.OnSelectClick() in e:\DynamoCombo\src\Libraries\Revit\RevitNodesUI\Selection.cs:line 295

**Comment by ikeough** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version. 

Thank you!
