### ISSUE TITLE
Dynamo has crashed when closing the application

### ISSUE THREAD

**Issue by podaruc** [DynamoDS/Dynamo#2325]
1) I launched Revit 2015 and they I started Dynamo (from revit tooldbar)
2) I loaded an older Dynamo file worked and left the application idle for about 9-10 hours
3) after that I saved the job and closed dynamo, then i got a crash

Object reference not set to an instance of an object.

   at Dynamo.VisualizationManagerRevit.<VisualizationManagerRenderComplete>b__2(NodeModel x)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dynamo.VisualizationManagerRevit.VisualizationManagerRenderComplete(Object sender, EventArgs e)
   at Dynamo.RenderCompleteEventHandler.Invoke(Object sender, RenderCompletionEventArgs e)
   at Dynamo.Models.CleanupHandler.Invoke(Object sender, EventArgs e)
   at Dynamo.DynamoController.ShutDown(Boolean shutDownHost, EventArgs args)
   at Dynamo.DynamoController_Revit.ShutDown(Boolean shutDownHost, EventArgs args)
   at System.ComponentModel.CancelEventHandler.Invoke(Object sender, CancelEventArgs e)
   at System.Windows.Window.WmClose()
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by ikeough** [comment]
Closing as out of date. If the problem persists in recent versions of Dynamo, please re-open.
