### ISSUE TITLE
I cannot run a recursive node...

### ISSUE THREAD

**Issue by d3emko** [DynamoDS/Dynamo#2335]
I am following this example. I am following this example.
http://autodeskvasari.com/forum/topics/recursive-for-loop-using-dynamo-nodes?id=6375667%3ATopic%3A53378&page=2#comments

I receive an error every time.

Exception of type 'System.OutOfMemoryException' was thrown.

   at System.Collections.Generic.List`1.set_Capacity(Int32 value)
   at System.Collections.Generic.List`1.Add(T item)
   at ProtoCore.Runtime.RuntimeMemory.Push(StackValue data)
   at ProtoCore.Runtime.RuntimeMemory.PushStackFrame(StackValue svThisPtr, Int32 classIndex, Int32 funcIndex, Int32 pc, Int32 functionBlockDecl, Int32 functionBlockCaller, StackFrameType callerType, StackFrameType type, Int32 depth, Int32 fp, List`1 registers, Int32 locsize, Int32 executionStates)
   at ProtoCore.Core.Bounce(Int32 exeblock, Int32 entry, Context context, StackFrame stackFrame, Int32 locals, EventSink sink)
   at ProtoScript.Runners.ProtoScriptTestRunner.Execute(Core core, Context context)
   at ProtoScript.Runners.LiveRunner.Execute()
   at ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.DSEngine.EngineController.UpdateGraph(Exception& fatalException)

![image](https://cloud.githubusercontent.com/assets/8660186/4155998/d69b9f1e-346f-11e4-83f1-1624c5c8ff51.png)

![image](https://cloud.githubusercontent.com/assets/8660186/4156015/ef7b2d06-346f-11e4-91ca-5716ca6fdea9.png)

**Comment by ikeough** [comment]
I'm closing this issue as out of date. I apologize for the delay in responding. If you're still experiencing this issue in a newer build, please re-open.
