### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by DavidWKoch** [DynamoDS/Dynamo#3458]
I was experimenting with creating a string from DateTime components, and wanted to have zero padding for two digits for the month and day.  Things were working up to a point (checking string length), but then I got an unhandled exception when I tried to concatenate a string of the numeral zero ("0") with the month string.

   at ProtoCore.DSASM.Executive.SetupGraphEntryPoint(Int32 entrypoint, Boolean isGlobalScope)
   at ProtoCore.DSASM.Executive.SetupExecutive(Int32 exeblock, Int32 entry)
   at ProtoCore.DSASM.Executive.BounceExplicit(Int32 exeblock, Int32 entry, Language language, StackFrame frame)
   at ProtoCore.DSASM.Executive.BOUNCE_Handler(Instruction instruction)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoAssociative.Executive.Execute(Int32 codeblock, Int32 entry, Context callContext, EventSink sink)
   at ProtoCore.Core.Bounce(Int32 exeblock, Int32 entry, Context context, StackFrame stackFrame, Int32 locals, EventSink sink)
   at ProtoScript.Runners.ProtoScriptTestRunner.Execute(Core core, Context context)
   at ProtoScript.Runners.LiveRunner.Execute()
   at ProtoScript.Runners.LiveRunner.PostExecution()
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Core.Threading.AsyncTask.Execute()

**Comment by jnealb** [comment]
@DavidWKoch @kronz @RodRecker @pboyer This is tracked with MAGN-5735.

**Comment by holyjewsus** [comment]
I'm having trouble remembering the exact rules for scope if, but I think you cannot refer to the same chain of values in both branches of the scope if.

**Comment by kronz** [comment]
http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-5299
Scope if does not evaluate if two branches are using the same input and dynamo returns null here. User will need to make a copy of the lines and pass it to ScopeIf.
So, the behavior is "as designed", but the design needs a lot of work.  Essentially, ScopeIf was created to get some of the recursive behavior back that was available in 0.6.3, but is unrefined, undocumented, and has some limitations in its use

**Comment by DavidWKoch** [comment]
Thanks for the explanation.  I was able to use an If node successfully.

**Comment by jnealb** [comment]
Closing, as If node is sufficient.
