### ISSUE TITLE
Crash Report: updated 075 release candidate

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#3484]
DynamoReleaseCandidate2Install0.7.5

Created a code block to check the output of a variable and that seems to have triggered the crash.
It's something I regularly do without a problem, usually.

Regards,
Vikram Subbaiah

Insufficient memory within specified address space range to continue the execution of the program.

   at System.Runtime.CompilerServices.RuntimeHelpers._CompileMethod(IRuntimeMethodInfo method)
   at System.Reflection.Emit.DynamicMethod.CreateDelegate(Type delegateType, Object target)
   at System.Linq.Expressions.Expression`1.Compile()
   at System.Runtime.CompilerServices.CallSiteBinder.BindCore[T](CallSite`1 site, Object[] args)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute6[T0,T1,T2,T3,T4,T5,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5)
   at CallSite.Target(Closure , CallSite , IWatchHandler , Object , Core , String , Boolean , WatchHandlerCallback )
   at Dynamo.Interfaces.WatchHandler.GenerateWatchViewModelForData(IWatchHandler handler, Object value, Core core, String tag, Boolean showRawData)
   at Dynamo.Interfaces.DefaultWatchHandler.ProcessThing(MirrorData data, Core core, String tag, Boolean showRawData, WatchHandlerCallback callback)
   at Dynamo.Interfaces.DefaultWatchHandler.ProcessThing(MirrorData data, Core core, String tag, Boolean showRawData, WatchHandlerCallback callback)
   at Dynamo.Interfaces.DefaultWatchHandler.ProcessThing(MirrorData data, Core core, String tag, Boolean showRawData, WatchHandlerCallback callback)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute6[T0,T1,T2,T3,T4,T5,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5)
   at CallSite.Target(Closure , CallSite , DefaultWatchHandler , Object , Core , String , Boolean , WatchHandlerCallback )
   at Dynamo.Interfaces.DefaultWatchHandler.Process(Object value, Core core, String tag, Boolean showRawData, WatchHandlerCallback callback)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute6[T0,T1,T2,T3,T4,T5,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5)
   at CallSite.Target(Closure , CallSite , IWatchHandler , Object , Core , String , Boolean , WatchHandlerCallback )
   at Dynamo.Interfaces.WatchHandler.GenerateWatchViewModelForData(IWatchHandler handler, Object value, Core core, String tag, Boolean showRawData)
   at Dynamo.UI.Controls.PreviewControl.RefreshExpandedDisplay()
   at Dynamo.UI.Controls.PreviewControl.BeginExpandTransition()
   at Dynamo.Controls.dynNodeView.OnPreviewIconMouseClicked(Object sender, MouseEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunInternal(Window window)
   at DynamoSandbox.Program.MakeStandaloneAndRun(String commandFilePath, DynamoViewModel& viewModel)
   at DynamoSandbox.Program.Main(String[] args)

**Comment by ikeough** [comment]
@vykrum Please try with newer builds of Dynamo and let us know if the issue persists.
