### ISSUE TITLE
Input string was not in a correct format.

### ISSUE THREAD

**Issue by HartgE46** [DynamoDS/Dynamo#3508]
Input string was not in a correct format.

   at System.Number.ParseUInt32(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.UInt16.Parse(String s, NumberStyles style, NumberFormatInfo info)
   at Dynamo.UpdateManager.UpdateManager.GetBinaryVersionFromFilePath(String installNameBase, String filePath)
   at Dynamo.UpdateManager.UpdateManager.UpdateDataAvailable(IAsynchronousRequest request)
   at Dynamo.UpdateManager.UpdateRequest.ReadResult(Object sender, OpenReadCompletedEventArgs e)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by DanTartagliaNBBJ** [comment]
I have the same error now using: DynamoInstall0.7.6.20141222T2127.exe. I uninstalled, deleted the Dynamo folder in Program Files, ProgramData and my roaming folder. Rebooted then reinstalled and get the same error.

**Comment by RodRecker** [comment]
Can you try again now? We were updating the release builds and used a name that likely caused this problem. It should be corrected now.

**Comment by DanTartagliaNBBJ** [comment]
Dynamo works now for me!

**Comment by HartgE46** [comment]
Works for me now as well, thanks Rod!
