### ISSUE TITLE
DynamoInstall0.7.6.20141222T2127 - Not starting anymore - Please help!...

### ISSUE THREAD

**Issue by thebimman** [DynamoDS/Dynamo#3509]
Dynamo Build (DynamoInstall0.7.6.20141222T2127) was working fine in both Revit 2014 and 2015, then it just stopped showing the Node Library and upon reopening Dynamo i get the below error message.

I've tried;
- Uninstalling, reinstalling (manually removing regkeys, and installed folders after the uninstall)
- Rolling back to an eariler version

Nothing seems to fix the below issue - please help!... i would like to complete a project in Dynamo this week, if at all possible.....

Input string was not in a correct format.

   at System.Number.ParseUInt32(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.UInt16.Parse(String s, NumberStyles style, NumberFormatInfo info)
   at Dynamo.UpdateManager.UpdateManager.GetBinaryVersionFromFilePath(String installNameBase, String filePath)
   at Dynamo.UpdateManager.UpdateManager.UpdateDataAvailable(IAsynchronousRequest request)
   at Dynamo.UpdateManager.UpdateRequest.ReadResult(Object sender, OpenReadCompletedEventArgs e)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by holyjewsus** [comment]
I believe this is being investigated currently, try turning off your internet when starting dynamo

**Comment by thebimman** [comment]
Weird - that's it exactly. If i unplug the network it works fine :)

Thank you

**Comment by RodRecker** [comment]
Apologies - we were in the process of posting a new build and this may have thrown this issue. It should be working now.

**Comment by monikaprabhu** [comment]
@thebimman - Is this still an issue?

**Comment by thebimman** [comment]
Working perfectly now thank you
