### ISSUE TITLE
Cutom Node is added twice to nodes tree

### ISSUE THREAD

**Issue by vmoyseenko** [DynamoDS/Dynamo#3559]
**Build:** 0.7.6.3803.

**Steps to reproduce:**
1. Open Dynamo
2. Press `CTRL + SHIFT + N`.
3. Enter "MyCustomNode" to "Name" field.
4. Enter "Operators" to "Category" field.
5. Press "OK" button. Notice that to "Operators" new node is added.
6. Add some node to just created custom node. Let's say operator `*`.
7. Save custom node to disc.
![capture](https://cloud.githubusercontent.com/assets/8158551/5775780/5902aff8-9d87-11e4-98f1-3ef86ce89f83.PNG)
*Make notice:* second node is added to "Operators" category.
8. Click on just created node to add it to Home workspace.
Exception is thrown. Error text is below:
```
Object reference not set to an instance of an object.

   at Dynamo.Nodes.CustomNodeController`1.SerializeCore(XmlElement nodeElement, SaveContext saveContext) in d:\OpenSource\Dynamo_orig\src\DynamoCore\Nodes\Custom Nodes\CustomNodeController.cs:line 116
   at Dynamo.Nodes.Function.SerializeCore(XmlElement element, SaveContext context) in d:\OpenSource\Dynamo_orig\src\DynamoCore\Nodes\Custom Nodes\Function.cs:line 46
   at Dynamo.Models.ModelBase.Serialize(XmlDocument xmlDocument, SaveContext context) in d:\OpenSource\Dynamo_orig\src\DynamoCore\Models\ModelBase.cs:line 230
   at Dynamo.Core.UndoRedoRecorder.RecordActionInternal(XmlElement group, ModelBase model, UserAction action) in d:\OpenSource\Dynamo_orig\src\DynamoCore\Core\UndoRedoRecorder.cs:line 340
   at Dynamo.Core.UndoRedoRecorder.RecordCreationForUndo(ModelBase model) in d:\OpenSource\Dynamo_orig\src\DynamoCore\Core\UndoRedoRecorder.cs:line 186
   at Dynamo.Models.WorkspaceModel.RecordCreatedModel(ModelBase model) in d:\OpenSource\Dynamo_orig\src\DynamoCore\Models\WorkspaceModel.cs:line 1039
   at Dynamo.Models.DynamoModel.CreateNodeImpl(CreateNodeCommand command) in d:\OpenSource\Dynamo_orig\src\DynamoCore\Models\DynamoModelCommands.cs:line 106
   at Dynamo.Models.DynamoModel.CreateNodeCommand.ExecuteCore(DynamoModel dynamoModel) in d:\OpenSource\Dynamo_orig\src\DynamoCore\Models\RecordableCommands.cs:line 508
   at Dynamo.Models.DynamoModel.RecordableCommand.Execute(DynamoModel dynamoModel) in d:\OpenSource\Dynamo_orig\src\DynamoCore\Models\RecordableCommands.cs:line 66
   at Dynamo.Models.DynamoModel.ExecuteCommand(RecordableCommand command) in d:\OpenSource\Dynamo_orig\src\DynamoCore\Models\DynamoModelCommands.cs:line 23
   at Dynamo.Models.DynamoModel.<.ctor>b__6(NodeModel node) in d:\OpenSource\Dynamo_orig\src\DynamoCore\Models\DynamoModel.cs:line 421
   at Dynamo.Search.SearchLibrary`2.OnItemProduced(TItem item) in d:\OpenSource\Dynamo_orig\src\DynamoCore\Search\SearchLibrary.cs:line 58
   at Dynamo.Search.SearchElements.NodeSearchElement.OnItemProduced(NodeModel obj) in d:\OpenSource\Dynamo_orig\src\DynamoCore\Search\SearchElements\NodeSearchElement.cs:line 135
   at Dynamo.Search.SearchElements.NodeSearchElement.ProduceNode() in d:\OpenSource\Dynamo_orig\src\DynamoCore\Search\SearchElements\NodeSearchElement.cs:line 149
   at Microsoft.Practices.Prism.Commands.DelegateCommand.<>c__DisplayClass6.<.ctor>b__2(Object o)
   at Microsoft.Practices.Prism.Commands.DelegateCommandBase.Execute(Object parameter)
   at Microsoft.Practices.Prism.Commands.DelegateCommandBase.System.Windows.Input.ICommand.Execute(Object parameter)
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunInternal(Window window)
   at DynamoSandbox.Program.MakeStandaloneAndRun(String commandFilePath, DynamoViewModel& viewModel) in d:\OpenSource\Dynamo_orig\src\DynamoSandbox\Program.cs:line 43
   at DynamoSandbox.Program.Main(String[] args) in d:\OpenSource\Dynamo_orig\src\DynamoSandbox\Program.cs:line 72
```

**Comment by monikaprabhu** [comment]
@vmoyseenko , Thanks for reporting the same. Ive recorded this issue internally -MAGN-5869
if this a obstacle at the moment , you can select an existing graph and convert that to custom node, which seems to be working fine.When you right click on graph you see option "New Node from Selection"

**Comment by ikeough** [comment]
Internal issue has been closed.
