### ISSUE TITLE
Dynamo opens the file, but does not show the content

### ISSUE THREAD

**Issue by mahdino2000** [DynamoDS/Dynamo#3943]
Object reference not set to an instance of an object.

   at ProtoCore.AssociativeEngine.Utils.GetDirtyNodeCountAtGlobalScope(Executable exe)
   at ProtoScript.Runners.LiveRunner.ApplyUpdate()
   at ProtoScript.Runners.LiveRunner.PostExecution()
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(String code)
   at ProtoScript.Runners.LiveRunner.UpdateCmdLineInterpreter(String code)
   at ProtoScript.Runners.LiveRunner.ResetVMAndResyncGraph(IEnumerable`1 libraries)
   at Dynamo.DSEngine.EngineController..ctor(DynamoModel dynamoModel, String geometryFactoryFileName)
   at Dynamo.Models.DynamoModel.ResetEngineInternal()
   at Dynamo.Models.DynamoModel.ResetEngine(Boolean markNodesAsDirty)
   at Dynamo.Models.DynamoModel.CleanWorkbench()
   at Dynamo.Models.DynamoModel.Clear(Object parameter)
   at Dynamo.ViewModels.DynamoViewModel.ClearHomeWorkspaceInternal()
   at Dynamo.ViewModels.DynamoViewModel.CloseHomeWorkspace(Object parameter)
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunInternal(Window window)
   at DynamoSandbox.Program.MakeStandaloneAndRun(String commandFilePath, DynamoViewModel& viewModel)
   at DynamoSandbox.Program.Main(String[] args)

**Comment by mahdino2000** [comment]
It seems like there is a problem with the "Energy Analysis Package"

Dynamo log started 3/10/2015 12:13:27 PM
3/10/2015 12:13:27 PM : RequestUpdateVersionInfo
3/10/2015 12:13:27 PM : Requesting version update info...
3/10/2015 12:13:28 PM : Dynamo is up to date.
3/10/2015 12:13:30 PM : Dynamo -- Build 0.7.5.3566
3/10/2015 12:13:30 PM : Duplicate type encountered: ForEach
3/10/2015 12:13:30 PM : Duplicate type encountered: And
3/10/2015 12:13:30 PM : Duplicate type encountered: Or
3/10/2015 12:13:30 PM : Duplicate type encountered: Formula
3/10/2015 12:13:30 PM : Duplicate type encountered: <>c__DisplayClass4
3/10/2015 12:13:30 PM : Duplicate type encountered: <>c__DisplayClass4
3/10/2015 12:13:30 PM : Duplicate type encountered: <>c__DisplayClass6
3/10/2015 12:13:30 PM : Duplicate type encountered: <>c__DisplayClass8
3/10/2015 12:13:30 PM : Duplicate type encountered: <>c__DisplayClass4
3/10/2015 12:13:30 PM : Duplicate type encountered: <>c__DisplayClass6
3/10/2015 12:13:30 PM : Duplicate type encountered: <>c__DisplayClass2
3/10/2015 12:13:30 PM : Duplicate type encountered: <>c__DisplayClass4
3/10/2015 12:13:30 PM : Duplicate type encountered: <>c__DisplayClass6
3/10/2015 12:13:30 PM : Duplicate type encountered: ComposeFunctions
3/10/2015 12:13:30 PM : Duplicate type encountered: ComposeFunctions
3/10/2015 12:13:30 PM : Duplicate type encountered: Apply1
3/10/2015 12:13:30 PM : Duplicate type encountered: Apply1
3/10/2015 12:13:30 PM : Duplicate type encountered: <>c__DisplayClass5
3/10/2015 12:13:30 PM : Duplicate type encountered: <>c__DisplayClass6
3/10/2015 12:13:30 PM : Duplicate type encountered: <>c__DisplayClass6
3/10/2015 12:13:30 PM : Duplicate type encountered: <>c__DisplayClass5
3/10/2015 12:13:30 PM : Duplicate type encountered: <>c__DisplayClass6
3/10/2015 12:13:30 PM : Duplicate type encountered: <>c__DisplayClass2
3/10/2015 12:13:30 PM : Duplicate type encountered: <>c__DisplayClass5
3/10/2015 12:13:30 PM : Exception when attempting to load package Energy Analysis for  Dynamo from C:\Users\mehdi\AppData\Roaming\Dynamo\0.7\packages\Energy Analysis for  Dynamo
3/10/2015 12:13:30 PM : System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
3/10/2015 12:13:32 PM : Welcome to Dynamo!
3/10/2015 12:13:32 PM : 00:00:01.3048505 elapsed for loading Dynamo main window.
3/10/2015 12:13:37 PM : Opening home workspace C:\Users\mehdi\Dropbox\Mehdi's Tutorials\Final Tutorial\4_Energy Opt\Energy Opt Dynamo.dyn...
3/10/2015 12:13:37 PM : Clearing workflow...
3/10/2015 12:13:38 PM : 00:00:00.0003748 elapsed for loading xml.
3/10/2015 12:13:38 PM : Build error for library: C:\Users\mehdi\AppData\Roaming\Dynamo\0.7\packages\Energy Analysis for  Dynamo\bin\EnergyAnalysisForDynamo.dll
3/10/2015 12:13:38 PM : Could not load file or assembly 'RevitAPI, Version=2014.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
3/10/2015 12:13:38 PM : Build error for library: C:\Users\mehdi\AppData\Roaming\Dynamo\0.7\packages\Energy Analysis for  Dynamo\bin\EnergyAnalysisForDynamo.dll
3/10/2015 12:13:38 PM : Could not load file or assembly 'RevitNodes, Version=0.7.5.3566, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
3/10/2015 12:13:38 PM : Build error for library: C:\Users\mehdi\AppData\Roaming\Dynamo\0.7\packages\Energy Analysis for  Dynamo\bin\EnergyAnalysisForDynamo.dll
3/10/2015 12:13:38 PM : Could not load file or assembly 'RevitNodes, Version=0.7.5.3566, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
3/10/2015 12:13:38 PM : There was an error opening the workbench.
3/10/2015 12:13:38 PM : System.NullReferenceException:
3/10/2015 12:13:38 PM : Object reference not set to an instance of an object.
3/10/2015 12:13:38 PM :    at ProtoCore.AssociativeEngine.Utils.GetDirtyNodeCountAtGlobalScope(Executable exe)
   at ProtoScript.Runners.LiveRunner.ApplyUpdate()
   at ProtoScript.Runners.LiveRunner.PostExecution()
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(String code)
   at ProtoScript.Runners.LiveRunner.UpdateCmdLineInterpreter(String code)
   at ProtoScript.Runners.LiveRunner.ResetVMAndResyncGraph(IEnumerable`1 libraries)
   at Dynamo.DSEngine.EngineController.LibraryLoaded(Object sender, LibraryLoadedEventArgs e)
   at Dynamo.DSEngine.LibraryServices.ImportLibrary(String library, ILogger logger)
   at Dynamo.Nodes.ZeroTouchNodeController.LoadNode(XmlNode nodeElement)
   at Dynamo.Nodes.DSFunctionBase.LoadNode(XmlNode nodeElement)
   at Dynamo.Models.NodeModel.Load(XmlNode elNode)
   at Dynamo.Models.DynamoModel.OpenWorkspace(String xmlPath)
3/10/2015 12:13:38 PM : Clearing workflow...
3/10/2015 12:13:38 PM : Error opening file:Object reference not set to an instance of an object.
3/10/2015 12:13:38 PM : System.NullReferenceException:
3/10/2015 12:13:38 PM : Object reference not set to an instance of an object.
3/10/2015 12:13:38 PM :    at ProtoCore.AssociativeEngine.Utils.GetDirtyNodeCountAtGlobalScope(Executable exe)
   at ProtoScript.Runners.LiveRunner.ApplyUpdate()
   at ProtoScript.Runners.LiveRunner.PostExecution()
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(String code)
   at ProtoScript.Runners.LiveRunner.UpdateCmdLineInterpreter(String code)
   at ProtoScript.Runners.LiveRunner.ResetVMAndResyncGraph(IEnumerable`1 libraries)
   at Dynamo.DSEngine.EngineController..ctor(DynamoModel dynamoModel, String geometryFactoryFileName)
   at Dynamo.Models.DynamoModel.ResetEngineInternal()
   at Dynamo.Models.DynamoModel.ResetEngine(Boolean markNodesAsDirty)
   at Dynamo.Models.DynamoModel.CleanWorkbench()
   at Dynamo.Models.DynamoModel.OpenWorkspace(String xmlPath)
   at Dynamo.Models.DynamoModel.OpenFileImpl(OpenFileCommand command)
   at Dynamo.Models.DynamoModel.ExecuteCommand(RecordableCommand command)
   at Dynamo.ViewModels.DynamoViewModel.Open(Object parameters)

**Comment by sharadkjaiswal** [comment]
@mahdino2000 just wanted to know if you are running Dynamo on top of Revit or just a standalone. Energy Analysis package has a dependency on Revit, so you need to run Dynamo from Revit application. If you are already running it on top of Revit then this looks like some other issue.

**Comment by epeter-** [comment]
maybe try zoom all. if you have older definitions they will not show on screen as screencoordinates have (obviously) changed

**Comment by johnpierson** [comment]
Closing as this issue is for an outdated version of Dynamo. If this persists in 2.0.x for you, please feel free to reopen and update accordingly.
