### ISSUE TITLE
Exception thrown

### ISSUE THREAD

**Issue by santiagodiazames** [DynamoDS/Dynamo#3986]
Exception has been thrown by the target of an invocation.

   at System.RuntimeMethodHandle.SerializationInvoke(IRuntimeMethodInfo method, Object target, SerializationInfo info, StreamingContext& context)
   at System.Runtime.Serialization.ObjectManager.CompleteISerializableObject(Object obj, SerializationInfo info, StreamingContext context)
   at System.Runtime.Serialization.ObjectManager.FixupSpecialObject(ObjectHolder holder)
   at System.Runtime.Serialization.ObjectManager.DoFixups()
   at System.Runtime.Serialization.Formatters.Soap.ObjectReader.Deserialize(HeaderHandler handler, ISerParser serParser)
   at System.Runtime.Serialization.Formatters.Soap.SoapFormatter.Deserialize(Stream serializationStream, HeaderHandler handler)
   at ProtoCore.CallSite.LoadSerializedDataIntoTraceCache(String serializedTraceData)
   at ProtoCore.CallSite..ctor(Int32 classScope, String methodName, FunctionTable globalFunctionTable, ExecutionMode execMode, String serializedTraceData)
   at ProtoCore.RuntimeData.GetCallSite(GraphNode graphNode, Int32 classScope, String methodName, Executable executable, Int32 runningBlock, Options options, RuntimeStatus runtimeStatus)
   at ProtoCore.DSASM.Executive.Callr(Int32 functionIndex, Int32 classIndex, Int32 depth, Boolean& explicitCall, Boolean isDynamicCall, Boolean hasDebugInfo)
   at ProtoCore.DSASM.Executive.CALLR_Handler(Instruction instruction)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Interpreter.Run(Int32 codeblock, Int32 entry, Language lang, List`1 breakpoints)
   at ProtoCore.DSASM.Executive.Bounce(Int32 exeblock, Int32 entry, Context context, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptTestRunner.Execute(Core core, Int32 runningBlock, Context staticContext, Context runtimeContext)
   at ProtoScript.Runners.LiveRunner.Execute()
   at ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Core.Threading.AsyncTask.Execute()

**Comment by RodRecker** [comment]
Thanks for logging this. Which build are you using?

**Comment by santiagodiazames** [comment]
This graph was made with 0.7.5. It was working fine. I installed 0.8.0.20150312T1814.exe, then ran this graph and got the exception.
Since then I re-installed 0.7.5, and ran the same graph, it's still working fine.
It's a shame that I cannot use this latest daily build.

**Comment by sharadkjaiswal** [comment]
Thanks for reporting this issue, we are working on it. https://github.com/DynamoDS/DynamoRevit/pull/241 attempts to fix this, but this is not yet merged due to other dependent changes.

**Comment by sharadkjaiswal** [comment]
Fix is merged now with https://github.com/DynamoDS/DynamoRevit/pull/246
