### ISSUE TITLE
bug when opening file

### ISSUE THREAD

**Issue by ParametricMonkey** [DynamoDS/Dynamo#3991]
I get this when trying to open a file:

Exception has been thrown by the target of an invocation.

   at System.RuntimeMethodHandle.SerializationInvoke(IRuntimeMethodInfo method, Object target, SerializationInfo info, StreamingContext& context)
   at System.Runtime.Serialization.ObjectManager.CompleteISerializableObject(Object obj, SerializationInfo info, StreamingContext context)
   at System.Runtime.Serialization.ObjectManager.FixupSpecialObject(ObjectHolder holder)
   at System.Runtime.Serialization.ObjectManager.DoFixups()
   at System.Runtime.Serialization.Formatters.Soap.ObjectReader.Deserialize(HeaderHandler handler, ISerParser serParser)
   at System.Runtime.Serialization.Formatters.Soap.SoapFormatter.Deserialize(Stream serializationStream, HeaderHandler handler)
   at ProtoCore.CallSite.LoadSerializedDataIntoTraceCache(String serializedTraceData)
   at ProtoCore.CallSite..ctor(Int32 classScope, String methodName, FunctionTable globalFunctionTable, ExecutionMode execMode, String serializedTraceData)
   at ProtoCore.RuntimeData.GetCallSite(GraphNode graphNode, Int32 classScope, String methodName, Executable executable, Int32 runningBlock, Options options, RuntimeStatus runtimeStatus)
   at ProtoCore.DSASM.Executive.Callr(Int32 functionIndex, Int32 classIndex, Int32 depth, Boolean& explicitCall, Boolean isDynamicCall, Boolean hasDebugInfo)
   at ProtoCore.DSASM.Executive.CALLR_Handler(Instruction instruction)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Interpreter.Run(Int32 codeblock, Int32 entry, Language lang, List`1 breakpoints)
   at ProtoCore.DSASM.Executive.Bounce(Int32 exeblock, Int32 entry, Context context, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptTestRunner.Execute(Core core, Int32 runningBlock, Context staticContext, Context runtimeContext)
   at ProtoScript.Runners.LiveRunner.Execute()
   at ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Core.Threading.AsyncTask.Execute()

**Comment by monikaprabhu** [comment]
@ParametricMonkey , a similar issue is fixed by our development team and the fix is in testing right now. Issue is tracked at (MAGN-6634).Please retest in the next daily build.If you can see this error in a file where there are no Revit nodes please send me the file. Thanks for reporting this.

**Comment by ParametricMonkey** [comment]
Note sure if this is the same...

Exception of type 'ProtoCore.Exceptions.CompilerInternalException' was thrown.

   at ProtoCore.Utils.ArrayUtils.GetKeys(StackValue array, RuntimeCore runtimeCore)
   at ProtoCore.Lang.BuiltInFunctionEndPoint.Execute(Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.CallSite.ExecWithZeroRI(List`1 functionEndPoint, Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore, FunctionGroup funcGroup, SingleRunTraceData previousTraceData, SingleRunTraceData newTraceData)
   at ProtoCore.CallSite.Execute(List`1 functionEndPoint, Context c, List`1 formalParameters, List`1 replicationInstructions, StackFrame stackFrame, RuntimeCore runtimeCore, FunctionGroup funcGroup)
   at ProtoCore.CallSite.DispatchNew(Context context, List`1 arguments, List`1 partialReplicationGuides, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.DSASM.Executive.Callr(Int32 functionIndex, Int32 classIndex, Int32 depth, Boolean& explicitCall, Boolean isDynamicCall, Boolean hasDebugInfo)
   at ProtoCore.DSASM.Executive.CALLR_Handler(Instruction instruction)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Interpreter.Run(Int32 codeblock, Int32 entry, Language lang, List`1 breakpoints)
   at ProtoCore.DSASM.Executive.Bounce(Int32 exeblock, Int32 entry, Context context, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptTestRunner.Execute(Core core, Int32 runningBlock, Context staticContext, Context runtimeContext)
   at ProtoScript.Runners.LiveRunner.Execute()
   at ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Core.Threading.AsyncTask.Execute()

**Comment by monikaprabhu** [comment]
@ParametricMonkey the issue you originally mentioned first is fixed in latest daily build posted yesterday.

The second crash looks like the same in https://github.com/DynamoDS/Dynamo/issues/3989

If its different pls send me your file.

**Comment by ikeough** [comment]
@ParametricMonkey Closing this issue as a fix has been linked for #1 and a duplicate exists for #2. Please re-open and provide comments if this is unique.
