### ISSUE TITLE
Crash when using File.ReadText

### ISSUE THREAD

**Issue by LukeyJohnson** [DynamoDS/Dynamo#4289]
Trying to read a 308kb rvt file using ReadText node. Error details copied below:

Index was outside the bounds of the array.

   at ProtoCore.Utils.EncodingUtils.ConvertInt64ToCharacter(Int64 data)
   at ProtoCore.DSASM.Mirror.ExecutionMirror.GetStringTrace(StackValue strptr, Heap heap)
   at ProtoCore.DSASM.Mirror.ExecutionMirror.GetStringValue(StackValue val, Heap heap, Int32 langblock, Int32 maxArraySize, Int32 maxOutputDepth, Boolean forPrint)
   at ProtoCore.Mirror.MirrorData.GetData(StackValue sv, Core core)
   at ProtoCore.Mirror.MirrorData.get_Data()
   at Dynamo.UI.Controls.PreviewControl.RefreshCondensedDisplay()
   at Dynamo.UI.Controls.PreviewControl.BeginFadeInTransition()
   at Dynamo.UI.Controls.PreviewControl.OnPreviewControlLoaded(Object sender, RoutedEventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at MS.Internal.FrameworkObject.OnLoaded(RoutedEventArgs args)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by LukeyJohnson** [comment]
![node](https://cloud.githubusercontent.com/assets/5659896/7244982/288c7c3c-e823-11e4-9fff-354ae0d0a9ad.png)

**Comment by monikaprabhu** [comment]
@LukeyJohnson - which version of Dynamo are you running with?Are you running Dynamo Standalone or within Revit ? Revit file created from which version of revit(I tried files from 2014,2015 and 2016)? I tried on 8.0 and both daily build (1396 kb file)with Standalone and Revit. It executes without crash, though Dynamo starts becoming slow after that. Can you share the file also.

**Comment by LukeyJohnson** [comment]
I am running 7.5.3566. My initial experience with 0.8.0.0 was not good, so I uninstalled it. I guess I should try again.

**Comment by monikaprabhu** [comment]
Yes this is crashing with 0.7.5 - Please try in 0.8.0 - the issues is gone. Im closing this .
if you can reproduce with latest daily build please reopen again.
