### ISSUE TITLE
Crash from Custom Node creation and Cleanup Node Layout

### ISSUE THREAD

**Issue by LukeyJohnson** [DynamoDS/Dynamo#4328]
Edit a definition (1)
Edit a custom node (2) in that definition
Create a Node from selection
Save the nested node (3) and close it
Switch back to (2)
Attempt to Cleanup Node Layout

Because wires floating around etc (in v0.8.0.706), I assume Dynamo has problem / crashes:
Object reference not set to an instance of an object.

   at GraphLayout.Edge..ctor(Guid startId, Guid endId, Double startY, Double endY, Graph ownerGraph)
   at GraphLayout.Graph.AddEdge(Guid startId, Guid endId, Double startY, Double endY)
   at Dynamo.ViewModels.WorkspaceViewModel.DoGraphAutoLayout(Object o)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by monikaprabhu** [comment]
@LukeyJohnson - are you still able to reproduce this? I could not reproduce this on latest daily build or 0.8.0 - is it specific to some nodes.If you can still see this crash please share the nodes. You can email me at monika.prabhu@autodesk.com

**Comment by LukeyJohnson** [comment]
Still occurs for me on 0.8.0.706, video here: https://screencast.autodesk.com/main/details/c152e228-75af-4a39-8060-10881f23bb15

Object reference not set to an instance of an object.

   at GraphLayout.Edge..ctor(Guid startId, Guid endId, Double startY, Double endY, Graph ownerGraph)
   at GraphLayout.Graph.AddEdge(Guid startId, Guid endId, Double startY, Double endY)
   at Dynamo.ViewModels.WorkspaceViewModel.DoGraphAutoLayout(Object o)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by ellensi** [comment]
@LukeyJohnson 

On the latest build, I could not reproduce the floating connectors from opening the custom node "Rotate Families Around Origin" from the package "Rotate Family Instances Arond Origin Axis by Angle" version 0.0.1.

Are you still able to reproduce this on your latest version of Dynamo? Could you please provide us more details on what step you had done before seeing the floating connectors? Did you do some undo commands or switching between workspace tabs?

**Comment by LukeyJohnson** [comment]
I have not seen this issue since update to 0.8.2, appears to be fixed.
