### ISSUE TITLE
Can't start Dynamo, crashes on startup

### ISSUE THREAD

**Issue by FrenchQuarters** [DynamoDS/Dynamo#4430]
This started happening when I installed - 0.8.1.20150505T0438
It say a dll is missing. I have confirmed that that dll is indeed NOT missing. 
I have uninstalled and reinstalled several times. went a version back, and a version forward. still get the same error. I am getting the following errors:
![dynamostartuperror01](https://cloud.githubusercontent.com/assets/5280440/7519530/730644a2-f4a6-11e4-93d0-bbcb9951effa.png)
![dynamostartuperror01_02](https://cloud.githubusercontent.com/assets/5280440/7519541/77e2973c-f4a6-11e4-9ee8-9d9bd727e190.png)

Object reference not set to an instance of an object.

   at HelixToolkit.Wpf.SharpDX.Viewport3DX.HelixToolkit.Wpf.SharpDX.IRenderer.Render(RenderContext context)
   at HelixToolkit.Wpf.SharpDX.DPFCanvas.Render()
   at HelixToolkit.Wpf.SharpDX.DPFCanvas.UpdateAndRender()
   at HelixToolkit.Wpf.SharpDX.DPFCanvas.OnRendering(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by holyjewsus** [comment]
@ikeough is there a current workaround for this?

**Comment by ikeough** [comment]
@FrenchQuarters Can you try the latest daily build to see whether this is still an issue? This is related to #4367 #4211

**Comment by FrenchQuarters** [comment]
That worked. The latest build has fixed the issue.
Thanks!


ASEEM DESHPANDE, AIA, LEED AP
Director of BIM Technologies

ESKEW+DUMEZ+RIPPLE, APC
2014 AIA National Architecture Firm Award

365 Canal Street Suite 3150
New Orleans LA 70130
504.561.8686
eskewdumezripple.com<http://www.eskewdumezripple.com/>

**Comment by ikeough** [comment]
Great! Thanks for checking. Please let us know if you continue to have problems.
