### ISSUE TITLE
Create Node from Selection causes Dynamo to Crash

### ISSUE THREAD

**Issue by LukeyJohnson** [DynamoDS/Dynamo#4443]
Object reference not set to an instance of an object.

   at Dynamo.ViewModels.ConnectorViewModel..ctor(WorkspaceViewModel workspace, ConnectorModel model)
   at Dynamo.ViewModels.WorkspaceViewModel.Connectors_ConnectorAdded(ConnectorModel c)
   at Dynamo.Models.NodeModel.PortConnected(PortModel port, ConnectorModel connector)
   at Dynamo.Models.PortModel.Connect(ConnectorModel connector)
   at Dynamo.Models.ConnectorModel.Make(NodeModel start, NodeModel end, Int32 startIndex, Int32 endIndex, Nullable`1 guid)
   at Dynamo.Core.CustomNodeManager.Collapse(IEnumerable`1 selectedNodes, WorkspaceModel currentWorkspace, Boolean isTestMode, FunctionNamePromptEventArgs args)
   at Dynamo.ViewModels.WorkspaceViewModel.CollapseNodes(IEnumerable`1 selectedNodes)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by monikaprabhu** [comment]
@LukeyJohnson - which version are you using? I'm able to convert to custom node on latest daily build. If its specific nodes please share more details on the same.

**Comment by LukeyJohnson** [comment]
I'm using official build 0.8. I wonder if its somehow system related.

Kind regards

Luke Johnson

* Author of **What Revit Wants* <http://whatrevitwants.blogspot.com/>

**Comment by monikaprabhu** [comment]
@LukeyJohnson , is this still an issue?

**Comment by LukeyJohnson** [comment]
Yes. I tried upgrading to daily build, but they had other problems. Then I uninstalled and returned to official 0.8 release, and the Create Node from Selection option still results in a Dynamo crash.

**Comment by johnpierson** [comment]
Closed as this issue is on a very old release. If this is still an issue for you, feel free to reopen and upload files to reproduce.
