### ISSUE TITLE
Level.Plane node bug

### ISSUE THREAD

**Issue by ParametricMonkey** [DynamoDS/Dynamo#4475]
Got this error when using the Level.Plane node (from Clockwork?)

//////////////
Object reference not set to an instance of an object.

   at ProtoScript.Runners.LiveRunner.GetBuildWarnings()
   at Dynamo.Core.Threading.UpdateGraphAsyncTask.HandleTaskCompletionCore()
   at Dynamo.Core.Threading.DynamoScheduler.ProcessTaskInternal(AsyncTask asyncTask)
   at Dynamo.Core.Threading.DynamoScheduler.ProcessNextTask(Boolean waitIfTaskQueueIsEmpty)
   at Dynamo.UI.Controls.PreviewControl.RunOnSchedulerSync(Action a)
   at Dynamo.UI.Controls.PreviewControl.RefreshCondensedDisplay()
   at Dynamo.UI.Controls.PreviewControl.BeginFadeInTransition()
   at Dynamo.UI.Controls.PreviewControl.OnPreviewControlLoaded(Object sender, RoutedEventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at MS.Internal.FrameworkObject.OnLoaded(RoutedEventArgs args)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by monikaprabhu** [comment]
@ParametricMonkey, This works fine at my end on latest daily build -   

![level plane](https://cloud.githubusercontent.com/assets/5218721/7625191/dff2383e-fa26-11e4-8884-d97000689d59.png)

**Comment by ikeough** [comment]
We're closing this issue as it cannot be reproduced on more recent builds of Dynamo. Please re-open if you're still experiencing this problem, or have an example which reproduces the problem.
