### ISSUE TITLE
Crash on Launch (Revit 2014)

### ISSUE THREAD

**Issue by RhysProbyn** [DynamoDS/Dynamo#4506]
Version: 0.8.1.20150515T0909
Revit 2014
Win7

Following error message appears on Dynamo Launch:

Object reference not set to an instance of an object.

   at Dynamo.UI.Views.LibrarySearchView.OnTopResultTargetUpdated(Object sender, DataTransferEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Data.BindingExpression.OnTargetUpdated(DependencyObject d, DependencyProperty dp)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.Activate(Object item)
   at System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)
   at System.Windows.Data.BindingExpression.MS.Internal.Data.IDataBindEngineClient.AttachToContext(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Task.Run(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Run(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by monikaprabhu** [comment]
@RhysProbyn - I tried this on win7 Revit Architecture 2014 ,0.8.1.20150515T0909 launched fine for me- We need to figure out why its crashing at your end.

**Comment by jnealb** [comment]
@RhysProbyn @monikaprabhu The same build of Dynamo loads fine with Revit 2014 Build 20141106_0900(x64) running Win7 SP1 here. Can you provide more details re: other installed Revit Add-Ins and other installed Autodesk products? Are you running English windows or a localized version? Exact Revit build version? Thanks.

**Comment by RhysProbyn** [comment]
Issue seems to have been resolved after updating to latest build
