### ISSUE TITLE
Crash: Array dimensions exceeded supported range

### ISSUE THREAD

**Issue by LukeyJohnson** [DynamoDS/Dynamo#4752]
I have created a node that consumes a large HTML file, and I receive the "Array dimensions exceeded supported range" when running it.

Report:
Array dimensions exceeded supported range.

   at System.Collections.Generic.List`1.set_Capacity(Int32 value)
   at System.Collections.Generic.List`1.Add(T item)
   at ProtoCore.DSASM.Heap.AddHeapElement(HeapElement hpe)
   at ProtoCore.DSASM.Heap.AllocateInternal(IEnumerable`1 values)
   at ProtoCore.DSASM.Heap.AllocateArray(IEnumerable`1 values, Dictionary`2 dict)
   at ProtoCore.Utils.ArrayUtils.CopyArray(StackValue array, Type type, RuntimeCore runtimeCore)
   at ProtoCore.TypeSystem.Coerce(StackValue sv, Type targetType, RuntimeCore runtimeCore)
   at ProtoCore.Utils.ArrayUtils.CopyArray(StackValue array, Type type, RuntimeCore runtimeCore)
   at ProtoCore.TypeSystem.Coerce(StackValue sv, Type targetType, RuntimeCore runtimeCore)
   at ProtoCore.Utils.ArrayUtils.CopyArray(StackValue array, Type type, RuntimeCore runtimeCore)
   at ProtoCore.TypeSystem.Coerce(StackValue sv, Type targetType, RuntimeCore runtimeCore)
   at ProtoCore.Utils.ArrayUtils.CopyArray(StackValue array, Type type, RuntimeCore runtimeCore)
   at ProtoCore.TypeSystem.Coerce(StackValue sv, Type targetType, RuntimeCore runtimeCore)
   at ProtoCore.FunctionEndPoint.CoerceParameters(List`1 formalParameters, RuntimeCore runtimeCore)
   at ProtoCore.CallSite.ExecWithZeroRI(List`1 functionEndPoint, Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore, FunctionGroup funcGroup, SingleRunTraceData previousTraceData, SingleRunTraceData newTraceData)
   at ProtoCore.CallSite.Execute(List`1 functionEndPoint, Context c, List`1 formalParameters, List`1 replicationInstructions, StackFrame stackFrame, RuntimeCore runtimeCore, FunctionGroup funcGroup)
   at ProtoCore.CallSite.DispatchNew(Context context, List`1 arguments, List`1 partialReplicationGuides, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.DSASM.Executive.Callr(Int32 functionIndex, Int32 classIndex, Int32 depth, Boolean& explicitCall, Boolean isDynamicCall, Boolean hasDebugInfo)
   at ProtoCore.DSASM.Executive.CALLR_Handler(Instruction instruction)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Interpreter.Run(Int32 codeblock, Int32 entry, Language lang, List`1 breakpoints)
   at ProtoCore.DSASM.Executive.Bounce(Int32 exeblock, Int32 entry, Context context, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptTestRunner.Execute(Core core, Int32 runningBlock, Context staticContext, Context runtimeContext)
   at ProtoScript.Runners.LiveRunner.Execute()
   at ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Core.Threading.AsyncTask.Execute()

**Comment by monikaprabhu** [comment]
@LukeyJohnson - could you please share the files with me monika.prabhu@autodesk.com. Which node are you using to read the html file ?

**Comment by LukeyJohnson** [comment]
---------- Forwarded message ----------
From: Luke Johnson <luke.s.johnson@gmail.com>
Date: Tue, Jun 23, 2015 at 12:07 PM
Subject: Re: [Dynamo] Crash: Array dimensions exceeded supported range
(#4752)
To: DynamoDS/Dynamo <
reply@reply.github.com
>


It works ok as a DYN, but when I put it in a DYF the node fails with the
'array dimensions' error. I have provided the DYN, DYF and HTML file I am
trying to parse. Thanks.

Kind regards

Luke Johnson

* Author of **What Revit Wants* <http://whatrevitwants.blogspot.com/>
