### ISSUE TITLE
Build Node from Selection crashing

### ISSUE THREAD

**Issue by Justrhys** [DynamoDS/Dynamo#4784]
Trying to build a node from a selection but keeps crashing.

**Comment by Justrhys** [comment]
Object reference not set to an instance of an object.

   at Dynamo.ViewModels.ConnectorViewModel..ctor(WorkspaceViewModel workspace, ConnectorModel model)
   at Dynamo.ViewModels.WorkspaceViewModel.Connectors_ConnectorAdded(ConnectorModel c)
   at Dynamo.Models.NodeModel.PortConnected(PortModel port, ConnectorModel connector)
   at Dynamo.Models.PortModel.Connect(ConnectorModel connector)
   at Dynamo.Models.ConnectorModel.Make(NodeModel start, NodeModel end, Int32 startIndex, Int32 endIndex, Nullable`1 guid)
   at Dynamo.Core.CustomNodeManager.Collapse(IEnumerable`1 selectedNodes, WorkspaceModel currentWorkspace, Boolean isTestMode, FunctionNamePromptEventArgs args)
   at Dynamo.ViewModels.WorkspaceViewModel.CollapseNodes(IEnumerable`1 selectedNodes)
   at System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   at System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndKeyboardInputProvider.FilterMessage(IntPtr hwnd, WindowMessage message, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by marcellosgamb** [comment]
I am not able to open the daily build (DynamoInstall0.8.2.20150624T0456.exe) once installed

**Comment by lillismith** [comment]
We see this issue too and are tracking internally at MAGN-7748. We'll let you know when it's fixed.

**Comment by lillismith** [comment]
Daily build not opening problem fixed as of DynamoInstall0.8.2.20150624T2053.exe
