### ISSUE TITLE
Unable to find sharpdx_direct3d11_effects_x64.dll in Revit

### ISSUE THREAD

**Issue by jechtma** [DynamoDS/Dynamo#4835]
When start Dynamo 0.8.2.20150630T2036 in Revit[20140709_2115(x64)
Update Release 3], the computer said it could not find  [sharpdx_direct3d11_effects_x64.dll] in the path, then following the error "the given key was not present in the dictionary". 

Object reference not set to an instance of an object.

   at HelixToolkit.Wpf.SharpDX.Viewport3DX.HelixToolkit.Wpf.SharpDX.IRenderer.Render(RenderContext context)
   at HelixToolkit.Wpf.SharpDX.DPFCanvas.Render()
   at HelixToolkit.Wpf.SharpDX.DPFCanvas.UpdateAndRender()
   at HelixToolkit.Wpf.SharpDX.DPFCanvas.OnRendering(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

If I go back to the stable release 0.8.0, Nodes related to geometry give me the warning “The type initializer for 'Autodesk.LibG.LibGPINVOKE' threw an exception.” 

However, everything goes fine in Dynamo sandbox except a poor visual effect as shown below. So my guess is that Revit can not find those dlls in Dynamo folder. I find similar issue in #4211 & #4430, but no solution for me. I am on a 64-bit win 7 pc with DirectX 11.
![image](https://cloud.githubusercontent.com/assets/7802534/8468568/9402756a-20a0-11e5-8b16-326101f12228.png)

**Comment by jnealb** [comment]
@ikeough Perhaps this is obvious to you? Alien LibG earlier on path? Thanks for a curbside.

**Comment by jnealb** [comment]
@jechtma Is this still an issue?

**Comment by jechtma** [comment]
I reinstalled  windows system and the problem was solved.

2015-09-11 5:29 GMT+08:00 Neal Burnham <notifications@github.com>:

**Comment by jnealb** [comment]
@jechtma Thanks.
