### ISSUE TITLE
Issues with aggregating several previously published nodes into a new package

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#487]
- Place some already published nodes on the canvas
- Select them
- In Packages menu select Publish Selected Nodes
- Dynamo will ask you to whether you want to publish a new version or move the node to a new package - select the option for new package
- Publish new package
- In package manager, go to the new package and select Publish New Version

Dynamo will crash with the following message:

```
Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index

   at Dynamo.PackageManager.PublishPackageViewModel.set_FunctionDefinitions(List`1 value)
   at Dynamo.PackageManager.PublishPackageViewModel.FromLocalPackage(Package l)
   at Dynamo.PackageManager.Package.PublishNewPackageVersion()
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
```

A possible cause might be that the dyn files are not copied or moved to the new package folder - they remain in their original package folders.

**Comment by kronz** [comment]
Dare I hope that this is obsolete?  Please reopen if still happening.
