### ISSUE TITLE
quota problem in energy optimization

### ISSUE THREAD

**Issue by murataltun** [DynamoDS/Dynamo#5065]
I just try to optimize building energy performance by changing building element's geometry and material properties. In optimization loops, some of the design gives result whereas some of the mdoes not give anything. When it gives results,  it runs in 15-20 seconds whereas this time increases up to 5 minutes for single run when it does not give any results. In optimization process for 400 function evaluation, it gives quota error although virtual quota is also increased. How can it be solved yet? 
You can find details of the single loop run in dynamobim forum : http://dynamobim.com/forums/topic/multiple-run-problems-in-revit-energy-analysis/

Not enough quota is available to process this command

   at MS.Win32.UnsafeNativeMethods.PostMessage(HandleRef hwnd, WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget)
   at System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by johnpierson** [comment]
Closing as this issue is for an outdated version of Dynamo. If this persists in 2.0.x for you, please feel free to reopen and update accordingly.
