### ISSUE TITLE
Dynamo crashes when using Structural Analysis Package

### ISSUE THREAD

**Issue by basboer** [DynamoDS/Dynamo#5102]
Retrieving the COM class factory for component with CLSID {F7870790-CDE5-11D1-8FF1-00A02447BAAE} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).

   at DynamoSimulation.RSA.RSACore.InitRSAApplication()
   at DynamoSimulation.RSA.RSACore.InitRSACore()
   at DynamoSimulation.RSA.RSACore.EnsureRSA()
   at DynamoSimulation.RSA.UI.LabelDropDown.PostPopulateItems()
   at DynamoSimulation.RSA.UI.LabelDropDown.PopulateItems()
   at DynamoSimulation.RSA.UI.LabelDropDown..ctor(Int32 label, String name)
   at DynamoSimulation.RSA.UI.Support..ctor()
   at lambda_method(Closure )
   at Dynamo.Search.SearchElements.NodeModelSearchElement.ConstructNewNodeModel()
   at Dynamo.Wpf.ViewModels.NodeSearchElementViewModel.OnClicked()
   at Dynamo.UI.Controls.StandardPanel.OnMouseLeftButtonUp(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by monikaprabhu** [comment]
@basboer - which version of Robot Strcutural Are you using ?

**Comment by basboer** [comment]
Problem is already solved... by upgrading. Thanks for your reaction.

Bas
