### ISSUE TITLE
The '+' Character, , hexadecimal value 0x2B, cannot be included in a name.

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/Dynamo#5120]
I was building some small UI Nodes and this comes up. Any ideas? 

The '+' character, hexadecimal value 0x2B, cannot be included in a name.

   at System.Xml.XmlDocument.CheckName(String name)
   at System.Xml.XmlDocument.CreateElement(String prefix, String localName, String namespaceURI)
   at Dynamo.Models.ModelBase.CreateElement(XmlDocument xmlDocument, SaveContext context)
   at Dynamo.Core.UndoRedoRecorder.RecordActionInternal(XmlElement group, ModelBase model, UserAction action)
   at Dynamo.Models.WorkspaceModel.RecordCreatedModel(ModelBase model)
   at Dynamo.Models.DynamoModel.ExecuteCommand(RecordableCommand command)
   at Dynamo.ViewModels.SearchViewModel.OnSearchElementClicked(NodeModel nodeModel, Point position)
   at Dynamo.Wpf.ViewModels.NodeSearchElementViewModel.OnClicked()
   at Dynamo.UI.Controls.ClassInformationView.OnMouseLeftButtonUp(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

Here is my UI Class: 

```C#
        [NodeName("SomeName")]
        [NodeCategory("Archi-lab_Grimshaw.Printing")]
        [NodeDescription("Retrieve all available Print Range options.")]
        [IsDesignScriptCompatible]
        public class PrintRanges : RevitDropDownBase
        {
            private const string NO_FAMILY_TYPES = "SomeText";
            public PrintRanges() : base("SomeName") { }
            public override void PopulateItems()
            {
                Items.Clear();

                var printRanges = Enum.GetValues(typeof(PrintRange))
                    .Cast<PrintRange>()
                    .ToList();

                if (printRanges.Count == 0)
                {
                    Items.Add(new DynamoDropDownItem(NO_FAMILY_TYPES, null));
                    SelectedIndex = 0;
                    return;
                }

                foreach (PrintRange pr in printRanges)
                {
                    Items.Add(new DynamoDropDownItem(pr.ToString(), pr));
                }
                Items = Items.OrderBy(x => x.Name).ToObservableCollection();
            }

            public override IEnumerable<AssociativeNode> BuildOutputAst(List<AssociativeNode> inputAstNodes)
            {
                if (Items.Count == 0 ||
                    Items[0].Name == NO_FAMILY_TYPES ||
                    SelectedIndex == -1)
                {
                    return new[] { AstFactory.BuildAssignment(GetAstIdentifierForOutputIndex(0), AstFactory.BuildNullNode()) };
                }

                var args = new List<AssociativeNode>
            {
                AstFactory.BuildStringNode(((PrintRange) Items[SelectedIndex].Item).ToString())
            };

                var func = new Func<string, PrintRange>(GetPrintRange.byName);
                var functionCall = AstFactory.BuildFunctionCall(func, args);

                return new[] { AstFactory.BuildAssignment(GetAstIdentifierForOutputIndex(0), functionCall) };
            }

        }
```

and here is the function that it calls:

```C#
    public class GetPrintRange
    {
        public static PrintRange byName(string name)
        {
            //exceptions
            if (name == null)
            {
                throw new ArgumentNullException("name");
            }
            //Gets Print Range by name
            PrintRange pr = Enum.GetValues(typeof(PrintRange))
                    .Cast<PrintRange>()
                    .ToList()
                    .FirstOrDefault(q => q.ToString() == name);

            return pr;
        }
    }
```

Any help would be much appreciated. Thank you,

**Comment by ksobon** [comment]
This seems like an issue for @ikeough as it smells to me like a Dynamo compiling error...unless i asked it to do something weird. I am a noob, so apologies for breaking it. :-)

**Comment by holyjewsus** [comment]
hmmm, the stack trace looks like it was actually when trying to record the creation of this node for undo that the xml representation had some invalid xml... apparently a + in the name... is there  "+" in the path to the UI dll?

**Comment by ksobon** [comment]
not likely. a + is not a character that i would use when creating a directory. both dlls were uploaded to a package so live in userData....Dynamo/packages/ location. Is that the path that you are referring to?

**Comment by ksobon** [comment]
I also checked paths to all of my references in VS and none have a + sign in them. Would it be possible to obtain an example of a dropdown node that uses the Enum object from Revit. There is a ton of them in Revit: PrintRange, BuiltInParameter, etc.

**Comment by ksobon** [comment]
It works now, although I have no idea what the issue was. I used a different method for extracting an Enum value and now its all good. Thanks for help though.
