### ISSUE TITLE
getting some istances parameters and got this error

### ISSUE THREAD

**Issue by Appio81** [DynamoDS/Dynamo#5160]
Object reference not set to an instance of an object.

   at ProtoCore.DSASM.Heap.GCMarkAndSweep(List`1 rootPointers, Executive exe)
   at ProtoCore.DSASM.Executive.GC()
   at ProtoCore.DSASM.Executive.DEP_Handler(Instruction instruction)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptTestRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   at ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Core.Threading.AsyncTask.Execute()

![image](https://cloud.githubusercontent.com/assets/13900760/9404695/f7e2d8ea-47f1-11e5-8223-4b9277e10ba4.png)

**Comment by monikaprabhu** [comment]
@Appio81 - Can you please post more information here - Which nodes are you using for querying parameters,  any specific type of family instance or all of them. Which build of Dynamo are you using - Please post your data set if consistently reproducible.

**Comment by Appio81** [comment]
The original file with the error was deleted, I've done a new one with many copy\paste. Next time I will send you the file too.

**Comment by monikaprabhu** [comment]
@Appio81 - Do you mean the file was not saved and after crash the file was lost ?We generally save a backup file every one min - could you please check in folder -C:\Users\... \AppData\Roaming\Dynamo\backup and see it could be recovered ?

**Comment by johnpierson** [comment]
Closing this as we need more information. Please reopen and update if this is still an issue for you.
