### ISSUE TITLE
Crash on Opening also crashes Revit

### ISSUE THREAD

**Issue by bdmackey** [DynamoDS/Dynamo#5355]
Open Dynamo from latest build

Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.

   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Dynamo.Wpf.NodeViewCustomizationLoader.LoadCustomizations(Assembly assem)
   at Dynamo.Wpf.AssemblyNodeViewCustomizations.GetCustomizations()
   at Dynamo.Wpf.NodeViewCustomizationLibrary.Add(INodeViewCustomizations cs)
   at Dynamo.Controls.DynamoView.LoadNodeViewCustomizations()
   at Dynamo.Controls.DynamoView.DynamoView_Loaded(Object sender, EventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at MS.Internal.FrameworkObject.OnLoaded(RoutedEventArgs args)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by RodRecker** [comment]
@bdmackey Is this still happening with newer builds? Which version of Revit and Dynamo are you using?

**Comment by bdmackey** [comment]
Rod,

 

I was happening with the daily build, the day I submitted.  This was true of one of my clients as well.  It was with Revit 2015, didn’t even think to try to open 2015 and Dynamo.  I went back to an older version and it wasn’t crashing.  I haven’t tried any of the newest daily builds.  

 

Brian Mackey

BD Mackey Consulting

 <http://bdmackeyconsulting.com/> bdmackeyconsulting.com

303.906.6619

**Comment by RodRecker** [comment]
@bdmackey thanks for the info. If you have a chance to try on a newer build, that will be helpful as we are about to start final testing and fixing for our next release, 0.9.0.

**Comment by ke-yu** [comment]
@bdmackey are you able to reproduce the crash?

**Comment by ke-yu** [comment]
Close as not enough information to do further investigation.
