### ISSUE TITLE
Nodes's Data Reviews show null and Crashes

### ISSUE THREAD

**Issue by mpdiker** [DynamoDS/Dynamo#5400]
I’ve made a clean install of DynamoInstall0.8.3.20150924T2050 and Data Preview of Nodes show null. And also Dynamo crashes regularly.
When I revert back to DynamoInstall0.8.2 everything works OK.

http://dynamobim.com/forums/topic/nodes-data-preview-not-working/

Here's a recent crash report:

The input argument "materialId" of function `anonymous-namespace'::TessellatedFace_constructor or one item in the collection is null at line 89 of file d:\ship\2016_px64\source\foundation\geomutilapi\gensrc\APITessellatedShapeBuilderProxy.cpp.
Parameter name: materialId

   at ?A0x3826548e.TessellatedFaceProxy_constructor(IList`1 outerLoopVertices, ElementId materialId)
   at Revit.GeometryConversion.ProtoToRevitMesh.ToRevitType(Surface srf, TessellatedShapeBuilderTarget target, TessellatedShapeBuilderFallback fallback, ElementId MaterialId, Boolean performHostUnitConversion)
   at Dynamo.Applications.ViewModel.RevitWatch3DViewModel.RevitGeometryObjectFromGraphicItem(IGraphicItem item, List`1& geoms)
   at Dynamo.Applications.ViewModel.RevitWatch3DViewModel.Draw()
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Dynamo.Models.DynamoModel.OnEvaluationCompleted(Object sender, EvaluationCompletedEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Dynamo.Models.HomeWorkspaceModel.OnEvaluationCompleted(EvaluationCompletedEventArgs e)
   at Dynamo.Models.DynamoModel.RunCancelImpl(RunCancelCommand command)
   at Dynamo.Models.DynamoModel.ExecuteCommand(RecordableCommand command)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by pboyer** [comment]
@ikeough what do you think?

**Comment by ikeough** [comment]
Sounds like the Revit material that is used by the background preview does not exist.
@mpdiker, which language revit do you use?

**Comment by mpdiker** [comment]
US-English

**Comment by mpdiker** [comment]
Is it possible to add that material to our template?

**Comment by amagie** [comment]
I think, I have the same problem. @mpdiker can you tell me how to import material into template? :)

**Comment by johnpierson** [comment]
Closing as this issue is for an outdated version of Dynamo. If this persists in 2.0.x for you, please feel free to reopen and update accordingly.
