### ISSUE TITLE
Dynamo Command Line Interface

### ISSUE THREAD

**Issue by NicklasOestergaard** [DynamoDS/Dynamo#5437]
I how just installed Dynamo. Then I try to run it from the commandline I get this error:

C:\Users\nvo>cd C:\Program Files\Dynamo 0.8

C:\Program Files\Dynamo 0.8>DynamoCLI.exe
Error: Class redefinition 'NavisworksAutomationAPI13.Document' (BE1C3285). (C:\U
sers\nvo\AppData\Roaming\Dynamo\0.8\packages\DynaWorks16\bin\Interop.NavisworksA
utomationAPI13.dll - line: -1, col: -1)
Error: Exception of type 'ProtoCore.Exceptions.CompilerInternalException' was th
rown.
Error: Can't import System.Collections.Generic.Dictionary`2+ValueCollection[[Sys
tem.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561
934e089],[System.Object, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyTo
ken=b77a5c561934e089]], ValueCollection is already imported as System.Collection
s.Generic.Dictionary`2+KeyCollection[[System.String, mscorlib, Version=4.0.0.0,
Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.Object, mscorlib, Vers
ion=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], namespace suppo
rt needed.

C:\Program Files\Dynamo 0.8>

**Comment by tatlin** [comment]
Looks like DynaWorks may not like running with the CLI. Does it run ok from Dynamo for Revit or sandbox mode? Try removing the DynamoWorks package from C:\Users\nvo\AppData\Roaming\Dynamo\0.8\packages\ and re-testing

**Comment by NicklasOestergaard** [comment]
C:\Program Files\Dynamo 0.8>DynamoCLI.exe -o "export_dwf.dyn"
Error: Can't import System.Collections.Generic.Dictionary`2+ValueCollection[[Sys
tem.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561
934e089],[System.Object, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyTo
ken=b77a5c561934e089]], ValueCollection is already imported as System.Collection
s.Generic.Dictionary`2+KeyCollection[[System.String, mscorlib, Version=4.0.0.0,
Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.Object, mscorlib, Vers
ion=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], namespace suppo
rt needed.
Could not find file 'C:\Program Files\Dynamo 0.8\export_dwf.dyn'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, I
nt32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions o
ptions, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolea
n useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access,
FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean
bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access,
FileShare share, Int32 bufferSize)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofO
bjectToReturn)
   at System.Xml.XmlTextReaderImpl.OpenUrlDelegate(Object xmlResolver)
   at System.Threading.CompressedStack.runTryCode(Object userData)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCl
eanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.CompressedStack.Run(CompressedStack compressedStack, Cont
extCallback callback, Object state)
   at System.Xml.XmlTextReaderImpl.OpenUrl()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean prese
rveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.Load(String filename)
   at Dynamo.Models.DynamoModel.OpenFileFromPath(String xmlPath, Boolean forceMa
nualExecutionMode)
   at DynamoCLI.CommandLineRunner.RunCommandLineArgs(DynamoModel model, CommandL
ineArguments cmdLineArgs)
   at DynamoCLI.CommandLineRunner.Run(CommandLineArguments args)
   at DynamoCLI.Program.Main(String[] args)

C:\Program Files\Dynamo 0.8>

**Comment by mjkkirschner** [comment]
try providing the full path to your file, is your file actually located in the dynamo directory?

**Comment by NicklasOestergaard** [comment]
No it's in da folder named dynamo.
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\nvo>cd C:\Program Files\Dynamo 0.8

C:\Program Files\Dynamo 0.8>DynamoCLI.exe -o "C:\Users\nvo\Desktop\export_dwf.dy
n"
Error: Can't import System.Collections.Generic.Dictionary`2+ValueCollection[[Sys
tem.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561
934e089],[System.Object, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyTo
ken=b77a5c561934e089]], ValueCollection is already imported as System.Collection
s.Generic.Dictionary`2+KeyCollection[[System.String, mscorlib, Version=4.0.0.0,
Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.Object, mscorlib, Vers
ion=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], namespace suppo
rt needed.
Could not find file 'C:\Users\nvo\Desktop\export_dwf.dyn'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, I
nt32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions o
ptions, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolea
n useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access,
FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean
bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access,
FileShare share, Int32 bufferSize)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofO
bjectToReturn)
   at System.Xml.XmlTextReaderImpl.OpenUrlDelegate(Object xmlResolver)
   at System.Threading.CompressedStack.runTryCode(Object userData)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCl
eanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.CompressedStack.Run(CompressedStack compressedStack, Cont
extCallback callback, Object state)
   at System.Xml.XmlTextReaderImpl.OpenUrl()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean prese
rveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.Load(String filename)
   at Dynamo.Models.DynamoModel.OpenFileFromPath(String xmlPath, Boolean forceMa
nualExecutionMode)
   at DynamoCLI.CommandLineRunner.RunCommandLineArgs(DynamoModel model, CommandL
ineArguments cmdLineArgs)
   at DynamoCLI.CommandLineRunner.Run(CommandLineArguments args)
   at DynamoCLI.Program.Main(String[] args)

C:\Program Files\Dynamo 0.8>

**Comment by mjkkirschner** [comment]
you are also getting this error: 
Could not find file 'C:\Users\nvo\Desktop\export_dwf.dyn'. is that the exact name?

can you remove all packages and definitions from your system temporarily?
what does the definition do? (some libraries are not loaded into the CLI) does it rely on some packages ?
can you email the dyn to me here: michael.kirschner@autodesk.com
