### ISSUE TITLE
Geometry does intersect

### ISSUE THREAD

**Issue by ParametricMonkey** [DynamoDS/Dynamo#5681]
Hi 
Is there a bug with the Geometry.DoesIntersect node? It use to work fine but now it is failing. I'm using version 0.9. Basically the script is just testing for the intersection of a model curve and room boundaries extracted from Lunchbox. I though that there may not actually be an intersection at all but it appears its the node, not the geometry. Deconstructing the start point shows that all points have a Z value of 0. Even moving the curves down and extruding it up (so it would def intersect) returns a null intersection. 

![doesintersect](https://cloud.githubusercontent.com/assets/10913639/11054846/e1d53b70-87c4-11e5-8155-3504fe3852a0.png)

**Comment by ParametricMonkey** [comment]
also getting this:

The input argument "materialId" of function `anonymous-namespace'::TessellatedFace_constructor or one item in the collection is null at line 96 of file d:\sundial\2015_px64\source\api\revitapi\gensrc\APITessellatedShapeBuilder.cpp.
Parameter name: materialId

   at ?A0x91c5a93f.TessellatedFace_constructor(IList`1 outerLoopVertices, ElementId materialId)
   at Autodesk.Revit.DB.TessellatedFace..ctor(IList`1 outerLoopVertices, ElementId materialId)
   at Revit.GeometryConversion.ProtoToRevitMesh.ToRevitType(Surface srf, TessellatedShapeBuilderTarget target, TessellatedShapeBuilderFallback fallback, ElementId MaterialId, Boolean performHostUnitConversion)
   at Dynamo.Applications.ViewModel.RevitWatch3DViewModel.RevitGeometryObjectFromGraphicItem(IGraphicItem item, List`1& geoms)
   at Dynamo.Applications.ViewModel.RevitWatch3DViewModel.Draw()
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Dynamo.Models.HomeWorkspaceModel.Run()
   at Dynamo.Models.DynamoModel.ExecuteCommand(RecordableCommand command)
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by mccrone** [comment]
Hi Paul, it sounds like there may be a problem with the Lunchbox node rather than the Geometry.Intersect node.  Try using Element.Geometry from the room elements as the entity with wich to test for intersection with the model curve.

**Comment by archinate** [comment]
The Room component outputs boundary geometry as Dynamo curves.  Yours looks to be working properly.  I'll do some testing tonight.

![image](https://cloud.githubusercontent.com/assets/1890663/11079109/7ecb7250-87cf-11e5-8600-a300e143a4b1.png)

**Comment by mjkkirschner** [comment]
@ParametricMonkey what version of Dynamo are you on?

can you try scaling your rooms down so coordinates are smaller, and try testing again, I have a feeling this is a precision issue. (i.e. try polycurves with coordinates in ft, as opposed to mm)

**Comment by ParametricMonkey** [comment]
I'm pretty sure its with the does intersect node. it doesn't even recognize am intersection with a solid...

![doesintersect2](https://cloud.githubusercontent.com/assets/10913639/11081777/d66c7e60-8873-11e5-85de-8225050c1469.JPG)

**Comment by archinate** [comment]
Could it be that you need to use List.Map?  This had me scratching my head, too.  Geometry.DoesIntersect seems to need to be "mapped" it if you are testing intersections on multiple objects.  

Not the most intuitive workflow... but List.Map never is :(

![image](https://cloud.githubusercontent.com/assets/1890663/11081989/0d773b30-87e7-11e5-9428-752764b76c51.png)

**Comment by archinate** [comment]
Scratch that...  I'm getting it to work.  I had my lacing wrong.

I'm still on version 0.8.2, though (I have projects finishing out in that version).  Maybe something is up with 0.9.  But intersections seem correct here...

![image](https://cloud.githubusercontent.com/assets/1890663/11082058/95864e1c-87e7-11e5-94d0-610817a16131.png)

**Comment by ParametricMonkey** [comment]
There was the lacing/ list map user error. But I'm finding the does intersect node doesn't like some splines. I can't troubleshoot why which ones fail and others succeed. Its very odd.

I'm running 0.8.2. I've tried on 0.9 but everytime I select a model element and run the script I get null. Trying to re-run it just causes it to crash with the error message above. 

![error1](https://cloud.githubusercontent.com/assets/10913639/11105483/1b216ea8-8923-11e5-83b2-201c92ac953e.JPG)
![error2](https://cloud.githubusercontent.com/assets/10913639/11105484/1c6e6ca2-8923-11e5-880d-fffcb018807a.JPG)
![Uploading Error3.JPG…]()

**Comment by ParametricMonkey** [comment]
![error3](https://cloud.githubusercontent.com/assets/10913639/11105524/7bec83f8-8923-11e5-80b8-28d302e90018.JPG)

**Comment by ParametricMonkey** [comment]
Ok this still isn't working. I'm testing on Dynamo 0.9 on Revit 2015. So the 2 issues are as follows:

- Geometry does intersect doesn't always work as shown in the example above
- If i have more complicated rooms with internal islands I get an error polycurves may not be branching. This is fine as I can just get the first item of the polycurves for the outline. But then using this outline for goes intersect i get an error: 

Warning: Internal error, please report: Dereferencing a non-pointer. (3f47aacd)
Internal error, please report: Dereferencing a non-pointer. (3f47aacd)

![error](https://cloud.githubusercontent.com/assets/10913639/12255768/834901aa-b94b-11e5-9e27-1b60bbdb3566.jpg)
0d92.jpg)

**Comment by mccrone** [comment]
@ParametricMonkey, you are correct!  Geometry.DoesIntersect does have something wrong with it.  Geometry.Intersect may sometimes return a result but Geometry.DoesIntersect still reports false.  This is being tracked internally as MAGN-9320.

![doesintersect](https://cloud.githubusercontent.com/assets/6430819/12303072/4cfa909a-b9dd-11e5-9b89-e75eb5c7d443.PNG)

[DoesIntersect.zip](https://github.com/DynamoDS/Dynamo/files/89304/DoesIntersect.zip)

@archinate, Lunchbox has also got a little hiccup going on.

![lunchbox](https://cloud.githubusercontent.com/assets/6430819/12303252/2c2ab934-b9de-11e5-9af5-f5ae45d4bd25.PNG)

**Comment by ParametricMonkey** [comment]
Hi. Is there any update on this?

**Comment by aparajit-pratap** [comment]
The issue with `DoesIntersect` and `Geometry.Intersect` not working reliably is when we use large coordinate values in the model, more specifically, anything > 10e4. This is a limitation of the ASM geometric kernel. The same thing is seen here in these use cases. We're trying solutions where we can scale down the models, perform the intersections, and then scale them back up again.

**Comment by ParametricMonkey** [comment]
There is also a problem with the curve.ParameterAtPoint not working for distances over 10,000. Please fix this as it is a major oversight.

**Comment by aparajit-pratap** [comment]
Fixed in Dynamo version 1.2.3 (daily builds). Closing ...
