### ISSUE TITLE
create polycurve from curves

### ISSUE THREAD

**Issue by ParametricMonkey** [DynamoDS/Dynamo#5690]
The input argument "materialId" of function `anonymous-namespace'::TessellatedFace_constructor or one item in the collection is null at line 96 of file d:\sundial\2015_px64\source\api\revitapi\gensrc\APITessellatedShapeBuilder.cpp.
Parameter name: materialId

   at ?A0x91c5a93f.TessellatedFace_constructor(IList`1 outerLoopVertices, ElementId materialId)
   at Autodesk.Revit.DB.TessellatedFace..ctor(IList`1 outerLoopVertices, ElementId materialId)
   at Revit.GeometryConversion.ProtoToRevitMesh.ToRevitType(Surface srf, TessellatedShapeBuilderTarget target, TessellatedShapeBuilderFallback fallback, ElementId MaterialId, Boolean performHostUnitConversion)
   at Dynamo.Applications.ViewModel.RevitWatch3DViewModel.RevitGeometryObjectFromGraphicItem(IGraphicItem item, List`1& geoms)
   at Dynamo.Applications.ViewModel.RevitWatch3DViewModel.Draw()
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Dynamo.Models.HomeWorkspaceModel.Run()
   at Dynamo.Models.DynamoModel.ExecuteCommand(RecordableCommand command)
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by mjkkirschner** [comment]
@ParametricMonkey thanks - what version of revit (guessing 2016?) and what version of Dynamo? When does this happen?

**Comment by mjkkirschner** [comment]
also - do you have the material library installed with Revit?

**Comment by ParametricMonkey** [comment]
I'm using Revit 2015 with Dynamo 0.9. I have the Base, low and medium libraries installed fro Revit 2015

**Comment by johnpierson** [comment]
Closing as this issue is for an outdated version of Dynamo. If this persists in 2.0.x for you, please feel free to reopen and update accordingly.
