### ISSUE TITLE
Dynamo crashes when trying to zoom to fit

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/Dynamo#5705]
'NaN,NaN,NaN' is not a valid value for property 'To'.

   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValueInternal(DependencyProperty dp, Object value)
   at HelixToolkit.Wpf.SharpDX.CameraExtensions.AnimateTo(Camera camera, Point3D newPosition, Vector3D newDirection, Vector3D newUpDirection, Double animationTime)
   at HelixToolkit.Wpf.SharpDX.CameraExtensions.LookAt(Camera camera, Point3D target, Vector3D newLookDirection, Vector3D newUpDirection, Double animationTime)
   at HelixToolkit.Wpf.SharpDX.ViewportExtensions.ZoomExtents(Viewport3DX viewport, Point3D center, Double radius, Double animationTime)
   at HelixToolkit.Wpf.SharpDX.ViewportExtensions.ZoomExtents(Viewport3DX viewport, Rect3D bounds, Double animationTime)
   at HelixToolkit.Wpf.SharpDX.ViewportExtensions.ZoomExtents(Viewport3DX viewport, Double animationTime)
   at Dynamo.Controls.DynamoView.DynamoViewModelRequestViewOperation(ViewOperationEventArgs e)
   at Dynamo.ViewModels.DynamoViewModel.OnRequestViewOperation(ViewOperationEventArgs e)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

This happened when I pressed this button: 

![image](https://cloud.githubusercontent.com/assets/529781/11122765/9e4e9f24-892a-11e5-8820-dd35eebcbbc4.png)

**Comment by monikaprabhu** [comment]
@ksobon - Is this still reproducible. If so are you able to see geometry in the background ?
@jnealb - JFYI ...

**Comment by jnealb** [comment]
@ksobon Can we close this?

**Comment by ksobon** [comment]
yeah. I haven't been experiencing any issues for a while now. Thanks!
