### ISSUE TITLE
Crash when opening file saved with focus in a Code Block definition

### ISSUE THREAD

**Issue by pilcru** [DynamoDS/Dynamo#5720]
When a file is saved with the focus inside a Code Block, opening this file fails with the following error:

```
Error opening file: Object reference not set to an instance of an object.
System.NullReferenceException:
Object reference not set to an instance of an object.
   at Dynamo.Models.DynamoModel.UpdateModelValueImpl(UpdateModelValueCommand command)
   at Dynamo.Models.DynamoModel.ExecuteCommand(RecordableCommand command)
   at Dynamo.UI.Controls.CodeBlockEditor.CommitChanges(UndoRedoRecorder recorder)
   at Dynamo.UI.Controls.CodeBlockEditor.TextArea_LostFocus(Object sender, RoutedEventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.IsFocused_Changed(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at ICSharpCode.AvalonEdit.Editing.TextArea.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.ClearValueCommon(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata)
   at System.Windows.DependencyObject.ClearValue(DependencyPropertyKey key)
   at System.Windows.Input.FocusManager.OnFocusedElementChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.Input.FocusManager.SetFocusedElement(DependencyObject element, IInputElement value)
   at System.Windows.Input.KeyboardNavigation.UpdateFocusedElement(DependencyObject focusTarget)
   at System.Windows.FrameworkElement.OnGotKeyboardFocus(Object sender, KeyboardFocusChangedEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.KeyboardDevice.ChangeFocus(DependencyObject focus, Int32 timestamp)
   at System.Windows.Input.KeyboardDevice.TryChangeFocus(DependencyObject newFocus, IKeyboardInputProvider keyboardInputProvider, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   at System.Windows.Input.KeyboardDevice.Focus(DependencyObject focus, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   at System.Windows.Input.KeyboardDevice.Focus(IInputElement element)
   at System.Windows.UIElement.Focus()
   at System.Windows.Controls.TabItem.SetFocus()
   at System.Windows.Controls.TabControl.OnSelectionChanged(SelectionChangedEventArgs e)
   at System.Windows.Controls.Primitives.Selector.SelectionChanger.End()
   at System.Windows.Controls.Primitives.Selector.SelectionChanger.SelectJustThisItem(ItemInfo info, Boolean assumeInItemsCollection)
   at System.Windows.Controls.Primitives.Selector.OnSelectedIndexChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   at System.Windows.Data.BindingExpressionBase.Invalidate(Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.ClrBindingWorker.NewValueAvailable(Boolean dependencySourcesChanged, Boolean initialValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.ClrBindingWorker.OnSourcePropertyChanged(Object o, String propName)
   at System.Windows.WeakEventManager.ListenerList`1.DeliverEvent(Object sender, EventArgs e, Type managerType)
   at System.ComponentModel.PropertyChangedEventManager.OnPropertyChanged(Object sender, PropertyChangedEventArgs args)
   at System.ComponentModel.PropertyChangedEventHandler.Invoke(Object sender, PropertyChangedEventArgs e)
   at Microsoft.Practices.Prism.ViewModel.NotificationObject.RaisePropertyChanged(String propertyName)
   at Dynamo.ViewModels.DynamoViewModel._model_PropertyChanged(Object sender, PropertyChangedEventArgs e)
   at System.ComponentModel.PropertyChangedEventHandler.Invoke(Object sender, PropertyChangedEventArgs e)
   at Dynamo.Models.DynamoModel.OnPropertyChanged(String propertyName)
   at Dynamo.Models.DynamoModel.OpenFileFromPath(String xmlPath, Boolean forceManualExecutionMode)
   at Dynamo.Models.DynamoModel.ExecuteCommand(RecordableCommand command)
   at Dynamo.ViewModels.DynamoViewModel.Open(Object parameters)
```

This is using Dynamo 0.9.1.3162.

Instead Dynamo should either

- open the file, bring the focus back to the main canvas, notice the changes in the Code Block definition, and recompile as appropriate; or
- open the file with the focus still inside the Code Block, waiting for the user the trigger the update by clicking outside the Code Block.

**Comment by monikaprabhu** [comment]
@pilcru - Are you still seeing this in the daily builds? I tried on 0.9.1.3266 and cannot reproduce the same. Can you please send me the exact script that you are seeing the crash with?

**Comment by pilcru** [comment]
@monikaprabhu -- Yes I am still seeing this in 0.9.1.3302.

Here the exact steps I am following, I agree that it is a very specific process but it was quite disturbing the first time it happened to me:

1. create a new file
2. add a code block, write anything inside it
3. save the file with the focus still in the code block (i.e. the text cursor is blinking) (see 1st screenshot below)
4. reopen this file immediately from Dynamo, the console will display the error and the canvas will be blank. (see 2nd screenshot)

4b. If the Dynamo windows is closed and the file reopened after that, there is no error but all modifications in the code block are lost. (see 3rd screenshot)

4c. If the file is closed by clicking on the X of its tab, Dynamo returns the focus to the canvas, "compiles" the block and sees the changes, then asks the user to save those changes. This is probably what should happen in the other two cases as well.

Since this happens with a new file and any code block, there is probably no point in sending you a file; and as per 4b. you would not be able to see the error.

![whilesaving](https://cloud.githubusercontent.com/assets/2668286/11449753/cde46968-954f-11e5-8a26-fa879780e937.jpg)
3: Save with the focus in the code block.

![reopenwithoutclosingdynamo](https://cloud.githubusercontent.com/assets/2668286/11449754/cde7bd0c-954f-11e5-93c8-6af44bb0f4fa.jpg)
4: Reopen without closing Dynamo or the file tab.

![reopenafterclosingdynamo](https://cloud.githubusercontent.com/assets/2668286/11449755/cde8001e-954f-11e5-968e-ffb8d8337449.jpg)
4b: Reopen after closing Dynamo.

**Comment by monikaprabhu** [comment]
@pilcru - I can reproduce this if I use the keyboard shortcuts for saving (Ctrl+S)and opening (Ctrl+O) the file -  If I use cursor for saving the highlight is lost from CBN , in which case the crash is not opening. Nice catch ; Im tracking this at MAGN-9202.

**Comment by ikeough** [comment]
Internal issue has been closed. https://github.com/DynamoDS/Dynamo/pull/5833
