### ISSUE TITLE
Crash when undoing a Group command

### ISSUE THREAD

**Issue by brianringley** [DynamoDS/Dynamo#5725]
Dynamo 0.9.0.3067
Revit 2016
Windows 7

Grouped nodes then hit undo, Dynamo crashed.

Re-opened file and ungrouped instead, Dynamo crashed.

Details:
Unable to create face from spline : IG_SURFACE_BS3_COI_VERTS -- Surface or its approximation have coincident control points

   at Autodesk.LibG.Geometry.scale(Double scale_factor)
   at Autodesk.LibG.GeometryHost.Scale(Double amount)
   at Revit.GeometryConversion.UnitConverter.InHostUnits[T](T geometry)
   at Revit.GeometryConversion.ProtoToRevitMesh.ToRevitType(Surface srf, TessellatedShapeBuilderTarget target, TessellatedShapeBuilderFallback fallback, ElementId MaterialId, Boolean performHostUnitConversion)
   at Dynamo.Applications.ViewModel.RevitWatch3DViewModel.RevitGeometryObjectFromGraphicItem(IGraphicItem item, List`1& geoms)
   at Dynamo.Applications.ViewModel.RevitWatch3DViewModel.Draw()
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Dynamo.Models.HomeWorkspaceModel.Run()
   at Dynamo.Models.WorkspaceModel.RecordAndDeleteModels(List`1 models)
   at Dynamo.Models.DynamoModel.DeleteModelInternal(List`1 modelsToDelete)
   at Dynamo.Models.DynamoModel.DeleteModelImpl(DeleteModelCommand command)
   at Dynamo.Models.DynamoModel.ExecuteCommand(RecordableCommand command)
   at Dynamo.ViewModels.DynamoViewModel.Delete(Object parameters)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by brianringley** [comment]
After I added some more nodes to the graph this stopped happening.

**Comment by jnealb** [comment]
@brianringley Did you keep the dyn that gave the crash? That would be useful to us.

**Comment by brianringley** [comment]
Yes and I was able to replicate the error which is good (well, good for fixing the fact that this is bad).

To cause the crash group the nodes and then try to ungroup.

Let me know where I should send the Dynamo and linked Rhino files.

**Comment by jnealb** [comment]
@brianringley Neal.burnham@autodesk.com please.

**Comment by brianringley** [comment]
Sent. Thank you!

**Comment by jnealb** [comment]
@brianringley I have your code running correctly with 0.9.0.3067. Can you please give me the exact grouping, Ctrl-Z steps (which nodes etc)?

**Comment by jnealb** [comment]
@brianringley In Dynamo under View, Background 3d Preview, Available Previews can you please turn off the "Revit Background Preview" and see if this cures the issue?

**Comment by brianringley** [comment]
Dynamo 0.9.0.3067, Rhynamo 2015.9.231, Revit 2016, Windows 7

1) Place and connect nodes in following order: File Path, File.FromPath, OpenRhino3dmModel.Get_RhinoFile, RhinoObject.Get_RhinoObjectsByLayer, Code Block (to provide string input for layer name), RhinoTranslationtoDS.Rhino_NurbsSurfaceToDS

2) Select all nodes and Group

3a) Right-click Group object and select Ungroup - Dynamo crashes every time

3b) After Grouping hit Ctrl+Z - Dynamo crashes every time

**Comment by brianringley** [comment]
Yes turning off "Revit Background Preview" solves the problem - no more crashing. Thank you.

**Comment by jnealb** [comment]
@brianringley Thanks for your help - we are tracking this with MAGN-9085.

**Comment by brianringley** [comment]
Fantastic - I appreciate the quick assistance.

**Comment by jnealb** [comment]
@brianringley We have a fix for when "Revit Background Preview" is on, it is available in the daily builds post 12/21 (inclusive).

**Comment by kronz** [comment]
https://github.com/DynamoDS/DynamoRevit/pull/780
https://github.com/DynamoDS/DynamoRevit/pull/781
https://github.com/DynamoDS/DynamoRevit/pull/782
