### ISSUE TITLE
Wire remains after source node is deleted while connecting, Dynamo 0.9

### ISSUE THREAD

**Issue by archinate** [DynamoDS/Dynamo#5734]
I found an instance where wires remain after a node is deleted.  It happens if a node is deleted as you are dragging to connect a wire and delete the source node.  

While this would probably be a rare "user moment", I happened it across it recently when doing some testing.

To reproduce...have a node selected and drag a wire.
![image](https://cloud.githubusercontent.com/assets/1890663/11291778/453c9554-8f0a-11e5-827a-31add547a67d.png)

In the middle of the drag, delete the original node...  oops!
![image](https://cloud.githubusercontent.com/assets/1890663/11291799/7d68558a-8f0a-11e5-9395-2fc50fc7c037.png)

If this dangling wire connects into the other node, Dynamo will crash.
![image](https://cloud.githubusercontent.com/assets/1890663/11291806/97478fc0-8f0a-11e5-8074-45f873de631a.png)

**Comment by monikaprabhu** [comment]
@archinate - I'm able to reproduce the dangling connection , but could not see the crash( itried both on 0.9.0 and 0.9.1 daily build) - could you please help me with the details of the exception above. Please copy paste the text in the crash above.  
I've filed MAGN-9127 to track the dangling connection.

**Comment by archinate** [comment]
Crash report details are as follows....

Object reference not set to an instance of an object.

   at Dynamo.ViewModels.ConnectorViewModel..ctor(WorkspaceViewModel workspace, ConnectorModel model)
   at Dynamo.ViewModels.WorkspaceViewModel.Connectors_ConnectorAdded(ConnectorModel c)
   at Dynamo.Models.WorkspaceModel.OnConnectorAdded(ConnectorModel obj)
   at Dynamo.Models.NodeModel.OnConnectorAdded(ConnectorModel obj)
   at Dynamo.Models.NodeModel.PortConnected(PortModel port, ConnectorModel connector)
   at System.Action`2.Invoke(T1 arg1, T2 arg2)
   at Dynamo.Models.PortModel.OnPortConnected(ConnectorModel connector)
   at Dynamo.Models.PortModel.Connect(ConnectorModel connector)
   at Dynamo.Models.ConnectorModel.Connect(PortModel p)
   at Dynamo.Models.ConnectorModel.Make(NodeModel start, NodeModel end, Int32 startIndex, Int32 endIndex, Nullable`1 guid)
   at Dynamo.Models.DynamoModel.EndConnection(Guid nodeId, Int32 portIndex, PortType portType)
   at Dynamo.Models.DynamoModel.MakeConnectionImpl(MakeConnectionCommand command)
   at Dynamo.Models.DynamoModel.ExecuteCommand(RecordableCommand command)
   at Dynamo.ViewModels.WorkspaceViewModel.StateMachine.HandlePortClicked(PortViewModel portViewModel)
   at Dynamo.ViewModels.PortViewModel.Connect(Object parameter)
   at System.Windows.Interactivity.InvokeCommandAction.Invoke(Object parameter)
   at System.Windows.Interactivity.TriggerBase.InvokeActions(Object parameter)
   at Dynamo.UI.Views.HandlingEventTrigger.OnEvent(EventArgs eventArgs)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at DynamoSandbox.Program.MakeStandaloneAndRun(String commandFilePath, DynamoViewModel& viewModel)
   at DynamoSandbox.Program.Main(String[] args)

**Comment by monikaprabhu** [comment]
@archinate - Thanks I can reproduce the crash. Ive attached the log to - MAGN-9127

**Comment by ikeough** [comment]
Internal issue has been closed.
