### ISSUE TITLE
Error opening PythonScipt Node for edit

### ISSUE THREAD

**Issue by mkweaver** [DynamoDS/Dynamo#5894]
Dynamo 0.9.0.3067 running in Revit 2016
Dynamo crashes when I try to edit a PythonScript node, either by right-click and edit, or double-click.

Crash report:

Initialization of 'ICSharpCode.AvalonEdit.TextEditor' threw an exception.

   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at PythonNodeModelsWpf.ScriptEditorWindow..ctor(DynamoViewModel dynamoViewModel)
   at PythonNodeModelsWpf.PythonNodeViewCustomization.EditScriptContent()
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by monikaprabhu** [comment]
@mkweaver - I tried this on Revit R2 with Dynamo (0.9.0.3067) and cannot reproduce this crash. Can you give us more details on the script- is it crashing with any script? Have you installed ironpython? what was the version of it ?

**Comment by ke-yu** [comment]
@mkweaver, we can't reproduce the crash now. Please re-open this issue if you encounter same crash.
