### ISSUE TITLE
Index out of bounds causing unhandled exception in dynamo engine

### ISSUE THREAD

**Issue by jluebker** [DynamoDS/Dynamo#5920]
Index was outside the bounds of the array.

   at ProtoCore.Lang.ArrayUtilsForBuiltIns.Transpose(StackValue sv, Interpreter runtime)
   at ProtoCore.Lang.BuiltInFunctionEndPoint.Execute(Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.CallSite.ExecWithZeroRI(List`1 functionEndPoint, Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore, FunctionGroup funcGroup, SingleRunTraceData previousTraceData, SingleRunTraceData newTraceData)
   at ProtoCore.CallSite.Execute(List`1 functionEndPoint, Context c, List`1 formalParameters, List`1 replicationInstructions, StackFrame stackFrame, RuntimeCore runtimeCore, FunctionGroup funcGroup)
   at ProtoCore.CallSite.DispatchNew(Context context, List`1 arguments, List`1 partialReplicationGuides, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.DSASM.Executive.Callr(Int32 blockDeclId, Int32 functionIndex, Int32 classIndex, Boolean& explicitCall, Boolean isDynamicCall, Boolean hasDebugInfo)
   at ProtoCore.DSASM.Executive.CALLR_Handler(Instruction instruction)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   at ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Core.Threading.AsyncTask.Execute()

Somewhere in this block of nodes started causing a persistent crash of the dynamo engine. I've tested the graph with out this block and it works just fine.

![capture](https://cloud.githubusercontent.com/assets/4041748/12182230/8d5505c0-b54c-11e5-9d63-60a69909dfbf.PNG)

**Comment by ramramps** [comment]
@jluebker - Can you send the dyn file?

**Comment by jluebker** [comment]
[RegGeo5.zip](https://github.com/DynamoDS/Dynamo/files/81743/RegGeo5.zip)

**Comment by jluebker** [comment]
unfortunately it is using flux. so it makes it a bit difficult for someone else to trouble shoot precisely. i am making some progress though. it might have been something in the temp

**Comment by jluebker** [comment]
nm i figured out what it is... the flux nodes are breaking communication with the flux server causing it to crash....
