### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by deartotoro** [DynamoDS/Dynamo#5973]
Ver: 0.9.0.3067
OS: Win7

When I want to create the point metrx with code block node to process the point which is the data with  Surface.pointAtParameter node. Then Dynamo is crash.

The crash report is below:
The input argument "materialId" of function `anonymous-namespace'::TessellatedFace_constructor or one item in the collection is null at line 96 of file d:\sundial\2015_px64\source\api\revitapi\gensrc\APITessellatedShapeBuilder.cpp.
Parameter name: materialId

   at ?A0x91c5a93f.TessellatedFace_constructor(IList`1 outerLoopVertices, ElementId materialId)
   at Autodesk.Revit.DB.TessellatedFace..ctor(IList`1 outerLoopVertices, ElementId materialId)
   at Revit.GeometryConversion.ProtoToRevitMesh.ToRevitType(Surface srf, TessellatedShapeBuilderTarget target, TessellatedShapeBuilderFallback fallback, ElementId MaterialId, Boolean performHostUnitConversion)
   at Dynamo.Applications.ViewModel.RevitWatch3DViewModel.RevitGeometryObjectFromGraphicItem(IGraphicItem item, List`1& geoms)
   at Dynamo.Applications.ViewModel.RevitWatch3DViewModel.Draw()
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Dynamo.Models.HomeWorkspaceModel.Run()
   at Dynamo.Models.WorkspaceModel.RecordAndDeleteModels(List`1 models)
   at Dynamo.Models.DynamoModel.BeginConnection(Guid nodeId, Int32 portIndex, PortType portType)
   at Dynamo.Models.DynamoModel.MakeConnectionImpl(MakeConnectionCommand command)
   at Dynamo.Models.DynamoModel.ExecuteCommand(RecordableCommand command)
   at Dynamo.ViewModels.WorkspaceViewModel.StateMachine.HandlePortClicked(PortViewModel portViewModel)
   at System.Windows.Interactivity.TriggerBase.InvokeActions(Object parameter)
   at Dynamo.UI.Views.HandlingEventTrigger.OnEvent(EventArgs eventArgs)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by mjkkirschner** [comment]
This should be fixed in the daily builds and 91 I believe

**Comment by aparajit-pratap** [comment]
This was fixed in https://github.com/DynamoDS/DynamoRevit/pull/795 by @Randy-Ma but I was still able to repro it with Revit2017 when opening a Revit file of an older version. Details are tracked here: http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-9229

**Comment by aparajit-pratap** [comment]
I believe this has been fixed. Closing for now. @deartotoro feel free to reopen if still reproducible in the latest builds.
