### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by natethegrate1** [DynamoDS/Dynamo#5981]
Object reference not set to an instance of an object.

   at Dynamo.ViewModels.ConnectorViewModel..ctor(WorkspaceViewModel workspace, ConnectorModel model)
   at Dynamo.ViewModels.WorkspaceViewModel.Connectors_ConnectorAdded(ConnectorModel c)
   at Dynamo.Models.NodeModel.PortConnected(PortModel port, ConnectorModel connector)
   at Dynamo.Models.PortModel.Connect(ConnectorModel connector)
   at Dynamo.Models.ConnectorModel.Make(NodeModel start, NodeModel end, Int32 startIndex, Int32 endIndex, Nullable`1 guid)
   at Dynamo.Core.CustomNodeManager.Collapse(IEnumerable`1 selectedNodes, WorkspaceModel currentWorkspace, Boolean isTestMode, FunctionNamePromptEventArgs args)
   at Dynamo.ViewModels.WorkspaceViewModel.CollapseNodes(IEnumerable`1 selectedNodes)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jnealb** [comment]
@natethegrate1 Thanks for reporting this; can you provide some more detail please? Build version, Win version, dyn, workflow etc.

**Comment by mjkkirschner** [comment]
looks like this occurred when creating a custom node by collapsing some selected nodes.

**Comment by natethegrate1** [comment]
I was on build .8. Windows 7. I selected some nodes and was trying to
create a custom node from the edit-> create node from selection.


On Wed, Jan 20, 2016 at 17:56 Michael Kirschner <notifications@github.com>
wrote:

> looks like this occurred when creating a custom node by collapsing some
> selected nodes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DynamoDS/Dynamo/issues/5981#issuecomment-173247679>.
>
-- 
Nathan and Lindsay Moore
Don't worry! Be Happy!

**Comment by jnealb** [comment]
@natethegrate1 Thanks - do you know if this still happens with the 9.1 daily builds? We have made some fixes in the custom node functionality since the .8 version.

**Comment by natethegrate1** [comment]
I just updated last week so I think the issue is resolved

**Comment by jnealb** [comment]
Thanks; closing until further notice.
