### ISSUE TITLE
Issue with background viewer will not display

### ISSUE THREAD

**Issue by TJSimoneau** [DynamoDS/Dynamo#6005]
'NaN,NaN,NaN' is not a valid value for property 'From'.

   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValueInternal(DependencyProperty dp, Object value)
   at HelixToolkit.Wpf.SharpDX.CameraExtensions.AnimateTo(Camera camera, Point3D newPosition, Vector3D newDirection, Vector3D newUpDirection, Double animationTime)
   at HelixToolkit.Wpf.SharpDX.CameraExtensions.LookAt(Camera camera, Point3D target, Vector3D newLookDirection, Vector3D newUpDirection, Double animationTime)
   at HelixToolkit.Wpf.SharpDX.ViewportExtensions.ZoomExtents(Viewport3DX viewport, Point3D center, Double radius, Double animationTime)
   at HelixToolkit.Wpf.SharpDX.ViewportExtensions.ZoomExtents(Viewport3DX viewport, Rect3D bounds, Double animationTime)
   at HelixToolkit.Wpf.SharpDX.ViewportExtensions.ZoomExtents(Viewport3DX viewport, Double animationTime)
   at Dynamo.Controls.DynamoView.DynamoViewModelRequestViewOperation(ViewOperationEventArgs e)
   at Dynamo.ViewModels.DynamoViewModel.OnRequestViewOperation(ViewOperationEventArgs e)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jnealb** [comment]
@TJSimoneau Thanks for reporting this, can you please give us more detail: Dynamo build version, Windows version, workflow etc.

**Comment by TJSimoneau** [comment]
@jnealb Revit 2016, Dynamo 0.9, Win 10, hp zbook workstation laptop. I think the issue might be the integrated graphics. I read that laptops switch back and forth to conserve battery.

Could this be true?

**Comment by jnealb** [comment]
@TJSimoneau yes

**Comment by jnealb** [comment]
@TJSimoneau Are you still having this issue?

**Comment by ColinDayOrg** [comment]
@TJSimoneau If you are still having this issue please re-open it.
