### ISSUE TITLE
Bug Running Script

### ISSUE THREAD

**Issue by madeforworship** [DynamoDS/Dynamo#6080]
Got this error message when running the attached script.  I've tried in in 8.2 and a tweaked version for .9.0

The script is complex and takes some special settings in a project file to run properly which I don't have time ATM to post.  I'm hoping that the script plus the bug report may be enough to get to the issue.  If not, let me know and I can post more later.

[02 - Update Fire Tapes To Views.zip](https://github.com/DynamoDS/Dynamo/files/118116/02.-.Update.Fire.Tapes.To.Views.zip)

Index was outside the bounds of the array.

   at ProtoCore.DSASM.Executive.GetProcedureNode(Int32 blockId, Int32 classIndex, Int32 functionIndex)
   at ProtoCore.DSASM.Executive.UpdateMethodDependencyGraph(Int32 entry, Int32 procIndex, Int32 classIndex)
   at ProtoCore.DSASM.Executive.SetupEntryPoint()
   at ProtoCore.DSASM.Executive.SetupExecutive(Int32 exeblock, Int32 entry)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptTestRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   at ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Core.Threading.AsyncTask.Execute()

**Comment by dimven** [comment]
Looks like one of the built-in list nodes is not failing gracefully when you query an index greater than the list length? You could try deleting portions of the script and later on individual nodes to try and narrow down the culprit.

**Comment by johnpierson** [comment]
Closing as this issue is for an outdated version of Dynamo. If this persists in 2.0.x for you, please feel free to reopen and update accordingly.
