### ISSUE TITLE
Crash when running nurbsurface

### ISSUE THREAD

**Issue by voellwhiten** [DynamoDS/Dynamo#6136]
I am trying to generate a nurbsurface, have been working on it a bit, but now when I click run it will either freeze or give me this error message.

Using Dynamo 0.9.0.3067
Windows 7 Professional

See error report below:

x must be a finite number.
Parameter name: x

   at Autodesk.Revit.DB.XYZ..ctor(Double x, Double y, Double z)
   at Dynamo.Applications.ViewModel.RevitWatch3DViewModel.Tessellate(Curve curve)
   at Dynamo.Applications.ViewModel.RevitWatch3DViewModel.RevitGeometryObjectFromGraphicItem(IGraphicItem item, List`1& geoms)
   at Dynamo.Applications.ViewModel.RevitWatch3DViewModel.Draw()
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Dynamo.Models.HomeWorkspaceModel.Run()
   at Dynamo.Models.DynamoModel.ExecuteCommand(RecordableCommand command)
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by voellwhiten** [comment]
Here is an image:
![egg dynamo](https://cloud.githubusercontent.com/assets/17299527/13119119/437a9d90-d55c-11e5-90d9-792ac20025f9.png)

**Comment by mjkkirschner** [comment]
@voellwhiten as a workaround turn off the revit background preview

**Comment by voellwhiten** [comment]
Thanks, that works for now.

**Comment by monikaprabhu** [comment]
@voellwhiten- are you able to reproduce this on 0.9.1 ? I could not reproduce this. Some issues related to this crash are fixed, but some boundary conditions are yet to be addressed - So I would like you to try this on latest release 0.9.1

**Comment by voellwhiten** [comment]
I am also having some issues with upgrading files. I will get all nodes reading null sometimes (see image)
![image](https://cloud.githubusercontent.com/assets/17299527/13223354/c072cd2e-d938-11e5-94c6-c7ce0a4133de.png)
Or, the nodes will drag to move, but their image stays in the same place. This doesn't happen all the time, so i'll try to get a screenshot when it happens again.

It seems that part of the problem was that one of my ellipses was actually just 10 points at the same location, removing that ellipse seemed to make it a bit more stable.

**Comment by jnealb** [comment]
Is this with the released 9.1?

**Comment by voellwhiten** [comment]
It was built in 0.9.0, and I was having issues with it then. Now upgraded to 9.1 I am having some issues with all of my upgraded files. (rebuilding them from scratch in 9.1 seems to work fine)

**Comment by jnealb** [comment]
If you could isolate this out to a file that gives issues when upgraded that would be helpful for us.

**Comment by voellwhiten** [comment]
Its not happening as much today as it was yesterday... It works better when the Revit preview is turned off. 
[egg0.9.1.zip](https://github.com/DynamoDS/Dynamo/files/140932/egg0.9.1.zip)
