### ISSUE TITLE
Dynamo crash

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/Dynamo#6165]
## Dynamo version

0.9.1.3872 candidate release

## Operating system

Windows 7

## What did you do? 

Double click on canvas, type in two quotation marks to make a string inside of Code Block ("").

## What did you expect to see?

String

## What did you see instead?

Operation is not valid due to the current state of the object.

   at Dynamo.UI.Controls.PreviewControl.BeginExpandTransition()
   at Dynamo.UI.Controls.PreviewControl.BeginNextTransition()
   at System.Windows.Media.Animation.Clock.FireEvent(EventPrivateKey key)
   at System.Windows.Media.Animation.Clock.RaiseAccumulatedEvents()
   at System.Windows.Media.Animation.TimeManager.RaiseEnqueuedEvents()
   at System.Windows.Media.Animation.TimeManager.Tick()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.AnimatedRenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Crashed three times in a row so pretty reliably.

**Comment by ksobon** [comment]
cc @ikeough I am sorry to bother you, but this has actually been a nagging issue that I have been encountering all day in all sorts of situations. It seems like starting a Code Block node, while in Automatic mode, and trying to type stuff into it makes it crash. It's a little weird, but it did crash me out about 8 times today. I will update from Release Candidate to 0.9.1 stable and report back. Just heads up.

**Comment by mostaphaRoudsari** [comment]
Double clicking and typing ```.``` inside the code block also cause Dynamo crash. I have less problem with this in version 1.0

**Comment by mjkkirschner** [comment]
@aosyatnik
