### ISSUE TITLE
Dynamo crash (Object reference not set to an instance of an object)

### ISSUE THREAD

**Issue by KirillLukyanenko** [DynamoDS/Dynamo#6179]
## Dynamo version

v 0.9.1.4203

Dynamo crashes in different situations, I can't find steps to reproduce it. 
I think before this line we should add null check to fix it.
rootDataContext.IsOneRowContent = cachedLargeContent.Children.Count == 0;(PreviewControl.xaml.cs)
## Operating system

Windows 7

Object reference not set to an instance of an object.

   at Dynamo.UI.Controls.PreviewControl.<>c__DisplayClassc.<RefreshExpandedDisplay>b__b(AsyncTask m) in d:\Projects\Dynamo-RC0.9.1_master\src\DynamoCoreWpf\Views\Preview\PreviewControl.xaml.cs:line 401
   at Dynamo.Scheduler.AsyncTaskExtensions.<>c__DisplayClass5.<ThenPost>b__4(Object _) in d:\Projects\Dynamo-RC0.9.1_master\src\DynamoCore\Scheduler\AsyncTaskExtensions.cs:line 31
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunInternal(Window window)
   at DynamoSandbox.Program.MakeStandaloneAndRun(String commandFilePath, DynamoViewModel& viewModel) in d:\Projects\Dynamo-RC0.9.1_master\src\DynamoSandbox\Program.cs:line 41
   at DynamoSandbox.Program.Main(String[] args) in d:\Projects\Dynamo-RC0.9.1_master\src\DynamoSandbox\Program.cs:line 82

**Comment by monikaprabhu** [comment]
@ramramps, @jnealb - We have seen this happening , do you have a reproducible scenario for this ?

**Comment by KirillLukyanenko** [comment]
I only know that it happens when we open node preview, but sometimes.

**Comment by smangarole** [comment]
@KirillLukyanenko This issue is fixed in Dynamo 1.3. Please re-open if you can reproduce this issue.
Thanks.
