### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/Dynamo#6226]
## Dynamo version

0.9.1.4062

## Operating system

Windows 10

## What did you do? 

It crashes consistently when using list.Create in automatic mode. I would unplug the input to list.create to either move it to another port or simply disconnect it, but it crashes every time. 

## What did you expect to see?

i expected list.create to give me a warning that i have unplugged one of the inputs. 

## What did you see instead?

crash.

Object reference not set to an instance of an object.

   at Dynamo.UI.Controls.PreviewControl.<>c__DisplayClassc.<RefreshExpandedDisplay>b__b(AsyncTask m)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at DynamoSandbox.Program.MakeStandaloneAndRun(String commandFilePath, DynamoViewModel& viewModel)
   at DynamoSandbox.Program.Main(String[] args)

**Comment by jnealb** [comment]
@ksobon Thanks, we will investigate asap.

**Comment by jnealb** [comment]
We are tracking this with MAGN-9568 and a fix will be available soon.

**Comment by jnealb** [comment]
@ksobon If you are able to, can you please try the latest daily 1.0 build from 03/11? We think this is fixed.

**Comment by ksobon** [comment]
@jnealb I tried this on the 9.2 update that came out recently and it works fine. Thanks!
