### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by beardface00** [DynamoDS/Dynamo#6228]
## Dynamo version

0.9.1.4062
## Operating system

Windows 7, Revit 2016
## What did you do?

Was looking at the dropdown list of results from a Custom Node
## What did you expect to see?

The dropdown with list of results
## What did you see instead?

A crash report, which was:

Value cannot be null.
Parameter name: element

   at System.Windows.Media.VisualTreeHelper.GetParent(DependencyObject reference)
   at System.Windows.Controls.VirtualizingStackPanel.FindScrollOffset(Visual v)
   at System.Windows.Controls.VirtualizingStackPanel.OnAnchorOperation(Boolean isAnchorOperationPending)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by sefkani** [comment]
i had same crash report.

**Comment by tayday01** [comment]
I have the same report, everytime i try to scroll down in a watch list everything locks up, including revit. 

Value cannot be null.
Parameter name: element

   at System.Windows.Media.VisualTreeHelper.GetParent(DependencyObject reference)
   at System.Windows.Controls.VirtualizingStackPanel.FindScrollOffset(Visual v)
   at System.Windows.Controls.VirtualizingStackPanel.OnAnchorOperation(Boolean isAnchorOperationPending)
   at System.Windows.Controls.VirtualizingStackPanel.SetAnchorInformation(Boolean isHorizontalOffset)
   at System.Windows.Controls.VirtualizingStackPanel.<AnchoredInvalidateMeasure>b__3()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by smangarole** [comment]
@beardface00 This issue got fixed with Dynamo 1.3. Please re-open if you are able to reproduce.
Thanks.
