### ISSUE TITLE
Crash on adding a point.

### ISSUE THREAD

**Issue by ghost** [DynamoDS/Dynamo#6308]
## Dynamo version

0.9.1.4062

Could not load file or assembly 'file:///C:\Program Files\Dynamo 0.9\LibG.ProtoInterface.dll' or one of its dependencies. The system cannot find the file specified.

   at Autodesk.DesignScript.Geometry.HostFactory.get_Factory()
   at Autodesk.DesignScript.Geometry.Vector.XAxis()
   at Dynamo.Manipulation.MousePointManipulator.AssignInputNodes()
   at Dynamo.Manipulation.NodeManipulator.GenerateRenderPackages()
   at Dynamo.Manipulation.NodeManipulator.DrawManipulator()
   at Dynamo.Manipulation.NodeManipulator..ctor(NodeModel node, DynamoManipulationExtension manipulatorContext)
   at Dynamo.Manipulation.MousePointManipulatorFactory.Create(NodeModel node, DynamoManipulationExtension manipulatorContext)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dynamo.Manipulation.ZeroTouchManipulatorFactory.Create(NodeModel node, DynamoManipulationExtension manipulatorContext)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dynamo.Manipulation.ManipulatorDaemon.CreateManipulator(NodeModel model, DynamoManipulationExtension manipulatorContext)
   at Dynamo.Manipulation.DynamoManipulationExtension.CreateManipulators(IEnumerable`1 nodes)
   at Dynamo.Wpf.Extensions.ViewLoadedParams.OnSelectionCollectionChanged(Object sender, NotifyCollectionChangedEventArgs notifyCollectionChangedEventArgs)
   at System.Collections.Specialized.NotifyCollectionChangedEventHandler.Invoke(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.InsertItem(Int32 index, T item)
   at Dynamo.Models.DynamoModel.CreateNodeImpl(CreateNodeCommand command)
   at Dynamo.Models.DynamoModel.ExecuteCommand(RecordableCommand command)
   at Dynamo.ViewModels.SearchViewModel.OnSearchElementClicked(NodeModel nodeModel, Point position)
   at Dynamo.Wpf.ViewModels.NodeSearchElementViewModel.OnClicked()
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at DynamoSandbox.Program.MakeStandaloneAndRun(String commandFilePath, DynamoViewModel& viewModel)
   at DynamoSandbox.Program.Main(String[] args)
## Operating system

Windows 10 64 bit, bootcamp. 

## What did you do? 

Add Point ByCoordinates(x,y,z) from the menu.

## What did you expect to see?

A Point

## What did you see instead?

Crash

**Comment by aparajit-pratap** [comment]
@melkhaldi It looks like you're not able to load the required geometry modules into Dynamo. As for the crash, it has been fixed in https://github.com/DynamoDS/Dynamo/pull/6317. You should see it in the daily build however I think you'll still have trouble creating geometry. Let us know if the crash still persist.

**Comment by aparajit-pratap** [comment]
Tracked in http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-9588

**Comment by kronz** [comment]
Fix merged https://github.com/DynamoDS/Dynamo/pull/7029
