### ISSUE TITLE
e=Dynamo engine : Array dimensions exceeded supported range

### ISSUE THREAD

**Issue by jbak1972** [DynamoDS/Dynamo#6403]
## Dynamo version

0.9.2.4472
(Which version of Dynamo are you using? Go to Help > About if you're not sure.)
## Operating system

Windblows 10.
(e.g. Windows 7, Windows 8.1, etc)
## What did you do?

Created a beautiful infinite loop with "Automatic" turned on.
(Fill in here)
## What did you expect to see?

"Dynamo Not Respoding"
(Fill in here)
## What did you see instead?

Unhandled exception in Dynamo engine.  If you don't mind......
Array dimensions exceeded supported range.

   at System.Collections.Generic.List`1.set_Capacity(Int32 value)
   at System.Collections.Generic.List`1.EnsureCapacity(Int32 min)
   at System.Collections.Generic.List`1.Add(T item)
   at ProtoCore.Runtime.RuntimeMemory.PushFrame(Int32 size)
   at ProtoCore.Runtime.RuntimeMemory.PushFrameForGlobals(Int32 size)
   at ProtoCore.RuntimeCore.SetupForExecution(Core compileCore, Int32 globalStackFrameSize)
   at ProtoScript.Runners.LiveRunner.SetupRuntimeCoreForExecution(Boolean isCodeCompiled)
   at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   at ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()

The odd thing is I got rid of the offending code but it keeps popping up.  Have not tried restarting yet.  Also, I can't attach the offending file for some reason.  So here is a link to it. [file.zip](https://www.dropbox.com/s/u9ohquzvfcixi2g/TheSkyIsFalling.zip?dl=0)

(Fill in here)

**Comment by ke-yu** [comment]
Thanks @jbak1972 , I'll take a look. 

FYI: @monikaprabhu @riteshchandawar @jnealb

**Comment by johnpierson** [comment]
Closing as this issue is for an outdated version of Dynamo. If this persists in 2.0.x for you, please feel free to reopen and update accordingly.
