### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Lexiko** [DynamoDS/Dynamo#6448]
## Dynamo version

0.9.2
## Operating system

Win 7
## What did you do?

Run portion of the graph, extracting faces from Revit
## What did you expect to see?

Geometry
## What did you see instead?

Unable to transform the body! : ACIS_EXCEPTION_ACCESS_VIOLATION -- Access violation

   at Autodesk.LibG.Geometry.scale(Double scale_factor)
   at Autodesk.LibG.GeometryHost.Scale(Double amount)
   at Autodesk.DesignScript.Geometry.Geometry.Scale(Double amount)
   at Revit.GeometryConversion.UnitConverter.InHostUnits[T](T geometry)
   at Revit.GeometryConversion.ProtoToRevitMesh.ToRevitType(Surface srf, TessellatedShapeBuilderTarget target, TessellatedShapeBuilderFallback fallback, ElementId MaterialId, Boolean performHostUnitConversion)
   at Dynamo.Applications.ViewModel.RevitWatch3DViewModel.RevitGeometryObjectFromGraphicItem(IGraphicItem item, List`1& geoms)
   at Dynamo.Applications.ViewModel.RevitWatch3DViewModel.Draw(NodeModel node)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Dynamo.Models.DynamoModel.OnEvaluationCompleted(Object sender, EvaluationCompletedEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Dynamo.Graph.Workspaces.HomeWorkspaceModel.OnEvaluationCompleted(EvaluationCompletedEventArgs e)
   at Dynamo.Models.DynamoModel.RunCancelImpl(RunCancelCommand command)
   at Dynamo.Models.DynamoModel.ExecuteCommand(RecordableCommand command)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by aparajit-pratap** [comment]
@Lexiko could you give details of the steps you followed to encounter this crash. A DYN file would be really helpful.

**Comment by smangarole** [comment]
We have released a new version of Dynamo since this issue was opened. The issue has been waiting for feedback for almost a year. Closing due to these reasons. Please reopen if this issue resurfaces.
