### ISSUE TITLE
reproduceable crash on loading packages

### ISSUE THREAD

**Issue by StevenRowland** [DynamoDS/Dynamo#6451]
## Dynamo version

0.9.2

## Operating system

Windows 7

## What did you do? 

setting package path

## What did you expect to see?

explorer

## What did you see instead?

Det går inte att hitta filen. (Exception from HRESULT: 0x80070002)

   at Dynamo.UI.DynamoFolderBrowserDialog.ShowDialog()
   at Dynamo.Wpf.Views.PackageManager.PackagePathView.OnRequestShowFileDialog(Object sender, EventArgs e)
   at Dynamo.ViewModels.PackagePathViewModel.OnRequestShowFileDialog(Object sender, PackagePathEventArgs e)
   at Dynamo.ViewModels.PackagePathViewModel.ShowFileDialog(PackagePathEventArgs e)
   at Dynamo.ViewModels.PackagePathViewModel.UpdatePathAt(Int32 index)
   at Dynamo.Wpf.Views.PackageManager.PackagePathView.OnEllipsisClicked(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by ke-yu** [comment]
@StevenRowland , which package you try to load?

**Comment by StevenRowland** [comment]
I was correcting the path to our custom node library. An admin had moved the folder and the path was no longer existing, so i clicked the ... to update to the new network location. Crash.

**Comment by NightHawk-Michael** [comment]
https://github.com/DynamoDS/Dynamo/pull/6946/files
This is the PR for the fix of this issue.
