### ISSUE TITLE
Crash Report for 1.0 stable build

### ISSUE THREAD

**Issue by dimven** [DynamoDS/Dynamo#6663]
## Dynamo version

1.0.0.1180 running in sandbox mode, Automatic execution

## Operating system

Windows 7

## What did you do? 

Copied, deleted and pasted a bunch of nodes

## What did you expect to see?

Nothing out of the ordinary.

## What did you see instead?
Multiple warning windows constantly propping up. Had to forcefully end the Dynamo instance.
![2016-05-24_11-29-06](https://cloud.githubusercontent.com/assets/7148394/15491452/16c1c448-21a3-11e6-98c9-946726172b27.png)
After opening the file from the backup, all the nodes on canvas were missing their wires.

```
Runtime exception occured. The Type of StackValue is not Integer

   at ProtoCore.DSASM.StackValue.get_IntegerValue()
   at ProtoCore.DSASM.Executive.GetCurrentScope(Int32& classIndex, Int32& functionIndex)
   at ProtoCore.DSASM.Executive.DEP_Handler(Instruction instruction)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
   at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   at ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()
```
![2016-05-24_11-36-23](https://cloud.githubusercontent.com/assets/7148394/15491498/8ae6e7e0-21a3-11e6-8eda-6dbb43c8269f.png)

This is very easy to replicate with the backup file. I'm attaching it as a *.txt, just rename it back to *.dyn
[backup - issue 6663.txt](https://github.com/DynamoDS/Dynamo/files/278710/backup.-.issue.6663.txt)

**Comment by monikaprabhu** [comment]
@dimven - thanks for reporting this issue. Please look at the following workaround.
@sharadkjaiswal thanks for help me workaround.
![listoperation](https://cloud.githubusercontent.com/assets/5218721/15606286/de49c64a-243d-11e6-822c-77812f2efb48.png)

**Comment by monikaprabhu** [comment]
MAGN-10162 is field to track this issue. @ke-yu  - please take look at this next sprint.

**Comment by dimven** [comment]
Hi @monikaprabhu, 
No need for a workaround. The nodes are working fine. This seems more like a canvas composition issue.

**Comment by monikaprabhu** [comment]
@dimven - if I remove watch node from your  graph, I cannot reproduce the crash. Can you please try at your end and let me know.

**Comment by dimven** [comment]
Thanks for your help but watch nodes don't seem to make a difference. I get the same thing. I also tried it on a different computer. Here's a screen capture of the result:

https://youtu.be/66sB7Vxzg6k

https://youtu.be/duSYHY-gwu0

**Comment by monikaprabhu** [comment]
@dimven -  I'm able reproduce the crash in https://youtu.be/duSYHY-gwu0- The issue is still with reorder node. Reorder node crashes with index - 1, which is why the first crash happens, once the crash has happened other operations may fail based on this crash. If I remove reorder node , the pated graph is correct 
![crash1](https://cloud.githubusercontent.com/assets/5218721/15641747/652dff30-2675-11e6-8cbe-13eaa27add60.png)
Without reorder
![nocrash](https://cloud.githubusercontent.com/assets/5218721/15641764/8757b466-2675-11e6-9cd1-9dea44e12664.png)

**Comment by dimven** [comment]
@monikaprabhu I think you nailed it - Reorder seems to be the root cause for these warnings :)
It should be easy to test for a -1 input inside the Reorder method and prevent this happening in the future.

But the bigger issue here is that just a single node failure can make the whole graph permanently unstable, until you restart the Dynamo instance. It would be great if the team could study this issue in greater detail.

**Comment by monikaprabhu** [comment]
@dimven - Thanks for reporting it. I agree that one node should not cause so much of damage to user workflow. Sorry for the inconvenience. We will try to find the root cause of wrong execution and try to fix it. @ke-yu JFYI...
