### ISSUE TITLE
Code Block error

### ISSUE THREAD

**Issue by garciadelcastillo** [DynamoDS/Dynamo#6709]
## Dynamo version

1.0.0.1126

## Operating system

Windows 7

## What did you do? 

In a code block, I want to create a grid of points with random heights. When the Z property of the point List is associated to a list of doubles (with the same structure), Dynamo crashes.

## What did you expect to see?

The Z values associated to the list of double values generated. If this wasn't possible, I would expect a thrown error on the node. 

## What did you see instead?

Program crash

## Further details

This is the Code Block that fails:

    // node inputs
    wid = width;
    len = length;
    maxHeight = maxHeight;
    uCount = uCount;
    vCount = vCount;

    ptCount = uCount * vCount;
    randHeights = List.Chop(maxHeight * Math.RandomList(ptCount), vCount);

    ptsOnSrf = Point.ByCoordinates( (0..wid..#uCount)<1>, (0..len..#vCount)<2>);
    // ptsOnSrf.Z = randHeights;  // uncomment this line to crash Dynamo...

Find file attached. [points_random_heights.zip](https://github.com/DynamoDS/Dynamo/files/305674/points_random_heights.zip)

**Comment by mjkkirschner** [comment]
you cannot modify the z property of the point, this is a getter, not a setter.

Of course a crash should not occur, what is the stack trace?

**Comment by garciadelcastillo** [comment]
I believe it was this:

Exception of type 'ProtoCore.Exceptions.CompilerInternalException' was thrown.

   at ProtoCore.Utils.NodeUtils.Clone(AssociativeNode rhsNode)
   at Dynamo.Graph.Nodes.CodeBlockNodeModel.GetAstIdentifierForOutputIndexInternal(Int32 portIndex, Boolean forRawName)
   at CoreNodeModelsWpf.Nodes.WatchNodeViewCustomization.OnPortConnected(PortModel port, ConnectorModel connectorModel)
   at System.Action`2.Invoke(T1 arg1, T2 arg2)
   at Dynamo.Graph.Nodes.NodeModel.RaisePortConnectedEvent(PortModel port, ConnectorModel connector)
   at Dynamo.Graph.Nodes.PortModel.OnPortConnected(ConnectorModel connector)
   at Dynamo.Graph.Nodes.PortModel.Connect(ConnectorModel connector)
   at Dynamo.Graph.Connectors.ConnectorModel.Connect(PortModel p)
   at Dynamo.Graph.Connectors.ConnectorModel.Make(NodeModel start, NodeModel end, Int32 startIndex, Int32 endIndex, Nullable`1 guid)
   at Dynamo.Graph.Nodes.CodeBlockNodeModel.LoadAndCreateConnectors(OrderedDictionary inportConnections, OrderedDictionary outportConnections)
   at Dynamo.Graph.Nodes.CodeBlockNodeModel.SetCodeContent(String newCode, ElementResolver workspaceElementResolver)
   at Dynamo.Graph.Nodes.CodeBlockNodeModel.UpdateValueCore(UpdateValueParams updateValueParams)
   at Dynamo.Graph.Workspaces.WorkspaceModel.UpdateModelValue(IEnumerable`1 modelGuids, String propertyName, String value)
   at Dynamo.Models.DynamoModel.UpdateModelValueImpl(UpdateModelValueCommand command)
   at Dynamo.Models.DynamoModel.ExecuteCommand(RecordableCommand command)
   at Dynamo.UI.Controls.CodeBlockEditor.CommitChanges(UndoRedoRecorder recorder)
   at Dynamo.UI.Controls.CodeBlockEditor.OnCommitChange()
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.IsFocused_Changed(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at ICSharpCode.AvalonEdit.Editing.TextArea.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.ClearValueCommon(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata)
   at System.Windows.DependencyObject.ClearValue(DependencyPropertyKey key)
   at System.Windows.Input.FocusManager.OnFocusedElementChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.Input.FocusManager.SetFocusedElement(DependencyObject element, IInputElement value)
   at System.Windows.Input.KeyboardNavigation.UpdateFocusedElement(DependencyObject focusTarget)
   at System.Windows.FrameworkElement.OnGotKeyboardFocus(Object sender, KeyboardFocusChangedEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.KeyboardDevice.ChangeFocus(DependencyObject focus, Int32 timestamp)
   at System.Windows.Input.KeyboardDevice.TryChangeFocus(DependencyObject newFocus, IKeyboardInputProvider keyboardInputProvider, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   at System.Windows.Input.KeyboardDevice.Focus(DependencyObject focus, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   at System.Windows.Input.KeyboardDevice.Focus(IInputElement element)
   at System.Windows.UIElement.Focus()
   at Dynamo.Controls.DynamoView.OnRequestReturnFocusToView()
   at Dynamo.ViewModels.DynamoViewModel.OnRequestReturnFocusToView()
   at Dynamo.ViewModels.DynamoViewModel.ExecuteCommand(RecordableCommand command)
   at Dynamo.ViewModels.WorkspaceViewModel.StateMachine.InitiateWindowSelectionSequence()
   at Dynamo.ViewModels.WorkspaceViewModel.StateMachine.HandleLeftButtonDown(Object sender, MouseButtonEventArgs e)
   at Dynamo.Views.WorkspaceView.OnMouseLeftButtonDown(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at DynamoStudio.DynamoCoreSetup.RunApplication(Application app)

**Comment by ke-yu** [comment]
I fixed the crash in #6718. There is a run-time warning when calling `ptsOnSrf.Z = randHeights`, somehow this warning is not bubbled up, I'll fix it later on.
