### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by dago2015** [DynamoDS/Dynamo#6740]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.0

## Operating system

(e.g. Windows 7)

## What did you do? 

hit run and it crashed.

(Value cannot be null.
Parameter name: element

   at System.Windows.Media.VisualTreeHelper.GetParent(DependencyObject reference)
   at System.Windows.Controls.VirtualizingStackPanel.FindScrollOffset(Visual v)
   at System.Windows.Controls.VirtualizingStackPanel.OnAnchorOperation(Boolean isAnchorOperationPending)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

)

## What did you expect to see?

(The attached file has a group of nodes in bright pink. I think the problem is that when a null is input into this region the program crashes.)

## What did you see instead?

(Fill in here)

[high roof.txt](https://github.com/DynamoDS/Dynamo/files/317027/high.roof.txt)

**Comment by ke-yu** [comment]
Hi @dago2015 , any more details?

**Comment by ke-yu** [comment]
Hi @dago2015 do you have step to reproduce this crash?

**Comment by ke-yu** [comment]
Looks duplicate issue #6570 : same call stack, crash on `VirtualizingStackPanel`
