### ISSUE TITLE
Dynamo Crashes with the message

### ISSUE THREAD

**Issue by cahitokten** [DynamoDS/Dynamo#6925]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.
## Dynamo version

1.1.0.2024
(Which version of Dynamo are you using? Go to Help > About if you're not sure.)
## Operating system

Windows 7
(e.g. Windows 7, Windows 8.1, etc)
## What did you do?

I was trying to change the workset for lighting fixtures
(Fill in here)
## What did you expect to see?

![workset change](https://cloud.githubusercontent.com/assets/9383710/17049770/2a823c52-4fe7-11e6-8403-c25681aa76d3.png)

(Fill in here)
## What did you see instead?

Index was outside the bounds of the array.

   at ProtoCore.DSASM.Executive.GetProcedureNode(Int32 blockId, Int32 classIndex, Int32 functionIndex)
   at ProtoCore.DSASM.Executive.UpdateMethodDependencyGraph(Int32 entry, Int32 procIndex, Int32 classIndex)
   at ProtoCore.DSASM.Executive.SetupExecutive(Int32 exeblock, Int32 entry)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   at ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.AsyncTask.Execute()

**Comment by ramramps** [comment]
@cahitokten I believe this is fixed. can you please confirm?
