### ISSUE TITLE
exception on drop down initialization

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/Dynamo#7239]
## Dynamo version

1.2

## Operating system

Windows 7

## What did you do? 

Tried making a dropdown node. 

## What did you expect to see?

Dropdown node.

## What did you see instead?

Crash
```
    [NodeName("Object Types")]
    [NodeCategory("Archi-lab_MantisShrimp.Rhinoceros.Properties")]
    [NodeDescription("Retrieve all available Rhino Object Types.")]
    [IsDesignScriptCompatible]
    public class msObjectTypesUI : DSDropDownBase
    {
        private const string NO_FAMILY_TYPES = "No types were found.";

        public msObjectTypesUI() : base("ObjectType") { }

        public static msTypes.msObjectTypes dTypes = new msTypes.msObjectTypes();

        protected override SelectionState PopulateItemsCore(string currentSelection)
        {
            Items.Clear();

            Dictionary<string, string> d = new Dictionary<string, string>(dTypes.Types);

            if (d.Count == 0)
            {
                Items.Add(new DynamoDropDownItem(NO_FAMILY_TYPES, null));
                SelectedIndex = 0;
                return SelectionState.Done;
            }

            foreach (KeyValuePair<string, string> pair in d)
            {
                Items.Add(new DynamoDropDownItem(pair.Key, pair.Value));
            }
            Items = Items.OrderBy(x => x.Name).ToObservableCollection();
            return SelectionState.Restore;
        }

        public override IEnumerable<AssociativeNode> BuildOutputAst(List<AssociativeNode> inputAstNodes)
        {
            if (Items.Count == 0 ||
                Items[0].Name == NO_FAMILY_TYPES ||
                SelectedIndex == -1)
            {
                return new[] { AstFactory.BuildAssignment(GetAstIdentifierForOutputIndex(0), AstFactory.BuildNullNode()) };
            }

            var args = new List<AssociativeNode>
            {
                AstFactory.BuildStringNode(((string) Items[SelectedIndex].Name))
            };

            var func = new Func<string, string>(msTypes.msObjectTypes.byName);
            var functionCall = AstFactory.BuildFunctionCall(func, args);

            return new[] { AstFactory.BuildAssignment(GetAstIdentifierForOutputIndex(0), functionCall) };
        }
    }
```
This throw this exception: 

The type initializer for 'MantisShrimpUI.msObjectTypesUI' threw an exception.

   at MantisShrimpUI.msObjectTypesUI..ctor()
   at lambda_method(Closure )
   at Dynamo.Wpf.ViewModels.NodeSearchElementViewModel.OnClicked()
   at Dynamo.UI.Controls.ClassInformationView.ExecuteSearchElement(ListBoxItem listBoxItem)
   at Dynamo.UI.Controls.ClassInformationView.OnMouseLeftButtonUp(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnPreviewMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.ContentElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at DynamoSandbox.DynamoCoreSetup.RunApplication(Application app)

**Comment by ksobon** [comment]
Well, as it turns out this was a weird issue. What happened was that somewhere between a package manager and customization dll for icons, an information about this node was stored and would not reload even when a dll that hosted code for this node was replaced with a new one. I tried everything from renaming the class to renaming the assembly, it would not reset its information about the node that "was supposed to be there" but code for it no longer existed so it kept throwing that exception. Now, I ended up just deleting the whole package, making a new one from scratch, adding new DLLs and customization files and now, It all works like its supposed to. I am not sure anyone will be able to re-create this so I am going to close this.
