### ISSUE TITLE
Crash when trying to edit a Python Node

### ISSUE THREAD

**Issue by xduckyy** [DynamoDS/Dynamo#7290]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.
## Dynamo version

Dynamo Core & Revit 1.2.0.2690
## Operating system

Windows 7
## What did you do?

Tried to edit a Python script node within a custom node.  I had recently updated to the most recent IronPython (version 2.7.6.3) and now I can't edit my python nodes
## What did you expect to see?

To be able to edit the python script in the node
## What did you see instead?

Dynamo has crashed.  Error:

"Could not load file or assembly 'IronPython, Version=2.7.0.40, Culture=neutral, PublicKeyToken=7f709c5b713576e1' or one of its dependencies. The system cannot find the file specified.

   at Dynamo.Python.IronPythonCompletionProvider..ctor()
   at PythonNodeModelsWpf.ScriptEditorWindow..ctor(DynamoViewModel dynamoViewModel)
   at PythonNodeModelsWpf.PythonNodeViewCustomization.EditScriptContent()
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)"

**Comment by sharadkjaiswal** [comment]
@xduckyy can you please check if IronPython 2.7 is installed on your system and you don't have higher version of python?

**Comment by johnpierson** [comment]
This issue was reported for version 1.x. Can you confirm for us if this is still an issue for you in Dynamo 2.0.x?

**Comment by xduckyy** [comment]
Nope, I can edit Python nodes in Custom nodes in 2.0.1 without crashing

**Comment by johnpierson** [comment]
@xduckyy Thanks for the update!
