### ISSUE TITLE
Crash Reading a Text file

### ISSUE THREAD

**Issue by madeforworship** [DynamoDS/Dynamo#7296]
## Dynamo version

1.2
## Operating system

Windows 10 Pro
## What did you do?

Renamed a .dyn to .txt to try to read it as a text file in dynamo
## What did you expect to see?

I expected to see text, since I can open the dyn definition in notepad.
## What did you see instead?

A crash, with the following message.

The managed object is not valid.

   at Autodesk.Revit.DB.Transaction.GetStatus()
   at RevitServices.Transactions.AutomaticTransactionStrategy.ForceCloseTransaction(TransactionHandle handle)
   at Dynamo.Applications.Models.RevitDynamoModel.OnEvaluationCompleted(Object sender, EvaluationCompletedEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Dynamo.Graph.Workspaces.HomeWorkspaceModel.OnEvaluationCompleted(EvaluationCompletedEventArgs e)
   at Dynamo.Models.DynamoModel.RunCancelImpl(RunCancelCommand command)
   at Dynamo.Models.DynamoModel.ExecuteCommand(RecordableCommand command)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

![dynamo crash](https://cloud.githubusercontent.com/assets/10763679/19663237/c5581928-9a00-11e6-8b8d-5d1ef1649073.png)

**Comment by QilongTang** [comment]
It does not seem to be a generic issue on XML file renamed to *.txt from my testing.

Result in latest daily build candidate:
![image](https://user-images.githubusercontent.com/3942418/31690335-6eea01d0-b360-11e7-9b9f-51f721a3e12a.png)

Result in Dynamo release Build 1.3.2:
![image](https://user-images.githubusercontent.com/3942418/31690476-d35b6226-b360-11e7-9fc8-fd501d2d3c17.png)

Closing for now, but if you could reproduce the issue in 1.3.2, please re-open the issue, attach the file and let us know.
