### ISSUE TITLE
Crash at startup Dynamo 

### ISSUE THREAD

**Issue by Legantmar** [DynamoDS/Dynamo#7315]
## Dynamo version

(Dynamo 1.1 or Dynamo 1.2.)

## Operating system

Windows 8.1

## What did you do? 

I try start Dynamo (sandbox or inside Revit)

## What did you expect to see?

Start sanbox - nothing
Start Dynamo inside Revit - crash and error below:

Ошибка десериализации объекта типа CSharpAnalytics.Sessions.SessionState. Имеется несколько корневых элементов. Строка 1, позиция 2.

   в System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   в System.Runtime.Serialization.XmlObjectSerializer.ReadObject(XmlDictionaryReader reader)
   в CSharpAnalytics.Serializers.AppDataContractSerializer.<Restore>d__0`1.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в CSharpAnalytics.WinFormAutoMeasurement.<Load>d__0`1.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в CSharpAnalytics.BaseAutoMeasurement.<Start>d__0.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jbenoit44** [comment]
seems I have similar issue

There was an error deserializing the object of type CSharpAnalytics.Sessions.SessionState. There are multiple root elements. Line 1, position 2.

   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObject(XmlDictionaryReader reader)
   at CSharpAnalytics.Serializers.AppDataContractSerializer.<Restore>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CSharpAnalytics.WinFormAutoMeasurement.<Load>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Analytics.NET.Google.WinNativeAutoMeasurement.<TryLoad>d__6`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Analytics.NET.Google.WinNativeAutoMeasurement.<Load>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CSharpAnalytics.BaseAutoMeasurement.<Start>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jbenoit44** [comment]
revit 2016 or 2017 or 2017.1. crashes all the time. dynamo 1.1 or 1.2
try to uninstall revit 2017. no luck.

**Comment by Legantmar** [comment]
I I decided my problem:
I removed all dynamo
I removed folder C:\Users\..\AppData\Roaming\Analytics
and removed folder C:\Program files\Autodesk\React teach view
install dynamo 1.2

**Comment by Legantmar** [comment]
I bring greetings to google analytics code inside Dynamo ))) (spying on us)

**Comment by jnealb** [comment]
You can turn off Analytics from Settings if you like.

**Comment by Legantmar** [comment]
it is turn off before )))

**Comment by jnealb** [comment]
This is tracked with MAGN-5263.

**Comment by sharadkjaiswal** [comment]
This particular issue has been fixed in latest 1.2.3 build. Please let me know if you can still reproduce this issue.
