### ISSUE TITLE
Dynamo crash on Import Library

### ISSUE THREAD

**Issue by garciadelcastillo** [DynamoDS/Dynamo#7331]
## Dynamo version

Dynamo Studio 2016 0.9.2.4461

## Operating system

Windows 8.1

## What did you do? 

Tried to import a dll that I am working on (DMX control for Andy's AU Pavillion ;)

## What did you expect to see?

The library loaded and the components showing. 

## What did you see instead?

The first time you load it, nothing happens and no library shows up. The crash happens the second time you try loading the same library. It is worth noting that it was working initially (I am unsure what I did/change so that it stopped working). It is also worth noting that I have tried loading a library that is confirmed to work in Dynamo (BRobot-for-Dynamo), with the ssame results. 

The trace:

Exception of type 'ProtoCore.Exceptions.CompilerInternalException' was thrown.

   at ProtoCore.AssociativeEngine.Utils.IsGlobalScopeDirty(Executable exe)
   at ProtoScript.Runners.LiveRunner.ApplyUpdate()
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(String code)
   at ProtoScript.Runners.LiveRunner.UpdateCmdLineInterpreter(String code)
   at Dynamo.Engine.EngineController.LibraryLoaded(Object sender, LibraryLoadedEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Dynamo.Engine.LibraryServices.OnLibraryLoaded(LibraryLoadedEventArgs e)
   at Dynamo.Engine.LibraryServices.ImportLibrary(String library)
   at Dynamo.ViewModels.DynamoViewModel.ImportLibrary(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at DynamoPro.Program.Main(String[] args)

**Comment by mjkkirschner** [comment]
@garciadelcastillo what errors are in the console the first time you try importing?

**Comment by mjkkirschner** [comment]
also, - if you can share the dll or repo (email is fine) I can debug faster, didn't you write Brobot on Dynamo 1.x? I would not expect nodes to load correctly in Dynamo .92 that you wrote on top of 1.x core.

**Comment by sharadkjaiswal** [comment]
@garciadelcastillo looks like you are on a very old version of Dynamo, can you please try on latest version of Dynamo from www.dynamobim.com?

**Comment by garciadelcastillo** [comment]
Yes, the problem is solved updating to Dynamo 2017 1.1.0.2093. Thanks guys ;)

**Comment by jnealb** [comment]
@garciadelcastillo You may want to go all the way to 1.2?
