### ISSUE TITLE
Dynamo crashing when closing

### ISSUE THREAD

**Issue by NIFWK** [DynamoDS/Dynamo#7496]
## Dynamo version

1.2.1

## Operating system

Windows 7

## What did you do? 

Closing dynamo.

## What did you expect to see?

Dynamo closed.

## What did you see instead?

The managed object is not valid.

   at Autodesk.Revit.DB.Transaction.GetStatus()
   at RevitServices.Transactions.AutomaticTransactionStrategy.ForceCloseTransaction(TransactionHandle handle)
   at Dynamo.Applications.Models.RevitDynamoModel.OnEvaluationCompleted(Object sender, EvaluationCompletedEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Dynamo.Graph.Workspaces.HomeWorkspaceModel.OnEvaluationCompleted(EvaluationCompletedEventArgs e)
   at Dynamo.Models.DynamoModel.RunCancelImpl(RunCancelCommand command)
   at Dynamo.Models.DynamoModel.ExecuteCommand(RecordableCommand command)
   at Dynamo.Wpf.ViewModels.RunSettingsViewModel.Model_PropertyChanged(Object sender, PropertyChangedEventArgs e)
   at System.ComponentModel.PropertyChangedEventHandler.Invoke(Object sender, PropertyChangedEventArgs e)
   at Dynamo.Core.NotificationObject.RaisePropertyChanged(String propertyName)
   at Dynamo.Models.RunSettings.Reset()
   at Dynamo.Graph.Workspaces.HomeWorkspaceModel.Clear()
   at Dynamo.Models.DynamoModel.ClearCurrentWorkspace()
   at Dynamo.ViewModels.DynamoViewModel.ClearHomeWorkspaceInternal()
   at Dynamo.ViewModels.DynamoViewModel.CloseHomeWorkspace(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by sharadkjaiswal** [comment]
@NIFWK , sorry to hear that Dynamo Crashed, can you please help us with steps to reproduce this crash? Before closing Dynamo, what are the last few operations did you do? Did you close Revit or close Dynamo? If you directly closed Revit, was Dynamo still doing any evaluation?

**Comment by NIFWK** [comment]
1. Open Revitproject
2. Open dynamo
3. Open the basics01 sample
4. Closing the sample tab, and dynamo crashed.

It all started when i tried to run a .dyn file i created on my own for changing limit offsets on rooms. Thats where i realised something was wrong with the "all elements of category"-node. Next up i tried tracking down the issue, and testing the the sample files. Everything end up with a dynamo crash.

![dynamo issue](https://cloud.githubusercontent.com/assets/25051214/21840012/405abeec-d7db-11e6-9f58-5993fb22f1fc.png)

**Comment by sharadkjaiswal** [comment]
Thanks @NIFWK we will look at it. @monikaprabhu, please help me get a reproducible step. This is being tracked as MAGN-10582

**Comment by NIFWK** [comment]
Seems like a Dynamo reinstall fixed the issue.
What triggered the issue in the first place is unknown.

All .dyn files running as intended, and the "All elements of category" works again.

Thanks.
