### ISSUE TITLE
Error Report 20170423

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#7814]
## Dynamo version

1.3.0.875

## Operating system

Windows 10

## What did you do? 

Pasted code from one code block to another. Code replaced was within a function.

## What did you expect to see?

An error warning, at the most.

## What did you see instead?
![error-20170423](https://cloud.githubusercontent.com/assets/5621624/25312665/dfa33d38-283c-11e7-9a84-d940d6f2d4a3.png)

```
Exception of type 'ProtoCore.Exceptions.CompilerInternalException' was thrown.

   at ProtoCore.Core.BfsBuildSequenceTable(CodeBlock codeBlock, SymbolTable[] runtimeSymbols)
   at ProtoCore.Core.BfsBuildSequenceTable(CodeBlock codeBlock, SymbolTable[] runtimeSymbols)
   at ProtoCore.Core.GenerateExecutable()
   at ProtoScript.Runners.ProtoScriptRunner.CompileAndGenerateExe(List`1 astList, Core compileCore, Context context)
   at ProtoScript.Runners.LiveRunner.Compile(List`1 astList, Core targetCore)
   at ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()
```

**Comment by vykrum** [comment]
Again, while altering functions in code block
```
Exception of type 'ProtoCore.Exceptions.CompilerInternalException' was thrown.

   at ProtoCore.DSASM.Executive.RetrieveExecutionStatesFromStack(Int32 localSize, Int32 paramSize)
   at ProtoCore.DSASM.Executive.RestoreFromCall()
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
   at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   at ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()
```

**Comment by aparajit-pratap** [comment]
Known issues: https://jira.autodesk.com/browse/DYN-607

**Comment by vykrum** [comment]
Runtime exception occured. Dsasm runtime error. Exiting...


   at ProtoCore.DSASM.Executive.RETCN_Handler(Instruction instruction)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
   at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   at ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()

**Comment by vykrum** [comment]
Runtime exception occured. The Type of StackValue is not Double

   at ProtoCore.DSASM.StackValue.get_DoubleValue()
   at ProtoCore.DSASM.Executive.IsNodeModified(StackValue svGraphNode, StackValue svUpdateNode)
   at ProtoCore.DSASM.Executive.XLangUpdateDependencyGraph(Int32 currentLangBlock)
   at ProtoCore.DSASM.Executive.RestoreFromBounce()
   at ProtoCore.DSASM.Executive.RETB_Handler()
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
   at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   at ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()

**Comment by jnealb** [comment]
@vykrum Is this latest crash also a result of "Pasted code from one code block to another. Code replaced was within a function."? or did it come from another workflow?

**Comment by vykrum** [comment]
@jnealb No. This is frustrating as a function (defined in a code block) was called and worked a few times, but then started giving me this error on subsequent runs. Problem not solved on restarting Dynamo or the system.
The function referred to above, has another function nested within, which I suspect is causing the problems.
If it helps, I could email the file, if you provide me with your email.

**Comment by jnealb** [comment]
Yes, please do: neal.burnham@autodesk.com

**Comment by jnealb** [comment]
Can I have your Rvt model as well? I get a  warning, but no crash with the DynamoSample model.

**Comment by vykrum** [comment]
I managed to get it to work consistently by shifting part of the code (in
the function bayStk) to within the Imperative code block.
Please find attached the working definition and the Revit file.

Regards,

*V i k r a m   S u b b a i a h*
| Principal Architect | Testing Waters Architecture |
testingwaters@gmail.com  | +919886402289 (m) |
| www.testingwaters.in <http://www.testingwaters.net/> | #821, 4'th A
Cross, 9'th Main, 1'st Block, Kalyan Nagar, Bangalore 560043 |

**Comment by jnealb** [comment]
Nice!
