### ISSUE TITLE
Crash when opend

### ISSUE THREAD

**Issue by T-Lueks** [DynamoDS/Dynamo#7861]
- Dynamo version 1.3.0
- Revit version 2017 2.1
- Windows 8.1

Dear Dynamo community,

I want to begin with a new script, but i cant even open Dynamo without a crash. This never happend before today. I have reinstalled dynamo (tried both 1.3.0 and 1.2.1) but no difference. I tried different templates in Revit, but this also doesn't make a difference.  The massage below shows

Can anyone help with this issue?

HRESULT: [0x8876086A], Module: [SharpDX.Direct3D9], ApiCode: [D3DERR_NOTAVAILABLE/NotAvailable], Message: Unknown

   at SharpDX.Result.CheckError()
   at SharpDX.Direct3D9.Direct3DEx.CreateDeviceEx(Int32 adapter, DeviceType deviceType, IntPtr hFocusWindow, Int32 behaviorFlags, PresentParameters[] presentationParametersRef, DisplayModeEx[] fullscreenDisplayModeRef, DeviceEx returnedDeviceInterfaceOut)
   at HelixToolkit.Wpf.SharpDX.DX11ImageSource.StartD3D()
   at HelixToolkit.Wpf.SharpDX.DX11ImageSource..ctor()
   at HelixToolkit.Wpf.SharpDX.DPFCanvas.StartD3D()
   at HelixToolkit.Wpf.SharpDX.DPFCanvas.RenderTechniquesManagerPropertyChanged()
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at HelixToolkit.Wpf.SharpDX.Viewport3DX.RenderTechniquesManagerPropertyChanged()
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   at System.Windows.Data.BindingExpressionBase.Invalidate(Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.Activate(Object item)
   at System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)
   at System.Windows.Data.BindingExpression.MS.Internal.Data.IDataBindEngineClient.AttachToContext(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Task.Run(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Run(Object arg)
   at System.Windows.ContextLayoutManager.fireLayoutUpdateEvent()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jnealb** [comment]
@T-Lueks Can you please run the Dxdiag program and capture the output to a file and send it to us? Thanks, neal.burnham@autodesk.com

**Comment by T-Lueks** [comment]
Dear jnealb,

Thanks for the quick reaction. I've send the Dxdiag output to the provided email address.

With kind regards,

T. Lueks

**Comment by mjkkirschner** [comment]
@jnealb any update here?

**Comment by jnealb** [comment]
@T-Lueks Thanks for the DxDiag file, which shows that you have an Intel(R) HD Graphics 4600 gfx card. Do you still get the crash?

**Comment by T-Lueks** [comment]
No, I fixed it via updating my main GPU. The Intel(R) HD Graphics 4600 is just an on board GPU.


Met vriendelijke groet,

T. (Tomas) Lueks
Tekenaar

Mobilis B.V.

T +31 683 256 320 | F +31 55 - 538 22 44 | t.lueks@mobilis.nl<mailto:t.lueks@mobilis.nl> | www.mobilis.nl<http://www.mobilis.nl/>

Landdrostlaan 49, 7327 GM Apeldoorn | Postbus 20175, 7302 HD Apeldoorn
Disclaimer<www.mobilis.nl/nl/footer/legal/5/disclaimer-e-mail/29> | KvK Oost Nederland 24289439

Van: Neal Burnham [mailto:notifications@github.com]
Verzonden: woensdag 18 oktober 2017 15:28
Aan: DynamoDS/Dynamo <Dynamo@noreply.github.com>
CC: Lueks, Tomas (Mobilis) <t.lueks@mobilis.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [DynamoDS/Dynamo] Crash when opend (#7861)


@T-Lueks<https://github.com/t-lueks> Thanks for the DxDiag file, which shows that you have an Intel(R) HD Graphics 4600 gfx card. Do you still get the crash?
