### ISSUE TITLE
Problem open examples in "../test/core/list/"

### ISSUE THREAD

**Issue by mwaraya** [DynamoDS/Dynamo#788]
Hi,
I'm trying to open the list examples in "../test/core/list/" but i can't load the files, i'm having this error:

There was an error opening the workbench.
System.Xml.XmlException:
'/' is an unexpected token. The expected token is '='. Line 28, position 72.
at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
at System.Xml.XmlTextReaderImpl.ParseAttributes()
at System.Xml.XmlTextReaderImpl.ParseElement()
at System.Xml.XmlTextReaderImpl.ParseElementContent()
at System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
at System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
at System.Xml.XmlDocument.Load(XmlReader reader)
at System.Xml.XmlDocument.Load(String filename)
at Dynamo.Models.WorkspaceHeader.FromPath(String path)
Workbench could not be opened.
Workbench could not be opened.
C:\Users\Manuel\Desktop\Dynamo\core\list\Sort_SimpleNumbers.dyn

I'm trying to learn the list stuff before asking to basics questions in the dynamo forum ;-)

PD: im using DynamoDailyInstall20131115T1237

**Comment by ikeough** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version. 

Thank you!
