### ISSUE TITLE
Import DLL Error

### ISSUE THREAD

**Issue by fathygad** [DynamoDS/Dynamo#7891]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

1.3.0.875

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Operating system

Windows 7

## What did you do? 

import DLL for zero touch nodes package to dynamo

## What did you expect to see?

the dll is lioaded and package to be seen in Dynamo libraries

## What did you see instead?

**it failed to load Dll however i loaded it successfully many times before.**

Exception of type 'ProtoCore.Exceptions.CompilerInternalException' was thrown.

   at ProtoCore.AssociativeEngine.Utils.IsGlobalScopeDirty(Executable exe)
   at ProtoScript.Runners.LiveRunner.ApplyUpdate()
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(String code)
   at ProtoScript.Runners.LiveRunner.UpdateCmdLineInterpreter(String code)
   at Dynamo.Engine.EngineController.OnLibraryLoaded()
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Dynamo.Engine.LibraryServices.OnLibraryLoaded(LibraryLoadedEventArgs e)
   at Dynamo.Engine.LibraryServices.ImportLibrary(String library)
   at Dynamo.ViewModels.DynamoViewModel.ImportLibrary(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by ksobon** [comment]
I am guessing we will need to get that DLL for us to be able to recreate the issue.

**Comment by ramramps** [comment]
@fathygad Any updates on this issue? did you still see this issue?
