### ISSUE TITLE
ZeroTouch Library Load Error

### ISSUE THREAD

**Issue by torkuen** [DynamoDS/Dynamo#8121]
## Dynamo version
1.3.0.875

## Operating system
Windows 7

## What did you do? 

Import Library (ZeroTouch dll)

## What did you expect to see?

Normal Loading

## What did you see instead?
Always get an Error message at the first try ( see below) . Then restarting Dynamo, loading of the Library always works.
---------------------------------
An item with the same key has already been added.

   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Dynamo.Engine.XmlDocumentationExtensions.LoadDataFromXml(XmlReader reader, String assemblyName)
   at Dynamo.Engine.XmlDocumentationExtensions.GetMemberDocumentNode(FunctionDescriptor function, XmlReader xml)
   at Dynamo.Engine.XmlDocumentationExtensions.GetMemberElement(FunctionDescriptor function, XmlReader xml, DocumentElementType property, String paramName)
   at Dynamo.Engine.FunctionDescriptor.get_Summary()
   at Dynamo.Engine.FunctionDescriptor.get_Description()
   at Dynamo.Search.SearchElements.ZeroTouchSearchElement..ctor(FunctionDescriptor functionDescriptor)
   at Dynamo.Models.DynamoModel.AddZeroTouchNodeToSearch(FunctionGroup funcGroup)
   at Dynamo.Models.DynamoModel.AddZeroTouchNodesToSearch(IEnumerable`1 functionGroups)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Dynamo.Engine.LibraryServices.OnLibraryLoaded(LibraryLoadedEventArgs e)
   at Dynamo.Engine.LibraryServices.ImportLibrary(String library)
   at Dynamo.ViewModels.DynamoViewModel.ImportLibrary(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by torkuen** [comment]
Hi mjkkirschner
but it isn´t imported before. As I mentioned, the second try always works.The way is: 1. Open Revit 2. Start Dynamo 3. Load Library 4. Error message 5. Dynamo Shuts down (Revit stays open) 6. Start Dynamo again 7. Load Library 8. it works. I know, that if a ZT dll is loaded into Dynamo you have to shut down Revit as well to exchange the dll. It would be helpful to know where the conflict ist detected by Dynamo (namespace/dll name etc.)
Thanks,
Torsten

**Comment by mjkkirschner** [comment]
Does your dll have any other dlls as dependencies - can you host your code somewhere we can take a look like GitHub ?

**Comment by torkuen** [comment]
I found the error: it was in the xml code: 3slashes to much. some copypaste error..
thanks for the effort!

   /// <param name="elementsToCope"> a list of elements to be coped</param>
        /// **///** <returns>a boolean list showing if the element was cut</returns>
        ///
