### ISSUE TITLE
Unhandled Exception in Dynamo Engine

### ISSUE THREAD

**Issue by cpalexander** [DynamoDS/Dynamo#8126]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.3.1.1736
Revit: 2017

## Operating system

Windows 10

## What did you do? 

Selected "Run"

## What did you expect to see?

The program to run and complete.

## What did you see instead?

Error Code:
Runtime exception occured. The Type of StackValue is not Integer

   at ProtoCore.DSASM.StackValue.get_IntegerValue()
   at ProtoCore.DSASM.Executive.GetCurrentScope(Int32& classIndex, Int32& functionIndex)
   at ProtoCore.DSASM.Executive.DEP_Handler(Instruction instruction)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
   at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   at ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()

**Comment by jnealb** [comment]
@cpalexander Can you please provide us with your Revit model and associated Dynamo dyn file and steps to reproduce?

**Comment by cpalexander** [comment]
I can do so – is replying and attaching to this email the correct method?

Thank you,

Christopher Alexander, AIA, NCARB, CSI, CDT
[cid:image002.jpg@01CEA4D2.C9412420]<http://www.progressiveae.com/>

**Comment by jnealb** [comment]
How big is the Revit model?

**Comment by cpalexander** [comment]
Good point. 92 MB.

It is a project that someone else is involved with and I am supporting, so I couldn’t even guess at what could be removed to help with the size.

Christopher Alexander, AIA, NCARB, CSI, CDT
[cid:image002.jpg@01CEA4D2.C9412420]<http://www.progressiveae.com/>

**Comment by jnealb** [comment]
Send it here: neal.burnham@autodesk.com

**Comment by cpalexander** [comment]
My apologies, Neal, but I am unable to send a file that size. It would have to be via a filesharing site to get something to accommodate that size.

I have attached the dynamo script, if that is help solo.

Thanks,

Christopher Alexander, AIA, NCARB, CSI, CDT
[cid:image002.jpg@01CEA4D2.C9412420]<http://www.progressiveae.com/>

**Comment by jnealb** [comment]
@cpalexander Is this still an issue for you?

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
