### ISSUE TITLE
Category is unexpectedly NULL.

### ISSUE THREAD

**Issue by cellophane303** [DynamoDS/Dynamo#8211]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

## Dynamo version

1.3.1.1736

## Operating system

Windows 8.1 Pro

## What did you do? 

I hit the run button...

## What did you expect to see?

The graph to run (it ran fine a few minutes ago...)  This is also the second or third time this has happened.  I can provide the graph if needed.

## What did you see instead?

Category is unexpectedly NULL.

   at Autodesk.Revit.DB.Category.get_Parent()
   at Revit.Elements.Category.get_Name()
   at ProtoFFI.CLRObjectMarshler.GetStringValue(StackValue dsObject)
   at ProtoCore.DSASM.Mirror.ExecutionMirror.GetClassTrace(StackValue val, Heap heap, Int32 langblock, Boolean forPrint)
   at ProtoCore.DSASM.Mirror.ExecutionMirror.GetStringValue(StackValue val, Heap heap, Int32 langblock, Int32 maxArraySize, Int32 maxOutputDepth, Boolean forPrint)
   at ProtoCore.Utils.StringUtils.ConvertToString(StackValue sv, RuntimeCore runtimeCore, RuntimeMemory rmem)
   at ProtoCore.Lang.BuiltInFunctionEndPoint.Execute(Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.CallSite.ExecWithZeroRI(List`1 functionEndPoint, Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore, FunctionGroup funcGroup, SingleRunTraceData previousTraceData, SingleRunTraceData newTraceData)
   at ProtoCore.CallSite.Execute(List`1 functionEndPoint, Context c, List`1 formalParameters, List`1 replicationInstructions, StackFrame stackFrame, RuntimeCore runtimeCore, FunctionGroup funcGroup)
   at ProtoCore.CallSite.DispatchNew(Context context, List`1 arguments, List`1 partialReplicationGuides, DominantListStructure domintListStructure, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.Lang.FunctionPointerEvaluator.Evaluate(List`1 args, StackFrame stackFrame)
   at ProtoCore.Lang.ArrayUtilsForBuiltIns.Evaluate(StackValue function, StackValue parameters, StackValue unpackParams, Interpreter runtime, StackFrame stackFrame)
   at ProtoCore.Lang.BuiltInFunctionEndPoint.Execute(Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.CallSite.ExecWithZeroRI(List`1 functionEndPoint, Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore, FunctionGroup funcGroup, SingleRunTraceData previousTraceData, SingleRunTraceData newTraceData)
   at ProtoCore.CallSite.Execute(List`1 functionEndPoint, Context c, List`1 formalParameters, List`1 replicationInstructions, StackFrame stackFrame, RuntimeCore runtimeCore, FunctionGroup funcGroup)
   at ProtoCore.CallSite.DispatchNew(Context context, List`1 arguments, List`1 partialReplicationGuides, DominantListStructure domintListStructure, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.DSASM.Executive.Callr(Int32 blockDeclId, Int32 functionIndex, Int32 classIndex, Boolean& explicitCall, Boolean isDynamicCall, Boolean hasDebugInfo)
   at ProtoCore.DSASM.Executive.CALLR_Handler(Instruction instruction)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
   at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   at ProtoScript.Runners.LiveRunner.ApplyUpdate()
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()

**Comment by jnealb** [comment]
@cellophane303 Yes, can you please provide the graph as well as the Revit model, if possible?

**Comment by cellophane303** [comment]
Sure thing.  I don't know if it is related, but I've gotten a crash report every time I've closed Revit after running the graph - I've sent those in as well.

[DeleteSubCategories.zip](https://github.com/DynamoDS/Dynamo/files/1334965/DeleteSubCategories.zip)

**Comment by jnealb** [comment]
@cellophane303 Missing the custom  node: Category.SubCategories. Also, we will likely need the rvt model.

**Comment by cellophane303** [comment]
Category.SubCategories is from the Clockwork package, I'm including it - don't know if it will work without the rest of Clockwork.  
The rvt model was just a blank file I was using for testing.  I loaded in some families, then ran the graph to remove all the junk sub categories that come with them (trying to clean up my library.)  I'm enclosing the file I was using but I don't know if it will be much help.

[Category.Subcategories.dyf.zip](https://github.com/DynamoDS/Dynamo/files/1337458/Category.Subcategories.dyf.zip)
[Project2.zip](https://github.com/DynamoDS/Dynamo/files/1337461/Project2.zip)

**Comment by jnealb** [comment]
@cellophane303 Still getting an unresolved List.FilterByString red custom node, despite downloading Clockwork, Lunchbox and Archilab?

**Comment by cellophane303** [comment]
Sorry about that - the List.FilterByString is from SteamNodes.  i didn't realize that when I posted earlier.

**Comment by jnealb** [comment]
@cellophane303 Clockwork is also a prereq for several custom nodes in the subcategories custom node (do you have it installed?). I am unable to reproduce the null return, for example: 
![image](https://user-images.githubusercontent.com/9357222/31196878-3cd6a7cc-a91d-11e7-8a74-7b6f5dc0c154.png)

Which version of Revit are you using?

**Comment by sixtysecondrevit** [comment]
Thanks for your feedback. As this is a Revit related issue, please re-open and link to the original issue here: https://github.com/DynamoDS/DynamoRevit/issues
