### ISSUE TITLE
Crash when copy-pasting nodes from one workspace to another

### ISSUE THREAD

**Issue by Dewb** [DynamoDS/Dynamo#8290]
## Dynamo version

Core 2.0.0.2821 (local build from master, commit 4cb471e61ee73190d619dd1b12a374e592ea70fc)

## Operating system

Windows 10

## What did you do? 

- Open workspace (the 06_SurfaceMilling.dyn in the extras folder of Machina-Dynamo 0.4.3)
- Select some nodes
- Edit > Copy
- New Home Workspace
- Right click > Paste

## What did you expect to see?

The pasted nodes in my new workspace

## What did you see instead?

A crash with the following callstack:

```
Sequence contains no elements

   at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source)
   at Dynamo.Controls.DynamoView.OnRequestPaste() in D:\dynamo\dynamo\src\DynamoCoreWpf\Views\Core\DynamoView.xaml.cs:line 213
   at Dynamo.ViewModels.DynamoViewModel.OnRequestPaste() in D:\dynamo\dynamo\src\DynamoCoreWpf\ViewModels\Core\DynamoViewModelEvents.cs:line 138
   at Dynamo.ViewModels.DynamoViewModel.Paste(Object parameter) in D:\dynamo\dynamo\src\DynamoCoreWpf\ViewModels\Core\DynamoViewModel.cs:line 953
   at Dynamo.UI.Commands.DelegateCommand.Execute(Object parameter) in D:\dynamo\dynamo\src\DynamoCoreWpf\Utilities\DelegateCommand.cs:line 39
   at System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   at System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at System.Windows.Threading.Dispatcher.Invoke(DispatcherPriority priority, Delegate method, Object arg)
   at System.Windows.Interop.HwndSource.OnPreprocessMessageThunk(MSG& msg, Boolean& handled)
   at System.Windows.Interop.ComponentDispatcherThread.RaiseThreadMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at DynamoSandbox.DynamoCoreSetup.RunApplication(Application app) in D:\dynamo\dynamo\src\DynamoSandbox\DynamoCoreSetup.cs:line 54
```

**Comment by Dewb** [comment]
[commands.zip](https://github.com/DynamoDS/Dynamo/files/1419355/commands.zip)

**Comment by mjkkirschner** [comment]
@QilongTang seems similar to @phliberato's PR.

**Comment by mjkkirschner** [comment]
tracked with:
https://jira.autodesk.com/browse/QNTM-2485

**Comment by mjkkirschner** [comment]
going to close this as I have not seen anything similar lately and last news was could not repro.
