### ISSUE TITLE
Dynamo 1.3.2 Has Crashed

### ISSUE THREAD

**Issue by gokhanozhim** [DynamoDS/Dynamo#8381]
HRESULT: [0x8876086A], Module: [SharpDX.Direct3D9], ApiCode: [D3DERR_NOTAVAILABLE/NotAvailable], Message: Unknown

   at SharpDX.Result.CheckError()
   at SharpDX.Direct3D9.Direct3DEx.CreateDeviceEx(Int32 adapter, DeviceType deviceType, IntPtr hFocusWindow, Int32 behaviorFlags, PresentParameters[] presentationParametersRef, DisplayModeEx[] fullscreenDisplayModeRef, DeviceEx returnedDeviceInterfaceOut)
   at HelixToolkit.Wpf.SharpDX.DX11ImageSource.StartD3D()
   at HelixToolkit.Wpf.SharpDX.DX11ImageSource..ctor()
   at HelixToolkit.Wpf.SharpDX.DPFCanvas.StartD3D()
   at HelixToolkit.Wpf.SharpDX.DPFCanvas.RenderTechniquesManagerPropertyChanged()
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at HelixToolkit.Wpf.SharpDX.Viewport3DX.RenderTechniquesManagerPropertyChanged()
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   at System.Windows.Data.BindingExpressionBase.Invalidate(Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.Activate(Object item)
   at System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)
   at System.Windows.Data.BindingExpression.MS.Internal.Data.IDataBindEngineClient.AttachToContext(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Task.Run(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Run(Object arg)
   at System.Windows.ContextLayoutManager.fireLayoutUpdateEvent()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

I installed Dynamo 1.3.2 for Revit 2016 Update7 R2 on Windows 10 Pro and get error. I tried to uninstall then install but problem is still go on. Does anybody know this issue ?

**Comment by jnealb** [comment]
Can you please provide more detail: dyn graph, dxdiag output, was it Dynamo for Revit?

**Comment by gokhanozhim** [comment]
I can not open dynamo. Yes dynamo for revit.

**Comment by jnealb** [comment]
Can you please run Dxdiag from a command line and send us the output: neal.burnham@autodesk.com

**Comment by gokhanozhim** [comment]
Thank you for your interest. I sent the output.

**Comment by sy-tay** [comment]
Hi There,

I am also facing the same issue. *Attached dynamo clash report including dxdiag output.

Just to provide more background information for my case.
Dynamo was installed on my Revit 2016 as an add-in before the installation of Revit 2018.
[Dynamo crash report.pdf](https://github.com/DynamoDS/Dynamo/files/1882866/Dynamo.crash.report.pdf)

Dynamo started to have this issue after Revit 2018 is installed.

However, dynamo still crashed after trying the steps below:
1. Uninstall Revit 2018, uninstall Dynamo, reinstall Revit 2018 and reinstall Dynamo
2. Uninstall Revit 2018, uninstall Dynamo, reinstall Dynamo, open in Revit 2016

Any advise would be much appreciated.
Thank you.

Regards, 
SY

**Comment by mjkkirschner** [comment]
Please try suggestions here related to graphics:
https://github.com/DynamoDS/Dynamo/wiki/Dynamo-FAQ

please reopen if this is still occurring after trying those suggestions.

**Comment by gokhanozhim** [comment]
Thank you Michael
________________________________
Gönderen: Michael Kirschner <notifications@github.com>
Gönderildi: 18 Kasım 2019 Pazartesi 22:31
Kime: DynamoDS/Dynamo <Dynamo@noreply.github.com>
Bilgi: gokhanozhim <gokhan.ozhim@hotmail.com>; Author <author@noreply.github.com>
Konu: Re: [DynamoDS/Dynamo] Dynamo 1.3.2 Has Crashed (#8381)


Please try suggestions here related to graphics:
https://github.com/DynamoDS/Dynamo/wiki/Dynamo-FAQ

please reopen if this is still occurring after trying those suggestions.
