### ISSUE TITLE
Tried to run 

### ISSUE THREAD

**Issue by CaseyCardin** [DynamoDS/Dynamo#8401]
The managed object is not valid.

   at Autodesk.Revit.DB.Transaction.GetStatus()
   at RevitServices.Transactions.AutomaticTransactionStrategy.ForceCloseTransaction(TransactionHandle handle)
   at Dynamo.Applications.Models.RevitDynamoModel.OnEvaluationCompleted(Object sender, EvaluationCompletedEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Dynamo.Graph.Workspaces.HomeWorkspaceModel.OnEvaluationCompleted(EvaluationCompletedEventArgs e)
   at Dynamo.Models.DynamoModel.RunCancelImpl(RunCancelCommand command)
   at Dynamo.Models.DynamoModel.ExecuteCommand(RecordableCommand command)
   at Dynamo.Wpf.ViewModels.RunSettingsViewModel.Model_PropertyChanged(Object sender, PropertyChangedEventArgs e)
   at System.ComponentModel.PropertyChangedEventHandler.Invoke(Object sender, PropertyChangedEventArgs e)
   at Dynamo.Core.NotificationObject.RaisePropertyChanged(String propertyName)
   at Dynamo.Models.RunSettings.Reset()
   at Dynamo.Graph.Workspaces.HomeWorkspaceModel.Clear()
   at Dynamo.Models.DynamoModel.ClearCurrentWorkspace()
   at Dynamo.ViewModels.DynamoViewModel.ClearHomeWorkspaceInternal()
   at Dynamo.ViewModels.DynamoViewModel.MakeNewHomeWorkspace(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

## Dynamo version

1.3.2.2480

## Operating system

Windows 10

## What did you do? 

Trying to list out all elevations to set Z of top/bottom of "section box."

## What did you expect to see?

Lines that define the elevation view box and a list of all elevations

## What did you see instead?

nothing happened, error occur as soon as I clicked "run"

**Comment by johnpierson** [comment]
@CaseyCardin, are you still receiving this error on Dynamo 2.0.1?

**Comment by CaseyCardin** [comment]
@johnpierson I was able to figure out this issue.

**Comment by johnpierson** [comment]
Thanks @CaseyCardin ! Closing now
