### ISSUE TITLE
Unhandeled Exception corrupts file

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#8509]
## Dynamo version
2.0.0.3865

## Operating system
Windows 7

## What did you do? 
Wrapped Imperative blocks within another Imperative block
![20180130-1](https://user-images.githubusercontent.com/5621624/35555218-7f9b2b6a-05c4-11e8-8bb0-456b0b22774d.png)
Before Error ...
![20180130-2](https://user-images.githubusercontent.com/5621624/35555289-b12cebc8-05c4-11e8-9350-6db2cf41d581.png)

## What did you expect to see?
An opportunity to further refine the code

## What did you see instead?
Unhandled Exception and more importantly the file is now corrupt and doesn't work even on relaunching Dynamo
[20180130.zip](https://github.com/DynamoDS/Dynamo/files/1676803/20180130.zip)
```
Index was outside the bounds of the array.

   at ProtoCore.DSASM.Executive.BOUNCE_Handler(Instruction instruction)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
   at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   at ProtoScript.Runners.LiveRunner.ApplyUpdate()
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()
```

**Comment by mjkkirschner** [comment]
if you try opening this file again it should open in manual mode and then you will be able to edit the codeblock, this doesn't happen?

**Comment by vykrum** [comment]
@mjkkirschner Did open and edit, but the results were all null (in all node previews)
Pasting the code in a new file was the solution.

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
