### ISSUE TITLE
The referenced object is not valid, possibly because it has been deleted from the database, or its creation was undone

### ISSUE THREAD

**Issue by ViktorKuzev** [DynamoDS/Dynamo#8567]
Dynamo 1.3.2.2480
Revit 2018.2
Windows 10

## What did you do? 

Using a Python Node to load multiple families into multiple project files
documents = []
families = []
for docpath in docpaths:
	doc=app.OpenDocumentFile(docpath)
	documents.append(doc)
for path in paths:
	family_doc = app.OpenDocumentFile(path)
	families.append(family_doc)

for document in documents:
	map(lambda family: family.LoadFamily(document, FamilyOption()), families)
doc = DocumentManager.Instance.CurrentDBDocument

map(lambda x: x.Close(True), documents)
map(lambda x: x.Close(False), families)
## What did you expect to see?

IT works. The families are loaded into the files and the files are saved. But upon completion I get an error message advising me to close Dynamo 

The referenced object is not valid, possibly because it has been deleted from the database, or its creation was undone.

   at validateNativeInstance(Void* ptr)
   at Autodesk.Revit.RevitDBAPIManagedWeakPointer<ADocument>.getValidPtr()
   at Autodesk.Revit.DB.Document.GetHashCode()
   at System.Collections.Generic.Dictionary`2.Remove(TKey key)
   at ProtoFFI.CLRObjectMarshler.OnDispose(StackValue dsObject, Context context, Interpreter dsi)
   at ProtoFFI.DisposeFunctionPointer.Execute(Context c, Interpreter dsi)
   at ProtoCore.Lang.FFIFunctionEndPoint.Execute(Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.CallSite.ExecWithZeroRI(List`1 functionEndPoint, Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore, FunctionGroup funcGroup, SingleRunTraceData previousTraceData, SingleRunTraceData newTraceData)
   at ProtoCore.CallSite.Execute(List`1 functionEndPoint, Context c, List`1 formalParameters, List`1 replicationInstructions, StackFrame stackFrame, RuntimeCore runtimeCore, FunctionGroup funcGroup)
   at ProtoCore.CallSite.DispatchNew(Context context, List`1 arguments, List`1 partialReplicationGuides, DominantListStructure domintListStructure, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.CallSite.JILDispatch(List`1 arguments, List`1 replicationGuides, DominantListStructure domintListStructure, StackFrame stackFrame, RuntimeCore runtimeCore, Context context)
   at ProtoCore.DSASM.Executive.Callr(Int32 blockDeclId, Int32 functionIndex, Int32 classIndex, Boolean& explicitCall, Boolean isDynamicCall, Boolean hasDebugInfo)
   at ProtoCore.DSASM.Heap.GCDisposeObject(StackValue svPtr, Executive exe)
   at ProtoCore.DSASM.Heap.Sweep()
   at ProtoCore.DSASM.Heap.SingleStep(Boolean forceGC)
   at ProtoCore.DSASM.Heap.FullGC(IEnumerable`1 gcroots, Executive exe)
   at ProtoScript.Runners.LiveRunner.ApplyUpdate()
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()

**Comment by ViktorKuzev** [comment]
Ok solved it. And I'm laughing now. The output was assigned a list of documents that were already closed. 
Of course I get this message.

**Comment by jnealb** [comment]
@ViktorKuzev Thank you.
