### ISSUE TITLE
Label.ByPointAndString unable to accept a concatenated String

### ISSUE THREAD

**Issue by dvlrnr** [DynamoDS/Dynamo#8736]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

Dynamo Core 1.3.0.875, Dynamo Studio 1.3.0.946

## Operating system

Windows 10

## What did you do? 

I linked the output of a String.Concat element to the String input of a Label.ByPointAndString.

## What did you expect to see?

That the Label.ByPointAndString would have added a Label with the content of the given String at the specified coordinates. 

## What did you see instead?

'3Variable name' is not a valid value for property 'Name'.

   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at Dynamo.Wpf.ViewModels.Watch3D.HelixWatch3DViewModel.AggregateRenderPackages(IEnumerable`1 packages)
   at Dynamo.Wpf.ViewModels.Watch3D.HelixWatch3DViewModel.GenerateViewGeometryFromRenderPackagesAndRequestUpdate(IEnumerable`1 taskPackages)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at DynamoStudio.DynamoCoreSetup.RunApplication(Application app)

**Comment by mjkkirschner** [comment]
I don't think this node should appear at all.
Have you ever gotten it to work? - it's an internal method that was somehow leaking out in 1.3 or that is my intuition anyway.

**Comment by dvlrnr** [comment]
Thank you Michael for the prompt response. This was my first attempt at using Label.ByPointAndString.

I then found the Dynamo Text package and its Test.FromStringOriginAndScale with which I was able to achieve what I wanted to do which is to add a legend showing the values of a select few parameters.
