### ISSUE TITLE
Dynamo 2.0.0 Crashing on moving custom node

### ISSUE THREAD

**Issue by kraftwerk15** [DynamoDS/Dynamo#8818]
Dynamo 1.3.1
Also, tested against Dynamo 2.0.0

## Operating system

Window 7

## What did you do? 

Added a custom node to the workspace. With Automatic turned on, the node completes correctly. If I attempt to move the node, Dynamo will crash.

## What did you expect to see?

I did see what I expect to see. Expected Dynamo not to crash.

## What did you see instead?

A crashing Dynamo.

Further Information: I do not know if this is important or a different issue, but some packages that I download from the package manager will execute correctly, others will forcibly crash Dynamo 2.0.

Log Below:

The '+' character, hexadecimal value 0x2B, cannot be included in a name.

   at System.Xml.XmlDocument.CheckName(String name)
   at System.Xml.XmlElement..ctor(XmlName name, Boolean empty, XmlDocument doc)
   at System.Xml.XmlDocument.CreateElement(String prefix, String localName, String namespaceURI)
   at System.Xml.XmlDocument.CreateElement(String name)
   at Dynamo.Core.UndoRedoRecorder.RecordActionInternal(XmlElement group, ModelBase model, UserAction action)
   at Dynamo.Graph.Workspaces.WorkspaceModel.RecordModelsForModification(List`1 models, UndoRedoRecorder recorder)
   at Dynamo.ViewModels.WorkspaceViewModel.RecordSelectionForUndo()
   at Dynamo.ViewModels.WorkspaceViewModel.BeginDragSelection(Point2D mouseCursor)
   at Dynamo.ViewModels.DynamoViewModel.OnModelCommandCompleted(RecordableCommand command)
   at Dynamo.Models.DynamoModel.ExecuteCommand(RecordableCommand command)
   at Dynamo.ViewModels.WorkspaceViewModel.StateMachine.HandleMouseMove(Object sender, Point mouseCursor)
   at Dynamo.ViewModels.WorkspaceViewModel.StateMachine.HandleMouseMove(Object sender, MouseEventArgs e)
   at Dynamo.Views.WorkspaceView.OnMouseMove(Object sender, MouseEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.MouseDevice.Synchronize()
   at System.Windows.Input.MouseDevice.ChangeMouseCapture(IInputElement mouseCapture, IMouseInputProvider providerCapture, CaptureMode captureMode, Int32 timestamp)
   at System.Windows.Input.MouseDevice.Capture(IInputElement element, CaptureMode captureMode)
   at Dynamo.Controls.DragCanvas.OnMouseLeftButtonDown(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

![image](https://user-images.githubusercontent.com/30668448/39546274-715f5952-4e19-11e8-9954-dc90037c7a93.png)

**Comment by jnealb** [comment]
@kraftwerk15 Where did this custom node come from? Can you share it with us?

**Comment by mjkkirschner** [comment]
https://github.com/DynamoDS/Dynamo/issues/5120

looks like you may be using some of archilabs code and adding it to another class?

**Comment by kraftwerk15** [comment]
@jnealb This is a custom node with code from our other issue. It is the third method called Slab Edge Types. First two methods work fine. The third dropdown is the issue. [https://github.com/DynamoDS/Dynamo/issues/8822](url) 

@mjkkirschner The RevitDropDownBase looks like it is coming from DSRevitNodesUI? I was attempting to build a dropdown and I was trying to build something like his code that is available, but I don't think it references his code. Not sure though.

**Comment by mjkkirschner** [comment]
@kraftwerk15 I think you ended up getting to the bottom of this? Re-open if not.

**Comment by kraftwerk15** [comment]
Yes. It has to do with mixture of Zero Touch and Node Model under one build. Separating those out into two separate VS Projects then merging back the two created .dlls will fix this issue.
