### ISSUE TITLE
Dynamo Crashes when pasting a group

### ISSUE THREAD

**Issue by rresende** [DynamoDS/Dynamo#8862]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

Dynamo Core 2.0.0.4654
Dynamo Revit 2.0.0.4655

## Operating system

Windows 10

## What did you do? 

Select a group, copy using the command on the Edit menu (shortcut is not working)., then pasted (using the Edit menu command). 

## What did you expect to see?

A copy of the group
## What did you see instead?

Dynamo crashes.

Error message is:

Sequence contains no elements

   at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source)
   at Dynamo.Controls.DynamoView.OnRequestPaste()
   at Dynamo.ViewModels.DynamoViewModel.OnRequestPaste()
   at Dynamo.ViewModels.DynamoViewModel.Paste(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by mjkkirschner** [comment]
@ramramps could this be related to this change:
https://github.com/DynamoDS/Dynamo/pull/8688/files

**Comment by mjkkirschner** [comment]
@rresende does this happen repeatedly with any group or only with a specific group?

**Comment by rresende** [comment]
The group does not contain custom nodes. It happened three times in a row but it no longer happens! Attaching the files.

[Rotina Dynamo.zip](https://github.com/DynamoDS/Dynamo/files/1997839/Rotina.Dynamo.zip)

**Comment by ramramps** [comment]
@rresende Does the group contains Notes?

**Comment by rresende** [comment]
It does not.

**Comment by jnealb** [comment]
@rresende @smangarole @Racel We are unable to reproduce the crash with your data (thanks for sending it) and our latest daily build (running Core 2.0.1.5000) and Revit 2019. Can you please upgrade to this D4R build (available from our website) and let us know if you see the crash again?
