### ISSUE TITLE
Dynamo 2.0 error watch node

### ISSUE THREAD

**Issue by hauvovan** [DynamoDS/Dynamo#8927]
Dynamo 2.0 error watch node. When I use Watch Node to see  value. it is not display and notice crash.  Please review this matter

Method not found: 'System.Collections.ObjectModel.ObservableCollection`1<Dynamo.Graph.Nodes.PortData> Dynamo.Graph.Nodes.NodeModel.get_InPortData()'.

   at CoreNodeModels.Watch..ctor()
   at lambda_method(Closure )
   at Dynamo.Wpf.ViewModels.NodeSearchElementViewModel.OnClicked()
   at Dynamo.UI.Controls.InCanvasSearchControl.ExecuteSearchElement(ListBoxItem listBoxItem)
   at Dynamo.UI.Controls.InCanvasSearchControl.OnMouseLeftButtonUp(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnPreviewMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.ContentElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jnealb** [comment]
@hauvovan Can you please provide us with your script and some information on your environment: OS etc.

**Comment by hauvovan** [comment]
dear jnealb.

i only create new file empty and add watch. i can not add node "watch". it is not display

**Comment by hauvovan** [comment]
i add watch 3d it display but watch and watch image is not working

**Comment by jnealb** [comment]
you have to hook up the watch node to other nodes that are upstream (before) it for the watch node to display something. Please take a look at the tutorials on Dynamobim.org for more information.

**Comment by hauvovan** [comment]
Dear jnealb

I have more one years use dynamo. i understand your mind. but this is a mistake. Dynamo 2.0 can not use node watch because when i double click mouse then this node is not add. No action when you click this node.

**Comment by hauvovan** [comment]
![image](https://user-images.githubusercontent.com/40243424/41365087-ad3408a0-6f62-11e8-9fcc-6c6f99aaff83.png)

**Comment by Racel** [comment]
Just checked in 2.0.1 build. It is working as expected. Please view the logic in the image below and try to build similar logic. Please let us know what results, so we can determine if we can close this issue, put it in our backlog, or determine if it is an issue on your local build.

![image](https://user-images.githubusercontent.com/2551261/41666782-96fd3d06-74ab-11e8-835f-bd28a9d9e3a9.png)

**Comment by hauvovan** [comment]
Hi you !
But when I click node " Watch", it do not display on screen windows. this is a big mistake

**Comment by mjkkirschner** [comment]
Hi @hauvovan something is loading an older version of dynamo core libraries. Please remove all packages. - perhaps VietBIMRebar.

I also see you have multiple notifications (green circle in menu) what do these say?

**Comment by hauvovan** [comment]
Hi Mjkkirschner.
I had tried remove all package in version 1.3. but I see error confict in notifications . now, I remove all version and reinstall. I hope it ok. wait me try

**Comment by hauvovan** [comment]
Hi all !
If I install dynamo 1.3.3 and dynamo 2.0 then dynamo 2.0 is conflict with 1.3 and multiple notifications (green circle in menu) . If I install only dynamo 2.0 without 1.3.3 then it worked ok. 

Why dynamo 2.0 and 1.3 cant work together ? please help

**Comment by mjkkirschner** [comment]
@hauvovan we cannot help further without knowing what notifications are present.

**Comment by smangarole** [comment]
@mjkkirschner @QilongTang I have added this as a bug and is tracked internally by: https://jira.autodesk.com/browse/QNTM-4597
