### ISSUE TITLE
SpringsUI.Refresh Node crashes Dynamo every time

### ISSUE THREAD

**Issue by JosefRadi** [DynamoDS/Dynamo#8943]
## Dynamo version

Dynamo Core 2.0.1.5055
Dynamo Revit 2.0.1.5065

## Operating system

Windows 10
Revit 2018

## What did you do? 

I loaded the SpringsUI.Refresh Node and clicked on "Refresh"
![2018-06-22 07_51_25-dynamo](https://user-images.githubusercontent.com/40483463/41759897-627149c0-75e0-11e8-921b-ac592367a06d.png)

## What did you expect to see?

an update/refresh of my other nodes.

## What did you see instead?

![2018-06-22 07_38_34-dynamo has crashed](https://user-images.githubusercontent.com/40483463/41759647-050bae3e-75df-11e8-90e9-fa09dba43ffa.png)

**Comment by JosefRadi** [comment]
@ramramps This is what was under Details:

Field not found: 'Dynamo.Graph.Workspaces.HomeWorkspaceModel.RunSettings'.

   at SpringsUI.RefreshButton.Flip()
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by ramramps** [comment]
one thought @JosefRadi did you convert this package for 2.0 version?

**Comment by JosefRadi** [comment]
@ramramps I dont think so? 
I just downloaded SpringsUI from the Packages?
Do I have to convert? How is this working?

**Comment by mjkkirschner** [comment]
The author of this package may not have updated it for use with dynamo 2.0 yet.
I would post on the springNodes github:
https://github.com/dimven/SpringNodes
