### ISSUE TITLE
Families.BatchUpdate

### ISSUE THREAD

**Issue by heinrichboldt** [DynamoDS/Dynamo#8945]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

Dynamo 1.3.2

## Operating system

 Windows 7

## What did you do? 

filter Files for upgrading

## What did you expect to see?

a result true

## What did you see instead?

![2018-06-22 17_35_34-clipboard](https://user-images.githubusercontent.com/7993879/41786064-bfbd5826-7644-11e8-8a8e-64de156e415c.png)

   at ProtoCore.DSASM.Heap.Sweep()
   at ProtoCore.DSASM.Heap.SingleStep(Boolean forceGC)
   at ProtoCore.DSASM.Heap.FullGC(IEnumerable`1 gcroots, Executive exe)
   at ProtoScript.Runners.LiveRunner.ApplyUpdate()
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()

**Comment by smangarole** [comment]
@heinrichboldt Can you provide me the following information:

- Revit version you are using
- the dyn file you were using

Thanks.

**Comment by heinrichboldt** [comment]
I use Revit 2016.

here is the file
[Familys_Update.zip](https://github.com/DynamoDS/Dynamo/files/2128453/Familys_Update.zip)

**Comment by sixtysecondrevit** [comment]
@heinrichboldt is this an issue with someone’s package? You might want to reach out to them directly by other means if that is the case. _(E.g. Dynamo forum, package’s github, etc)_
