### ISSUE TITLE
Insertin Archi lab node "Lines Styles" causes dynamo to crash

### ISSUE THREAD

**Issue by phil-sh** [DynamoDS/Dynamo#8955]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version 1.3.2.2480

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Operating system

Windows 10

## What did you do? 

I tried to add arch-lab node "Line Styles" to my dynamo graph

## What did you see instead?

Every time i attempted this dynamo crashed
I have uninstalled and re installed the archi lab package but it still crashes

Object reference not set to an instance of an object.

   at archilabUI.LineStyleUi.PopulateItemsCore(String currentSelection)
   at CoreNodeModels.DSDropDownBase.PopulateItems()
   at CoreNodeModels.DSDropDownBase..ctor(String outputName)
   at DSRevitNodesUI.RevitDropDownBase..ctor(String value)
   at archilabUI.LineStyleUi..ctor()
   at lambda_method(Closure )
   at Dynamo.Wpf.ViewModels.NodeSearchElementViewModel.OnClicked()
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by mjkkirschner** [comment]
@phil-sh seems like you might be loading a version of this package for dynamo 2.0 and not 1.3 - what version of archilab are you installing?

**Comment by ksobon** [comment]
Archi-lab.net package versions follow this logic: 

Version 2019.2.1

* 2019 - last version of Revit that this package was tested on
* 2 - last version of Dynamo that this package was built against
* 1 - build instance incremented with each release

So for Dynamo 1.3 you want to install Archi-lab.net v. 2018.13.13 as that was probably the last version before I moved on to 2.0.
