### ISSUE TITLE
ProtoCore.Exceptions.CompilerInternalException on importing library

### ISSUE THREAD

**Issue by HossZamani** [DynamoDS/Dynamo#8974]
## Dynamo version

1.3.2

## Operating system

Windows 10

## What did you do? 

Tried creating zerotouch nodes. I'm debugging with this post build actions:

```
xcopy /Y "$(TargetDir)*.*" "$(AppData)\Dynamo\Dynamo Core\1.3\packages\$(ProjectName)\bin\"

xcopy /Y "$(ProjectDir)pkg.json" "$(AppData)\Dynamo\Dynamo Core\1.3\packages\$(ProjectName)" 
```

and setting DynamoSandbox for starting to debug. In the package folder these folders exist as well:

![image](https://user-images.githubusercontent.com/27878288/42251648-e6b2615c-7f7b-11e8-8eae-b0b760d0ae10.png)

My project contains references to COM object Microsoft Outlook 16.0. I'm suspecting this is causing the error. 

## What did you expect to see?

Nodes popping up in library.

## What did you see instead?

Nothing. As if DynamoSandbox has ignored the package. Although I get this in my VS debug output:

`'DynamoSandbox.exe' (Managed (v4.0.30319)): Loaded 'C:\Users\Hoss\AppData\Roaming\Dynamo\Dynamo Core\1.3\packages\test\bin\test.dll', Symbols loaded.`

I tried importing the same dll through import library. I received exception below:

```
Exception of type 'ProtoCore.Exceptions.CompilerInternalException' was thrown.

   at ProtoCore.AssociativeEngine.Utils.IsGlobalScopeDirty(Executable exe)
   at ProtoScript.Runners.LiveRunner.ApplyUpdate()
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(String code)
   at ProtoScript.Runners.LiveRunner.UpdateCmdLineInterpreter(String code)
   at Dynamo.Engine.EngineController.OnLibraryLoaded()
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Dynamo.Engine.LibraryServices.OnLibraryLoaded(LibraryLoadedEventArgs e)
   at Dynamo.Engine.LibraryServices.ImportLibrary(String library)
   at Dynamo.ViewModels.DynamoViewModel.ImportLibrary(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at DynamoSandbox.DynamoCoreSetup.RunApplication(Application app)
```

In the VS 2017 I get this error message:

```
An unhandled exception of type 'System.AccessViolationException' occurred in LibG.Managed.dll
Additional information: Attempted to read or write protected memory. This is often an indication that other memory is corrupt. occurred
```

**Comment by smangarole** [comment]
@mjkkirschner @QilongTang @aparajit-pratap Any inputs?

**Comment by mjkkirschner** [comment]
not really :( - This error means there was some issue importing the dll. There are some features we don't support of c#.

Without seeing the code it's difficult to tell - I would make sure the com library is not marked as a node library in the package.json.

Are you using any features in your node library like generics?
Whats in your bin folder?
what does your package.json look like?

**Comment by johnpierson** [comment]
@HossZamani have you had a chance to look at @mjkkirschner's comments? Let us know or we will go ahead and close this.

**Comment by HossZamani** [comment]
Yes. I did. I think there was something wrong with the way I had my dll's referenced. Build action property was set to Embedded if I remember correctly, But it's all good now anyway. I'll close.
