### ISSUE TITLE
BasicInteractive should allow an outport title and tooltip renaming

### ISSUE THREAD

**Issue by Mabiro** [DynamoDS/Dynamo#9049]
Currently, when extending BasicInteractive, there is no way of actually defining an OutPort Name and ToolTip without being forced into using reflection. 

Snippet of what I am forced to do :
```
public MyNode()
        {
            //BasicInteractive adds a default outport... There is no way to override it without using reflection.
            var outPort = OutPorts.First();

            var namePropertyInfo = outPort.GetType().GetProperty("Name");
            namePropertyInfo.SetValue(outPort, "MyName");

            var toolTipPropertyInfo = outPort.GetType().GetProperty("ToolTip");
            toolTipPropertyInfo.SetValue(outPort, "MyToolTip");

            RegisterAllPorts();
        }
```

My suggestion would be to add a new constructor to BasicInteractive that takes in a name and tooltip.

**Comment by mjkkirschner** [comment]
Hi @Mabiro I'm not sure of the suggestion given - will think about it a bit, but instead of reflection you should be able to just remove the port and add your own.
```
OutPorts.Clear();
OutPorts.OutPorts.Add(new PortModel(PortType.Output, this, new PortData("result", "some description")));
```

**Comment by Mabiro** [comment]
Hi @mjkkirschner,

I tried your solution before using reflection and I was unfortunately having a crash when I would click on the outport afterwards.

**Comment by mjkkirschner** [comment]
Hi @Mabiro - 

I cannot reproduce your crash:

<img width="282" alt="screen shot 2018-08-14 at 12 37 13 pm" src="https://user-images.githubusercontent.com/508936/44105239-118d5ec8-9fbf-11e8-898a-76f810c5c420.png">

```
 [IsDesignScriptCompatible]
    public class testChangePorts : BasicInteractive<double>
    {
 snip
   ...


    public testChangePorts()
        {
            this.OutPorts.Clear();
            this.OutPorts.Add(new PortModel(PortType.Output, this, new PortData("name", "tooltip")));
            RegisterAllPorts();
        }
    }
```
Please send the stack trace if it happens again.

But! Yes! I do think it makes sense to extend the constructor, but I'm trying to think of the most idiomatic way to do this. 😃

**Comment by Mabiro** [comment]
Hi @mjkkirschner 

Here is the stacktrace, I just tried again :
```
Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index

   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Dynamo.ViewModels.WorkspaceViewModel.BeginConnection(Guid nodeId, Int32 portIndex, PortType portType)
   at Dynamo.ViewModels.DynamoViewModel.MakeConnectionImpl(MakeConnectionCommand command)
   at Dynamo.Models.DynamoModel.ExecuteCommand(RecordableCommand command)
   at Dynamo.ViewModels.WorkspaceViewModel.StateMachine.HandlePortClicked(PortViewModel portViewModel)
   at Dynamo.ViewModels.PortViewModel.Connect(Object parameter)
   at System.Windows.Interactivity.InvokeCommandAction.Invoke(Object parameter)
   at System.Windows.Interactivity.TriggerBase.InvokeActions(Object parameter)
   at Dynamo.UI.Views.HandlingEventTrigger.OnEvent(EventArgs eventArgs)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at DynamoSandbox.DynamoCoreSetup.RunApplication(Application app)
```

Here is my class :

```
[IsDesignScriptCompatible]
    public class Test : BasicInteractive<string>
    {
        public Test()
        {
            OutPorts.Clear();
            OutPorts.Add(new PortModel(PortType.Input, this, new PortData("Data Set", "Dictionary")));
            RegisterAllPorts();
        }

        protected override string DeserializeValue(string val)
        {
            return val;
        }

        protected override string SerializeValue()
        {
            return "";
        }
    }
```
