### ISSUE TITLE
Error Wile Importing .dll file

### ISSUE THREAD

**Issue by SuhailSS** [DynamoDS/Dynamo#9184]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)
2.0
## Operating system

(e.g. Windows 7, Windows 8.1, etc)
Windows 10
## What did you do? 
Import Zero Touch Node .dll file

## What did you expect to see?

Successful Import
## What did you see instead?
Exception of type 'ProtoCore.Exceptions.CompilerInternalException' was thrown.

   at ProtoCore.AssociativeEngine.Utils.IsGlobalScopeDirty(Executable exe)
   at ProtoScript.Runners.LiveRunner.ApplyUpdate()
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(String code)
   at ProtoScript.Runners.LiveRunner.UpdateCmdLineInterpreter(String code)
   at Dynamo.Engine.EngineController.OnLibraryLoaded()
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Dynamo.Engine.LibraryServices.OnLibraryLoaded(LibraryLoadedEventArgs e)
   at Dynamo.Engine.LibraryServices.ImportLibrary(String library, Boolean isExplicitlyImportedLib)
   at Dynamo.ViewModels.DynamoViewModel.ImportLibrary(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at DynamoSandbox.DynamoCoreSetup.RunApplication(Application app)

**Comment by johnpierson** [comment]
@SuhailSS, are you able to provide the DLL you are trying to import or the visual studio solution?

**Comment by johnpierson** [comment]
Going to go ahead and close this for now as we need sample files to continue. If this is still an issue for you, please feel free to reopen and attach the files needed for us to test.
