### ISSUE TITLE
Node to code crashing Dynamo

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#9227]
## Dynamo version

2.0.1 stable

## Operating system

Windows 10

## What did you do? 

Ran node to code

## What did you expect to see?

A code block

## What did you see instead?

Dynamo crashing

Stack trace:
```
Object reference not set to an instance of an object.

   at Dynamo.Graph.Nodes.CodeBlockNodeModel.GetTypeHintForOutput(Int32 index)
   at Dynamo.Engine.NodeToCode.NodeToCodeCompiler.GetInputOutputMap(IEnumerable`1 nodes, Dictionary`2& inputMap, Dictionary`2& outputMap, Dictionary`2& renamingMap, Dictionary`2& typeHintMap)
   at Dynamo.Engine.NodeToCode.NodeToCodeCompiler.NodeToCode(Core core, IEnumerable`1 workspaceNodes, IEnumerable`1 nodes, INamingProvider namingProvider)
   at Dynamo.Graph.Workspaces.NodesToCodeExtensions.ConvertNodesToCodeInternal(WorkspaceModel workspace, EngineController engineController, INamingProvider namingProvider)
   at Dynamo.Models.DynamoModel.ConvertNodesToCodeImpl(ConvertNodesToCodeCommand command)
   at Dynamo.Models.DynamoModel.ExecuteCommand(RecordableCommand command)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

## Steps to reproduce
* Open Core_Math.dyn from the sample files that ship with Dynamo
* Select all 
* Run node to code

**Comment by johnpierson** [comment]
Curious if this is related to this [8981](https://github.com/DynamoDS/Dynamo/issues/8981)

**Comment by mjkkirschner** [comment]
tracked with: https://jira.autodesk.com/browse/DYN-2289
