### ISSUE TITLE
Crash when putting code block on canvas

### ISSUE THREAD

**Issue by josols** [DynamoDS/Dynamo#9369]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.0.2, Revit 2019

## Operating system

Win10

## What did you do? 

Put a codeblock on canvas

## What did you expect to see?

A codeblock

## What did you see instead?

Crash.
The user in question did not have PyRevit installed, as I've seen that that has caused troubles before? Also, We've added an extension for tracking usage internally, mentioned in the stack trace, could it be the cause?

Method not found: 'System.String Dynamo.Graph.Nodes.NodeModel.get_NickName()'.

   at SwecoNodeUsageStatisticsExtension.SwecoNodeUsageStatisticsExtension.CurrentWorkspaceModel_NodesChanged(NodeModel obj)
   at System.Action`1.Invoke(T obj)
   at Dynamo.Graph.Workspaces.WorkspaceModel.OnNodeAdded(NodeModel node)
   at Dynamo.Graph.Workspaces.WorkspaceModel.AddNode(NodeModel node)
   at Dynamo.Graph.Workspaces.WorkspaceModel.AddAndRegisterNode(NodeModel node, Boolean centered)
   at Dynamo.Models.DynamoModel.CreateNodeImpl(CreateNodeCommand command)
   at Dynamo.Models.DynamoModel.ExecuteCommand(RecordableCommand command)
   at Dynamo.ViewModels.WorkspaceViewModel.StateMachine.CreateCodeBlockNode(Point cursor)
   at Dynamo.ViewModels.WorkspaceViewModel.StateMachine.HandleLeftButtonDown(Object sender, MouseButtonEventArgs e)
   at Dynamo.Views.WorkspaceView.OnMouseLeftButtonDown(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by mjkkirschner** [comment]
If your extension is asking for a property which was removed that will cause an exception and it may not be caught. I believe nickname and name were merged.

**Comment by josols** [comment]
Your absolutely right. property is removed. I'll close.
