### ISSUE TITLE
Clicking on a string object in a watch node crashed Dynamo

### ISSUE THREAD

**Issue by dimven** [DynamoDS/Dynamo#9508]
## Dynamo version

2.0.2 under Revit 2019

## Operating system

Windows 10

## What did you do? 

Left clicked on a string object in a watch node, after a long graph was executed.

## What did you expect to see?

Nothing unusual

## What did you see instead?

Dynamo captured the following exception and gracefully crashed:

```
Object reference not set to an instance of an object.

   at Dynamo.Controls.WatchTree.HandleItemChanged(TreeViewItem tvi, WatchViewModel node)
   at Dynamo.Controls.WatchTree.treeviewItem_MouseLeftButtonUp(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

Never had this happen before. This is possibly just an isolated incident, but just in case I'm sharing the exception trace. On a side note, it's crazy how many things get triggered in windows when you just click on something :)

**Comment by dimven** [comment]
Bump, got another one of these:
![image](https://user-images.githubusercontent.com/7148394/53680430-6e437400-3d16-11e9-85e4-e1476f7abdff.png)

Possibly related to Revit somehow? Running under 2019.2

**Comment by QilongTang** [comment]
@dimven Hi I could not reproduce this locally and I saw function `HandleItemChanged` already contains null check. I suspect this is an issue when running inside host only but would like to verify it first. Do you mind sending me a small part of your dyn for our team to investigate?

**Comment by dimven** [comment]
I could possibly share the graph, but it would be useless without a sample of the content it is supposed to and unfortunately I can't share that.

Since this seems like a rare corner case I'll just close it for now until I can get a more easily reproducible sample.
