### ISSUE TITLE
The image data generated an overflow during processing. 

### ISSUE THREAD

**Issue by sherifabdelhalim1** [DynamoDS/Dynamo#9603]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version
2.1
(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Operating system
windows 10
(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 

The image data generated an overflow during processing.

   at System.Windows.Media.Renderer.Render(IntPtr pRenderTarget, Channel channel, Visual visual, Int32 width, Int32 height, Double dpiX, Double dpiY, Matrix worldTransform, Rect windowClip)
   at System.Windows.Media.Imaging.BitmapVisualManager.Render(Visual visual, Matrix worldTransform, Rect windowClip)
   at System.Windows.Media.Imaging.BitmapVisualManager.Render(Visual visual)
   at Dynamo.Views.WorkspaceView.SaveWorkspaceAsImage(String path)
   at Dynamo.ViewModels.DynamoViewModel.OnRequestSaveImage(Object sender, ImageSaveEventArgs e)
   at Dynamo.ViewModels.DynamoViewModel.SaveImage(Object parameters)
   at Dynamo.ViewModels.DynamoViewModel.ShowSaveImageDialogAndSaveResult(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

## What did you expect to see?

(Fill in here)

## What did you see instead?

(Fill in here)

**Comment by QilongTang** [comment]
@sherifabdelhalim1 Thank you for reporting! Can you add some more details for our team to diagnose this issue by specifying which image processing node you used and how big the image is?

**Comment by mjkkirschner** [comment]
@sherifabdelhalim1 seems to me we need the graph to reproduce this - where you zoomed in far?

**Comment by mjkkirschner** [comment]
closing - need more information to reproduce.
