### ISSUE TITLE
Returning Autodesk.Revit.DB.Document results in crash if the document is lost

### ISSUE THREAD

**Issue by johnpierson** [DynamoDS/Dynamo#9682]
## Dynamo version

1.3.x, 2.x.x

## Operating system

Windows 10

## What did you do? 

When you return an `Autodesk.Revit.DB.Document` from a custom zero touch node, you will receive a nasty crash if the document is lost (fairly typical if you use background opened document workflows) and Dynamo is in automatic run mode.

FWIW I "fixed it" with the string fix I mention below. But this basically made it to where my nodes only work with each other. lol

## What would you like to see?

I was curious if there is anyway to prevent the error that results. I have thought about several different ways to do this from view extensions to remove the connection or force to manual run mode. I finally landed on storing the document internally and returning the string name but that isn't great as some nodes require and `Autodesk.Revit.DB.Document` .

## What did you see instead?
```
Object reference not set to an instance of an object.

   at ProtoCore.DSASM.Heap.Sweep()
   at ProtoCore.DSASM.Heap.SingleStep(Boolean forceGC)
   at ProtoCore.DSASM.Heap.FullGC(IEnumerable`1 gcroots, Executive exe)
   at ProtoScript.Runners.LiveRunner.ApplyUpdate()
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()
```
## Related Links:
https://forum.dynamobim.com/t/copy-views-to-document-on-file/33448
https://forum.dynamobim.com/t/close-background-revit-files/32837/10

**Comment by dimven** [comment]
This is why you usually need wrapper classes, like the one that's already in place (but very limited) for document objects:

https://github.com/DynamoDS/DynamoRevit/blob/master/src/Libraries/RevitNodes/Application/Document.cs

Ideally the wrapper would track the life-cycle of the document and invalidate itself if the document is lost? I think that the best approach would be to extend the existing document wrapper and add a public constructor for it, so that in the long term all nodes and packages can use it.

**Comment by johnpierson** [comment]
Yeah that would be my hope as well. I think for the time being (to get this at least partially solved sooner than later), I might have my nodes toggle to manual run mode on placement for document related workflows. 😒

**Comment by johnpierson** [comment]
I also, fully understand that what we are doing is definitely not what Dynamo was intended for. So I don't expect it to be perfect right off the bat 😂

**Comment by johnpierson** [comment]
Eh here is my temp fix. Force manual mode on placement of the "risky" nodes. 
![20190425-documentBandaid](https://user-images.githubusercontent.com/15744724/56752751-408f1000-6746-11e9-8f50-e81fd8aab990.gif)

**Comment by ThomasMahon** [comment]
Your only solution would be to incorporate the close and save input into the document open node. That way the document object gets safely disposed. The exception thrown by Dynamo i suspect is due to the fact that the document object is both open and closed at the same time which leads to an inconsistent state. Since graphs are acyclic by nature (which therefore gives rise to the inconsistent state of the document object), I doubt there are many options available to resolve this without creating a special condition in Dynamo's VM to handle this exception. It may also explain why Dynamo's document wrapper class is static which also doesn't bode well for a solution which doesn't involve collating both open, close and save into one node. Just my 10 cents on the subject - its the workaround I used for CAD.ReportInstances in BimorphNodes.

**Comment by johnpierson** [comment]
Thanks for the comments @ThomasMahon. I agree with your points. I have actually implemented something similar to what you mentioned in my node that upgrades Revit files. It handles both open and close in the same node with no issues.

I was also handling this another way by storing the document in AppDomain with the title as the key. That resulted in no crashes as well since I was not returning the raw `Autodesk.Revit.DB.Document` but a string. The issue with that was, users inevitably wanted to use the `Autodesk.Revit.DB.Document` with other nodes and couldn't since my version was made to work with my nodes only using the AppDomain

**Comment by ThomasMahon** [comment]
Seems sensible - an alternative, although still far from perfect might be make the close document node asynchronous and to only execute on Dynamo's close event. If this is clearly documented in the node description, users will at least understand the document will remain open while Dynamo is still open. The immediate problem with this though....is when a user needs to close the document and do something else while in the same Dynamo session. I think any approach will be a compromise tbh, as the problem is intrinsically linked to the mechanics of visual programming (or at least, Dynamo's VP mechanics).

**Comment by johnpierson** [comment]
> execute on Dynamo's close event

Oooh, that is a pretty nifty idea too. So the node would kind of "mark for closing". Like you said, not perfect, but better than a hard crash. 👍

**Comment by ThomasMahon** [comment]
Yep exactly 👍

**Comment by mjkkirschner** [comment]
hmm @aparajit-pratap in any case - garbage collection should not crash should it when trying to collect a null?

**Comment by mjkkirschner** [comment]
@johnpierson - we're considering marking this `won't fix` - do you have any data (anecdotal or otherwise) on how often this occurs?

It also sounds like there is a larger DynamoRevit API redesign that you want to discuss here - where simply avoiding the crash might not actually help?

**Comment by johnpierson** [comment]
I think I basically need a wrapper for Document. 😁

**Comment by mjkkirschner** [comment]
tracked the crash with: https://jira.autodesk.com/browse/DYN-2287
