### ISSUE TITLE
DYNAMO CRASHES when i open it

### ISSUE THREAD

**Issue by michelemaz** [DynamoDS/Dynamo#9747]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

dynamo 1.3.4 revit 2019.2

## Operating system
windows 10

## What did you do? 

I opened dynamo

## What did you expect to see?

dynamo work

**Comment by tmaleski** [comment]
I'm using Revit 2019.2.0.65 with Dynamo Core 2.02.6826 Dynamo Revit 2.0.2.6833 and version 2019.2.10 of DynaMaps. When I select the DynaMaps view extention, Dynamo crashes with this:

'The invocation of the constructor on type 'Microsoft.Maps.MapControl.WPF.Map' that matches the specified binding constraints threw an exception.' Line number '23' and line position '10'.

   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at DynaMapsViewExtension.DynaMapsWindow.InitializeComponent()
   at DynaMapsViewExtension.DynaMapsWindow..ctor(ReadyParams p, DynamoViewModel vm)
   at DynaMapsViewExtension.DynaMapsViewExtension.<>c__DisplayClass2_0.<Loaded>b__0(Object sender, RoutedEventArgs args)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by mjkkirschner** [comment]
I think you may want to report this to @ MostafaElAyoubi

**Comment by djmezo** [comment]
I have this problem too. It happens in all versions I've installed. I don't know where this problem is coming from :(
