### ISSUE TITLE
Dynamo 2.5 - Pkg.json fails to deserialize

### ISSUE THREAD

**Issue by alvpickmans** [DynamoDS/Dynamo#9943]
## Dynamo version
2.5 (latest master)

## Operating system

Win 10

## What did you do? 

Build Dynamo from source, debug and load some packages. Packages were both locally developed and downloaded from Package Manager.

## What did you expect to see?

Packages loaded.

## What did you see instead?

It seems to be failing when deserializing the `pkg.json` files to instances of `PackageUploadRequestBody`.

https://github.com/DynamoDS/Dynamo/blob/master/src/DynamoPackages/Package.cs#L168

Exception Message: 
`
"Unable to find a constructor to use for type Greg.Requests.PackageUploadRequestBody. A class should either have a default constructor, one constructor with arguments or a constructor marked with the JsonConstructor attribute. Path 'license', line 1, position 11."
`

Stacktrace: 
```
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Dynamo.PackageManager.Package.FromJson(String headerPath, ILogger logger) in C:\Users\{...}\GitHub\Dynamo\src\DynamoPackages\Package.cs:line 168
```

## Proposed Solutions

It seems to be failing on the constructor. Unaware what changes can have caused this, but should be an easy solution by either:

- Having a ctor with no inputs an letting Json.NET instantiate the properties (requires changes on Greg repository)
- Defining each required input on the ctor with the same as the serialized key property (changes on Greg)
- Use a custom `JsonConverter` to customize the serialize/deserialize process (more complicated and need of maintenance)

**Comment by mjkkirschner** [comment]
This should be fixed now

Can you get latest master?

**Comment by alvpickmans** [comment]
Yes, this is fixed on latest master push.

Thanks!
