### ISSUE TITLE
Crash - Unhandled Exception in Dynamo Engine

### ISSUE THREAD

**Issue by beardface00** [DynamoDS/Dynamo#9958]
## Dynamo version

Dynamo Core: 1.3.3.4651
Dynamo Revit: 1.3.3.4651

## Operating system

Windows 10

## What did you do? 

Ran a script which has been working without issue for the last few months.

## What did you expect to see?

Updated Lists (crash now occurs on first run of the script), which would then be exported to excel spreadsheets, but this node is currently frozen.

## What did you see instead?

Specified cast is not valid.

   at ProtoCore.DSASM.Heap.ToHeapObject[T](StackValue heapObject)
   at ProtoCore.Lang.Replication.AtLevelHandler.GetElementsAtLevel(StackValue argument, Int32 level, List`1 indices, Boolean recordIndices, RuntimeCore runtimeCore)
   at ProtoCore.Lang.Replication.AtLevelHandler.<>c__DisplayClass0_0.<GetElementsAtLevel>b__1(StackValue v, Int32 i)
   at System.Linq.Enumerable.<ZipIterator>d__61`3.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ProtoCore.Lang.Replication.AtLevelHandler.GetArgumentAtLevel(StackValue argument, AtLevel atLevel, RuntimeCore runtimeCore)
   at ProtoCore.Lang.Replication.AtLevelHandler.GetArgumentsAtLevels(List`1 arguments, List`1 atLevels, RuntimeCore runtimeCore)
   at ProtoCore.Lang.Replication.AtLevelHandler.GetArgumentAtLevelStructure(List`1 arguments, List`1 atLevels, RuntimeCore runtimeCore)
   at ProtoCore.DSASM.Executive.Callr(Int32 blockDeclId, Int32 functionIndex, Int32 classIndex, Boolean& explicitCall, Boolean isDynamicCall, Boolean hasDebugInfo)
   at ProtoCore.DSASM.Executive.CALLR_Handler(Instruction instruction)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
   at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   at ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()

**Comment by mjkkirschner** [comment]
@beardface00 - thanks for reporting this, however to help us reproduce please reopen this issue with files attached (.dyn / rvt) that reproduce the issue along with any steps that are required.
