### ISSUE TITLE
Workspace file saved with .dyf extension and Custom Node saved with .dyn extension {Crash report from Dynamo 2.2.1.5175}

### ISSUE THREAD

**Issue by abisabbas** [DynamoDS/Dynamo#9987]
## Dynamo version

Dynamo Core 2.2.1.5175

## Revit version

Dynamo Revit 2.1.0.7733

## Operating system

Windows 7

## What did you do? 

I was working on my Python Script. I save changes a couple of times, and everything is fine. But then I open a custom node I was working on and edit the python script. At this point, I have Python Script from both my workspace and the custom node open at the same time. As soon as I save changes to my Python Script in my workspace, Dynamo crashes. It gives me the option to save my work files before closing, which I do. But when I open my files, my Workspace file is saved with the extension .dyf (extension for custom node), and my custom node is saved with the extension .dyn (extension for dynamo workspace file)
P.S.: I had the python script from the custom node and my workspace open at the same time when the crash happened

## What did you expect to see?

My workspace file saved with .dyn extension and the custom node saved with .dyf extension

## What did you see instead?

My workspace file saved with .dyf extension and the custom node saved with .dyn extension

## Stack Trace

```
UpdateModelValue: Model not found

   at Dynamo.Graph.Workspaces.WorkspaceModel.UpdateModelValue(IEnumerable`1 modelGuids, String propertyName, String value)
   at Dynamo.Models.DynamoModel.UpdateModelValueImpl(UpdateModelValueCommand command)
   at Dynamo.Models.DynamoModel.ExecuteCommand(RecordableCommand command)
   at PythonNodeModelsWpf.ScriptEditorWindow.UpdateScript(String scriptText)
   at PythonNodeModelsWpf.ScriptEditorWindow.OnSaveClicked(Object sender, RoutedEventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

---
OS: `Microsoft Windows NT 6.1.7601 Service Pack 1`
CLR: `4.0.30319.42000`
Dynamo: `2.2.1.5175`

**Comment by mjkkirschner** [comment]
@abisabbas thanks for reporting this - 
you've hit two bugs - 
1. python save button is looking in the current workspace for the python node, but you had another ws open.
2. saving the graph on crash uses the current workspace to determine file extension and saves the graph with incorrect extension.

I believe both have been reported before separately, if found/tracked will close this and reference it there.

**Comment by mjkkirschner** [comment]
https://github.com/DynamoDS/Dynamo/issues/8913

**Comment by mjkkirschner** [comment]
https://github.com/DynamoDS/Dynamo/issues/9479
