### ISSUE TITLE
DynamoCoreRuntime not starting

### ISSUE THREAD

**Issue by radumg** [DynamoDS/Dynamo#9989]
## Dynamo version

2.3 and 2.4

## Operating system

Windows 10 - fresh install.

## What did you do? 

Download 2.3 and 2.4 DynamoCoreRuntime zip & unzip using built-in windows utility.
Click DynamoSandbox.exe and see the settings migration splash screen for a second, after which nothing happens.

## What did you expect to see?

Dynamo to actually launch.

## What did you see instead?

Nothing. This is a fresh install of Windows so there's no Revit or other apps installed beyond some dev tools (VisualStudio, etc) & office tools (Office, Slack, etc).

Log file isn't very useful either :

```
Dynamo log started 2019-09-18 21:31:15Z
2019-09-18 21:31:16Z : Could not find file 'C:\Users\radug\AppData\Roaming\Dynamo\Dynamo Core\2.3\DynamoSettings.xml'.
2019-09-18 21:31:16Z : Python template set to default.
2019-09-18 21:31:16Z : Could not create an instance of Dynamo.PackageManager.PackageManagerExtension
2019-09-18 21:31:16Z : Could not load file or assembly 'file:///C:\DynamoCoreRuntime2.4.0\DynamoPackages.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
2019-09-18 21:31:16Z :    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Dynamo.Extensions.ExtensionLoader.Load(ExtensionDefinition extension)
```

The `DynamoPackages.dll` definitely exists at that path and after I manually unblocked it, logs stop recording anything after `2019-09-18 21:31:16Z : Python template set to default.
`

**Comment by mjkkirschner** [comment]
1. use 7zip to unzip the dlls
2. or make sure to unblock the zip before unzipping
3. delete the packages which were migrated

**Comment by mjkkirschner** [comment]
@radumg did you ever solve this?

**Comment by radumg** [comment]
Hey @mjkkirschner, yes I eventually remembered to use 7zip. Had re-installed windows and assumed I wouldn’t need it again.

Was using the released zips.

**Comment by radumg** [comment]
Do think there’s a bigger user story here on first use/install of Sandbox. Since the zip still has these limitations, perhaps there should be consideration for a light installer ? Maybe something light like a ClickOnce or something not requiring asmin privileges.

Cc @solamour
